Tribler/tribler

Tribler/Core/TorrentDef.py
Tribler/Core/permid.py

Remove unused stuff

---

.gitmodules

Fix pymdht

---

Tribler/Core/defaults.py
Tribler/Main/Dialogs/SaveAs.py
Tribler/Main/Utility/utility.py
Tribler/Main/vwxGUI/MainFrame.py
Tribler/Main/vwxGUI/settingsDialog.py
Tribler/Main/vwxGUI/widgets.py

Add default anonymous level in settings

---

mac/makedistmac.sh

Fixes crash problem on mac

---

win/makedist.bat

Remove ffmpeg.exe

---

Tribler/Main/Dialogs/SaveAs.py

fix anonymous_slidebar in SaveAs dialog

---

.gitignore
Tribler/Category/FamilyFilter.py
Tribler/Core/RawServer/SocketHandler.py
Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/MainFrame.py
Tribler/Test/test_sqlitecachedb_upgrade.py
Tribler/Test/test_tunnel_community.py
Tribler/TrackerChecking/TrackerUtility.py
Tribler/community/tunnel/community.py

And some debug stuff to get more info when some bugs happen

misc fixes for stuff found during the preparation to allow for network isolated test runs.

---

win/makedist.bat

sign windows installer

---

Tribler/Core/RemoteTorrentHandler.py

Do not download if TFTP has been shutdown

---

Tribler/community/tunnel/community.py

Related to https://github.com/Tribler/tribler/issues/1132

make a couple assertions a bit more informative

---

Tribler/Main/vwxGUI/settingsDialog.py

Fix SettingsDialog restart segfault problem

---

.gitignore
.gitmodules
Tribler/Category/FamilyFilter.py
Tribler/Core/RawServer/SocketHandler.py
Tribler/Core/RemoteTorrentHandler.py
Tribler/Core/defaults.py
Tribler/Main/Dialogs/SaveAs.py
Tribler/Main/Utility/utility.py
Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/MainFrame.py
Tribler/Main/vwxGUI/settingsDialog.py
Tribler/Main/vwxGUI/widgets.py
Tribler/Test/test_sqlitecachedb_upgrade.py
Tribler/Test/test_tunnel_community.py
Tribler/TrackerChecking/TrackerUtility.py
Tribler/community/tunnel/community.py
mac/makedistmac.sh
win/makedist.bat

Merge next back to devel and fix some conflicts.

Merge next to devel

---

README.md
Tribler/Main/tribler.py
debian/control
tribler.sh

Check python version

---

Tribler/Main/vwxGUI/widgets.py

Add a checkbox for anonymity slider and use correct descriptions for anonymity levels.

Add a checkbox for anonymity slider and use correct descriptions for anonymity levels

---

Tribler/Main/vwxGUI/MainFrame.py

Fix adding magnet link download

---

.gitmodules

update pymdht pointer

---

README.md

Add devscripts dependency to the build instructions.

---

Tribler/Core/SessionConfig.py
Tribler/Core/Utilities/utilities.py
debian/control

Do not merge until tested on Windows

use avconv or ffmpeg, whatever is available on Linux

---

Tribler/Main/tribler_main.py

Show error dialog when a download has stopped on error

---

Tribler/Core/TorrentDef.py
Tribler/Core/Utilities/twisted_thread.py
Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/GuiUtility.py
Tribler/Main/vwxGUI/list.py
Tribler/Main/vwxGUI/list_body.py
Tribler/Main/vwxGUI/list_details.py
Tribler/Test/test_as_server.py
Tribler/Test/test_gui_dialogs.py
Tribler/Test/test_remote_torrent_handler.py
Tribler/Test/test_tunnel_community.py

I've splitted them into a new branch so the can get merged while the torrent store stuff gets tested.

Some fixes from the torrent store branch

---

Tribler/Core/DownloadConfig.py
win/tools/reset-keepid.bat
win/tools/reset.bat

Closes #1014 
Closes #1017
Do not merge until tested on windows and mac

Put TriblerDownloads to Downloads/ instead of Desktop/ by default

---

Tribler/Main/vwxGUI/MainFrame.py

Show an error dialog when add magnet download fails

---

Tribler/Main/tribler_main.py
Tribler/Test/test_as_server.py
Tribler/Test/test_tunnel_community.py
Tribler/community/channel/community.py

Remove is_unit_testing and fix the tests using it.

---

Tribler/Main/Build/Win32/tribler.nsi

See http://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_devel/186 for the problem.
Tested. Ready to be merged.

Fixes Windows build script

---

Tribler/Main/Build/Win32/setuptribler.py
Tribler/Main/Build/Win32/tribler.nsi
win/makedist.bat

Fix Windows build script to use new crypto stuff

---

Tribler/Main/Build/Mac/setuptriblermac.py

Fix mac bulid script

---

Tribler/Main/vwxGUI/SearchGridManager.py

Just stop looking for them already :)

We dont' have torrent files anymore.

---

Tribler/Main/Utility/GuiDBTuples.py
Tribler/Main/vwxGUI/SearchGridManager.py
Tribler/Main/vwxGUI/list.py
Tribler/Main/vwxGUI/list_details.py
Tribler/Main/vwxGUI/list_item.py
Tribler/Policies/RateManager.py

A leftover from the swift removal refactor.
Closes #973

Remove MergedDs

---

Tribler/Main/Build/Mac/setuptriblermac.py
mac/makedistmac.sh

@whirm Tested. Ready to be merged.

Update mac build

---

Tribler/Main/Utility/GuiDBTuples.py
Tribler/Main/vwxGUI/SearchGridManager.py
Tribler/Main/vwxGUI/list.py
Tribler/Main/vwxGUI/list_item.py

And download_status->download_state
Ready if it passes

Fix a few missed ds->download_status replacements

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Main/vwxGUI/SearchGridManager.py
Tribler/Test/test_sqlitecachedbhandler.py
Tribler/TrackerChecking/TorrentChecking.py
Tribler/schema_sdb_v25.sql

Partially fix #1213 
We need to modify the database upgrade script.

Remove Torrent Source Table

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Main/Dialogs/AddTorrent.py
Tribler/Main/Dialogs/SaveAs.py
Tribler/Main/vwxGUI/SearchGridManager.py
Tribler/Main/vwxGUI/home.py
Tribler/Main/vwxGUI/list.py
Tribler/Main/vwxGUI/list_details.py

@whirm ready to be merged after it passes

Remove unnecessary getTorrent() in SearchGridManager

---

Tribler/Main/Utility/GuiDBTuples.py

fix serializing ChannelTorrent using pickle

---

Tribler/Main/tribler_main.py

Fix typo in tunnel optin dialog

---

Tribler/Main/vwxGUI/SRstatusbar.py
Tribler/Test/test_as_server.py
Tribler/Test/util.py

WIP: Do not merge yet
Closes #1209

Catch unhandled exceptions and fail the tests if any has been raised

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Core/Session.py
Tribler/Test/test_sqlitecachedbhandler.py
Tribler/Test/test_tracker_checking.py

Add trackers into torrent files

---

Tribler/community/search/community.py

Fix RequestCache KeyError in SearchCommunity

---

README.md

Added description how to install required dependencies in Ubuntu 14.04, which could not be installed by calling the command listed under "Installing Dependencies". Related to Issue #1259

Added Install Manual for dependencies to README.md

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Core/RemoteTorrentHandler.py
Tribler/Main/Utility/GuiDBTuples.py
Tribler/Main/vwxGUI/SearchGridManager.py
Tribler/Main/vwxGUI/__init__.py
Tribler/Main/vwxGUI/list_details.py
Tribler/Test/test_sqlitecachedbhandler.py
Tribler/schema_sdb_v25.sql

1. `thumbnail` column is removed from the `Torrent` table
2. `torrent_file_name` column is replaced with `is_collected`.
3. some other fixes

Replace torrent_file_name column

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Main/Utility/GuiDBTuples.py
Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/MainFrame.py
Tribler/Main/vwxGUI/SearchGridManager.py
Tribler/Main/vwxGUI/__init__.py
Tribler/Main/vwxGUI/list.py
Tribler/Main/vwxGUI/list_details.py
Tribler/Test/test_sqlitecachedbhandler.py
Tribler/schema_sdb_v25.sql

Remove progress column

---

Tribler/Core/CacheDB/db_versions.py
Tribler/Core/Upgrade/db_upgrader.py
Tribler/schema_sdb_v26.sql

Add database upgrade script

---

Tribler/TrackerChecking/TorrentChecking.py

Fix tracker checking threading problem

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py

Check if a tracker url is valid before adding it

---

Tribler/Main/vwxGUI/SearchGridManager.py

I guess this part of the code has never been tested.

A small fix

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/APIImplementation/maketorrent.py
Tribler/Core/TorrentDef.py
Tribler/Core/Utilities/utilities.py
Tribler/Main/Dialogs/CreateTorrent.py
Tribler/Main/vwxGUI/MainFrame.py
Tribler/Test/API/test_tdef.py

Remove azureus_property and some other things

---

Tribler/Core/Upgrade/torrent_upgrade65.py
Tribler/Core/Upgrade/upgrade.py

Fix upgrade script

---

Tribler/TrackerChecking/TrackerSession.py

Some fixes for Tracker Checking

---

Tribler/Main/vwxGUI/SearchGridManager.py

Fix a family filter problem in channels

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py

Fix this backtrace:
```
File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/tribler/Tribler/community/channel/community.py", line 387, in _disp_on_torrent
self._channelcast_db.on_torrents_from_dispersy(torrentlist)
File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 1570, in on_torrents_from_dispersy
torrent_ids, inserted = self.torrent_db.addOrGetTorrentIDSReturn(infohashes)
File "/home/jenkins/workspace/GH_Tribler_pull-request-tester-isolated_devel/tribler/Tribler/Core/CacheDB/SqliteCacheDBHandler.py", line 514, in addOrGetTorrentIDSReturn
assert all(torrent_id for torrent_id in torrent_ids), torrent_ids
exceptions.AssertionError: [5200, 5201, 5202, 5203, 5204, None, 5205]
```

Fix None torrent_id problem

---

Tribler/Core/Utilities/utilities.py

Check if port is either int or long

---

Tribler/Main/vwxGUI/list.py

Check if search list has key before doing anything else

---

Tribler/Main/vwxGUI/widgets.py

Only call self.selectcallback if it's set.

---

Tribler/community/channel/community.py
Tribler/community/tunnel/tunnel_community.py
logger.conf

actually record the right bartercast stuff :)
+ advance dispersy pointer for the isolated network gumby stuff

Fix bc data

---

Tribler/community/tunnel/tunnel_community.py

sento method allows a hostname in its destination

---

Tribler/Main/tribler_main.py
Tribler/Test/test_as_server.py

fix the problem that cannot open torrent file with Tribler on Mac OS X

---

Tribler/Core/Libtorrent/LibtorrentMgr.py

on the non-tunneled session
Closes #887

Enable oportunistic encryption

---

Tribler/Main/vwxGUI/list.py

Fix category KeyError

---

Tribler/Test/test_bartercast4_community.py
Tribler/community/bartercast4/community.py
Tribler/community/bartercast4/statistics.py

(thanks for helping @LipuFei !)

Bc4 community tests (fixes #1238)

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py

Fix None torrent_id assertion

---

Tribler/Main/Dialogs/SaveAs.py
Tribler/Main/tribler_main.py
Tribler/community/tunnel/hidden_community.py
Tribler/community/tunnel/tunnel_community.py

This PR fixes two bugs related to anonymity in current devel:
* Downloading over circuits won't work when the circuit length was 1. 
* No blocking ok-button in the save-as dialog, this was only required for setting the anonymous=1 flag correctly but is not relevant anymore.

Fix critical bugs related to circuits

---

Tribler/Main/vwxGUI/widgets.py

Thing was breaking up the test too. :astonished:

Another occurence of toggling ok button for tunnels

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/Modules/cache.py
Tribler/Core/Modules/channel_manager.py
Tribler/Core/Modules/channel_rss.py
Tribler/Core/Session.py
Tribler/Core/simpledefs.py
Tribler/Main/metadata-injector.py
Tribler/Main/vwxGUI/list.py
Tribler/community/channel/community.py

New metadata-injector with support for multiple Channels

---

Tribler/Core/torrentstore.py
Tribler/Test/test_torrent_store.py

It doesn't add any performance improvement and it simplifies everything
a bit.

Make torrent store flush() sync

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py

I suspect we are getting repeated infohashes. (should clarify the cause of #1449)

Add more debug info in getTorrentIDS.

---

Tribler/Main/Dialogs/AddTorrent.py
Tribler/Main/Dialogs/CreateTorrentDialog.py
Tribler/Test/test_gui_dialogs.py
Tribler/Test/test_hidden_community.py
Tribler/Test/test_tunnel_community_fails.py
Tribler/Test/test_tunnel_community_success.py

Use libtorrent to create torrent files

---

Tribler/Main/vwxGUI/TopSearchPanel.py

Fix a PyDeadObject

---

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Main/vwxGUI/GuiUtility.py

Some Fixes

---

Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Test/test_as_server.py

Fix a notifier problem

---

Tribler/Core/TorrentChecker/torrent_checker.py

No blocking_call for TorrentChecking thread

---

Tribler/Core/TorrentDef.py
Tribler/Main/Dialogs/AddTorrent.py
Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/GuiUtility.py
Tribler/Main/vwxGUI/MainFrame.py
Tribler/Test/test_libtorrent_download.py

Now supporting
* http, https
* magnet
* emc
* file:
links from the AddDialog, searchBars, and commandline.
Fixes #1361

Fixed addtorrent

---

Tribler/Core/plyveladapter.py
Tribler/Core/torrentstore.py
Tribler/Test/test_torrent_store_plyvel.py

An alternative for @Darsestheus's pull request #1484. Adds Plyvel support to TorrentStore.

add support for plyvel

---

setup.py

this is the setup.py that is used to install Tribler for the shadow-Internet app

add setup.py for core functionality

---

Tribler/Test/test_hidden_community.py
Tribler/Test/test_tunnel_community_negative.py
Tribler/Test/test_tunnel_community_positive.py
Tribler/community/bartercast4/statistics.py
Tribler/community/tunnel/crypto/tunnelcrypto.py
Tribler/community/tunnel/tunnel_community.py
logger.conf

* No more bartercast debug logging
* NoCrypto fix missing key

Various small bugfixes

---

Tribler/community/tunnel/hidden_community.py
Tribler/community/tunnel/tunnel_community.py

Creating info_hash based on appending `tribler anyonymous download` typo fixed. Also added some more logging.

Typo fixed in anonymous info_hash

---

.gitignore
Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Test/test_as_server.py
Tribler/Test/test_gui_dialogs.py
Tribler/Test/test_gui_general.py
Tribler/Test/test_hidden_community.py
Tribler/Test/test_libtorrent_download.py
Tribler/Test/test_metadata_community.py
Tribler/Test/test_my_channel.py
Tribler/Test/test_remote_search.py
Tribler/Test/test_tunnel_community_negative.py
Tribler/Test/test_tunnel_community_positive.py

A few cosmetic refactors to make the base test classes API look a bit more consistent with twisted and a small fix for a rare issue with operations on the torrent store happening after it's closed.

Misc refactors and fixes

---

Tribler/Main/Utility/GuiDBTuples.py
Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/GuiUtility.py
Tribler/Main/vwxGUI/SearchGridManager.py
Tribler/Main/vwxGUI/TorrentStateManager.py
Tribler/Main/vwxGUI/list_details.py
Tribler/community/channel/community.py

Some more cleanup for old metadata.
After this one I will make a PR for the new metadata implementation.

Cleanup old metadata stuff 2

---

Tribler/Main/vwxGUI/list.py

No Videoplayer tab for Mac

---

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py

Don't try to add a task if the threadpool is gone.

---

Tribler/Core/TorrentDef.py

Skip invalid trackers

---

Tribler/community/tunnel/tunnel_community.py

If it still comes from the same address.
Closes #1132

Allow for the source port to change.

---

Tribler/Core/TorrentChecker/session.py
Tribler/Core/TorrentChecker/torrent_checker.py

Closes #1534
Check if a tracker is dead before creating a session for it.

Fix tracker check

---

Tribler/Core/DownloadConfig.py
Tribler/Core/defaults.py
Tribler/Main/Dialogs/SaveAs.py
Tribler/Main/Utility/utility.py
Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/MainFrame.py
Tribler/Main/vwxGUI/settingsDialog.py
Tribler/Main/vwxGUI/widgets.py
Tribler/community/tunnel/hidden_community.py

Fix issues with circuits

---

Tribler/Main/Build/Mac/setuptriblermac.py
Tribler/Main/Build/Win32/setuptribler.py

Fix Mac and Windows build

---

Tribler/Main/vwxGUI/widgets.py

Replace message string for anon seeding

---

Tribler/Main/vwxGUI/home.py

Hide artwork pannel

---

Tribler/Main/Build/Win32/tribler.nsi

Make empty tribler.exe.log

---

Tribler/Main/Build/Win32/tribler.nsi

Update windows installer script

---

Tribler/Core/TorrentChecker/session.py
Tribler/Core/TorrentChecker/torrent_checker.py

Lower torrent-checking-related log level

---

Tribler/Core/SessionConfig.py
Tribler/Core/leveldbstore.py

Fix leveldb file system encoding problem

---

Tribler/Main/vwxGUI/MainFrame.py

no subdirectory for single file torrents

---

Tribler/Main/vwxGUI/list_details.py

Set flag after the item has been created

---

Tribler/community/tunnel/Socks5/server.py

To help debugging error logged in unrelated issue #1588

Log the actual reason of the socks5 CMD denial

---

Tribler/Main/tribler_main.py

Fix download state

---

Tribler/Main/tribler_main.py

no seeding when "no seeding" is selected

---

Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/settingsDialog.py
Tribler/Test/test_gui_dialogs.py

Fix download location settings

---

Tribler/community/tunnel/Socks5/conversion.py
Tribler/community/tunnel/Socks5/server.py
Tribler/community/tunnel/tunnel_community.py

Fix ipv6 datagram tunnel

---

Tribler/community/tunnel/tunnel_community.py

When due to unknown circuit ID or hop count value.

Be more informative when dropping an incoming msg

---

Tribler/Main/vwxGUI/list_details.py

Fix item encoding issue

---

Tribler/Main/hacks.py
Tribler/Main/tribler_main.py

backend scanning when frozen by py2app.

Add monkeypatch to fix python-cryptography

---

Tribler/Core/Video/utils.py
Tribler/Core/leveldbstore.py
Tribler/Main/hacks.py
Tribler/Main/tribler.py
Tribler/Main/tribler_main.py

Handful o'fixes

---

README.md

Just a trivial mistake i noticed.
Thx for the great project.

Fixed minor grammar error

---

Tribler/Main/vwxGUI/settingsDialog.py

Improve the exit node checkbox description

---

Tribler/Main/tribler_main.py

I came across some unused variables when inspecting code. These variables are not used in ABCApp class and outside it and can probably be removed.

Removed some unused variables in the ABCApp class.

---

Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Main/vwxGUI/settingsDialog.py

Set bandwidh settings on tunnel sessions 

---

Tribler/Main/Dialogs/SaveAs.py
Tribler/Main/vwxGUI/MainFrame.py

Fix download dir

---

Tribler/community/tunnel/tunnel_community.py

Make the string format less strict.

---

Tribler/Core/APIImplementation/LaunchManyCore.py

fixes #1803

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/__init__.py

I encountered some unused variables that could be removed.

Removed unused variables.

---

Tribler/Core/defaults.py
Tribler/Main/Dialogs/SaveAs.py
Tribler/Main/vwxGUI/MainFrame.py
Tribler/Main/vwxGUI/settingsDialog.py
Tribler/Main/vwxGUI/widgets.py

Reported by `gr8` via IRC (thanks!)

Fix all mistyped anonymity instances

---

Tribler/community/tunnel/Socks5/conversion.py

Report the address type we don't support

---

Tribler/Core/DownloadConfig.py
Tribler/Core/Utilities/configparser.py
Tribler/Main/globals.py

Fix 1821 dlconfig read file

---

Tribler/Core/Utilities/instrumentation.py

To avoid a rare race condition

Lock-wrapped checks

---

doc/Tribler development on OS X.md

The part about the manual installation was incomplete. I've added some more information about the installation process.

Added more details about the wx installation in the OS X guide

---

Tribler/Main/Dialogs/CreateTorrentDialog.py

As libtorrent is expecting a char*
Fixes #1829

Encode the comment text in UTF-8.

---

Tribler/Main/vwxGUI/list_details.py

Fix tracker URL decoding

---

doc/Tribler development on Windows.md

Removed plyvel as a dependency, written about the compilation process of leveldb.

Written about the compilation of leveldb

---

Tribler/vlc.py

This update breaks vlc DLL loading on windows.
This reverts commit 4cc48baa11ac976493dc3d08aa865cfcff0ab303.

Revert "Update vlc.py from upstream"

---

Tribler/community/tunnel/tunnel_community.py

Raise max transfer limit to 250MB

---

Tribler/Core/Session.py
Tribler/Core/Upgrade/torrent_upgrade65.py
Tribler/Core/Upgrade/upgrade.py
Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/gaugesplash.py

This fixes all issues introduced by @lfdversluis on the upgrade procedure (that I could find).

Multiple fixes for the startup/upgrade procedure

---

Tribler/Core/APIImplementation/maketorrent.py
Tribler/Main/Dialogs/FeedbackWindow.py
Tribler/Main/Dialogs/SaveAs.py
Tribler/Main/channelcast_supporter.py
Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/GuiUtility.py
Tribler/Main/vwxGUI/MainFrame.py
Tribler/Main/vwxGUI/gaugesplash.py
Tribler/Main/vwxGUI/home.py
Tribler/Main/vwxGUI/list_details.py
Tribler/Test/test_gui_dialogs.py

Devel stable fix PR

---

Tribler/Main/vwxGUI/home.py

The background color of the network graph is now white.

Fixed #1907

---

doc/Tribler development on Linux.md

I just managed to find out which packages are needed for Arch Linux (they have slightly different package names) and thought it would be nice if they could be found in here.

Add Arch Linux dependencies

---

tribler.sh

Added conditional statement for Cygwin environment

---

doc/Building Tribler on Windows.md

This file explains how to build a Windows installer for Tribler (32 and 64 bit).

Create Building Tribler on Windows.md

---

Tribler/Main/vwxGUI/gaugesplash.py

This reverts commit 0b6037dd78106b0a670dff4b773a97ae3a98c8ee.

Revert "Do a Yield() instead of a SafeYield()"

---

Tribler/Main/Utility/utility.py
Tribler/Main/vwxGUI/SRstatusbar.py
Tribler/community/bartercast4/statistics.py

Snorberhuis never got to implementing front page counters for the tunnel community. I did them as a first assignment in Tribler. I'd kinda forgotten about them. I tidied up the status bar logic a little bit while I was at it. And a few nitpicks.

Counters for total tunnel usage and net result

---

Tribler/Main/vwxGUI/widgets.py

fixed bitmap error

---

README.md

Now pointing to the doc/ folder containing the full guide.

Updated the package instructions for windows

---

Tribler/Core/Utilities/utilities.py

These lines will never trigger.

Removed check for length in info metadata

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Core/leveldbstore.py

Found some unused imports and lines

Removed unused lines and imports

---

Tribler/Main/vwxGUI/SearchGridManager.py

Fix expandedPanel_videoplayer is None on Mac

---

Tribler/Core/Libtorrent/LibtorrentMgr.py

I forgot to remove this one apparently...

Removed wrong logger statement

---

Tribler/Core/SessionConfig.py
Tribler/Main/hacks.py
Tribler/Main/tribler_exe.py
Tribler/community/tunnel/tunnel_community.py

Use the unicode API to obtain the PATH on windows

---

Tribler/Test/Community/Tunnel/__init__.py
Tribler/Test/Community/Tunnel/test_tunnel_base.py
Tribler/Test/Community/Tunnel/test_tunnelcommunity.py
Tribler/Test/Community/__init__.py
Tribler/community/tunnel/tunnel_community.py

I found a bug when some data was printed in the `TunnelCommunity` (when performing the string formatting, more parameters than expected were passed).
Also, I attempted to setup a unit testing framework to test the tunnel community and I've written some small tests. It would be nice if we can write some more unit tests for this and the other communities.

Fixed a bug in tunnel community and written some small tests for it

---

README.md

The instructions for running tribler were missing some important steps

Update instructions for running tribler

---

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py

Since libtorrent 1.0.9 (or maybe earlier), function `files()` on `torrent_info` object returned a `file_storage` object, instead of dictionary. I think it's safe to update the function usage to a new one.
This PR will fix that problem.

Update files() call on torrent_info

---

Tribler/Main/Build/Win32/setuptribler.py
Tribler/Main/Build/Win32/tribler.nsi
win/makedist.bat

@whirm Can you give this build script a go on the builder? Or can I do it?
Fixes #2049
Fixes **1** bug.

Now packing and installing windows c++ redistributable 2008 and 2010

---

Tribler/Core/Modules/restapi/my_channel_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_my_channel_endpoints.py
doc/Tribler REST API.md

In this PR, I've implemented the endpoint to fetch torrents that are present in your channel. I've also refactored some methods into a base class so they can be reused easier in future endpoint implementations.

Implemented my channel torrents endpoint

---

Tribler/Core/Modules/restapi/root_endpoint.py
Tribler/Core/Modules/restapi/variables_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_variables_endpoint.py
doc/Tribler REST API.md

This PR implements the endpoint to fetch runtime-defined variables.

Implemented variables endpoint

---

Tribler/Core/Modules/restapi/my_channel_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_my_channel_endpoints.py
doc/Tribler REST API.md

And another one! This one implements the endpoint to fetch RSS feeds used by your channel.

Implemented the RSS feeds endpoint

---

Tribler/Core/Modules/restapi/channels_endpoint.py
Tribler/Core/Modules/restapi/root_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_channels_endpoints.py
doc/Tribler REST API.md

This endpoint returns information about the channels the user is subscribed to.

Implemented the subscribed channels endpoint

---

Tribler/Core/SessionConfig.py
Tribler/Core/osutils.py
Tribler/Test/Core/test_osutils.py

Set proper paths on devices running Android and fetch the run-time API version.

osutils.py rewrite is_android() using get_android_api_version()

---

Tribler/Core/Modules/restapi/channels_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_channels_endpoints.py
doc/Tribler REST API.md

Also did some small refactoring in `channels_endpoint.py`.

Implemented endpoint to fetch all channels in Tribler

---

Tribler/Core/Modules/restapi/my_channel_endpoint.py
Tribler/Test/Core/Modules/RestApi/base_api_test.py
Tribler/Test/Core/Modules/RestApi/test_my_channel_endpoints.py
doc/Tribler REST API.md

I also did some refactoring of test files (since we have to support other requests than `GET` now).

Implemented endpoint to add a rss feed to your channel

---

Tribler/Core/Modules/restapi/my_channel_endpoint.py
Tribler/Test/Core/Modules/RestApi/base_api_test.py
Tribler/Test/Core/Modules/RestApi/test_my_channel_endpoints.py
doc/Tribler REST API.md

This PR implements the endpoint to remove a rss feed from your channel. Also, I completely refactored the endpoint to add a RSS feed in the process to make it more REST.

Implemented endpoint to remove a rss feed from your channel

---

Tribler/Core/Session.py
Tribler/Core/version.py
Tribler/Main/tribler_exe.py
debian/changelog

Port all fixes from `next` to `devel`

Next to devel

---

Tribler/Test/Core/Modules/RestApi/base_api_test.py

Split complexity of chained callbacks from simpler base class.

minor refactor basetest

---

Tribler/Core/CacheDB/sqlitecachedb.py
Tribler/Test/Core/test_sqlitecachedb.py

Fixes **1** bug
Adds **2** tests
Fixes #2234

Issue 2234 fix delete sqlitecachedb

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Test/Community/Tunnel/test_tunnelcommunity.py
Tribler/community/tunnel/tunnel_community.py

Several improvements to the tunnel community.
The biggest one: #2169 becuase it freezes the GUI which is undesirable to say the least.
Not waiting for stopListening bug: #2124 
Several logging levels lowered:  #2201
Fixes **2** bugs, unresponsiveness and not waiting for the UDP socket to close.
**3** enhancements: logging level, removed unused argument from TunnelSettings and more docstring
Adds **2** tests
Fixes #2169, Fixes #2124 , Fixes #2201

Tunnel community improvements

---

Tribler/Main/Utility/utility.py
Tribler/Test/Main/Utility/test_size_format.py
Tribler/Test/Main/Utility/test_speed_format.py

Test cases just test the current behaviour. Refactoring size_format might be usefull after Qt transition.

Fixes #2188, added test cases for byte formatting methods

---

Tribler/Core/Modules/restapi/channels_endpoint.py
Tribler/Core/Modules/restapi/my_channel_endpoint.py
Tribler/Core/Modules/restapi/search_endpoint.py
Tribler/Core/Session.py
Tribler/Core/TorrentDef.py
Tribler/Core/exceptions.py
Tribler/Test/Core/Modules/RestApi/test_my_channel_endpoints.py
Tribler/Test/Core/test_session.py
doc/Tribler REST API.md

Current code resides in Main and must be refactored to Core.

Add torrent to channel

---

Tribler/Core/TorrentChecker/session.py

Removed one of the double transaction_id fields

---

Tribler/Core/Modules/tracker_manager.py
Tribler/Core/TorrentChecker/torrent_checker.py

Issue 2183 fix update tracker

---

.pylintrc

Disable:
- invalid-name
- missing-docstring
- missing-type-doc

Ignore some pylint checks for now

---

Tribler/Core/TorrentDef.py
Tribler/Core/Upgrade/pickle_converter.py
Tribler/Test/Core/Modules/Channel/test_channel_rss.py
Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_my_channel_endpoints.py

Fixes #2289, fixes #2290, fixes #2291, fixes #2288.

Fixed various race conditions/errors in the tests

---

Tribler/Test/Core/test_session.py

Refactored create channel tests to wait for notification

---

Tribler/Core/Modules/restapi/events_endpoint.py
Tribler/Core/Modules/restapi/rest_manager.py
Tribler/Core/Modules/restapi/root_endpoint.py
Tribler/Core/Modules/restapi/search_endpoint.py
Tribler/Core/Modules/restapi/util.py
Tribler/Core/TorrentDef.py
Tribler/Test/Core/Modules/RestApi/test_channels_endpoints.py
Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_util.py
Tribler/Test/Core/test_torrent_def.py
doc/Tribler REST API.md

As requested by @brussee, some rest API fixes.
Fixes #2287

REST API fixes

---

Tribler/Category/Category.py
Tribler/Test/Category/test_category.py

Removed general excepts from category.py

---

doc/Building Tribler on Windows.md

As we have recompiled them and adjusted our build script accordingly.

Removed the MSVC100 dependency requirement.

---

Tribler/Main/tribler_main.py
Tribler/Main/tribler_profiler.py
Tribler/Test/test_tribler_profile.py

Fixes **1** bug
Adds **1** test
Adds the option to write the stats to a specified environment variable (feature).
Fixes #2227

Fix and upgrade profiler

---

Tribler/Test/Community/Multichain/test_multichain_community.py
Tribler/community/multichain/database.py

Multichain half signed value fix

---

Tribler/Test/Community/AbstractTestCommunity.py
Tribler/Test/Community/Tunnel/test_tunnel_base.py
Tribler/Test/Community/channel/__init__.py
Tribler/Test/Community/channel/test_channel_base.py
Tribler/Test/Community/channel/test_channel_community.py
Tribler/community/channel/community.py

Refactored general except in channel community

---

Tribler/Category/filter_terms.filter

This was messing up my tests lol...

Removed 'channel' term from filter terms

---

Tribler/Main/vwxGUI/home.py
Tribler/Test/Community/Multichain/test_multichain_community.py
Tribler/community/multichain/community.py
Tribler/community/multichain/database.py

This adds basic multichain info in the debug panel.
I have not been super strict on the pep8, because:
1) all the other wx stuff is using old style (e.g. CamelCase)
2) The wx gui will be eliminated in the foreseeable future

Add a basic debug interface for the multichain

---

Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
doc/restapi/downloads.rst

Now with automatic doc generation :)

Implemented endpoints to remove, resume and stop downloads

---

doc/requirements.txt

Added requirements.txt file to doc

---

Tribler/Test/Core/Modules/RestApi/test_channels_endpoints.py

This check can safely be removed since the check whether there are exactly 10 channels in the result JSON is enough.
Fixes #2333

Changed check when fetching discovered channels in tests

---

Tribler/Test/Community/Tunnel/test_tunnelcommunity.py
Tribler/community/tunnel/routing.py
Tribler/community/tunnel/tunnel_community.py

Tunnel increase bytes fix

---

Tribler/Core/Upgrade/upgrade.py
Tribler/Test/Core/Upgrade/test_upgrader.py

Causing problems when the upgrader has to do work :(

Fixed bug when broadcasting upgrade tick

---

Tribler/Policies/BoostingManager.py
Tribler/Test/Core/CreditMining/test_creditmining_sys.py

This PR will fix changed iteration size error in selecting torrents.
Referred in issue #2348

Fix changed iteration size error in selecting torrents

---

Tribler/Core/Utilities/twisted_utils.py

Check if threadpool is None

---

README.rst

Found another reference to the now moved .md file.

Fix another .md to .rst reference.

---

Tribler/Test/Core/CreditMining/test_creditmining.py
Tribler/Test/Core/CreditMining/test_creditmining_sys.py

Disabled credit mining tests

---

Tribler/Core/osutils.py

Android code coverage coming soon :) #2387

fix unicode path warning on android

---

setup.py

Nose now runs the Tribler tests on Android.

WIP: use setuptools and update setup.py with readme and license

---

Tribler/Main/vwxGUI/home.py

READY: Clear up a multichain log message

---

Tribler/community/multichain/database.py

Relying on MAX() to leave the right row under the cursor for non-aggregate query results is explicitly not guaranteed to work in sqlite.

Fix Multichain aggregation SQL queries

---

Tribler/Test/Community/Multichain/test_multichain_community.py

Skip multichain test

---

Tribler/Core/CacheDB/Notifier.py
Tribler/Core/Modules/restapi/events_endpoint.py
Tribler/Core/simpledefs.py
Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py
Tribler/community/channel/community.py

This is used in the new GUI to dynamically update the number of channels/torrents.

Added events on torrent/channel discovery

---

debian/control

add setuptools dependency for setup.py to debian control

---

Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Core/Modules/restapi/channels/channels_torrents_endpoint.py
Tribler/Core/Modules/versioncheck_manager.py
Tribler/Core/TorrentDef.py
Tribler/Core/Utilities/utilities.py
Tribler/Core/exceptions.py
Tribler/Main/vwxGUI/home.py
Tribler/Test/Core/CreditMining/test_creditmining.py
Tribler/Test/Core/CreditMining/test_creditmining_sys.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_torrents_endpoint.py
Tribler/Test/Core/test_torrent_def.py

Refactor from url

---

Tribler/Main/tribler_main.py

@whirm gui callback on WxThread

fix callback from main thread

---

Tribler/Test/Core/TFTP/__init__.py
Tribler/Test/Core/TFTP/test_tftp_handler.py
Tribler/Test/Core/TFTP/test_tftp_packet.py

I noticed that the coverage of the TFTP package regarding error handling is very bad, so I took some time to write tests for the error handling mechanism.

Written some tests for TFTP error handling

---

Tribler/Core/Modules/restapi/channels/channels_subscription_endpoint.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_subscription_endpoint.py

Since it is not necessary for the channel to be discovered in order to subscribe to this channel.

Removed check when subscribing to channel

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/Modules/restapi/root_endpoint.py
Tribler/Core/Modules/restapi/shutdown_endpoint.py
Tribler/Core/Session.py
Tribler/Test/Core/Modules/RestApi/test_shutdown_endpoint.py

Includes fixes in session to gracefully shutdown.

Shutdown endpoint

---

Tribler/Core/defaults.py
Tribler/Test/Community/Multichain/test_multichain_database.py
Tribler/Test/test_as_server.py
Tribler/Test/test_tunnel_base.py
Tribler/community/multichain/community.py
Tribler/community/multichain/database.py
Tribler/community/tunnel/hidden_community_multichain.py

Prep mc for exp release

---

.gitignore
Tribler/Core/Modules/restapi/shutdown_endpoint.py

fixes broken http connection on shutdown

send response on shutdown

---

Tribler/Core/Modules/restapi/create_torrent_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_create_torrent_endpoint.py

Create torrent REST API endpoint changed to POST

---

Tribler/Main/Build/Mac/setuptriblermac_64bit.py
Tribler/Main/Build/Win/tribler.nsi
debian/tribler.install
mac/makedistmac_64bit.sh
win/makedist_win.bat

This should fix the builders for the devel branch again.

Fixed various builder issues after moving the Category package

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Core/Category/Category.py
Tribler/Core/Upgrade/db_upgrader.py
Tribler/Main/tribler_main.py
Tribler/Main/vwxGUI/GuiUtility.py
Tribler/Main/vwxGUI/MainFrame.py
Tribler/Main/vwxGUI/SearchGridManager.py
Tribler/Main/vwxGUI/channel.py
Tribler/Main/vwxGUI/home.py
Tribler/Main/vwxGUI/list.py
Tribler/Main/vwxGUI/list_header.py
Tribler/Test/Core/Category/test_category.py
Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py

Since singletons makes testing significantly harder, I removed the singleton pattern from the `Category` class. This is not the only singleton but it contributes towards #2286.

Category is not a singleton anymore

---

Tribler/Core/Config/config.spec
Tribler/Core/Config/tribler_config.py
Tribler/Core/Modules/restapi/channels/channels_discovered_endpoint.py
Tribler/Core/Modules/restapi/channels/channels_playlists_endpoint.py
Tribler/Core/Modules/restapi/channels/channels_popular_endpoint.py
Tribler/Core/Modules/restapi/channels/channels_torrents_endpoint.py
Tribler/Core/Modules/restapi/events_endpoint.py
Tribler/Test/Core/Config/test_tribler_config.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_endpoint.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_playlist_endpoint.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_popular_endpoint.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_torrents_endpoint.py
Tribler/Test/Core/Modules/RestApi/base_api_test.py
Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py

So we can hide inappropriate content in the GUI.

Implemented the family filter in the API

---

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Test/Core/CreditMining/mock_creditmining.py
Tribler/Test/Core/CreditMining/test_creditmining.py
Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py

This information is displayed in the GUI.

Added peer info to get downloads endpoint

---

Tribler/Core/Modules/restapi/root_endpoint.py
Tribler/Core/Modules/restapi/statistics_endpoint.py
Tribler/Core/RemoteTorrentHandler.py
Tribler/Core/Session.py
Tribler/Core/statistics.py
Tribler/Main/vwxGUI/home.py
Tribler/Test/Core/Modules/RestApi/test_statistics_endpoint.py
Tribler/Test/test_as_server.py
doc/restapi/introduction.rst
doc/restapi/statistics.rst

These statistics are displayed in the debug panel of the new GUI.

Created various endpoints to fetch Tribler, Dispersy and community statistics

---

Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Core/Session.py
Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
Tribler/Test/Core/test_network_utils.py

It's weird that I did not implement this one yet.

Added endpoint to start a download from an URI

---

README.rst
Tribler/Core/Modules/restapi/events_endpoint.py
Tribler/Core/Modules/restapi/settings_endpoint.py
Tribler/Core/Modules/restapi/torrents_endpoint.py
Tribler/Core/Modules/restapi/util.py
Tribler/Core/version.py
Tribler/Main/tribler_main.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_subscription_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_torrents_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_util.py
doc/development/development_on_linux.rst
doc/development/development_on_osx.rst
doc/development/development_on_windows.rst
twisted/plugins/tribler_plugin.py

This PR contains various fixes for Tribler 7.
Fixes #2581, fixes #2568, fixes #2580, fixes #2433, fixes https://github.com/devos50/tribler/issues/9

WIP: Various fixes for Tribler 7

---

Tribler/Core/Category/filter_terms.filter
Tribler/Core/Modules/restapi/channels/channels_torrents_endpoint.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_torrents_endpoint.py

Also removed some terms from the family filter list.

Fixed filter when fetching torrents in your own channel

---

Tribler/Test/Core/CreditMining/mock_creditmining.py
Tribler/Test/Core/CreditMining/test_creditmining.py

This pull request removed bloated session launching in simple credit mining test.

Remove unnecessary bloated session in credit mining tests

---

doc/conf.py

Fixed readthedocs compilation of API

---

Tribler/Test/Community/Bartercast/test_bartercast4_community.py
Tribler/Test/Core/Modules/RestApi/test_torrents_endpoint.py

Obviously, we should break out of the for-loop if we satisfy the test condition.

Fixed error in tests

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Core/Modules/restapi/events_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py
Tribler/Test/Core/test_sqlitecachedbhandler_channels.py
twisted/plugins/tunnel_helper_plugin.py

Credits to @brussee for the remove torrent event (I didn't cherry-pick the commit).
Fixes #2239, fixes #2584

WIP: Removed cherrypy from tunnel helper, added torrent removed event

---

Tribler/Test/Community/Multichain/test_multichain_community.py
Tribler/community/multichain/community.py

Reenable a multichain test

---

Tribler/Core/TorrentChecker/session.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker_session.py

Fixed UnicodeDecodeError

---

.gitmodules
Tribler/Test/GUI/test_gui.py
TriblerGUI/widgets/downloadsdetailstabwidget.py
TriblerGUI/widgets/downloadspage.py

So it's more efficient regarding rendering of items.

Refactored download details widget panel

---

Tribler/Core/TorrentChecker/session.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker_session.py

Http session unicode fix

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Test/Community/Multichain/test_multichain_community.py
Tribler/Test/Community/Tunnel/test_routing.py
Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
Tribler/community/multichain/community.py
Tribler/community/tunnel/hidden_community.py
Tribler/community/tunnel/routing.py
Tribler/community/tunnel/tunnel_community.py
TriblerGUI/dialogs/startdownloaddialog.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/qt_resources/startdownloaddialog.ui
TriblerGUI/widgets/downloadsdetailstabwidget.py
TriblerGUI/widgets/downloadspage.py
TriblerGUI/widgets/downloadwidgetitem.py

This PR again contains various fixes for Tribler 7, including an option to change the anonymity level of a download and the ability to select multiple files for inclusion/exclusion during a download.
Fixes #2692, fixes #1013, fixes #2180, fixes #2181, fixes #2068, fixes #2262
Addressed various bullet points in #2668

Various fixes/improvements for Tribler 7

---

Tribler/Test/Community/Tunnel/test_tunnelcommunity.py
Tribler/community/tunnel/routing.py
Tribler/community/tunnel/tunnel_community.py

Fixes #2655.
Also fixes bug where RelayRoute mid initialization value was being ignored.

Made tunnel remove notification candidate immutable

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Core/Session.py
Tribler/Core/simpledefs.py
TriblerGUI/widgets/createtorrentpage.py
TriblerGUI/widgets/downloadsdetailstabwidget.py
TriblerGUI/widgets/editchannelpage.py

Some minor issues I encountered when testing/going through the issues
Fixes #1716, fixes #2278, fixes #2705

Various fixes tribler 7

---

Tribler/community/tunnel/tunnel_community.py

Fixed copy_shallow_candidate not decoding HEX mid

---

Tribler/Test/Community/Tunnel/Socks5/__init__.py
Tribler/Test/Community/Tunnel/Socks5/test_conversion.py
Tribler/community/tunnel/Socks5/conversion.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/widgets/downloadsdetailstabwidget.py

Various fixes for tribler 7

---

Tribler/Core/Modules/restapi/rest_manager.py
Tribler/Test/Core/TFTP/test_tftp_handler.py
Tribler/community/tunnel/tunnel_community.py
TriblerGUI/widgets/downloadprogressbar.py

Fixed tftp test, improved piece drawing algorithm, improved support for older Twisted versions, fixed TunnelExitSocket error

---

Tribler/Test/Community/Tunnel/test_tunnelcommunity.py
Tribler/community/tunnel/tunnel_community.py

Remove tunnel always notifies with a valid Candidate

---

CONTRIBUTING.rst
README.rst
doc/building/building_on_windows.rst
doc/development/development_on_linux.rst
doc/development/development_on_osx.rst
doc/development/development_on_windows.rst

Fixed spelling errors in documentation

---

Tribler/Core/CreditMining/BoostingSource.py

Fix possible duplicate task on updating channel

---

Tribler/Core/Modules/restapi/rest_manager.py
Tribler/Test/GUI/test_gui.py
TriblerGUI/core_manager.py
TriblerGUI/defs.py
TriblerGUI/event_request_manager.py
TriblerGUI/tribler_request_manager.py
TriblerGUI/tribler_window.py
doc/development/development_on_linux.rst

Fixes #2807, fixes #2790, fixes #2806

READY: Various fixes for Tribler 7

---

Tribler/Core/APIImplementation/LaunchManyCore.py

Fixed formatting bug

---

Tribler/Main/hacks.py

Remove get_unicode_sys_argv() from hacks.py

---

Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
TriblerGUI/tribler_window.py
TriblerGUI/widgets/createtorrentpage.py
TriblerGUI/widgets/downloadsdetailstabwidget.py

Fixes #2832 
Also contains fixes for some unicode issues.

READY: Including/excluding files now uses file indices instead of file names

---

twisted/plugins/tribler_plugin.py

HTTP API re-enable in twisted plugin fix

---

Tribler/Main/hacks.py

The comment I removed is about a previous workaround which is already removed.

Remove irrelevant comment in Main.hacks

---

debian/tribler.docs

Simply point to the new location and name

Fixes issue #2867

---

Tribler/Core/TorrentDef.py
Tribler/Core/Utilities/maketorrent.py
Tribler/Core/Utilities/utilities.py
Tribler/Test/Core/test_torrent_def.py
Tribler/Test/Core/test_utilities.py

utilities.py refactor

---

doc/index.rst
doc/twisted101.rst

This should allow new recruits to get acquainted with Twisted's control flow.

Created a twisted 101 tutorial

---

systemd/multichain-crawler.service
twisted/plugins/multichain_crawler_plugin.py

Fixed the shutdown procedure and service file

Fixed Multichain crawler

---

TriblerGUI/core_manager.py
TriblerGUI/event_request_manager.py
TriblerGUI/tribler_request_manager.py

Fixed QIODevice error

---

Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
Tribler/Test/Community/channel/test_channel_conversion.py
Tribler/Test/Core/Modules/RestApi/test_torrentinfo_endpoint.py
Tribler/community/channel/conversion.py
TriblerGUI/tribler_request_manager.py

Fixed invalid torrent crashes

---

TriblerGUI/dialogs/confirmationdialog.py
TriblerGUI/tribler_window.py

Minor GUI improvements

---

TriblerGUI/tribler_request_manager.py
TriblerGUI/widgets/downloadspage.py

This PR should fix the notorious GUI freeze bug after a couple of days.
I've also added an additional dialog to specify the torrent name when a torrent is being exported.
Fixes #2941, fixes #2842

Fix gui freeze

---

win/makedist_win.bat

Fixed Windows signing

---

Tribler/Test/GUI/test_gui.py

By restoring a line that shouldn't have been removed.
@vandenheuvel @MaxVanDeursen

Fixed GUI tests on devel branch

---

Tribler/Test/Core/CreditMining/test_creditmining_sys.py

So we can talk with the bootstrap server again

Updated Dispersy pointer

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Core/Session.py
Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py
Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
Tribler/Test/Core/test_session.py

Deferred torrent removal

---

Tribler/community/trustchain/block.py

Fix decoding of time data from HEX

---

Tribler/Core/Modules/restapi/settings_endpoint.py
Tribler/Core/Utilities/configparser.py
Tribler/Test/Core/Modules/RestApi/test_settings_endpoint.py

Fixed settingsdict with unicode

---

Tribler/Core/Utilities/encoding.py
Tribler/Test/Core/Utilities/test_encoding.py

Turned encoding.py KeyError into ValueError

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Test/Core/CreditMining/test_creditmining_sys.py
Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py

Fixed minor issues in db tests

---

TriblerGUI/dialogs/startdownloaddialog.py

The anon checkbox currently isn't set based upon the setting in the config. This PR fixes that.

Set correct checkbox with settings

---

.github/ISSUE_TEMPLATE.md

Move "Steps to reproduce the behavior" above "Expected/Actual behaviour", as the latter follows from the former.

Reordered sections in issue template

---

Tribler/Core/CacheDB/sqlitecachedb.py
Tribler/Core/Config/tribler_config.py
Tribler/Core/Modules/restapi/trustchain_endpoint.py
Tribler/community/market/wallet/btc_wallet.py
Tribler/community/market/wallet/wallet.py
Tribler/community/trustchain/community.py
TriblerGUI/tribler_window.py
doc/development/development_on_linux.rst
doc/development/development_on_osx.rst
doc/development/development_on_windows.rst
tribler.spec

Fixes #3024, fixes #3023, fixes #3011, fixes #3008

Various devel fixes

---

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py

Checkpoint downloads earlier for persistence between restarts

---

Tribler/Core/Modules/channel/channel_rss.py
Tribler/Test/Core/Modules/Channel/test_channel_rss.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_rss_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_create_torrent_endpoint.py
Tribler/Test/test_as_server.py

This PR fixes the tests on the new Windows builder.

Fixed tests on new Windows builder

---

Tribler/Test/test_as_server.py

This PR attempts to find the thread pool leak

Reverted threadpool check

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/Modules/resource_monitor.py
Tribler/Core/Modules/restapi/debug_endpoint.py
Tribler/Core/SessionConfig.py
Tribler/Core/Utilities/instrumentation.py
Tribler/Core/defaults.py
Tribler/Test/Core/Modules/Channel/test_channel.py
Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py
Tribler/Test/Core/Modules/test_resource_monitor.py
Tribler/Test/Core/test_instrumentation.py
Tribler/Test/Core/test_sessionconfig.py
Tribler/Test/GUI/test_gui.py
TriblerGUI/debug_window.py
TriblerGUI/qt_resources/debugwindow.ui
TriblerGUI/qt_resources/mainwindow.ui

This PR extends the debug pane with more functionality and insights in the Tribler core process.
Features:
- Implemented a resource monitor that periodically polls CPU/memory usage and stores them. Settings for these resource monitor can be changed using the configuration file.
- Added endpoints to fetch information about threads/open sockets/open files/CPU history/memory history
- Added disk usage info to the debug pane
Screenshots:

Improved debug pane

---

Tribler/Core/Modules/restapi/downloads_endpoint.py

Fixed endpoint race condition for update_hops

---

TriblerGUI/tribler_window.py
TriblerGUI/widgets/downloadspage.py

Fixes #3014 
Confirmed fix for Ubuntu 17.04.

Fix for fd leak on Ubuntu 17.04

---

Tribler/Core/Modules/restapi/debug_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py
Tribler/Test/test_as_server.py
TriblerGUI/debug_window.py
TriblerGUI/qt_resources/debugwindow.ui
doc/development/development_on_linux.rst
doc/development/development_on_osx.rst
doc/development/development_on_windows.rst

This helps us to debug memory issues faster.

Added ability to perform a memory dump to the debug pane

---

Tribler/Main/Build/Win/tribler.nsi
win/makedist_win.bat

Added 2015 runtime to builder script
Updated windows dist bat file to copy missing dlls

Updated windows build

---

logger.conf
run_tribler.py
tribler.spec

Error & info logs  are now written to respective error.log & info.log files inside .Tribler directory for each platform

Error logging to log files inside .Tribler directory

---

Tribler/Core/Modules/restapi/debug_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py
Tribler/Test/GUI/test_gui.py
TriblerGUI/debug_window.py
TriblerGUI/qt_resources/debugwindow.ui

Added logs in debug pane along with tests for endpoint and the GUI

Logs tab in debug pane

---

Tribler/Core/Modules/restapi/create_torrent_endpoint.py
Tribler/Core/Utilities/torrent_utils.py
Tribler/Test/Core/Modules/RestApi/test_create_torrent_endpoint.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/widgets/createtorrentpage.py

Fix #3132 : Creating torrent in My Channel
Added name in the torrent creation. 
Added a label showing creating torrent

Fix #3132 : Creating torrent in My Channel

---

Tribler/Core/Modules/restapi/channels/channels_torrents_endpoint.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_torrents_endpoint.py
TriblerGUI/widgets/editchannelpage.py

Fixes #3152 Remove selected torrents button now deletes all selected torrents

Remove selected torrents button now deletes all selected torrents

---

TriblerGUI/tribler_window.py

Kill the tray icon on shutdown or error

---

TriblerGUI/tribler_request_manager.py

Fix #3166 request key error

---

Tribler/Core/Modules/restapi/channels/channels_subscription_endpoint.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_subscription_endpoint.py
TriblerGUI/tribler_window.py
TriblerGUI/widgets/discoveredpage.py
TriblerGUI/widgets/subscriptionswidget.py

Fixed #3168 request error on subscription to channel in search results, discovered and subscription page

Fix for request error on subscription to a channel

---

Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
Tribler/Core/Utilities/utilities.py
Tribler/Test/Core/Modules/RestApi/test_torrentinfo_endpoint.py
Tribler/Test/Core/Utilities/test_utilities.py
TriblerGUI/dialogs/startdownloaddialog.py
TriblerGUI/tribler_window.py

Fix adding torrents with URI escape chars

---

TriblerGUI/widgets/subscriptionswidget.py

Fixed endless querying of SubscriptionsWidget

---

TriblerGUI/dialogs/feedbackdialog.py

READY: Added confirmation pop-up on successful error report send

---

Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py

Fixes #3059
Confirmed to fail with message of #3059 without 2 line fix.

Fixed illegal fields being passed in downloads_endpoint

---

Tribler/Core/Modules/resource_monitor.py
Tribler/Test/Core/Modules/test_resource_monitor.py

Added try for memory_full_info

---

TriblerGUI/widgets/channel_torrent_list_item.py

Fixed callback while channel_torrent item is removed

---

Tribler/Core/Modules/restapi/torrentinfo_endpoint.py

Fixed torrentinfo endpoint not catching HTTP errors

---

Tribler/Core/TFTP/handler.py
Tribler/Test/Core/TFTP/test_tftp_handler.py

(cherry picked from commit 8ac32d542c0cf51942b74a50af24a3be4820f354)
Fixes #3200

Stop handling TFTP request if metadatastore is not enabled

---

Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
Tribler/Core/Modules/restapi/torrents_endpoint.py

Added request finished checks

---

Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py

Fix gui extended peer info

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Core/Modules/restapi/torrents_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_torrents_endpoint.py
Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/qt_resources/torrent_channel_list_container.ui
TriblerGUI/tribler_window.py
TriblerGUI/widgets/channel_torrent_list_item.py
TriblerGUI/widgets/channelpage.py
TriblerGUI/widgets/lazyloadlist.py
TriblerGUI/widgets/searchresultspage.py
TriblerGUI/widgets/torrentdetailstabwidget.py

Added details tab when you click on a torrent

---

TriblerGUI/tribler_window.py

Added check for None search completions

---

Tribler/Main/Build/Win/tribler.nsi

Fixed the issue with uninstaller location.

Fix uninstaller location issue

---

TriblerGUI/tribler_window.py
TriblerGUI/widgets/searchresultspage.py

Filtered duplicate torrents and channels from search results and added a delay of 500ms for same query search

Filtered duplicate search results

---

check_os.py
run_tribler.py

Fix #3247 
- Checked for insufficient disk space before running Tribler GUI
- Additionally, placed the error dialog to the center of screen

Checked for insufficient disk space before running Tribler GUI

---

TriblerGUI/dialogs/confirmationdialog.py
TriblerGUI/dialogs/startdownloaddialog.py
TriblerGUI/tribler_window.py
TriblerGUI/utilities.py

Checked if there is sufficient write permission on the download path before attempting to download the torrent.

Fix for download path write permission issue

---

Tribler/Core/TFTP/handler.py
Tribler/Test/Core/TFTP/test_tftp_handler.py

Fixed TFTP handler not filtering out illegal candidates

---

README.rst

- Added shield.io badges for downloads, issues and pull requests.
- Updated the run command in windows

Updated README with statistics

---

Tribler/Core/TorrentChecker/session.py
Tribler/Core/TorrentChecker/torrent_checker.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker_session.py

Fixes https://github.com/Tribler/tribler/issues/3269.

Use a single UDP socket while scraping trackers

---

Tribler/Core/DecentralizedTracking/mainlineDHT.py
Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py
Tribler/community/triblerchain/community.py
Tribler/community/tunnel/hidden_community.py
Tribler/community/tunnel/tunnel_community.py

Companion to [Gumby PR #330](https://github.com/Tribler/gumby/pull/330)
This is mainly an edit of LibTorrentMgr's session creation code.

Changes to LibTorrentMgr to enable gumby DHT isolation

---

Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py

Increased timeout of memory dump test

---

TriblerGUI/dialogs/feedbackdialog.py
TriblerGUI/widgets/searchresultspage.py

I've also added the most recent events to the crash report.
Fixes #3276

Fixed overflow of insertion when searching for torrents

---

Tribler/Core/leveldbstore.py
TriblerGUI/tribler_window.py

Contributes to #3200 but does not fix it.
Fixes #3284

Reraising exception during leveldb creation + fixed GUI bug

---

TriblerGUI/widgets/searchresultspage.py

Improved search result display

---

Tribler/Core/Modules/restapi/debug_endpoint.py
Tribler/Core/SessionConfig.py
Tribler/Core/defaults.py
Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py
Tribler/Test/Core/test_sessionconfig.py
Tribler/Test/GUI/test_gui.py
TriblerGUI/core_manager.py
TriblerGUI/debug_window.py
TriblerGUI/qt_resources/debugwindow.ui
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/widgets/settingspage.py
check_os.py
run_tribler.py

Separated core and GUI logs and added a custom log directory option in settings

Custom log directory with separate core and GUI logs

---

Tribler/Core/TorrentChecker/session.py
Tribler/Core/TorrentChecker/torrent_checker.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker_session.py

READY: Fixed socket error in torrent checker

---

Tribler/Core/Modules/channel/channel.py
Tribler/Core/Modules/channel/channel_rss.py
Tribler/Core/Modules/restapi/channels/channels_rss_endpoint.py
Tribler/Test/Core/Modules/Channel/test_channel_rss.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_rss_endpoint.py
Tribler/Test/data/test_rss.xml

RSS parser is using twisted now to fetch feeds

---

Tribler/Test/GUI/test_gui.py
TriblerGUI/utilities.py

Checked for the path is writable even if it does not exist.

Check for writable permission on path

---

Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py

Fixes https://github.com/Tribler/tribler/issues/3289.

fix duplicate download exception

---

Tribler/Core/Modules/restapi/debug_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py

Fixes #3330 
This PR closes the file handlers opened by the DebugEndpoint.
This PR also fixes the Windows unittest segfault.

Fix DebugEndpoint file leak

---

TriblerGUI/debug_window.py

Catching AccessDenied error for psutil in GUI

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Test/Core/Upgrade/test_upgrader.py
TriblerGUI/debug_window.py

Decoupled loading of multichain community from tunnel community

---

Tribler/Core/APIImplementation/LaunchManyCore.py

Added check when removing torrent in periodic cb

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/CacheDB/sqlitecachedb.py
Tribler/Core/leveldbstore.py
Tribler/Test/Core/test_launch_many_cores.py
Tribler/Test/Core/test_sqlitecachedb.py

Checked LevelDB and SQLite databases for common startup errors.

Startup checks for LevelDB and SQLite database errors

---

TriblerGUI/widgets/channel_torrent_list_item.py
TriblerGUI/widgets/downloadwidgetitem.py

Catching RuntimeError on cancel GUI health request

---

README.rst

Updated the downloads count badge for RC-5

Update the badge for RC-5 stats

---

TriblerGUI/widgets/lazyloadlist.py

Not manually keeping track of loaded items anymore

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Core/Modules/restapi/events_endpoint.py
Tribler/Core/Modules/restapi/util.py
Tribler/Core/Session.py
Tribler/Test/Community/Market/Integration/test_market_base.py
Tribler/Test/Community/Search/FullSession/test_search_community.py
Tribler/Test/Community/Tunnel/FullSession/test_tunnel_base.py
Tribler/Test/Core/Modules/RestApi/test_util.py
Tribler/Test/Core/Modules/channel/test_channel_manager.py
Tribler/Test/Core/Modules/test_tracker_manager.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker_session.py
Tribler/Test/Core/Upgrade/upgrade_base.py
Tribler/Test/Core/test_session.py
Tribler/Test/Core/test_sqlitecachedbhandler.py
Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py
Tribler/Test/test_as_server.py
Tribler/Test/test_remote_torrent_handler.py

Solves #2286, requires https://github.com/Tribler/tribler/pull/3372.

Remove session singleton

---

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Test/Core/CreditMining/mock_creditmining.py
Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py
Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py

Also removed country resolution.
Fixes #3377

Fixed compatibility with libtorrent 1.1.0 and up (next)

---

TriblerGUI/debug_window.py
TriblerGUI/tribler_window.py

Fixed multiple debug window.
Positioned the debug window at the screen center.

Fix multiple debug window

---

Tribler/Core/Modules/restapi/trustchain_endpoint.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/widgets/trustpage.py

Fixed a bug that was introduced during the latest next to devel backport. Also fixed a bug in the trust screen.

Various GUI fixes

---

TriblerGUI/defs.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/tribler_window.py
TriblerGUI/widgets/loadingpage.py

Added force shutdown button on closing Tribler window.
Fixes #3386

Force shutdown

---

Tribler/Core/Modules/channel/channel_rss.py
Tribler/Test/Core/Modules/Channel/test_channel_rss.py
Tribler/community/tunnel/routing.py
tribler.spec

This PR hides the consoles in a built Tribler executable.
**Please wait with merging this.**

Hiding console on Windows and macOS

---

README.rst

Updated Tribler 7 downloads badge

Updated Tribler 7 downloads badge

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/Config/tribler_config.py
Tribler/Core/Modules/restapi/settings_endpoint.py
Tribler/Core/Upgrade/config_converter.py
Tribler/Test/Core/Modules/RestApi/test_settings_endpoint.py
Tribler/Test/Core/Upgrade/test_config_upgrade_70_71.py
Tribler/Test/Core/data/config_files/libtribler70.conf
TriblerGUI/core_manager.py
TriblerGUI/tribler_window.py
TriblerGUI/widgets/marketpage.py
debian/tribler.install

fixes #3395, fixes #3114, fixes #3407, fixes #3051, fixes #3235.

Fixed a few issues on devel

---

TriblerGUI/qt_resources/mainwindow.ui

Thanks to user [Frost_Azimov from tweakers.net](https://tweakers.net/nieuws/134585/nieuwe-tribler-release-integreert-blockchain-voor-bandbreedte-tokens.html?showReaction=11105659#r_11105659).

Change 'which' to 'who' in string

---

.gitmodules
Tribler/Core/APIImplementation/IPv8EndpointAdapter.py
Tribler/Core/APIImplementation/IPv8Module.py
Tribler/Core/APIImplementation/LaunchManyCore.py

Added the IPv8 stack (without loaded communities) onto the existing Dispersy endpoint.

Hooked IPv8 into MIMEndpoint

---

Tribler/Core/APIImplementation/IPv8Module.py
Tribler/Core/APIImplementation/LaunchManyCore.py

This was causing a crash on Windows.

Fixed IPv8 key loading from file

---

Tribler/Core/Modules/restapi/channels/channels_torrents_endpoint.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_torrents_endpoint.py

Fixed timeout issue on adding a torrent to the channel.
Fixes #3415  `exceptions.TypeError: Strings are not supported by Failure`

Fixed timeout issue on adding a torrent to the channel

---

Tribler/Core/Modules/resource_monitor.py

Fixed typo for required free disk size

Fix typo for required free disk size

---

TriblerGUI/widgets/editchannelpage.py

Fix RSS feed removal issue.
Fixes #3432

Fix RSS feed removal issue

---

TriblerGUI/widgets/settingspage.py

Fixed overflow error with bandwidth limits.
Fixes #3431

Fix overflow error with bandwidth limits

---

TriblerGUI/dialogs/startdownloaddialog.py
TriblerGUI/tribler_window.py
TriblerGUI/widgets/settingspage.py

Fixed Unicode issue with default download location and recent downloads lists.
Fixes #3421 ,  #3430

Fix Unicode issue

---

Tribler/Test/Community/Tunnel/FullSession/test_hidden_services.py
Tribler/Test/Community/Tunnel/FullSession/test_tunnel_base.py
Tribler/Test/Community/Tunnel/test_community.py
Tribler/community/triblertunnel/community.py

8 Session setup overhead: 10 seconds
Libtorrent file transfer time: 27 seconds
Fixes #3464

Re-added hidden services test

---

TriblerGUI/debug_window.py
TriblerGUI/event_request_manager.py
TriblerGUI/tribler_window.py

Added Tribler version to title bar in GUI

---

TriblerGUI/core_manager.py
TriblerGUI/tribler_request_manager.py

Now request dispatcher dispatches the request to available request worker (QNetworkAccessManager) to process the request.

Added Tribler request dispatcher with a multiple priority request pools

---

Tribler/Core/Utilities/utilities.py
Tribler/Test/Core/test_utilities.py

Fixes #3441 : NotImplementedError: SSL support unavailable

Fixed SSL support with treq

---

Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
TriblerGUI/tribler_window.py

Few fixes for the quote issues with the URIs.
Fixes #3509

Fixes for quotes on file URI

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Core/Modules/restapi/wallets_endpoint.py
Tribler/Test/Community/Market/Wallet/test_btc_wallet.py
Tribler/Test/Community/Market/test_community.py
Tribler/Test/Community/Market/test_database.py
Tribler/Test/Community/Market/test_tick.py
Tribler/Test/Community/Triblerchain/test_community.py
Tribler/Test/Core/Modules/RestApi/test_market_endpoint.py
Tribler/community/market/community.py
Tribler/community/market/core/tick.py
Tribler/community/market/database.py
Tribler/community/market/payload.py
Tribler/community/market/reputation/temporal_pagerank_manager.py
Tribler/community/market/wallet/btc_wallet.py
Tribler/community/triblerchain/block.py
Tribler/community/triblerchain/community.py
Tribler/community/triblertunnel/community.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/widgets/marketwalletspage.py

Again, a PR with various improvements for the market.
The most important change in this PR is that I've added an order book synchronization mechanism back. It uses bloom filters to minimize the amount of traffic exchanged between market participants. I've also added a ping mechanism to discover offline matchmakers (and they are now automatically removed from the `self.matchmakers` set).
Finally, I've fixed a few bugs regarding record signing in TriblerChain.

Various improvements for the market

---

TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/widgets/downloadwidgetitem.py
tribler.spec

Some fixes for 7.1

---

Tribler/Core/TFTP/exception.py
Tribler/Core/TFTP/packet.py
Tribler/Test/Community/Tunnel/FullSession/test_tunnel_base.py
Tribler/Test/Core/Modules/RestApi/test_market_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_trustchain_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_wallets_endpoint.py
Tribler/Test/Core/TFTP/test_tftp_packet.py
Tribler/Test/test_as_server.py
Tribler/community/market/community.py
TriblerGUI/widgets/downloadsdetailstabwidget.py
TriblerGUI/widgets/trustpage.py
doc/building/building_on_osx.rst
doc/development_methodology.rst
doc/trustchain.rst

Fixes #3018, fixes #3514, fixes #3425

Various fixes for 7.1

---

Tribler/Test/GUI/test_gui.py
TriblerGUI/core_manager.py
TriblerGUI/defs.py
TriblerGUI/event_request_manager.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/tribler_request_manager.py
TriblerGUI/tribler_window.py
TriblerGUI/widgets/createtorrentpage.py
TriblerGUI/widgets/settingspage.py

Various fixes for next

---

Tribler/Core/DownloadState.py
Tribler/Test/Core/test_downloadstate.py

Fixes https://github.com/Tribler/tribler/issues/3518.

Fix DownloadState.get_availability

---

Tribler/Core/Modules/restapi/wallets_endpoint.py
Tribler/Main/Build/Win/tribler.nsi
Tribler/Test/Community/Market/Wallet/test_btc_wallet.py
Tribler/community/market/wallet/btc_wallet.py
Tribler/community/market/wallet/dummy_wallet.py
Tribler/community/market/wallet/tc_wallet.py
Tribler/community/market/wallet/wallet.py
TriblerGUI/core_manager.py
TriblerGUI/widgets/downloadspage.py
TriblerGUI/widgets/marketpage.py

Various keyring fixes

---

Tribler/Core/Config/tribler_config.py
Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
TriblerGUI/tribler_window.py

- Fixed yet another issue with Unicode (Fixes #3527) 
- Fixed add torrents from a directory (Fixes #3534)
- Set defaults download directory

Fixed unicode issue and issue with adding torrents from directory

---

TriblerGUI/widgets/downloadspage.py

Fixed referencing deleted tray icon

---

Tribler/Core/Config/tribler_config.py
Tribler/Core/Modules/watch_folder.py

Fixed a bug when a torrent from the watch folder didn't have the right destination directory

---

TriblerGUI/defs.py
TriblerGUI/tribler_request_manager.py
TriblerGUI/tribler_window.py

Fixed the issue with the port causing Tribler request manager and event manager to fail. Also added support for changing the protocol, host so we can support https and remote host in future.
Fixes #3553

Updated request manager

---

Tribler/Core/DownloadState.py
Tribler/Test/Core/test_downloadstate.py

Fixes https://github.com/Tribler/tribler/issues/3547.

Fix file progress for multi file downloads

---

TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/widgets/downloadspage.py
TriblerGUI/widgets/subscriptionswidget.py

Fixes https://github.com/Tribler/tribler/issues/3478.

Small credit mining updates

---

Tribler/Core/Utilities/utilities.py
Tribler/Test/Core/test_utilities.py
TriblerGUI/widgets/trustpage.py
check_os.py
debian/control
run_tribler.py

Fixed bug + enabled faulthandler in Tribler

---

Tribler/Core/DownloadState.py
Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Test/Community/Market/test_community.py
Tribler/Test/Core/test_downloadstate.py

Fixes https://github.com/Tribler/tribler/issues/3576.

Fix seeding time/ratio

---

Tribler/Test/Community/Market/test_community.py
Tribler/Test/Community/Tunnel/test_community.py
Tribler/community/market/community.py
Tribler/community/triblertunnel/caches.py
Tribler/community/triblertunnel/community.py
Tribler/community/triblertunnel/payload.py

In this PR, I've implemented a basic freeride policy, based on the token balance of users. See issue #3573 for more information.
Depends on https://github.com/Tribler/py-ipv8/pull/99
Fixes #3573

Implemented basic strategy for freerider prevention

---

TriblerGUI/core_manager.py

Potentially fixes the shutting down problem

Core manager should shutdown even if core process is None

---

TriblerGUI/debug_window.py

Fix Dispersy community statistics bug in debug pane

Fix Dispersy community statistics bug in debug pane

---

Tribler/Core/Utilities/configparser.py

Loading a big example torrent (from https://github.com/Tribler/tribler/issues/3609) took ~2min, with this PR it took 0.23s,

READY: Fix loading large checkpoints

---

Tribler/Core/CacheDB/sqlitecachedb.py
Tribler/Test/Core/test_sqlitecachedb.py

Integrity check at the startup is done only when necessary because it is quite expensive and slows down the startup process. It seems it is sufficient to do integrity check only when there are leftover rollback files (WAL and/or SHM) present.

Integrity check is only done if there is WAL or SHM file present

---

check_os.py

Fix issue with restarting Tribler in Linux

Fix issue with restarting Tribler

---

Tribler/Core/Modules/resource_monitor.py
Tribler/Test/Core/Modules/test_resource_monitor.py

Fixes potentially #3624 Index Error on writing resource logs

Fix Index Error on writing resource logs

---

TriblerGUI/tribler_window.py

Fixes #3600 Key Error: statistics

Fix Key Error: statistics

---

TriblerGUI/debug_window.py
TriblerGUI/dialogs/feedbackdialog.py
TriblerGUI/tribler_request_manager.py

This PR fixes a memory leak in the GUI caused by HTTP replies not being destroyed properly.

Fix memory leak in the GUI

---

Tribler/Core/TorrentChecker/session.py
Tribler/Core/TorrentChecker/torrent_checker.py
Tribler/Core/Utilities/utilities.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker_session.py
Tribler/Test/Core/Utilities/test_utilities.py

This fix potentially solves the eternal shutdown of Tribler.

Fixed issue with closing Torrent checker

---

Tribler/Test/GUI/test_gui.py
TriblerGUI/vlc.py

In this PR, I updated the VLC bindings to 3.0.2. This PR has been tested on all platforms within frozen environments 👍 
Fixes #3640, fixes #3635

Updated VLC bindings to 3.0.2 and testing video playback in GUI tests

---

README.rst
Tribler/Core/Category/FamilyFilter.py
Tribler/Test/Core/Category/test_family_filter.py
Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py
Tribler/Test/Core/Modules/RestApi/test_wallets_endpoint.py
Tribler/Test/GUI/test_gui.py
TriblerGUI/debug_window.py
TriblerGUI/tribler_request_manager.py
TriblerGUI/tribler_window.py

Fixes #3639, fixes #3629, fixes #3628

Various small fixes for Tribler 7.1

---

Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
Tribler/Core/TorrentChecker/session.py
Tribler/Core/TorrentChecker/torrent_checker.py
TriblerGUI/tribler_window.py
TriblerGUI/widgets/leftmenuplaylist.py

This PR fixes various issues.
Fixes #3648, fixes #3637, fixes #3596, fixes #3468, fixes #3651

Various fixes for Tribler 7.1

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Test/Core/test_launch_many_cores.py
Tribler/Test/GUI/test_gui.py

Re-adding plain download when safe seeding is enabled

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/TorrentChecker/session.py
Tribler/Test/Community/Tunnel/test_community.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker_session.py
Tribler/community/triblertunnel/community.py
TriblerGUI/dialogs/confirmationdialog.py
TriblerGUI/dialogs/dialogcontainer.py
TriblerGUI/dialogs/startdownloaddialog.py
TriblerGUI/tribler_request_manager.py
TriblerGUI/tribler_window.py
TriblerGUI/widgets/createtorrentpage.py
TriblerGUI/widgets/downloadspage.py
TriblerGUI/widgets/editchannelpage.py
TriblerGUI/widgets/marketorderspage.py
TriblerGUI/widgets/marketpage.py
TriblerGUI/widgets/marketwalletspage.py
TriblerGUI/widgets/settingspage.py
TriblerGUI/widgets/subscribedchannelspage.py

In this PR, I fixed a few memory leaks.
fixes #3655, fixes #3656

Fixed memory leaks in GUI and Tribler Core

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Core/Modules/restapi/events_endpoint.py
TriblerGUI/widgets/searchresultspage.py

This PR fixes a bug which was causing relevance ranking score of torrents in the search results to be None. With this PR, good score torrents will show up higher in the search results.

Fixed a bug in relevance ranking

---

Tribler/Test/GUI/test_gui.py

Fixes #3664, fixes #3638, fixes #3636

Updated IPv8 pointer

---

Tribler/community/market/community.py
TriblerGUI/widgets/createtorrentpage.py

Fix create torrent button, updated IPv8 pointer

---

TriblerGUI/widgets/downloadsdetailstabwidget.py
TriblerGUI/widgets/videoplayerpage.py

Fix video player bug on selecting multi-file video swarm

---

systemd/anontunnel_helper@.service

So we can pass spaces to this variable

Not expanding variable in tunnel helper service

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/TorrentDef.py

Various fixes

---

Tribler/Core/Session.py
Tribler/Test/Core/test_session.py

Added workaround for resolve socket.error 16

---

Tribler/Core/Modules/restapi/util.py

Removed unreachable code

---

Tribler/community/popularity/payload.py

Fix #3703 error in popularity community

Fixed error in popularity community

---

run_tribler.py

Added support for cp65001

---

Tribler/Core/Utilities/random_utils.py
Tribler/Test/Community/popularity/test_community.py
Tribler/Test/Core/Utilities/test_random_utils.py
Tribler/community/popularity/payload.py

Fixes popularity channel issues.
Fix #3716 pack issue
Fix #3715 unicode issue

Fix popularity channel errors

---

.sonar/analyse.py

This PR includes a Jenkins job script to analyze SonarQube results.
I'm also using it to check the integration of https://sonarcloud.io Tribler account with our Jenkins server at https://jenkins-ci.tribler.org

Added SonarQube analyze script

---

Tribler/community/market/database.py

Fixes #3736 
Manually tested by switching between versions, with a clean state directory.

Fixed bug when upgrading market database

---

Tribler/Test/Community/popularity/test_payload.py
Tribler/community/popularity/payload.py

Updated torrent info response payload date field to long.

Popularity community payload update

---

Tribler/Test/Community/Market/test_block.py
Tribler/community/market/block.py
Tribler/community/market/community.py
TriblerGUI/qt_resources/channel_list_item.ui
TriblerGUI/widgets/marketpage.py

In this PR, I fixed a few small issues I encountered when working with the market community.
I also fixed an error when the number of subscriptions in the GUI was clipped and did not display correctly.
Fixes #3740, fixes #3741

Small fixes for the market + GUI

---

Tribler/Core/CreditMining/CreditMiningManager.py

Switched CreditMiningManager download dir to session's

---

Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/widgets/channelpage.py
TriblerGUI/widgets/downloadspage.py
TriblerGUI/widgets/lazyloadlist.py

Added multi-selection to downloads and channels

---

logger.conf

TrustChain logging is insanity and completely drowns out all other communities.

Updated default log level of TrustChain to ERROR

---

TriblerGUI/tribler_window.py

Added drag and drop support

---

TriblerGUI/widgets/downloadspage.py

Added loading message for downloads page

---

Tribler/community/market/community.py

Proven to work in Gumby.
Failing experiment (due to this error): https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_market/5/
Working experiment (with this branch): https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_market/6/

Fixed bug in market community

---

Tribler/Core/Session.py
Tribler/Test/Core/test_session.py

Catch unhandled internal Twisted response error

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Test/Core/test_launch_many_cores.py
twisted/plugins/tunnel_helper_plugin.py

Running it on tunnel helpers will really help us to debug the DHT implementation 👍 
Fixes #3798

Tunnel helpers will now use EgbertDHT instead of mainline DHT

---

tribler.spec

Disabled the console in build version.

Disabled the console in build version

---

TriblerGUI/tribler_window.py
TriblerGUI/widgets/home_recommended_item.py

Fixed NoneType GUI bug again

---

Tribler/Core/Socks5/conversion.py
Tribler/Test/Core/Socks5/test_connection.py
twisted/plugins/tunnel_helper_plugin.py

Various improvements for the tunnel helpers

---

Tribler/Test/Community/Tunnel/test_community.py
Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py
Tribler/community/triblertunnel/community.py

Added exit node snapshotting

---

Tribler/Test/Community/Market/test_timestamp.py

Fixed market timestamp test

---

Tribler/community/triblertunnel/community.py

Checking whether balance request exists or not

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py

Fixed non ASCII torrent name updates

---

TriblerGUI/tribler_window.py

Fixed tray icon already deleted bug.
Fixes #3840

Fixed tray icon already deleted bug

---

Tribler/Test/Community/popularity/test_repository.py
Tribler/community/popularity/repository.py

Fixed unknown torrent bug appearing on clicking search results.
Fixes #3821

Fixed unknown torrent bug appearing on clicking search results

---

Tribler/Test/Community/popularity/test_repository.py
Tribler/community/popularity/repository.py

- Fixed Unicode decode error in popularity community. Fixes #3847 
- Updated seeder/leecher info from the search results

Fixed unicode decode error in popularity community

---

Tribler/Core/Modules/bitcoinlib_main.py
Tribler/Core/Modules/wallet/btc_wallet.py
Tribler/Test/Core/Modules/Wallet/test_trustchain_wallet.py
TriblerGUI/widgets/marketwalletspage.py
tribler.spec

Fixed bitcoinlib in frozen environments, fixed double dock icon on mac

---

Tribler/Core/CacheDB/Notifier.py
Tribler/Core/CreditMining/CreditMiningManager.py
Tribler/Core/Modules/restapi/events_endpoint.py
Tribler/Core/simpledefs.py
Tribler/Test/Core/CreditMining/test_credit_mining_manager.py
Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py
TriblerGUI/event_request_manager.py
TriblerGUI/tribler_window.py

Fixed credit mining bug about the non-existing path.
Fixes #3837

Fixed credit mining bug about non-existing path

---

logger.conf

Updated logger configuration

---

Tribler/Test/Core/Modules/test_process_checker.py

The dummy process does not react to `terminate` and only dies with the interpreter. This patch adds a correct, `Value`-based shared var mechanism to shut it down.

Fix dummy process unable to terminate in test_process_checker

---

Tribler/Test/Core/Modules/Wallet/test_btc_wallet.py

READY: Mocked update_transactions in BTC wallet tests

---

TriblerGUI/widgets/subscriptionswidget.py

Fixed issue in GUI when settings are not loaded yet

---

.gitignore
Tribler/Test/Community/Market/test_transaction.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/widgets/marketpage.py

Also added the screenshots dir to the `.gitignore` file.
Fixes #3886

Fixed crash in market page

---

Tribler/community/search/community.py

Fixes https://github.com/Tribler/tribler/issues/3889.

Fix torrent collecting

---

TriblerGUI/debug_window.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/widgets/settingspage.py
TriblerGUI/widgets/trustpage.py

- changed format of TrustChain horizontal axis to ISO8601
- made it more clear what happens when changing anonymity
- converted IPv8 statistics to MB where applicable

Some small GUI improvements

---

Tribler/Core/Category/Category.py
Tribler/Test/Core/Category/test_category.py
TriblerGUI/debug_window.py

Fixed two bugs, updated IPv8 pointer

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/statistics.py
TriblerGUI/debug_window.py
TriblerGUI/qt_resources/debugwindow.ui
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/widgets/settingspage.py

Added support for detailed community statistics

Tooling enhancements

---

Tribler/Core/Modules/restapi/debug_endpoint.py

Fixed crash when starting Tribler with statistics enabled

---

TriblerGUI/qt_resources/mainwindow.ui

Fixes https://github.com/Tribler/tribler/issues/3888

Fixed GUI glitch in Trust statistics graph

---

TriblerGUI/debug_window.py
TriblerGUI/qt_resources/debugwindow.ui

Missing IPv8 statistics

---

Tribler/Core/Modules/restapi/debug_endpoint.py
TriblerGUI/debug_window.py

Fixed CPU history bug in debug endpoint

---

TriblerGUI/widgets/downloadspage.py

Fixed crash when filtering downloads

---

TriblerGUI/tribler_window.py
TriblerGUI/widgets/trustpage.py

Reduced the number of requests to trustchain/statistics

---

Tribler/Test/Community/Market/test_block.py
Tribler/Test/Community/Market/test_community.py
Tribler/Test/Core/Modules/RestApi/test_market_endpoint.py
Tribler/community/market/block.py
Tribler/community/market/community.py
Tribler/community/market/core/tick.py
twisted/plugins/market_plugin.py

In this PR, I removed the requirement for a counter signature when creating new orders. I also updated the market plugin by disabling a few overlays, fixed a bug when initializing the market and increased the version indicator of the market.
Fixes #3945

Various market fixes, updated IPv8 pointer

---

TriblerGUI/defs.py
TriblerGUI/tribler_window.py
TriblerGUI/widgets/trustpage.py

Matplotlib memory leak.
Fixes #3944

Fixed memory issue with matplotlib

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Core/Modules/restapi/debug_endpoint.py
Tribler/Core/Modules/wallet/tc_wallet.py
Tribler/Test/Community/Market/test_block.py
Tribler/Test/Community/Market/test_community.py
Tribler/Test/Core/Modules/RestApi/test_market_endpoint.py
Tribler/community/market/block.py
Tribler/community/market/community.py
Tribler/community/market/core/tick.py
Tribler/community/triblertunnel/community.py
TriblerGUI/debug_window.py
TriblerGUI/defs.py
TriblerGUI/dialogs/trustexplanationdialog.py
TriblerGUI/qt_resources/debugwindow.ui
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/qt_resources/trustexplanation.ui
TriblerGUI/tribler_window.py
TriblerGUI/widgets/downloadspage.py
TriblerGUI/widgets/searchresultspage.py
TriblerGUI/widgets/trustpage.py
twisted/plugins/market_plugin.py

From now on, all commits should go to `devel`, and cherry-pick in `next`.

Final next to devel PR

---

README.rst

Added Tribler 7.1.0 downloads in readme

Added Tribler 7.1.0 downloads in readme

---

README.rst
Tribler/Core/CacheDB/sqlitecachedb.py

Enabled memory map pragma in sqlite.

Enabled memory map pragma in sqlite

---

TriblerGUI/widgets/marketwalletspage.py

pip's return codes are unreliable and it's messages misleading so users may need extra guidance.

READY: pip for bitcoinlib workaround

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/Modules/restapi/wallets_endpoint.py
Tribler/Core/Session.py
Tribler/Test/Core/test_session.py
Tribler/community/triblertunnel/community.py
TriblerGUI/dialogs/newmarketorderdialog.py
TriblerGUI/qt_resources/mainwindow.ui
TriblerGUI/qt_resources/newmarketorderdialog.ui
TriblerGUI/widgets/marketpage.py

Fixes #3965, fixes #3963, fixes #3958, fixes #3959

Various fixes for Tribler 7.2

---

Tribler/Core/Modules/payout_manager.py
Tribler/Test/Community/Market/test_community.py
Tribler/community/market/community.py

Properly handling errors raised by the DHT

---

TriblerGUI/widgets/home_recommended_item.py

Fixed NoneType error in home recommended items page
Fixes #3968

Fixed NoneType error in home recommended items page

---

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py
TriblerGUI/widgets/downloadwidgetitem.py

The total number of seeders and peers and the ones we are connected to could be different. This PR shows the active seeds and peers for each download in the GUI.

Active seeds/peers vs Total seeds/peers

---

Tribler/Core/Modules/restapi/channels/channels_subscription_endpoint.py
Tribler/Core/Modules/restapi/util.py
Tribler/Test/Core/Modules/RestApi/Channels/test_channels_subscription_endpoint.py

Added support for GigaChannel-managed channels in "subscribed" REST endpoint.

READY: Show GigaChannel channels in "subscribed" list

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Core/CacheDB/sqlitecachedb.py
Tribler/Core/Modules/restapi/torrents_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_torrents_endpoint.py

HealthChecker and bound endpoints should be fixed to properly support getting info from GigaChannel metadata store.

READY: Compatiblity fixes for HealthChecker to support GigaChannel

---

Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Core/Modules/restapi/libtorrent_endpoint.py
Tribler/Core/Modules/restapi/root_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_libtorrent_endpoint.py
Tribler/Test/GUI/test_gui.py
TriblerGUI/debug_window.py
TriblerGUI/qt_resources/debugwindow.ui

Added Libtorrent endpoint in core and a new tab in debug pane to show information about libtorrent. It basically includes the settings and session information for different hop configuration.

Added LibTorrent endpoint and GUI in Debug pane

---

tribler.spec

Added pony dependencies in PyInstaller spec.
Fixes #4004

Added pony deps in pyinstaller spec

---

Tribler/community/gigachannel/community.py

Fix missing database entry for channel

---

Tribler/Core/CreditMining/CreditMiningManager.py
Tribler/Core/Modules/restapi/downloads_endpoint.py
TriblerGUI/core_manager.py
TriblerGUI/dialogs/startdownloaddialog.py
TriblerGUI/tribler_window.py
TriblerGUI/widgets/downloadspage.py
TriblerGUI/widgets/downloadwidgetitem.py
TriblerGUI/widgets/home_recommended_item.py
TriblerGUI/widgets/marketorderspage.py

Fixes all the issues listed in #4018

Fixed GUI errors

---

Tribler/community/gigachannel/community.py

Discard old channel versions

---

Tribler/Core/Modules/restapi/downloads_endpoint.py
Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
Tribler/Core/Utilities/utilities.py

Fixes https://github.com/Tribler/tribler/issues/4022

Unicode twisted error in endpoints

---

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Core/Utilities/torrent_utils.py
Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py

Fixes https://github.com/Tribler/tribler/issues/3988

Fixed issue with torrent info missing files

---

Tribler/Test/Community/popularity/test_community.py
Tribler/community/popularity/pubsub.py

Fixes https://github.com/Tribler/tribler/issues/4034

Fixed key error in pubsub subscription status

---

Tribler/Core/DownloadConfig.py

Also updated the IPv8 pointer.

Fixed crash when NoneType is returned for a download

---

Tribler/Core/Modules/bitcoinlib_main.py
Tribler/Test/Core/Modules/Wallet/test_btc_wallet.py

Fix for newer bitcoinlib versions

---

Tribler/Core/Modules/payout_manager.py
Tribler/Core/Modules/wallet/tc_wallet.py
Tribler/Test/Core/Modules/test_payout_manager.py
Tribler/community/market/community.py

Added default errback to sign_block calls

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/community/gigachannel/community.py

So we have our own overlay for testing purposes 👍

Added testnet for gigachannel overlay

---

check_os.py
run_tribler.py

**Debug build for Tribler**
If debug is enabled with runtime argument `--trace-debug`, `--trace-exception`, code tracing is enabled and all the calls and exceptions are logged. It should be easier now to debug the issues where Tribler fails to boot.

Debug build for Tribler (--trace-debug & --trace-exception)

---

TriblerGUI/dialogs/startdownloaddialog.py
TriblerGUI/widgets/downloadspage.py
TriblerGUI/widgets/subscriptionswidget.py

These bugs were revealed by the application tester 👍 
Fixes #4069

Fixed two small bugs in the GUI

---

TriblerGUI/widgets/home_recommended_item.py

Checking for presence of the "category" key is not enough.

Fixed category check in GUI

---

TriblerGUI/code_executor.py

If Tribler already crashed when opening the code socket, send the stack trace through it.

Sending stack trace through code socket on open

---

Tribler/Test/GUI/test_gui.py

Also updated the Dispersy pointer.
Fixes #4081

Fixed GUI tests

---

Tribler/Core/CacheDB/sqlitecachedb.py
Tribler/Test/Core/test_sqlitecachedb.py

Don't error sqlitecachedb on exit

---

.sonar/analyse.py
Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Core/RemoteTorrentHandler.py
Tribler/Test/Community/Tunnel/FullSession/test_hidden_services.py
Tribler/Test/test_as_server.py
Tribler/Test/util/Tracker/UDPTracker.py
check_os.py
win/locate-python.py

IN https://github.com/Tribler/tribler/issues/3883#issuecomment-445044813 I thought we had a big task in front of us to find and fix Python 3 syntax errors but it was quite easy.  Fixes in these nine files were required but this PR would bring us to:
Python 2 syntax errors: 0
Python 3 syntax errors: 1 --> __Tribler/community/market/community.py__ see #4092

Fix Python 3 syntax errors

---

Tribler/Core/Libtorrent/LibtorrentMgr.py

Added check whether deferred_added has been called

---

Tribler/Test/Core/Modules/RestApi/test_torrents_endpoint.py

This files was pulled out of #4100 because it has many instances of __hexlify()__ and __unhexlify()__ to get working properly.

Fix unicode in test_torrents_endpoint.py

---

Tribler/Main/Build/Mac/Info.plist

Updated MacOS Info.plist

---

TriblerGUI/debug_window.py

Fix imports in debug window

---

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py

By creating getters for the swarmname and directory name of the unwanted folder.
Fixes #4129

Refactored unwanteddir_abs attribute

---

Tribler/Core/Modules/wallet/btc_wallet.py

Fix wallet transfer endpoint, add error message for insufficient funds

---

Tribler/community/market/community.py
Tribler/community/market/core/wallet_address.py

Small fixes for the market

---

Tribler/Test/Core/Utilities/test_utilities.py
TriblerGUI/code_executor.py

This PR should fix some errors we observe occasionally during the win64 unit tests (we got it in #4169). I also updated the IPv8 pointer and made a small change to the remote code execution.

Various small fixes

---

Tribler/community/triblertunnel/community.py

The circuit_dead() call is responsible for updating the destinations dict of the dispatcher. By having this call inside the deferred callback, it only runs after the tunnel is fully closed and paid for. During this time the dispatcher will drop any data still being sent over this circuit instead of already selecting another circuit to use.
So the call to circuit_dead() should happen as early as possible. This must be after the call to the super since we need the circuit to be in an unselectable state before we remove it from the dispatcher's destinations (to not risk it immediately reselecting the closing circuit).

Reorder tunnel close events to notify tunnel dispatcher early

---

Tribler/Core/APIImplementation/LaunchManyCore.py
Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Test/Community/Tunnel/FullSession/test_tunnel_base.py
Tribler/Test/Community/Tunnel/test_community.py
Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py
Tribler/community/triblertunnel/community.py

Fixes https://github.com/Tribler/tribler/issues/3379.

Update circuits_needed from within monitor_downloads

---

Tribler/Core/TorrentChecker/session.py

The UDP tracker could send us invalid bytes. We should check for this.
Fixes #4160

Added UDP tracker response check

---

TriblerGUI/qt_resources/mainwindow.ui

- Fixed Tribler window status bar label issue
- Changed style of Token Mining button in Trust Page

Fixed Tribler window status bar label issue

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py

Fixed UnicodeDecodeError on incoming remote search

---

Tribler/Core/CacheDB/SqliteCacheDBHandler.py

Fixed search keyword list; 
Fixes #4187

Fixed search keyword list; Fixes #4187

---

Tribler/Core/APIImplementation/LaunchManyCore.py
TriblerGUI/debug_window.py
TriblerGUI/defs.py

Added a 5 seconds refresh timer to some tabs in the Debug Pane

Added refresh timer to some tabs in Debug Pane

---

Tribler/community/triblertunnel/community.py

Updates the IPv8 pointer and modifies TriblerTunnelCommunity to work with the newest IPv8.

Update IPv8 pointer

---

TriblerGUI/debug_window.py
TriblerGUI/tribler_window.py

Fixed the issue with debug pane timer

Fixed issue with debug pane timer

---

Tribler/community/market/community.py
TriblerGUI/tribler_window.py
TriblerGUI/widgets/channelpage.py

Various GUI fixes 7.2.2

---

Tribler/Test/GUI/test_gui.py

Fixed metainfo signal in GUI tests

---

TriblerGUI/debug_window.py

This allows everyone to see the overlay health without knowing the healthy peer counts, see https://github.com/Tribler/tribler/issues/4171#issuecomment-462121405 .

Colorized peer counts in debug window

---

Tribler/Core/Libtorrent/LibtorrentMgr.py

Fixed add_torrent handle desync

---

Tribler/Core/Modules/restapi/events_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py
Tribler/community/triblertunnel/community.py
twisted/plugins/tunnel_helper_plugin.py

This will be used by the application tester to gather statistics on circuit lifetime and performance.

Added event when circuit is removed

---

Tribler/Core/Modules/restapi/debug_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py
Tribler/Test/GUI/test_gui.py

It is already available in IPv8 (/ipv8/tunnel/circuits).

Removed debug/circuits GET endpoint

---

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Test/Core/CreditMining/test_credit_mining_manager.py

Fixes #4190
Fixed issue with adding torrent which already exists in credit mining

Fixed issue with adding torrent which already exists in credit mining

---

TriblerGUI/widgets/subscriptionswidget.py

This error got caught by the application tester.

Fixed crash when unsubscribing from channel

---

Tribler/Core/Modules/restapi/statistics_endpoint.py
Tribler/Core/Session.py
Tribler/Core/statistics.py
Tribler/Test/Core/Modules/RestApi/test_statistics_endpoint.py
TriblerGUI/debug_window.py

In conjunction with https://github.com/Tribler/fake-tribler-api/pull/41

Removed statistics/overlays endpoint from Tribler

---

Tribler/Core/CreditMining/CreditMiningSource.py
TriblerGUI/widgets/subscriptionswidget.py

This PR is targeted on fixing issues encountered while stabilizing the Giga Channel PR (#4090) and improving the code coverage.
- Fix adding a giga channel for credit mining

PR for Giga Channel

---

Tribler/community/gigachannel/community.py

We can lose some code in the new GigaChannelCommunity class by using the latest and greatest IPv8 functionality.

Use latest IPv8 definitions in GigaChannelCommunity

---

Tribler/Core/TorrentChecker/torrent_checker.py

Currently, only torrents that are present in the database will be checked by a request to `/metadata/torrents/<infohash>/health`. In this PR, I changed this so it can check *any* torrent, whether it is in the database or not. If it is already in the database, it will use that information if it is still representative.

Made torrent health endpoint also check torrents that are not available in the database

---

TriblerGUI/widgets/editchannelpage.py
TriblerGUI/widgets/lazytableview.py

Also fixed a small GUI issue.
Partially addresses #4225

Made it possible to add multiple torrents at once to your channel

---

snap/snapcraft.yaml

Fixes #3935
Fixes #3052
Added support for building snap package

Snap package

---

Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
Tribler/Test/Core/Modules/RestApi/test_torrentinfo_endpoint.py
TriblerGUI/dialogs/startdownloaddialog.py

Fixed encoding in start download dialog

---

Tribler/Core/Libtorrent/LibtorrentMgr.py
Tribler/Core/Modules/watch_folder.py
Tribler/Core/Session.py
Tribler/Test/Core/Modules/test_watch_folder.py
Tribler/Test/Core/test_session.py
TriblerGUI/tribler_window.py

Fixes #3992, fixes #4037, fixes #4217, fixes #4168

Various fixes 

---

TriblerGUI/qt_resources/torrents_list.ui
TriblerGUI/tribler_window.py
TriblerGUI/widgets/channelpage.py

A few minor fixes for the GUI.

Small GUI fixes

---

Tribler/Core/Modules/tracker_manager.py
Tribler/Core/TorrentChecker/torrent_checker.py
Tribler/Test/Core/Modules/test_tracker_manager.py
Tribler/Test/Core/TorrentChecker/test_torrentchecker.py

Added tracker blacklist file

---

Tribler/community/market/core/matching_engine.py
TriblerGUI/widgets/downloadprogressbar.py

```
./TriblerGUI/widgets/downloadprogressbar.py:59:26: F821 undefined name 'xrange'
for i in xrange(len(self.pieces)):
./TriblerGUI/widgets/downloadprogressbar.py:65:26: F821 undefined name 'xrange'
for i in xrange(self.width()):
./TriblerGUI/widgets/downloadprogressbar.py:69:30: F821 undefined name 'xrange'
for j in xrange(begin_piece, end_piece):
./Tribler/community/market/core/matching_engine.py:32:67: F821 undefined name 'xrange'
return ''.join(random.choice('0123456789abcdef') for _ in xrange(20))
```

from six.moves import xrange for Python 3

---

Tribler/Core/Video/VideoServer.py

Fixes #4063
TODO: Find a way to test this, as the current configuration doesn't really allow for easy testing.

Retry VideoServer port on failure
