Tribler/tribler

Tribler/Utilities/SingleInstanceChecker.py
pgrep removes itself from the list of results and with grep 2.21 or greater grep will print `grep: warning: GREP_OPTIONS is deprecated; please use an alias or script` if GREP_OPTIONS is set, causing Tribler to believe there is already a process running.
=> Remove unnecessary grep in SingleInstanceChecker.py

Tribler/Core/Upgrade/torrent_upgrade64.py, Tribler/Core/Upgrade/upgrade.py, Tribler/Main/Utility/Feeds/rssparser.py, Tribler/Main/vwxGUI/list_item.py, Tribler/Main/vwxGUI/settingsDialog.py
To allow to move files across filesystems. 
Related to: #1115
=> Use shutil.move instead of os.rename in several places

Tribler/community/tunnel/main.py
Small fix - for some reason Ubuntu on my mac stopped recognizing the enter key, rendering the main debugger useless. By specifying \n hardcoded, problems is solved.
=> Set delimiter for linehandler in tunnel main to \n

Tribler/community/tunnel/hidden_community.py
Fixes a backtrace mention in #1204 
```
CRITICAL 1423226122.23     minitwisted:105   MINITWISTED CRASHED
ERROR   1423226122.23     minitwisted:106   MINITWISTED CRASHED 
File "/home/rob/git/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 103, in run2
self.run_one_step()
File "/home/rob/git/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 179, in run_one_step
datagram_received)
File "/home/rob/git/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/controller.py", line 262, in on_datagram_received
callback_f(lookup_id, peers, msg.src_node)
File "/home/rob/git/tribler/Tribler/community/tunnel/hidden_community.py", line 227, in dht_callback
self.create_key_request(info_hash, peer)
File …
```
=> Fix a dht_callback threading problem in hidden community

Tribler/Core/Video/VLCWrapper.py, Tribler/Core/Video/VideoPlayer.py
Got a backtrace on Windows during shutdown. It may be related to the error message problem during shutdown on Windows. Somehow some code still tries to initialize the VLC stuff even after shutdown, so I added a `is_shutting_down` flag there.
```
File "wx\_misc.pyo", line 1358, in Notify
File "wx\_core.pyo", line 14771, in Notify
File "D:\workspaces\tribler\Tribler\Core\Video\VLCWrapper.py", line 61, in _init_vlc
self.media = self.get_vlc_mediactrl()
File "D:\workspaces\tribler\Tribler\Core\Video\VLCWrapper.py", line 20, in invoke_func
raise Exception("VLCWrapper: Thread violation!")
Exception: VLCWrapper: Thread violation!
```
=> Shutdown VLC wrapper

Tribler/Main/tribler_main.py, Tribler/Main/vwxGUI/DispersyDebugFrame.py, Tribler/community/allchannel/community.py, Tribler/community/bartercast4/community.py, Tribler/community/bartercast4/conversion.py, Tribler/community/bartercast4/payload.py, Tribler/community/bartercast4/statistics.py, Tribler/community/channel/community.py, Tribler/community/tunnel/routing.py, Tribler/community/tunnel/tunnel_community.py, Tribler/twisted/plugins/bartercast_crawler_plugin.py, logger.conf
Adds bartercast4 community and statistics for tunnel and torrent received stats. Also adds statistics database and debug panel for these stats. (works with dispersy/devel)
=> Bartercast statistics community

Tribler/Test/test_magnetlink.py
It's useless and breaks jenkins' xunit plugin.
=> Don't print binary stuff.

Tribler/Test/test_status.py
Also they output xml which seems to break jenkins xunit plugin.
=> Skip livinglab reporter tests, not used.

Tribler/Main/Dialogs/TunnelOptin.py
Just downloaded and saw this typo, figured it would be a good excuse to learn how to do a pull request through github.
=> Fixed typo in Experimental Anonymity Optin Dialog

debian/bin/tribler
Instead of the first one on the PATH.
Closes #1346
=> Force use of system's python.

Tribler/community/bartercast4/community.py, Tribler/community/channel/community.py
instead of member id so we can generate a coherent bartercast graph
=> record ip for peer1 in interaction_log 

Tribler/Core/Libtorrent/LibtorrentMgr.py
Fix this error:
```
Unhandled Error
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/Utilities/twisted_thread.py", line 54, in _reactor_runner
reactor.run(installSignalHandlers=False)
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
self.mainLoop()
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
self.runUntilCurrent()
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
f(*a, **kw)
File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/TorrentChecker/session.py", line 607, in on_metainfo_received …
```
=> Fix a DHT check bug

Tribler/Core/APIImplementation/LaunchManyCore.py
Fix this backtrace
```
File "/home/lfei/workspace/tud/p2p/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 467, in load_download_pstate_noexc
filename = os.path.join(dir, basename)
File "/usr/lib/python2.7/posixpath.py", line 77, in join
elif path == '' or path.endswith('/'):
AttributeError: 'builtin_function_or_method' object has no attribute 'endswith'
```
=> Fix pstate dir

Tribler/Core/TFTP/handler.py, Tribler/Core/TFTP/session.py
TFTP retry mechanism for data transmission ONLY. Negotiation packets such as OP_RRQ and OP_OACK will not be retransmitted.
Closes #1392 and #903
=> Retry for TFTP data transmission

Tribler/Test/test_libtorrent_download.py, Tribler/Test/test_magnetlink.py
The Pioneer torrent seems to be dead. Use ubuntu instead.
Fixes two tests:
1. `test_libtorrent_download.py:TestLibtorrentDownload.test_downloadfrommagnet`
2. `test_magnetlink.py:TestMagnet.test_good_transfer`
=> Fix magnet link unittests

Tribler/Test/test_remote_search.py
As the content is disappearing from the network so the search tests fail
more often.
=> Use ubuntu + desktop instead of vodo + pioneer

Tribler/Main/vwxGUI/list.py, Tribler/Test/API/test_seeding.py, Tribler/Test/API/test_tdef.py, Tribler/Test/bak_tribler_sdb.py, Tribler/Test/test_as_server.py, Tribler/Test/test_gui_dialogs.py, Tribler/Test/test_libtorrent_download.py, Tribler/Test/test_magnetlink.py, Tribler/Test/test_metadata_community.py, Tribler/Test/test_my_channel.py, Tribler/Test/test_remote_torrent_handler.py, Tribler/Test/test_sqlitecachedbhandler.py, Tribler/Test/test_torrent_checking.py, Tribler/Test/test_tunnel_community.py, Tribler/Test/test_video_server.py, Tribler/community/bartercast4/community.py
This is needed to be able to parallelize test execution.
=> Use a temporary dir as tribler state dir.

Tribler/Core/defaults.py, Tribler/Test/test_tunnel_community.py, Tribler/community/tunnel/hidden_community.py, Tribler/community/tunnel/main.py, Tribler/community/tunnel/routing.py, Tribler/community/tunnel/tunnel_community.py
Hidden services should recover from circuits that break down because of time-limits / throughput limits.
=> Rebuild tunnels when rendezvous or introduction circuits break down

Tribler/Main/Utility/utility.py
The current circuit length was set to 0, which gives strange results on adding new .torrents via gui to the downloads list in Tribler. Anonymous downloading can only be disabled by unchecking the box in the saveas dialog.
=> Bugfix, default anonymous circuit length to 1

Tribler/Core/CacheDB/Notifier.py, Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Core/RemoteTorrentHandler.py, Tribler/Core/Utilities/twisted_thread.py, Tribler/Core/Utilities/twisted_utils.py, Tribler/Main/Utility/GuiDBHandler.py, Tribler/community/metadata/community.py, Tribler/community/tunnel/main.py
To avoid problems when not running the reactor on a separate thread.
=> Move the twisted utility methods to its own module.

Tribler/Main/vwxGUI/list_body.py
Don't know which function is causing dead object error from the backtrace, so I added checks everywhere.
Closes #1497
=> Add self-check in ListBody

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/RemoteTorrentHandler.py, Tribler/Core/Session.py, Tribler/Core/SessionConfig.py, Tribler/Core/TFTP/handler.py, Tribler/Core/Upgrade/upgrade.py, Tribler/Core/defaults.py, Tribler/Core/leveldbstore.py, Tribler/Core/simpledefs.py, Tribler/Test/test_as_server.py, Tribler/Test/test_leveldb_store.py, Tribler/Test/test_leveldb_store_plyvel.py, Tribler/Test/test_remote_torrent_handler.py, Tribler/community/channel/community.py
Fix metadata download through TFTP.
Thumbnails are stored in LevelDb. The key is the SHA1 hash of the thumbnail file.
=> Fix metadata TFTP

Tribler/community/tunnel/tunnel_community.py
Crypto errors sometimes happen when a circuit breaks (due to security limiters or timeouts) and there are still messages in transit on the circuit. Those messages can't be decrypted because the keys have already been cleaned up. Those errors are useful for debugging but not relevant in production, as they can happen any time.
Change error to warning for communication errors related to encrypting / decrypting. Solves #1559
=> Change error to warning for communication errors in crypto

Tribler/Core/Modules/tracker_manager.py, Tribler/Core/TorrentChecker/torrent_checker.py
Closes #1565
The old tracker checking interval was a bit crazy. If a tracker is "alive", we will check it as much as we want; if a tracker is "dead", we will only check it after at least 60 seconds since the last check. If tracker has failed 5 times, it will be marked as "dead". So that's why we see those log messages appearing every 60 seconds or so.
In this PR, I changed it to use an incremental interval:
`this_interval = default_interval * 2^failures`
where `default_interval` is 60 seconds.
=> Change Tracker Checking interval mechanism

Tribler/Main/vwxGUI/MainFrame.py
Fixes this problem:
```
File "Tribler\Main\vwxGUI\MainFrame.pyo", line 661, in start_tribler
File "subprocess.pyo", line 710, in init
File "subprocess.pyo", line 958, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
```
=> Fix restart on Windows

.gitignore
Adds ignores for the .project and .pydevproject files within the
Tribler folder.
Setting up the Eclipse project according to the "Compiling Tribler
from Sources under Eclipse" wiki page, results in these files
being recognised by Git.
Edit: [Compiling Tribler from Sources under Eclipse] (https://github.com/Tribler/tribler/wiki/Compiling-Tribler-from-sources-under-Eclipse)
=> Add eclipse files in Tribler folder to .gitignore

README.md, doc/Tribler development on Linux.md, doc/Tribler development on OS X.md, doc/Tribler development on Windows.md
I've written some documentation about installing the required packages on all major platforms Tribler is supporting currently. I've tested the OS X and Windows guide myself. The documentation might still contain some minor errors.
Feel free to try it out and see whether it works for your environment.
=> Added documentation about setting up development environment on Windows, Linux and OS X

Tribler/Core/permid.py
On Windows, I encountered an issue when setting up a 64-bit environment. The problem occurred when invoking M2Crypto functions. I've explained the issue in more detail on Stack Overflow [here](http://stackoverflow.com/questions/33720087/error-when-importing-m2crypto-in-python-on-windows-x64/33728728#33728728).
One solution for this problem is to recompile Python and to include `openssl/applink.c` in the `Python.c` file. Since recompiling Python turned out to be quite hard (and not very desirable), I believe we can use the workaround as given by the answer on Stack Overflow. By making use of M2Crypto.BIO, we avoid using the openssl applink interface and thus the No OPENSSL_AppLink error.
Note that this problem only occurs on Windows (and I believe in particular 64-bit builds). On Linux and …
=> Windows openssl applink fix

README.md
The relative paths were pointing to **docs**/Tribler development on \<insert OS here\>.md
But the relative file path is just **doc**/Tribler development on \<insert OS here\>.md
Just a small mistake that I noticed when reading the new guides. :smiley:
=> Fixing filepath error in README.md. docs/ should be doc/

tribler.sh
To run Tribler from the Tribler.sh script, we first have to add the current working directory to the `PYTHONPATH` variable. Otherwise, the Tribler modules cannot be found.
=> Fixed tribler.sh startup script on OS X

doc/Tribler development on Linux.md
The link for python-cryptograph is broken. This package is not available for Ubuntu below 15.04. This PR fixes the link directing to the package (from 15.04).
I can confirm that this method works in 14.04, 64 bit.
=> Fix link to python-cryptography 14.04 LTS

doc/Tribler development on Windows.md
Added advise to download libtorrent 1.0.6 on Windows instead of the latest version (1.0.7).
=> Update Tribler development on Windows.md

Tribler/Main/Utility/utility.py, Tribler/Main/tribler_main.py, Tribler/Test/test_as_server.py
When running the unit tests on Ubuntu, it occasionally gives a segmentation fault when startup up Tribler. Loading the X11 library before the `TriblerApp` object is created should solve this.
=> Fixed segmentation fault when running the GUI tests on Ubuntu

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Test/test_tunnel_community_positive.py, Tribler/community/tunnel/crypto/tunnelcrypto.py, Tribler/community/tunnel/routing.py, Tribler/community/tunnel/tunnel_community.py
Overal cleanup of the code. Biggest changed:
* Removed retrying for circuits
* Fixed Extended message (the created message was actually forwarded back to the origin, instead of the last hop). Causing the Extended message never to be created :smile: 
* Tried to simply the crypto stuffs, but failed
* Removed the tunnel_to_end methods
For now I left on all the debug logging. Laurens, have a look at the number of (very small) packets being sent to the same ip/ports during a libtorrent download (e.g. the test_hidden_community). I think adding a buffer, and batch sending those will substantially improve download speeds.
=> Refactor tunnel code

Tribler/Main/Utility/utility.py
Turns out RawConfigParser constructor doesn't understand sections on the
defaults dict and makes a mess of the config file.
=> Fix tribler.conf Tribler section.

Tribler/Main/vwxGUI/list_header.py
On OS X, the popup menus would not disappear when clicking outside the popup menu. Changing the mouse event fixes this.
=> Fixed popup menus in panels on OS X

Tribler/Main/tribler_main.py
The `self.lastwantpeers` variable is not used anywhere in the `tribler_main` script so the assignment is redundant.
=> Removed unused assignment

Tribler/Main/tribler_main.py, Tribler/Main/vwxGUI/TriblerApp.py, Tribler/Test/test_as_server.py
The TriblerApp class is part of the GUI so it is better to move it to the `vwxGUI` directory.
=> Moved TriblerApp class to seperate file

Tribler/Test/test_hidden_community.py, Tribler/Test/test_libtorrent_download.py
It doesn't make sense to waste so much time re-running broken tests. 
When somebody gets around fixing the tunnel community and its tests, they can be enabled again.
Pioneer one torrent is dying and it takes a long time to start downloading, so switching to a different torrent for the test.
=> Temporarily disable broken tunnel tests

Tribler/Main/tribler_main.py
The upgrader splash was still a very short time visible for me in the latest checkout of `level`.
Fixes #1733
=> Fixed observer changetype of the upgrader event

.gitignore, Tribler/Main/tribler.py, Tribler/Main/vwxGUI/list_body.py, Tribler/Main/vwxGUI/list_details.py, Tribler/Main/vwxGUI/list_header.py, Tribler/Test/test_as_server.py, tribler.sh
This PR contains some fixes for Wx3.
The most important change is an conditional check in the `tribler.py` file that checks whether Wx3 is installed on the users' system. If so, it uses Wx3. If not, it fallbacks to Wx2.8. In some sense, we now have an experimental version of Wx3 in Tribler.
I've tested manually on Windows, Ubuntu and OS X and everything still seems to work ok. Wx3 on OS X is quite stable currently with some minor issues left.
=> Conditional Wx3 import

CONTRIBUTING.md
Adds step-by-step instructions to backup the Tribler installation and checkout the next branch to reproducde issues before submitting.
=> Add Backup + Checkout of Stabilization Branch

Tribler/Main/Build/license.txt, mac/makedistmac.sh
We're now adding the EULA to the .dmg file using the `eulagise` script. I've installed this script on the old OS X builder. I've tested this script using the new Mac Mini. I'm pull requesting this against next so we can use this new EULA for the 6.5 release.
=> Changed the way the old builder adds the license to the .dmg file

doc/Building Tribler on OS X.md
This guide contains instructions about setting up the environment to run the builder for creating a `.dmg` file.
=> Added instructions about setting up the Tribler.dmg builder on OS X

Tribler/Main/vwxGUI/widgets.py
On OS X, the filesize widget did not appear. This seems to be due to a bug in wx (see http://stackoverflow.com/questions/35201245/size-of-panel-in-panel-using-wxpython-incorrect/). So now, I pass the size in the call to `super`. Moreover, the return value of the `GetClientRect` method always returns a (0, 0, 0, 0) rect so I removed this call. The y-position of the up/down arrow images are now dependent on the `self.slider_size` attribute.
=> Filesize widget fix

README.md, doc/README.md, doc/german/README.md
I added the German translation of the README.md within the /doc directory and also created a new directory structure where I put the English versions in /doc/english and the German ones in /doc/german. I have also fixed the referece paths of the image accordingly.
=> Added German translation of README.md

Tribler/community/tunnel/tunnel_community.py
We don't have integrity checks for the message, so we can't know if it's
corrupted or not.
Closes #1617
Closes #1932
=> Catch InvalidTag exception.

Tribler/Main/vwxGUI/list_details.py
We noticed an assertion during the test runs where an assertion came up after starting to stream a video file. This was due to the panel below the video player button in the left menu which was too high. The height of this panel caused the popup that shows up when adding a torrent to be squashed, resulting in an assertion.
=> Changed height of expanding panel below button

Tribler/Test/test_gui_dialogs.py, Tribler/Test/test_libtorrent_download.py, Tribler/Test/test_my_channel.py
Very dangerous to be depending on the internet since our used torrent is not working anymore: http://torrent.fedoraproject.org/torrents/Fedora-20-i386-DVD.torrent.
=> WIP: Replace fetching of remote torrents with the usage of local ones

Tribler/Core/Utilities/network_utils.py
Currently when the socket type is hard-coded (for instance, `tcp` or `udp`), a string is being passed to the `_test_port` method, triggering the assertion which expects something else. Instead, the `_sock_type` parameter should be passed.
=> Fixed parameter type passed to _test_port

Tribler/Core/Utilities/unicode.py
After having a discussion on IRC (#python channel), I got several suggestions about refactoring the `str2unicode ` method so I made the following changes:
1) Catching a more specific exception (`UnicodeDecodeError`)
2) Using True/False values instead of 0/1
3) Removed  `unicode-escape` encoding from the list since `iso-8859-1` will be able to decode any byte string
4) Due to point 3, the `unicode(s, sys.getdefaultencoding(), errors='replace')` statement is not needed anymore.
@whirm we might use Chardet (https://pypi.python.org/pypi/chardet) to do the encoding/decoding of strings?
=> Refactored str2unicode method

Tribler/Main/Dialogs/systray.py, Tribler/Main/Utility/utility.py, Tribler/Main/tribler_main.py, Tribler/Main/vwxGUI/SRstatusbar.py
The tooltip of Tribler on Unix and Windows now show the download/upload speeds of all active downloads in the library as requested by #1650.
=> Tooltip of tray icon now contains upload/download speeds

Tribler/Core/__init__.py
It seems that these declarations are not used anywhere in the project and I don't see any use for them. Please correct me if I'm wrong if they actually have a purpose.
=> Removed unused info in __init__ of the Tribler core

Tribler/Core/TorrentDef.py
According to the Python docs, the call to `sys.getfilesystemencoding()` does not raise any exception.
=> Removed try/except block around sys.getfilesystemencoding call

Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Core/Modules/channel/channel_rss.py
The LibtorrentMgr.py imported the incorrect reactor. This caused exceptions in gumby experiments that use the full tribler core as dispersy source. I searched for other uses of the twisted_thread, and found and fixed another one that is probably wrong.
=> LibtorrentMgr and channel_rss import the correct reactor

Tribler/Core/TorrentDef.py
`urllib` does however but we are not using that. We probably used that library before but forgot to change the exception being catched.
=> The requests library does not throw URLError

Tribler/Category/Category.py, Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Upgrade/db_upgrader.py, Tribler/Main/tribler_main.py, Tribler/Test/Category/__init__.py, Tribler/Test/Category/data/Tribler/Category/category.conf, Tribler/Test/Category/data/Tribler/Category/filter_terms.filter, Tribler/Test/Category/data/category.conf, Tribler/Test/Category/test_category.py, Tribler/Test/Category/test_family_filter.py, Tribler/Test/Category/test_init_category.py, Tribler/Test/test_sqlitecachedbhandler.py
Contained in this PR:
-unit tests for the Category package. The code coverage of `Tribler.Category` is 91% after running these tests.
-custom `filter_terms.py` and `category.con` files that are used for testing purposes.
-refactored `Category.py` a bit. The `session` parameter now does not have to be passed anymore to the constructor of `Category`. For testing purposes, I've added an optional parameter to override the location of the `category.conf` file. Fixes #1986
=> Created unit tests for the Category package, decoupled Session and Category

Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Core/Session.py, Tribler/Core/exceptions.py, Tribler/Main/Utility/version_check.py, Tribler/Main/tribler_main.py, Tribler/Main/vwxGUI/MainFrame.py, Tribler/Test/API/test_download.py, Tribler/Test/API/test_seeding.py, Tribler/Test/test_magnetlink.py, Tribler/Test/test_tunnel_base.py, Tribler/Test/test_video_server.py, Tribler/Test/test_vod.py, Tribler/community/tunnel/main.py
Currently, the method to start a download using a file url, http url, magnet link or emercoin download, is located inside `MainFrame` which is part of the GUI. Eventually, `libtribler` should contain an endpoint to start a download. This PR creates a GUI-independent implementation of methods to start a download inside `LibtorrentMgr` (since that class is responsible for managing libtorrent downloads).
For now, the emercoin download is not supported since that requires porting of some emercoin functionality to the core (for instance, the `EmercoinMgr` class). Moreover, downloads started with this method do not support anonymity (yet) and uses the default configuration.
=> Created a start_download method in LibtorrentMgr

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Test/API/test_download.py
The `hide` attribute does not exist anymore in `LibtorrentDownloadImpl`.
=> Removed hide from string definition of LibtorrentDownloadImpl

Tribler/Test/API/test_download.py, Tribler/Test/test_remote_search.py
I made two improvements to the test suite:
-changed the keyword for the channel search to `de`. This is way more common than `tv` (I checked this in my own local Tribler database - `tv` has 25 hits where `de` has 300 hits). I've performed this test several times on my machine and I didn't have a single failure.
-the test that starts a download using the `start_download_from_uri` method in session now only checks whether a download has started.
=> Test improvements

Tribler/Test/Core/base_test.py, Tribler/Test/Core/data/config_files/config1.conf, Tribler/Test/Core/data/config_files/corrupt_download_config.conf, Tribler/Test/Core/data/config_files/corrupt_session_config.conf, Tribler/Test/Core/test_configparser.py, Tribler/Test/Core/test_downloadconfig.py, Tribler/Test/Core/test_network_utils.py, Tribler/Test/Core/test_sessionconfig.py
Tribler is using various kinds of configuration files. I've written some basic unit tests for the general configuration file parser, the session configuration file and the download configuration file. Each of the tested files now has a coverage of > 90%.
=> Written some more unit tests for the configuration files

Tribler/Main/tribler.py, Tribler/Main/tribler_exe.py, Tribler/Main/tribler_main.py
To fix the case where the users' PATH env. var. contains non-ASCII
characters on windows.
I've moved the multiplatform version to tribler.py and skipped it in
case we are running windows too.
=> Implement a win32 env var setter

Tribler/community/tunnel/tunnel_community.py
It's on release code and Tribler keeps telling the user that errors
occurred.
=> Lower "cannot exit data" log entry.

Tribler/Core/Utilities/torrent_utils.py, Tribler/Test/Core/test_torrent_utils.py, Tribler/Test/test_torrent.py
On OS X, an assertion was thrown when using the `libtorrent.add_files` method. After some searching, I found https://github.com/StorjOld/storjtorrent/blob/master/storjtorrent/storjtorrent.py which was working very well for me. I took their code as guideline and refactored our code to create a torrent.
=> Refactored the creation of a torrent file

Tribler/Core/Utilities/tracker_utils.py, Tribler/Test/Core/test_tracker_utils.py, Tribler/Test/test_remote_search.py
The channel search test is still failing because it cannot find channels (though a lot less than before). I increased the number of peers to have before the search can be executed. I also increased the callback time for the check whether there are channel results.
Still, these GUI tests needs a major refactoring but that's something for the longer term. Hopefully this change will increase the stability of the channel search test.
=> Changed parameters of channel search test + removed blocking call to lookup trackers

Tribler/Main/Build/Win/tribler.nsi, Tribler/Main/Build/update_version_from_git.py
Fixes #2014, #1943, #1878
- The 64 bit will now have a `_x64` suffix and the 32 bit a `_x86`.
- Will now check if Tribler is running when installer or uninstalling
- Now installs in `Program files` when 64 bit rather than `Program files (x86)`
- Misc. improvements in strings and formatting.
=> Fixes and changes to the Windows package script

Tribler/Main/Build/Win/tribler.nsi
Will now read the uninstallstring in the register on windows and use that location, rather than the $INSTDIR of the installer which is always the default location at that point.
Fixes #1664
=> Nsis fix uninstall location

Tribler/Core/Utilities/utilities.py, Tribler/Test/Core/test_utilities.py
As described in #2002, web seeds are not working when downloading torrents with Tribler that contains a `url-list` metainfo key. The reason for this is that we only accept `url-list` arguments as a list, however, the  `mktorrent` tool creates the `url-list` value as a string if only one web seed is given. I've added some code to convert a string to a single-item list.
=> url-list with type string in torrent metainfo is now supported

Tribler/Core/CacheDB/SqliteCacheDBHandler.py, Tribler/Core/CacheDB/sqlitecachedb.py, Tribler/Core/Session.py, Tribler/Test/Core/test_session.py, Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py
This PR fixes the bug where the freespace method does not delete anything. 
Fixes **1** bug
Added **1** (property) method for lint issues (enhancement). This can be used by other classes also accessing the protected member `_connection`.
Adds **2**  and modifies **1** tests.
=> Free space actually deletes items

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Core/Libtorrent/LibtorrentMgr.py
When adding or loading a torrent file in Tribler, the `auto_managed` settings (and some other settings) were not automatically set in a libtorrent without deprecated methods, making it behave very weird when trying to pause or resume a torrent. This PR should fix this.
=> Fixed flags when adding a torrent file

Tribler/Test/Community/Tunnel/test_tunnelhelper.py, Tribler/community/tunnel/main.py, twisted/twisted/plugins/bartercast_crawler_plugin.py
After a day of memory investigation, I found the root cause of the memory usage problem in the tunnel helpers when they are running for a long time.
The problem is that the Twisted log observer is intercepting lower-level Twisted events. When Twisted starts, a `LimitedHistoryLogObserver` is created, however, the name is very misleading since the observed history is not limited at all! An entry is written to the log, every time something interesting happens in the Tunnel community (for instance, the reactor starts or stops listening on a specific port or the `TunnelExitSocket` protocol starts).
Searching on the internet, brought me to this issue: [here](http://twistedmatrix.com/trac/ticket/7841). A workaround has been implemented [here](https://github.com/plq/neurons/blob/417836a729706f2d14 …
=> Fixed a memory issue when running the tunnel helpers

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/CacheDB/Notifier.py, Tribler/Core/Modules/watch_folder.py, Tribler/Core/SessionConfig.py, Tribler/Core/defaults.py, Tribler/Core/simpledefs.py, Tribler/Main/tribler_main.py, Tribler/Main/vwxGUI/settingsDialog.py, Tribler/Test/Core/Modules/__init__.py, Tribler/Test/Core/Modules/test_watch_folder.py, Tribler/Test/test_as_server.py
As requested in #1038, I've implemented the watch folder functionality.
I've created a separate subclass of `TaskManager` that polls the watch folder functionality every two minutes and adds downloads of (new) torrent files it finds in this directory. I'm aware that there are several directory watching libraries available in Python (for instance, [watchdog](https://pypi.python.org/pypi/watchdog)) but I don't want to add another dependency to Tribler (but this is open for discussion).
The watch folder can be enabled in settings -> general and the path of the watch directory can be adjusted.
=> Implemented the watch folder functionality

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Test/Core/test_libtorrent_download_impl.py
Removed a callback being passed to two functions in libtorrentdownloadimpl, refactored one of them and let the other return a deferred instead.
Fixes #2032
Fixes **1** PEP8 violation in launchmanycores (enchancement)
Removes several callbacks to use deferreds instead (code complexity/quality enchancement)
Adds **7** tests that cover the libtorrentdownloadmanagerimpl
**improves** responsiveness by making use of asynchronous callbacks.
=> Refactored a callback to deferred in libtorrentdownloadmanagerimpl

Tribler/Main/vwxGUI/widgets.py
On Debian when clicking on `channels`, it would crash. The reason for this is that there is one frame in-between the redrawing of the left menu where the height of the row in the list would be 1. This makes the `path.AddRoundedRectangle(...)` to crash Python (since there is not enough space to draw the rounded corners with radius 5). I've added a check to make sure that this does not happen.
@lfdversluis can you review this one?
Fixes #2095 (tested on Debian)
=> Fixed bug where wx would crash when adding rounded corners to a widget on Debian

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Main/vwxGUI/SearchGridManager.py, Tribler/Main/vwxGUI/list_details.py, Tribler/Main/vwxGUI/list_item.py
The problem is that `self.torrent.magnetstatus` will always be **not** None when adding from a magnet link, even when the .torrent has been downloaded. This will trigger the first if statement and set the status wrong. So now the DL status takes priority over the magnetstatus.
I also tried removing the `if self.torrent.magnetstatus` check which seems to work, but as I do not understand the logic behind [this undocumented function](https://github.com/Tribler/tribler/blob/devel/Tribler/Main/Utility/GuiDBTuples.py#L215) I decided to go with the current approach. Confirmed by removing + data and readding. Now changes immediately.
Thinking about it, it makes no sense. It switched to seeding just fine but it should not if that magnetstatus list is not None. I'll delete this magnetstatus object …
=> Fixed wrong status when downloading

Tribler/Main/Build/Win/setuptribler.py
Most likely fixes the case of #2056. I have tested the installation on proxmox 144 and tribler starts with no (visible) problems.
based on: http://stackoverflow.com/questions/20930173/how-to-include-components-of-psutil-in-py2exe-that-py2exe-cant-find
Fixes **1** bug.
=> READY: Added some dlls to the exclude list when building Tribler on Windows

Tribler/Test/test_as_server.py
Fixes #2075 
Prevent from cascading delayed calls in other tests (enhancement).
Added a check which tests for left readers/writers in the reactor (enhancement)
@whirm I ran this with the Core tests (unittests) and it seems to work fine, no errors. Should a test be written for this case? It's hard because you are in the teardown after all.
=> READY: Now cleaning the reactor after a test has left delayed calls behind

Tribler/Main/vwxGUI/list_body.py
`wx.ACCEL_RAW_CTRL` is not implemented in wx2.8. We should still support wx2.8 so users on Ubuntu 14.04 and older can Tribler.
=> Disabled select all functionalities on wx versions older than 3

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/CacheDB/Notifier.py, Tribler/Core/Modules/versioncheck_manager.py, Tribler/Core/defaults.py, Tribler/Core/simpledefs.py, Tribler/Main/Dialogs/NewVersionDialog.py, Tribler/Main/tribler_main.py, Tribler/Test/Core/Modules/test_versioncheck.py
Github has a nice API endpoint that can be used to fetch the latest release: `https://api.github.com/repos/tribler/tribler/releases`. This gives the latest stable release.
I propose to add a version check manager that can schedule version checks in the future. This can for instance be called when the GUI starts.
I'm not really sure about the best way to integrate this into the GUI but we can discuss this. This is just a quick implementation of a version check manager that should replace `version_check.py` in `Main/Utility`.
This PR contains work on #14.
=> Added a version check manager

Tribler/Core/SessionConfig.py, Tribler/Core/Utilities/configparser.py
So a non-ASCII one can be decoded correctly by the config parser.
Fixes #2093
=> Hack quotes in the nickname config.

Tribler/Main/vwxGUI/list_header.py
Placing a `wx.SearchCtrl` widget inside a container makes GTK happy.
=> WIP: Implemented workaround for GTK assertions when starting Tribler on Ubuntu or Debian

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Session.py, Tribler/Core/TorrentChecker/session.py, Tribler/Core/TorrentChecker/torrent_checker.py, Tribler/Core/Utilities/encoding.py, Tribler/Test/Core/test_torrentchecker.py, Tribler/Test/Core/test_torrentchecker_session.py, Tribler/Test/Core/test_utilities.py, Tribler/Test/test_torrent_checking.py
More deletions than additions while keeping the same functionality (I hope), but much more clean!
- HTTP tracker code now makes use of Twisted's RedirectAgent. This means it will automatically redirect when a 30x code is returned, is asynchronous and has a timeout implemented. 
- The UDP tracker is now asynchronous, has a timeout added and has some bug fixes.
- Shutdown of a UDP connection is now asynchronous, this is propogated in Tribler where it preparations are made for other components to shutdown asynchronous as well by using Deferreds.
Fixes #2035, contributing to #1848
Adds **29** tests
Improves responsiveness a lot, watchdog was tripping with > 10 seconds timeout. Not anymore.
Fixed **2** bugs
Improved redirection by making use of Twisted's redirectAgent
Added lots of …
=> Refactored tracker health check code to become asynchronous. Adjusted a part of the tribler shutdown procedure as a result.

Tribler/Core/Utilities/configparser.py
The tests in `Tribler/Test/API/test_download.py` occasionally got stuck. It turned out that is caused by locks in the `threading` and `logging` framework which seems to contain a bug (http://bugs.python.org/issue6721).
The location where the tests were hanging is always the `get` method of `configparser.py`. There is a lock here but no thread critical code as far as I can see so I propose to remove the lock. I tested the code below and the tests do not get stuck anymore (been running them for a while in several terminals).
I will run the unit tests several times.
=> Removed lock in get method of configparser

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Modules/restapi/__init__.py, Tribler/Core/Modules/restapi/my_channel_endpoint.py, Tribler/Core/Modules/restapi/rest_manager.py, Tribler/Core/Modules/restapi/root_endpoint.py, Tribler/Core/SessionConfig.py, Tribler/Core/defaults.py, Tribler/Test/Core/Modules/RestApi/__init__.py, Tribler/Test/Core/Modules/RestApi/base_api_test.py, Tribler/Test/Core/Modules/RestApi/test_my_channel_endpoints.py, Tribler/Test/Core/test_sessionconfig.py, Tribler/Test/test_as_server.py, doc/Tribler REST API.md, setup.py
In this PR, I created the classes that are setting up the Tribler HTTP API. The API can be enabled or disabled by using the session configuration file. Also, changing the port is possible. By default, the API listens on port 8085 (we should fix this port so the new Qt GUI knows which port to use) but it's also possible to assign a random port to the API as I do in the unit tests.
The first endpoint of the API is to fetch the overview of your channel. This returns the name, identifier (hex-encoded) and description of your channel. The API will be gradually improved and expanded in separate PRs after this one has been merged. I will first focus on the endpoints related to your channel (getting/adding torrents, playlists and rss-feeds) as requested by @brussee.
I've also written a document …
=> Ready: Created the HTTP API classes and written a first endpoint to fetch information about your channel

Tribler/Core/Modules/restapi/root_endpoint.py, Tribler/Core/Modules/restapi/settings_endpoint.py, Tribler/Core/Utilities/configparser.py, Tribler/Test/Core/Modules/RestApi/base_api_test.py, Tribler/Test/Core/Modules/RestApi/test_settings_endpoint.py, doc/Tribler REST API.md
In this PR, I've implemented the next endpoint: getting the settings present in Tribler. The fact that we are using three different configuration files makes it harder to return a single JSON dictionary with all the settings. Nevertheless, this endpoint returns a single JSON dictionary that should contain all settings needed for the new GUI.
I also made some minor changes to other files. For instance, I created a static method `get_literal_value` in `configparser.py` and I've added a method in that class to return a configuration file as dictionary. Moreover, I've written a test to check the new settings endpoint and extended the documentation.
=> READY: Implemented endpoint to fetch Tribler settings

twisted/twisted/plugins/tribler_plugin.py
This PR adds a twistd plugin so Tribler can be started using the `twistd` command. To run the plugin, `cd` to the root folder of Tribler (not the `Tribler` directory) and execute: `PYTHONPATH=twisted twistd -n tribler`. This will run the twistd daemon.
Note that this PR requires https://github.com/Tribler/dispersy/pull/474 to work (otherwise, Tribler hangs during startup).
@whirm Should I cover the code in this PR with a test? I'm not sure how I should write a test for this plugin.
=> Added Tribler twistd plugin

Tribler/Test/test_multichain_community.py
This removes a timeout listed in https://github.com/Tribler/tribler/issues/2130
Now that multichain no longer uses a custom timeout, this is basically just a dispersy test now, which should be tested elsewhere.
=> Remove multichain dispersy timeout test

Tribler/Core/CacheDB/SqliteCacheDBHandler.py, Tribler/Core/Modules/restapi/channels_endpoint.py, Tribler/Main/vwxGUI/SearchGridManager.py, Tribler/Test/Core/test_sqlitecachedbhandler_channels.py
Bugs me for a while. This fixes the typo in those which affected. Is there any other place using this method?
=> fix typo includeDispsersy to includeDispersy

Tribler/Core/Modules/restapi/channels_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_channels_endpoints.py, doc/Tribler REST API.md
This endpoint makes it possible to subscribe to a channel. The testing of this endpoint turned out to be a little harder since a request in AllChannel community is made when subscribing to a channel. Since I didn't want to start Dispersy for this test, I created a fake instance of Dispersy and AllChannel community.
=> Implemented endpoint to subscribe to and unsubscribe from a channel

Tribler/Core/CacheDB/SqliteCacheDBHandler.py, Tribler/Core/Modules/restapi/channels_endpoint.py, Tribler/Core/Modules/restapi/events_endpoint.py, Tribler/Core/Modules/restapi/root_endpoint.py, Tribler/Core/Modules/restapi/search_endpoint.py, Tribler/Core/Modules/restapi/util.py, Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_search_endpoint.py, Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py, doc/Tribler REST API.md
I think this is one of the most important endpoints in Tribler. A GET request to this endpoint will return the channels and torrents matching a query.
This PR is a little bigger since it also contains a bug fix and a test for a problem when sorting the list of torrents results in `SQLiteCacheDBHandler.py`. Special thanks to @lfdversluis, @LipuFei and @whirm for helping with debugging this one 👍 
Update: I found another bug in the `searchNames` method where the name of the loop variable was redefined inside the for-loop so I also fixed that one.
=> READY: Implemented endpoint to search for torrents and channels in Tribler

Tribler/Core/osutils.py, Tribler/Test/Core/test_osutils.py
Triblerd running as a service does not need to know the api version.
=>  Avoid 2 unnecessary dependecies.

.gitignore, Tribler/Core/Modules/channel/channel.py, Tribler/Core/Modules/channel/channel_manager.py, Tribler/Core/Modules/restapi/my_channel_endpoint.py, Tribler/Core/Modules/restapi/rest_manager.py, Tribler/Core/Session.py, Tribler/Core/exceptions.py, Tribler/Test/Core/Modules/RestApi/base_api_test.py, Tribler/Test/Core/Modules/RestApi/test_my_channel_endpoints.py, Tribler/Test/Core/Modules/RestApi/test_rest_manager.py, Tribler/Test/Core/Modules/channel/__init__.py, Tribler/Test/Core/Modules/channel/test_channel_manager.py, Tribler/Test/Core/test_session.py, doc/Tribler REST API.md
Why are channel names required to be unique? -> Design decision.
And why the silent fail? on channel_manager.py:70 -> Solved.
=> Create channel api endpoint

Tribler/Core/Modules/restapi/downloads_endpoint.py, Tribler/Core/Modules/restapi/root_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py, Tribler/Test/Core/Modules/channel/__init__.py, doc/Tribler REST API.md
Think this is one of the more important endpoints we are going to implement. It gets all downloads, both active and inactive, in Tribler. This endpoint can be used as a quick way to get a list of all ongoing downloads. Besides this endpoint, I'm thinking about pushing changes to downloads over the events connection (in particular, the libtorrent alerts) but we should probably discuss this first. And this is also work that should be done in a separate PR.
I also want to create a separate endpoint to get full details about a particular download (that has the url `http://localhost:8085/downloads/4344503b7e797ebf31582327a5baae35b11bda01`). This includes information about trackers, files and peers.
=> Implemented endpoint to get all downloads in Tribler

Tribler/Main/Build/Mac/setuptriblermac_64bit.py
This fixes the OS X builder. The readme.txt file has been removed a while ago.
=> Removed readme from OS X builder

Tribler/Main/Build/Win/tribler.nsi
So after quite a while I managed to get rid of the double running problem. The problem was in the UAC plugin and after having a nice chat with the author Anders (nice guy by the way :D) he told me to sacrifice the check box at the last page and get rid of the UAC plugin.
So I got rid of the UAC and kept the check box anyway that now calls the desktop shortcut that is created during installation and works perfect. Tested on proxmox 144 and works splendid.
While I was at it, I formatted the file because it was 2, 3 and 4 space indented mixed with tabs.
Also added a bit of comments to let future generations know why decisions were made and what it does.
Oh... ignore most fixup commits as they feature tries by me to either identify the root cause of this bug, get to know how stuff works, …
=> Fix NSIS running twice

twisted/twisted/plugins/tunnel_helper_plugin.py
To avoid arguments being evaluated to True by python and accidental running the tunnels with exit mode enabled.
Fixes #2259
Sorry for the inconvenience!
=> Made the exit node option a flag rather instead of argument.

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py
This PR create alert for `save_resume_data`. I used `Deferred` on `resume_data`. This deferred object will call `lm.start_download` as callback (I don't find other use beside this). Resume data will be stored in `LibtorrentDownloadImpl` attribute if available.
The result is, `engineresumedata` is now available in disk-saved state. This to a certain extent, solves #2251. However, I can't get fastresume in libtorrent working, even with my own small program. So #2199 is not solved yet.
=> Alert for resume data

Tribler/Test/test_as_server.py
Let's see whether it is this deferred that's causing problems on Windows. I will retest this several times.
=> Increased timeout of teardown deferred

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Modules/restapi/root_endpoint.py, Tribler/Core/Session.py
In this PR, I start the events endpoint before the upgrader starts. This is because I want to sent important upgrader events over the events connection.
When the upgrader is finished, the other endpoints will be activated.
=> Moved the startup of the REST API

Tribler/Core/Modules/restapi/channels/channels_endpoint.py, Tribler/Core/Modules/restapi/channels/channels_popular_endpoint.py, Tribler/Test/Core/Modules/RestApi/Channels/test_channels_popular_endpoint.py, doc/restapi/channels_popular.rst, doc/restapi/introduction.rst
They are displayed on the front page in the new GUI.
=> Implemented endpoint to fetch popular channels

doc/building/building.rst
It appears the changes in setup.py requires an additional package (not installed by default on Ubuntu). This was likely the cause for the failed build 624 on https://jenkins.tribler.org/job/Build-Tribler_Ubuntu-64_devel/624/console
=> Update required package for building on Debian / Ubuntu

Tribler/community/tunnel/tunnel_community.py
Fixes #2352. The circuit object has not been constructed at this time, so we cannot account bytes up/down on it yet. Since this is only a few bytes of control traffic at every tunnel creation, we can safely ignore the stats count on this packet.
=> Tunnel extension counted bytes on a non-existant tunnel

Tribler/Main/tribler_main.py
when shutting down to avoid getting them triggered half way during
shutdown and crashing because the GUI or any other component has been
removed.
=> Remove session-registered notification callbacks

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py
@ardhipoetra when writing additional tests, I noticed that a checkHandleAndSynchronize decorator missed parenthesis.
=> Fixed decorator in LibtorrentDownloadImpl

Tribler/Core/Modules/restapi/events_endpoint.py, Tribler/Test/test_remote_search.py
I refactored the remote search tests so they do not make use of a GUI anymore.
=> Removed GUI from remote channel/torrent search

Tribler/Test/Core/CreditMining/test_creditmining.py, Tribler/Test/Core/CreditMining/test_creditmining_sys.py
As part of PR #2399. This will solve issue #2365.
Sometime the random value cannot be determined although start at the same seed. Use `random.seed` inside of the test hopefully solve this issue.
=> Fix creditmining test randomness

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Core/Modules/restapi/downloads_endpoint.py, Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py, Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
This problematic wrapper function is now unused:  (a flag is used instead by @devos50)
```
@waitForHandleAndSynchronize(True)
def set_share_mode(self, share_mode):
self.handle.set_share_mode(share_mode)
```
=> RestAPI start download endpoint

Tribler/Core/SessionConfig.py
find_executable relies on the executable to be on the path, but on android it is in the current folder and not on the path
=> READY: absolute path for android

Tribler/Main/hacks.py
Anonymous downloads were not working in the bundled version of OS X due to the openssl backend which cannot be found. I've enabled the monkey patch for cryptography on OS X too when we're frozen.
I've tested it and anonymous downloads seems to work correctly now. It's probably not the best fix but it's the best fix I can think of right now.
See https://github.com/pyca/cryptography/issues/2039
=> Enable monkey crypto patch with py2app

Tribler/Main/Build/Mac/setuptriblermac_64bit.py
This will reduce the size of Tribler.app from around 231mb to 100.5mb 👍 
Py2app somehow manages to include pyqt5 in the app bundle. The problem is that I cannot remove pyqt5 from the site packages, otherwise my new GUI won't work anymore on the builder.
Hopefully we can switch to PyInstaller soon!
=> WIP: Excluded pyqt5 from build

Tribler/Test/Core/CreditMining/test_creditmining.py, Tribler/Test/Core/CreditMining/test_creditmining_sys.py
This PR reverts commit aa47be891d7ea8cdd5565e9a22a7ec0c2c3ea9af, which reverts the disabling of credit mining test.
=> re-Disabled credit mining tests

Tribler/Test/test_as_server.py
The dirty reactor check at the end of a test run has been broken for a while now.
Brace yourselves.
=> Actually check for a dirty reactor

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Test/Core/CreditMining/test_creditmining.py, Tribler/Test/Core/CreditMining/test_creditmining_sys.py
As part of PR #2399. This will solve issue mentioned in [here](https://github.com/Tribler/tribler/pull/2399#issuecomment-230398652).
Sometime, function called in twisted cannot find the object that should be there. This case is rare, in my opinion. This PR works as a precaution for that, though.
EDIT:
The work is similar with old PR #2462. This will solve issue #2378. Related to #2303. Some of the decorator is wrong. This may cause race condition when threadpool is already shutting down. This PR will solve those issue. Also, provided correct default value on decorator
=> Fix creditmining test asynchronous issue

Tribler/Main/vwxGUI/CreditMiningPanel.py, Tribler/Policies/BoostingSource.py, Tribler/Policies/credit_mining_util.py, Tribler/Test/Core/CreditMining/test_creditmining_sys.py
As fix for Issue #2356.
This will remove `Main` package dependencies on credit mining. It might be slow when downloading the credit source, but it works. How can I download the torrent via DHT/Peers?
Btw, made PR into `next` because this is a bugfix for experimental feature (credit mining)
=> WIP: GuiDBTuples credit mining removal

Tribler/Core/APIImplementation/LaunchManyCore.py
This makes sure that when closing Tribler, uninitialized pstates do not cause AssertionErrors.
This fixes #2577 (see for more info).
=> READY: Added save_resume_data None case

Tribler/Core/Modules/restapi/events_endpoint.py, Tribler/community/channel/community.py
The infohash is needed on the client and available on the server. Why not send all potentially relevant information along?
=> Put entire message payload info in torrent discovered event

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Test/Core/CreditMining/test_creditmining.py
Fixes #2598
Fixed random seed sometimes produce different number in linux and win32. This pull request will replace those random test with artificial-random test.
=> Fixed credit mining random policy test

Tribler/Core/TorrentChecker/session.py, Tribler/Test/API/test_download.py
It can be that there is no scraper available if the ip resolution has failed.
Fixes #2621
=> Fixed scraper issue

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Core/Libtorrent/__init__.py, Tribler/Core/Modules/restapi/settings_endpoint.py, Tribler/Core/Session.py, Tribler/Core/TorrentChecker/session.py, Tribler/Core/exceptions.py, Tribler/Policies/BoostingManager.py, Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py, Tribler/Test/Core/Modules/RestApi/base_api_test.py, Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_multichain_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_search_endpoint.py, Tribler/Test/Core/Video/test_video_server.py, Tribler/Test/test_as_server.py, twisted/plugins/tribler_plugin.py
I've found out that our resume data is not written away which can be addressed to the checkpointing mechanism and the fact that we are not waiting on our shutdown deferred when closing Tribler from the twistd plugin.
In this PR, I've refactored the complete checkpointing mechanism to make it more simple and so it is using Twisted. Moreover, I've created a `get_handle` method for each download that returns a deferred that fires when the libtorrent handle is available and valid. This allowed me to remove the `waitForHandleAndSynchronized` method which was rather ugly.
Also, various Twisted issues have been fixed, i.e. when we don't wait for a deferred to fire.
Fixes #2531
=> Refactored checkpointing system

Tribler/Core/Modules/restapi/shutdown_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_shutdown_endpoint.py
Removal of arguments in https://github.com/Tribler/tribler/pull/2595/commits/b0ff88272cf23732b30224a406d63db9211f4e89
=> Fix session.shutdown arguments

doc/development/development_on_linux.rst
Another note: `libsodium13` (1.0.3) does not exist on Ubuntu 1604, so I installed `libsodium18` (1.0.11) instead and tribler starts fine (I haven't tested all the functionalities). Perhaps it's useful to comment on this in the instructions too?
=> Typo in Linux build instructions

Tribler/Core/CacheDB/Notifier.py, Tribler/Core/Session.py, Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py, Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_search_endpoint.py, Tribler/Test/Core/test_notifier.py
When the wx GUI was active, we used to have the notifier callback on the threadpool. Now that we are not having multiple threads anymore, we should have this callback being invoked on the reactor thread. This might also solve some race conditions we are experiencing and avoids having to write code to delegate logic in the callback method to the reactor thread.
Fixes #2597
=> WIP: Notifier callback is now on reactor thread

Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Policies/BoostingManager.py, Tribler/Test/Core/CreditMining/mock_creditmining.py
This PR will add a function to check libtorrent version. On old version of libtorrent, we can call this by `libtorrent.version`. However, starting from version RC_1_0, that will be deprecated and replaced by `libtorrent.__version__` (which more python-like).
Relevant : https://github.com/arvidn/libtorrent/blob/master/bindings/python/src/version.cpp
This should close issue #2676 if merged.
=> Added function to check libtorrent version

Tribler/Test/Community/Tunnel/test_tunnelcommunity.py, Tribler/community/tunnel/crypto/tunnelcrypto.py
Fixes #2663, contains:
- Correction of exception thrown by `decrypt_str()`
- Unit test for this case
=> Fixed wrong exception for invalid received encryption

Tribler/Test/Community/Tunnel/test_tunnelcommunity.py, Tribler/community/tunnel/hidden_community.py, Tribler/community/tunnel/tunnel_community.py
Fixes #2713
- Fixed anon-circuit request-cache with an extension mid of 0
- Fixed RelayRoutes created in hidden_tunnelcommunity without mid
- Refactored copy_shallow_candidate so the `mid` value is used for Circuits, RelayRoutes and TunnelExitSockets alike
=> Refactored copy_shallow_candidate

doc/development/development_on_linux.rst
Second attempt, this time for `devel`. I removed the python2-gmpy2, python2-pillow and wxpython2.8 packages and added python2-chardet, python2-pyqt5, qt5-svg and phonon-qt5-vlc.
This fixes https://github.com/Tribler/tribler/issues/2732.
=> Update documentation on dependencies for Arch Linux

Tribler/Core/TorrentChecker/torrent_checker.py, Tribler/Core/Utilities/tracker_utils.py, Tribler/Test/Core/TorrentChecker/test_torrentchecker.py, Tribler/Test/Core/test_tracker_utils.py
RuntimeError crashes the GUI, so we throw MalformedTrackerURLException, catch it and log the error.
Fixes #2723
I didn't attempt to delete the invalid tracker, I may attempt it at a later stage. I did see a `update_tracker_info` method in `TrackerManager`, it has a `is_successful` flag that increments the failure count. If it's reasonable to increment the failure count in this scenario then I can modify my code to do it.
=> Throw MalformedTrackerURLException

twisted/plugins/tunnel_helper_plugin.py
If there is no logger.conf in the working directory, then invoking twistd will produce an uncaught exception on the stderr. This is because the tunnel_helper unconditionally uses the logger.conf file. This made gumby spew several errors that have nothing to do with my experiments.
=> Twistd failed to reflect the tunnel helper plugin

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
This might happen when downloading anonymously.
Fixes #2786
=> Fixed a negative number of peers

Tribler/Core/CacheDB/SqliteCacheDBHandler.py
Otherwise, the HTTP request URL can get too long. For now, I've hard-coded this limit to 30.
=> Limit torrents queried by the torrent checker

TriblerGUI/tribler_request_manager.py, TriblerGUI/widgets/downloadspage.py
Also increased the Dispersy pointer and fixed a crash when the error dialog was displayed during a request to Tribler and the cancel button was clicked.
=> Fixed crash in torrent export functionality

Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Test/Community/Tunnel/Socks5/test_connection.py, Tribler/community/tunnel/Socks5/server.py
Fixes #2787, this switches the SOCKS5 behavior from old:
1. Deny connection if no circuits available
2. Fallback to naked downloading
To new:
1. Always allow connection
2. [Drop packets while no circuits are available](https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/Socks5/server.py#L64)
This also includes a base for future unittests for the Socks5Connection.
Pylint violation in unit test:
I had to use a protected member since [SocksUDPConnection does not yield on the listen_port.stopListening() deferred](https://github.com/Tribler/tribler/blob/devel/Tribler/community/tunnel/Socks5/server.py#L79) causing a dirty reactor.
=> READY: Allow UDP associate without circuits

TriblerGUI/widgets/downloadwidgetitem.py
This fixes #1591 by considering torrents with an ETA of 0 to have an
ETA of infinity.
It does not deteriorate pep8, pylint or the unit tests.
=> Consider torrents without ETA taking the longest

Tribler/community/tunnel/tunnel_community.py
During gumby refactoring I stubled across this situation. Apparently all tunnel settings needed to have the socks port set explicitly after setting it in the session. This PR makes the tunnel_community_socks5_listen_ports behave the same as the other tunnel_community settings.
=> TunnelSettings respect socks port settings in session

Tribler/Core/Utilities/tracker_utils.py, Tribler/Test/Core/Utilities/test_tracker_utils.py
Fixes https://github.com/Tribler/tribler/issues/2860.
I catch all exceptions in that come from parsing the given tracker url with `urlparse`. I believe violating pylint rules is justified.
=> Catch all exceptions of urlparse in tracker_utils

Tribler/Core/APIImplementation/LaunchManyCore.py
I removed the import of `prctl` as it isn't used.
=> Remove prctl import from LaunchManyCore

TriblerGUI/widgets/videoplayerpage.py
This check was a bit too strict; on some systems it could be that there is no plugin path set but that VLC is still functioning.
=> Removed VLC plugin check

Tribler/Test/Community/Multichain/test_multichain_database.py, Tribler/community/multichain/database.py
Fixes #2916 
Apparently the multichain database version was already 2 at some point in time. This causes the database not to update to the new version introduced by the true halves PR.
=> Increased multichain db version

doc/development/development_on_linux.rst
I found that Tribler requires `python2-matplotlib` on Arch when I was trying to install without it. I ran into no other dependency issues, and the list seems complete barring that.
=> Small addition to Arch dependencies

Tribler/Core/TFTP/handler.py, Tribler/Test/Core/TFTP/test_tftp_handler.py
Instead of risking an AttributeError, return from handling a request.
=> Only attempt to load metadata when metadata store is enabled

Tribler/Core/TFTP/handler.py, Tribler/Test/Core/TFTP/test_tftp_handler.py
Instead of risking an AttributeError, return from handling a request.
=> Check if torrent store is enabled before attempting to retrieve torrent

doc/development/development_on_linux.rst
The `python-crypto` is not necessary for Ubuntu. I tested this on 17.04. Moreover, for the Arch dependencies, the package is not listed either.
=> Remove unused dependency from Ubuntu documentation

Tribler/Core/Modules/watch_folder.py
This (partially) fixes https://github.com/Tribler/tribler/issues/3008.
=> Set safeseeding value in watch folder with result of function

Tribler/Core/Config/config.spec, Tribler/Core/Config/tribler_config.py, Tribler/Test/Community/Triblerchain/test_community.py, Tribler/Test/Community/Trustchain/test_community.py, Tribler/community/triblerchain/community.py, Tribler/community/trustchain/community.py, Tribler/community/trustchain/conversion.py
This PR implements live edges for the MultiChain community as discussed in https://github.com/Tribler/tribler/issues/2894 and https://github.com/Tribler/tribler/issues/2458 .
Extra functionality:
- Refactored `MultiChainCommunity.cleanup_pending()` to be a `TaskManager` task, so that it gets destroyed when the community is unloaded.
- Added negative chain sequence numbers. This behaves like Python negative array indices: -1 gives the last element, -2 the last two elements and so on.
=> Live edges

doc/development/development_on_linux.rst
A typo was introduced in https://github.com/Tribler/tribler/pull/3025. See [this](https://www.archlinux.org/packages/?sort=&q=python2-keyrings&maintainer=&flagged=).
=> Fix typo in Arch Linux depencies

doc/development/development_on_linux.rst
Ran into multiple ImportError's while trying to use devel branch cddfbad065c9a1425e3889f2d45391d15da8480b, fixed with these deps.
=> Add missing Arch deps for devel

Tribler/Core/Config/config.spec, Tribler/Core/Config/tribler_config.py, Tribler/Test/Community/Market/Integration/test_market_community.py, Tribler/Test/Community/Market/Integration/test_market_session.py, Tribler/Test/Community/Market/test_community.py, Tribler/Test/Community/Market/test_conversion.py, Tribler/Test/Community/Market/test_database.py, Tribler/Test/Community/Market/test_matching_engine.py, Tribler/Test/Community/Market/test_order.py, Tribler/Test/Community/Market/test_orderbook.py, Tribler/Test/Community/Market/test_payload.py, Tribler/Test/Community/Market/test_tickentry.py, Tribler/Test/Community/Market/test_trade.py, Tribler/Test/Community/Market/test_transaction_manager.py, Tribler/Test/Core/Config/test_tribler_config.py, Tribler/Test/Core/Modules/RestApi/test_market_endpoint.py, Tribler/community/market/community.py, Tribler/community/market/conversion.py, Tribler/community/market/core/__init__.py, Tribler/community/market/core/matching_engine.py, Tribler/community/market/core/order.py, Tribler/community/market/core/orderbook.py, Tribler/community/market/core/pricelevel.py, Tribler/community/market/core/side.py, Tribler/community/market/core/tickentry.py, Tribler/community/market/core/trade.py, Tribler/community/market/core/transaction.py, Tribler/community/market/core/transaction_manager.py, Tribler/community/market/database.py, Tribler/community/market/payload.py
This PR implements various functionalities in the market community:
- **generic matching**: instead of matching orders, it is now possible to match any tick with any other tick (first commit).
- **matchmakers**: matchmakers are responsible for finding matches between asks and bids in the market. By default, every new user in a matchmaker, however, being matchmaker can be disabled with a configuration option (second commit).
- **test suite improvement**: I've added some additional tests and fixed existing ones (third commit). 
Matchmaking protocol:
=> Implemented matchmakers in the market

Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py
Fixes #3070.
In particular what was happening:
- If `libtorrent.find_torrent()` does not find a download, it returns an invalid handle.
- If `libtorrent.find_torrent()` finds a download it can have an invalid handle if it is still in the `checking_resume_data` state while it needs to fetch metadata.
I previously assumed that an invalid handle always means the torrent does not exist.
=> Fixed find_torrents finding invalid torrents

Tribler/Test/Core/Modules/channel/test_channel_manager.py, TriblerGUI/debug_window.py
This is a backport of d4099e73324b0eae3400982d7c393cb5b8125e6b.
=> Fixed channel manager session during tests

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Modules/tracker_manager.py, Tribler/Core/TorrentChecker/torrent_checker.py, Tribler/Test/Community/Tunnel/test_tunnelcommunity.py, Tribler/Test/Core/Modules/test_tracker_manager.py, Tribler/Test/Core/TorrentChecker/test_torrentchecker.py, Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py, Tribler/community/tunnel/tunnel_community.py
This PR fixes various memory issues which caused the Tribler memory to grow over time. This issue most likely fixes #2966.
Additionally, I've refactored the torrent checker. Before, we kept all tracker status dictionaries in memory. Now, we will fetch them from the SQLite database.
=> Various memory fixes

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Fixes #3102 
Before, we would always checkpoint with no data as early as possible. This ignored the fact that this save data might actually exist though. This PR checks whether save data already exists and only if it does NOT exist, it will write a dataless checkpoint as before.
=> Fix always rechecking on restart

check_os.py
Related to #3120 .
This replaces the `Qt` dialog with a `Tkinter` dialog when Tribler fails to start (reason being that Qt might be the component that fails to load). In contrast to `Qt`, `Tkinter` is shipped with Python 2.7 by default.
Due to `Tkinter` being an inferior product, I did get rid of the `close` button.
This is how it looks on Ubuntu 16:
This is how it looks on Windows 7:
=> READY: Replaced fallback error dialog backend with Tkinter

debian/tribler.install
This is a backport of #3110. Fixes #3123.
=> If check_os is not found tribler will not run

Tribler/Core/Modules/resource_monitor.py
Old version of psutil (<4.0.0) does not have memory_full_info() method, so checked for the existence of the method and added proper fallback for it.
=> Fix memory usage psutil bug

TriblerGUI/widgets/downloadspage.py
Export torrent now uses name instead of infohash
[Issue #3131](https://github.com/Tribler/tribler/issues/3131)
Fixes #3131
=> Fix #3131: export torrent now uses name instead of infohash

Tribler/Core/Utilities/json_util.py
Related to #3159. The UnicodeDecodeError.message being sent with error reports is empty, while the `str()` representation includes all of the additional debug info we need.
=> Fixed UnicodeDecodeError.message being empty

logger.conf, run_tribler.py
Fixed log rotation and enforced flushing all logs before system exit
=> Fix #3163 non-responsive debug logs

Tribler/Core/Modules/restapi/torrentinfo_endpoint.py, TriblerGUI/dialogs/startdownloaddialog.py
Using quote_plus and unquote_plus on torrent file name when it is used as file URI
=> Fix #3161 torrent name error

run_tribler.py
Fix #3174 It seems the problem was with resolving _MEIPASS environment variable in Mac so refactored the code to use existing base path to properly compose the logging path.
=> Fix for missing logs in Mac

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Test/Core/test_launch_many_cores.py
Fixes #3169, fixes #3186.
This PR removes the hidden seeding feature which readds the torrent with a different amount of hops for hidden seeding.
This PR also fixes a LibtorrentDownloadImpl still being in LibtorrentMgr.torrents when its removed deferred is fired.
=> Fix download reappear

Tribler/Core/Modules/restapi/torrentinfo_endpoint.py, TriblerGUI/dialogs/startdownloaddialog.py
This reverts commit a0a49cc20e6d13ff0a26e6d19843dc2dc8375e70.
Fixes #3185 (see for more details), reopens #3161.
=> READY: Revert "Fix #3161 torrent name error"

run_tribler.py
Base path for logger.conf was mistakenly set in TriblerGUI which should actually be in the base tribler directory.
=> Fix logger.conf base path

Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py
If torrent already exists in the session, it is now removed from the session and added again. This triggers the metadata_received_alert handled by 'process_alert'. This removal and addition of torrent to the session is done for the new torrents only so it does not affect the existing torrents in the downloads.
Issue #3263
=> READY: Fix torrent already exists in session exception

Tribler/Core/Libtorrent/LibtorrentMgr.py
Issue Fix #3251: When all the downloads are removed, torrent details tab is no longer shown.
Alert type 'torrent_removed_alert' is properly handled.
=> Fix hide torrent details tab

Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py
Before, it was changing the logging system and this propagated to other tests, leading to unreadable test files.
=> Changed log test

Tribler/Core/Modules/restapi/rest_manager.py
Before any data is written by request.write() it now checks if the request has not already finished and the channel is not None. One case where the channel is None is when a remote host closes the connection before the response is served. In such a case just checking 'request.finished is not True' is not sufficient and channel should also be checked.
Fixes #3274
=> Fix crash on remote host closing connection

TriblerGUI/tribler_window.py
Checked if the dialog or dialog_widget is None before performing start download request. An error dialog is shown in case any of them is None.
Fix #3301
=> Fix for AttributeError: 'NoneType' object has no attribute 'dialog_widget'

TriblerGUI/widgets/torrentdetailstabwidget.py
Updated torrent health label in torrent details tab on clicking a torrent.
Fix #3307
=> Updated torrent health status in details tab

Tribler/Core/Session.py, Tribler/Test/Core/test_session.py
Fix #3315 Invalid DNS-ID
This error occurs if twisted cannot verify the SSL certificate of the DNS-ID. Since this is handled by twisted internally, we can just ignore the error in the upper layer.
=> Ignore Invalid DNS-ID exception

TriblerGUI/qt_resources/torrent_channel_list_container.ui
To make it consistent with the details pane on the downloads page.
=> Removed border around torrent details pane

TriblerGUI/widgets/downloadspage.py
This bug causes mess when deleting multiple downloads within 1 second. It may delete nothing or wrong download.
=> Bug fix in downloadpage

TriblerGUI/debug_window.py, TriblerGUI/dialogs/feedbackdialog.py, TriblerGUI/tribler_request_manager.py, TriblerGUI/tribler_window.py, TriblerGUI/widgets/channel_torrent_list_item.py, TriblerGUI/widgets/downloadspage.py
This PR adds a priority-based request queue for the GUI's HTTP requests to the core.
This PR also immediately lowers the maximum amount of (non-critical) outstanding requests to 200 and assigns health requests a low priority.
The code is done, but this PR still requires some stress testing on different machines before merging.
Fixes #3303.
Fixes #3319.
=> GUI HTTP request queue

check_os.py, run_tribler.py
Asks user whether to force restart Tribler if there is more than one instance running. This will help user to kill any zombie instances which might have been left behind by previous force kill command or some other unexpected exceptions and relaunch Tribler again.
Fixes #3348
=> Force restart Tribler

Tribler/Core/TorrentChecker/torrent_checker.py
They shouldn't be set to None since individual torrent checker session still require these attributes in their callback/errbacks.
=> Fixed bugs in torrent checker

Tribler/Core/Libtorrent/LibtorrentMgr.py
The `sha1_hash` doesn't exist in older versions of libtorrent and we should use the `big_number` function instead. According to the Python bindings, `big_number` provides exactly the same functionality as `sha1_hash`.
Credits to @EinNarr for finding this bug.
=> Fixed compatibility with libtorrent 0.16.18

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Test/Core/CreditMining/mock_creditmining.py, Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py, Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py
This PR fixes anonymous downloading and anonymous seeding in Tribler for libtorrent 1.1.0 and higher.
Based on #3084 and credits to @Captain-Coder for finding most of the new settings.
Fixes #3353
=> Fixed compatibility with newer versions of libtorrent while maintaining backwards compatibility (devel)

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
This method appears to contain useless statements.
=> Remove redundant logic from LibtorrentDownloadImpl.network_stop

Tribler/Core/Modules/restapi/trustchain_endpoint.py, Tribler/Test/Community/Triblerchain/test_community.py, Tribler/Test/Community/Trustchain/test_trustchain_utilities.py, Tribler/Test/Core/Modules/RestApi/test_trustchain_endpoint.py, Tribler/community/triblerchain/community.py, TriblerGUI/qt_resources/mainwindow.ui, TriblerGUI/widgets/settingspage.py, tribler-headless.sh
This PR adds the ability to export funds without a network connection by using a throw-away identity for transferring between the two different identities
=> One-way communication offline funds transfer using QR-code

TriblerGUI/widgets/trustpage.py
An untested basic idea.
Run the load_trust_statistics() every minute.
=> Add timer to refresh trust page stats

doc/development/development_on_linux.rst, doc/development/development_on_osx.rst, doc/development/development_on_windows.rst
This adds the `libnacl` dependency installation instructions to the Windows/Unix/Mac development documents.
=> Added libnacl library dependencies

tribler.spec
Fixed issue with mac installer #3428
Removed `libsodium.so` from the included binaries for macOS
=> Fix macOS installer issue with libsodium

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py
Value error is caught and logged if it occurs on metadata received alert.
=> Fix ValueError

TriblerGUI/widgets/home_recommended_item.py
Remove quote_plus in download URI for magnet links in home recommended torrents page.
=> Fix encoded magnet links

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/community/market/community.py
In this PR, I load the mainline DHT before loading IPv8 overlays. I also disabled thread pool processing of messages in the market and tunnel overlays.
=> Fixed mainline DHT when used for hidden seeding

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Test/Community/Market/test_community.py, Tribler/Test/Community/Triblerchain/test_community.py, Tribler/Test/Community/Tunnel/test_community.py, Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py, Tribler/Test/mocking/exit_socket.py, Tribler/community/triblerchain/community.py, Tribler/community/triblertunnel/community.py, Tribler/community/triblertunnel/payload.py
In this PR, I implemented the payouts for the tunnel community. When destroying a 'regular' data circuit or an e2e circuit, the downloader pays the subsequent node in the form of bandwidth tokens. Note that this implementation is the most basic implementation possible and does not contain any sophisticated security/anonymity features.
Depends on https://github.com/Tribler/py-ipv8/pull/67
Fixes #3493
=> Implemented tunnel payouts

Tribler/Core/Modules/process_checker.py, Tribler/Test/Core/Modules/test_process_checker.py, TriblerGUI/core_manager.py, check_os.py
Refactored Process Checker so that it does not create a lock file immediately. This fixes the problem with running Tribler with twistd possibly caused by the fix for zombie process.
Also, added a restart timer which restarts the Core if it does not restart within 30 seconds. This fixes one of the problems causing Tribler to get stuck at gear window.
> Inconsistency detected by ld.so: dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
=> Refactored Process Checker

Tribler/Core/Utilities/utilities.py, TriblerGUI/tribler_window.py, TriblerGUI/widgets/downloadspage.py, check_os.py, debian/control, run_tribler.py
Various Tribler fixes:
- Check if Tribler settings are available before starting download ( Fixes #3460 )
- Checked for NoneType in various JSON responses in the downloads page
- Restart Tribler with proper resource cleanup
- Added treq as optional debian dependency
=> Various Tribler fixes for 7.0.2

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Modules/restapi/market/matchmakers_endpoint.py, Tribler/Core/Modules/restapi/market_endpoint.py, Tribler/Core/Modules/restapi/wallets_endpoint.py, Tribler/Test/Community/Market/Wallet/test_btc_wallet.py, Tribler/Test/Community/Market/Wallet/test_trustchain_wallet.py, Tribler/Test/Community/Market/test_community.py, Tribler/Test/Community/Market/test_orderbook.py, Tribler/Test/Community/Market/test_trade.py, Tribler/Test/Core/Modules/RestApi/test_market_endpoint.py, Tribler/community/market/community.py, Tribler/community/market/core/matching_engine.py, Tribler/community/market/core/orderbook.py, Tribler/community/market/core/side.py, Tribler/community/market/core/trade.py, Tribler/community/market/wallet/btc_wallet.py, Tribler/community/market/wallet/tc_wallet.py, Tribler/community/triblertunnel/dispatcher.py, TriblerGUI/qt_resources/mainwindow.ui, TriblerGUI/tribler_window.py, TriblerGUI/utilities.py, TriblerGUI/widgets/marketpage.py, TriblerGUI/widgets/marketwalletspage.py, systemd/tribler.service
In this PR, I fixed some bugs in the market community. I also removed a log statement in the tunnel community that slowed anonymous downloads. I decided to have the improvement as suggested by @qstokkink in a separate PR since it did not work out of the box and this PR was growing quite a lot with fixes/improvements for the market community.
I also upgraded the Electrum wallet to 2.9.4 and tested some basic trading functionality between two different machines, with Testnet Bitcoin wallets.
Working market experiment with this PR: https://jenkins.tribler.org/job/pers/job/market_experiment_devos50/745/
Fixes #3494
=> Various bug fixes and improvements for the market

Tribler/Test/GUI/test_gui.py, TriblerGUI/dialogs/feedbackdialog.py, TriblerGUI/tribler_request_manager.py
Fixed issue with base URL on sending crash reports using TriblerRequestManager.
Added a GUI test to ensure crash reports are sent properly.
=> Fixed issue with sending crash reports

TriblerGUI/tribler_window.py
Solves:
```python
Error in sys.excepthook:
File "/home/quinten/Documents/tribler/TriblerGUI/tribler_window.py", line 67, in on_exception
self.tray_icon.deleteLater()
RuntimeError: wrapped C/C++ object of type QSystemTrayIcon has been deleted
Original exception was:
File "/home/quinten/Documents/tribler/TriblerGUI/widgets/trustpage.py", line 112, in received_trustchain_statistics
```
on shutdown
=> Do not remove the tray icon twice

Tribler/Core/Modules/restapi/create_torrent_endpoint.py
When adding a torrent with multiple files to your channel and when starting to download it, it would not seed immediately since the base directory was not set correctly.
Fixes #3550
=> Fixed issue when adding torrent to channel

Tribler/Main/Build/Win/tribler.nsi, TriblerGUI/vlc.py, doc/building/building_on_windows.rst, win/makedist_win.bat
In this PR, I bundle the VLC media player with Tribler. I've modified the script to simply copy the necessary VLC files, instead of installing a stand-alone version of VLC, which pollutes the system of Windows users.
Note that if our shipped `libvlc.dll` does not load for any reason, it still attempts to use an installed VLC version.
I've tested this PR on Windows 32-bit and 64-bit systems. Playback seems to work fine.
Fixes #3545, fixes #2769
=> Bundle VLC with Tribler

Tribler/Core/Modules/restapi/downloads_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py, Tribler/Test/GUI/test_gui.py, TriblerGUI/tribler_window.py, TriblerGUI/widgets/channel_torrent_list_item.py, TriblerGUI/widgets/downloadsdetailstabwidget.py, TriblerGUI/widgets/downloadspage.py, TriblerGUI/widgets/leftmenuplaylist.py, TriblerGUI/widgets/videoplayerpage.py
In this PR, I refactored the VoD logic. Currently, the code that manages the VoD, is fragmented into several classes. I tried to make the logic a bit better by giving the `VideoPage` class more responsibilities. Note that this is only a minor step and more work should be done eventually.
I also added an endpoint to fetch files and the status of files in a specific download. Also, I've modified the GUI tests so the files are fetched from the fake core when starting a VoD session.
Finally, I fixed the annoying issue where a crash during the GUI tests would lead to a segmentation fault (or abort trap on MacOS). When an error occurs during the GUI tests, the test will now fail and provide us with debug output 👍 
Fixes #3546
=> Refactored VoD logic

.gitignore, Tribler/Core/Modules/resource_monitor.py, Tribler/Core/Modules/restapi/debug_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py, Tribler/Test/Core/Modules/test_resource_monitor.py, TriblerGUI/debug_window.py, TriblerGUI/qt_resources/debugwindow.ui
I've added the Yappi profiler to the core and the GUI. The profiler itself can be started from the HTTP API with requests to `/debug/profiler`. I've also added an additional tab in the debug panel where the profiler can be enabled and disabled.
When the profiler is stopped, the data file is written to the `logs` directory in the state dir of Tribler. The filename contains the timestamp when the profiler was started. When shutting down Tribler while the profiler is still running, this file is also written to the disk.
=> Added the Yappi profiler to the core and GUI

TriblerGUI/core_manager.py
Environment variables are now encoded before starting the core process.
Potentially fix for #3579
=> Environment variables are now encoded before starting the core process

logger.conf
Update logger default formatter to include the logger name
=> Update logger default formatter to include the logger name

Tribler/Core/Utilities/utilities.py
ValueError is only raised for non-empty announce URLs if they are invalid.
Fixes #3609 Tribler fails to chew a mega-torrent
=> Fix ValueError for empty URLs

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Test/Community/Tunnel/test_community.py
The long-awaited pull request, that enables the new Twisted-based IPv8 UDP endpoint. Dispersy is now merely an `EndpointListener` being served by IPv8.
This required changing initialization order to IPv8 first, Dispersy second, and  `_use_main_thread=False` compatibility workaround for unit tests using `deliver_messages` method.
In addition, the patch removes explicit teardown command for IPv8 endpoint `self.ipv8.endpoint.close()`, since it is now handled by IPv8 itself.
=> Use IPv8 endpoint, then packets data to Dispersy

.gitignore, Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Config/config.spec, Tribler/Core/Config/tribler_config.py, Tribler/Test/Core/Config/test_tribler_config.py, Tribler/Test/Core/test_launch_many_cores.py, twisted/plugins/tribler_plugin.py, twisted/plugins/tunnel_helper_plugin.py
This pull request removes `use_testnet` option and replaces it with more general `bootstrap_override` option, that allows to, well, override bootstrap servers list. It is very useful to build your own isolated testnets without hacking the code.
The corresponding new option is added to `tunnel_helper` and Tribler Twisted plugins (it seems not to have any effect for the latter, probably because of Dispersy endpoint interference).
Anyways, support for this option is required to proceed with building Jenkins performance tests.
p.s.
as a small bonus, there is a small change to `.gitignore` to ignore log file generated by `nosetests`.
p.p.s
monstrous regexp for checking IP addresses is a shameless copypaste from a popular Stackexchange answer.
=> Add bootstrap override option

TriblerGUI/widgets/downloadspage.py
Instead, I let the removal of downloads being handled by the `on_received_downloads` method, which should check whether there are removed downloads or not. After some testing, I can confirm this fixes the issue in #3548.
Fixes #3548
=> Fixed bug when removing downloads

Tribler/Core/Upgrade/config_converter.py, Tribler/Test/Core/Upgrade/test_config_upgrade_70_71.py, Tribler/Test/Core/data/config_files/download_pstate_70.state
We forgot to upgrade the existing .state files for downloads that have already been added to Tribler. By renaming the downloadconfig section to download_defaults, the upgrade from 7.0 to 7.1 should not mess up the downloads anymore.
Fixes #3645, fixes #3556
=> Fixed upgrade from 7.0 to 7.1

Tribler/Core/Config/config.spec, Tribler/Core/Config/tribler_config.py
Tried a more general approach by writing a custom parser/checker for `<IP> : <port>` format. It failed because the `config` module writes the tuple back automatically in the form of tuple ` <IP> , <port>`.
Had to resort to this simple fix.
Fixes #3675
=> Fix bug 3675: bootstrap_override parsing in config

Tribler/Core/Modules/restapi/downloads_endpoint.py, Tribler/Core/TorrentDef.py, Tribler/Test/Core/test_torrent_def.py
Fixes #3599 
This adds a method for getting a utf8 safe torrent name from a `TorrentDef`.
=> Fixed crash on torrents with exotic names

debian/bin/tribler
RIght now, after running tribler via terminal, we stay in `/usr/share/tribler`. Depending on your environment you may not experience this issue. I changed the script to use `pushd` and `popd` instead of `cd`.
=> debian: return to previous dir after running the tribler script

twisted/plugins/tribler_plugin.py, twisted/plugins/tunnel_helper_plugin.py
When not specifying a custom bootstrap server, it would write the empty string in the Tribler configuration file, which in turn results in an `InvalidConfigurationException`.
=> Fixed bug in twistd plugins

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Config/config.spec, Tribler/Core/Config/tribler_config.py, Tribler/Core/Session.py, Tribler/Core/Upgrade/config_converter.py, Tribler/Test/Core/Config/test_tribler_config.py, Tribler/community/market/community.py, Tribler/community/triblertunnel/community.py, twisted/plugins/tribler_plugin.py, twisted/plugins/tunnel_helper_plugin.py
In this PR, I changed the testnet option to generalize it. When enabling the testnet option in the Tribler config file, other (testnet) communities for the market, trustchain and tunnel community will be loaded and used instead. These communities will also be joined with a different identity.
=> Generalized testnet configuration options

TriblerGUI/widgets/channelpage.py
If a torrent is deselected in a discovered channel, the torrent info is now hidden.
=> Hide torrent info on channel torrent deselect

Tribler/Core/CacheDB/SqliteCacheDBHandler.py, Tribler/Core/Modules/restapi/torrentinfo_endpoint.py, Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py
Unnamed torrents are now updated on metainfo check.
Related #3759
=> Update unnamed torrents on metainfo check

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Core/Modules/payout_manager.py, Tribler/Core/Modules/wallet/bandwidth_block.py, Tribler/Test/Community/popularity/test_payload.py, Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py, Tribler/Test/Core/Modules/test_payout_manager.py, Tribler/Test/Core/test_launch_many_cores.py, Tribler/community/popularity/pubsub.py
This PR implements direct payouts between Tribler instances (zero-hop downloads).
TODO:
Fixes #3718
=> Performing direct payouts to other Tribler clients

README.rst, doc/contributing.rst, doc/development/development_on_linux.rst, doc/development_methodology.rst
Fixes #3749
Also, the label on the README now points to `next` instead of `devel`.
=> Point docs to jenkins-ci instead of jenkins

Tribler/Core/Modules/restapi/downloads_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py, TriblerGUI/widgets/downloadspage.py
=> Fixed exporting of torrents

Tribler/Core/Config/config.spec, Tribler/Core/Config/tribler_config.py, Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Core/Modules/restapi/debug_endpoint.py, Tribler/Core/Modules/restapi/statistics_endpoint.py, Tribler/Core/Session.py, Tribler/Core/statistics.py, Tribler/Test/Core/Config/test_tribler_config.py, Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py, Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_statistics_endpoint.py, Tribler/Test/GUI/test_gui.py, Tribler/Test/test_as_server.py, TriblerGUI/debug_window.py, TriblerGUI/qt_resources/debugwindow.ui
In this PR, I did the following:
- added option to disable the libtorrent DHT, I enabled it in the tests by default. Fixes #3790 
- added an endpoint to fetch general statistics about IPv8
- replaced Dispersy statistics with IPv8 statistics
- added endpoint to fetch info about filled slots (this should help me to debug the tunnel helpers)
=> Various improvement/fixes

Tribler/Test/test_as_server.py
It messed up the tests on Mac since that machine has an older version of OpenSSL (and therefore is unable to establish a secure connection to github.com).
=> Disabled version checker in seeder session

Tribler/Core/DownloadState.py, Tribler/Test/Core/test_downloadstate.py
This PR also sanitizes the crawling process of TrustChain.
Fixes #3815
=> Updated IPv8 pointer, fixed crash when downloading torrent with zero-byte files

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Core/Session.py
Fixes https://github.com/Tribler/tribler/issues/3805, https://github.com/Tribler/tribler/issues/3173,  https://github.com/Tribler/tribler/issues/3199.
Also fixes LibtorrentDownloadImpl.setup not correctly handling the pstate argument.
=> Reuse pstate when changing hop count

Tribler/Test/GUI/test_gui.py
It seems that we were not correctly closing the application, which might have led to numerous tray icons in Windows.
=> Fixed shutdown of GUI tests

Tribler/Core/Modules/restapi/torrentinfo_endpoint.py, Tribler/Core/Utilities/utilities.py, Tribler/Test/Core/Utilities/test_utilities.py, debian/control
Fixes #3828 
With previous PR #3795 Twisted agent now supports HTTPS so we no longer need treq.
Therefore, I'm removing this dependency.
=> Fixed bug on adding torrent from HTTP URL that resolves to a magnet link

Tribler/Test/Community/Market/test_community.py, Tribler/community/market/community.py, Tribler/community/market/core/order_repository.py, Tribler/community/market/core/transaction_repository.py, TriblerGUI/tribler_window.py, TriblerGUI/widgets/downloadspage.py, TriblerGUI/widgets/marketpage.py
The calls for showing notifications/removing the tray icon is now wrapped in a try/except block.
Next to fixing the tray icon in the GUI, I'm also running the market tests on the reactor thread now. They consistently pass on Linux now (I've tested and verified this on bbq).
Fixes #3843
=> Properly fixed tray icon + small market fix

Tribler/Core/TorrentChecker/session.py, TriblerGUI/widgets/videoplayerpage.py, tribler.spec
In this PR, I fixed some stuff and improved the tribler.spec file to exclude `PyQt4`. This makes it possible to build Tribler on Linux (i.e. bundle all `.so` files together and create a Tribler executable file).
Fixes #3859 (not sure how to test this one properly).
=> Various fixes

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Config/config.spec, Tribler/Core/Config/tribler_config.py, Tribler/Test/Community/Market/test_community.py, Tribler/Test/Community/Market/test_matching_engine.py, Tribler/Test/Core/Config/test_tribler_config.py, Tribler/Test/Core/Modules/Wallet/test_btc_wallet.py, Tribler/community/market/community.py, Tribler/community/market/core/matching_engine.py
In this PR, I fixed three bugs in the market:
- fixed a bug in the matching engine where two orders of the same trader could be matched
- fixed order cancellation test
- changed logic for simultaneous order creation. I made the tests more challenging by removing the `yield` statement before `create_ask`/`create_bid`, which always errors out without the new logic.
I also updated the IPv8 pointer, added a configuration option to toggle the IPv8 statistics and mocked the `balance` method of a BTC wallet during tests (so we don't make requests to external websites).
=> Fixed a few bugs in the market, updated IPv8 pointer

Tribler/Test/Community/Tunnel/test_community.py, Tribler/Test/Core/Modules/Wallet/test_btc_wallet.py, Tribler/community/triblertunnel/community.py
This patch adds calls to correctly tear down bandwidth wallet on shutdown of TriblerTunnel community.
Related to #3876
=> Fix Wallet shutdown in TriblerTunnel community

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Test/Core/Modules/Wallet/test_trustchain_wallet.py
This removes the need for custom random id creation.
Also switched away from `save_pstate` id based on time, which is unsafe.
=> Switched to register_anonymous_task where applicable

Tribler/Core/Modules/wallet/btc_wallet.py, Tribler/Test/Core/Modules/RestApi/Channels/test_channels_subscription_endpoint.py, Tribler/Test/Core/Modules/test_tracker_manager.py, Tribler/Test/Core/Upgrade/upgrade_base.py, Tribler/Test/Core/base_test_channel.py, Tribler/Test/test_as_server.py, Tribler/community/market/community.py
In windows the temporary session directories in tests were not being cleared. This was mostly because of improper tearDown and confusing hierarchy of tests. Read issue #3867.
Previously we were suppressing any OS error occurring on removing the temp session directories which is why we did not notice the issue until now. In this PR, OS error is raised and all the suppressed error are fixed.
Fixes #3867
=> Fixed issue with removing temporary test directories

TriblerGUI/dialogs/startdownloaddialog.py, TriblerGUI/tribler_window.py, TriblerGUI/utilities.py, TriblerGUI/widgets/settingspage.py
Error dialog now shows the actual error as well if the directory is not writable.
With this PR the user can report the actual error in #3862.
This PR will close this issue for now. When we get the report of the actual issue, we can create a new issue.
Fixes #3862
=> Error dialog now shows the actual error as well if the directory is not writable

Tribler/Core/APIImplementation/LaunchManyCore.py
Loading keys was inversed: when testnet was disabled, we were using a Testnet key and vice versa.
=> Fixed TrustChain key usage

Tribler/Core/Upgrade/db_upgrader.py
It seems that removing tables that are required by a view results in an error in newer versions of apsw/sqlite. This patch makes sure that each view is removed before its referenced table.
Fixes #3913
=> Fixed errors in SQL upgrade script

Tribler/community/triblertunnel/community.py
This crashed on the exit nodes.
=> Fixed logging message that still used relay.mid

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
Potentially fixes #3905 
The reference to tunnel and TrustChain are cleared when these communities are unloaded and the existence of tunnel community is checked before trying to build tunnels.
=> Fixes endpoint issue with tunnel community

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/CacheDB/sqlitecachedb.py, Tribler/Core/CreditMining/CreditMiningSource.py, Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Core/Modules/channel/channel.py, Tribler/Core/Modules/channel/channel_manager.py, Tribler/Core/Modules/channel/channel_rss.py, Tribler/Core/Modules/restapi/channels/channels_torrents_endpoint.py, Tribler/Core/Modules/search_manager.py, Tribler/Core/Modules/tracker_manager.py, Tribler/Core/Modules/wallet/tc_wallet.py, Tribler/Core/RemoteTorrentHandler.py, Tribler/Core/Session.py, Tribler/Core/TFTP/handler.py, Tribler/Core/TorrentChecker/torrent_checker.py, Tribler/Core/TorrentDef.py, Tribler/Core/Upgrade/upgrade.py
Remove `@blocking_call_from_reactor_thread` decorators from everything. Because these are obsolete.
=> Remove blocking_call_from_reactor_thread decorators

Tribler/Core/APIImplementation/LaunchManyCore.py
Shutting down TFTP before Dispersy.
Fixes #3932
=> TFTP shutdowns before Dispersy now

Tribler/Core/Modules/wallet/tc_wallet.py, TriblerGUI/dialogs/trustexplanationdialog.py, TriblerGUI/qt_resources/mainwindow.ui, TriblerGUI/qt_resources/trustexplanation.ui, TriblerGUI/widgets/trustpage.py
Since there has been quite some confusion regarding the bandwidth token functionality, I've added a small explanation to the GUI. I will write a more extensive explanation in the FAQ on the website, which should address the questions asked in #3657.
Also fixed a minor rounding issue, causing incompatibilities between the balance as reported by the wallet and TrustChain.
=> Explaning bandwidth tokens in the GUI

TriblerGUI/qt_resources/mainwindow.ui, TriblerGUI/widgets/channelpage.py, TriblerGUI/widgets/editchannelpage.py
Remove hidden Edit Channel button from the GUI. The button's purpose was to be able to edit other people's Dispersy channels, but this never worked properly, so the button was hidden long time ago. And no one missed it.
Now it's gone for good.
=> Remove unused Edit Channel buttons from everywhere

Tribler/Core/Modules/restapi/channels/channels_torrents_endpoint.py
SchemeNotSupported twisted error on creating a discovered channel is trapped.
Fixes #3970
=> Trap SchemeNotSupported twisted error on creating discovered channel

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Modules/restapi/torrentinfo_endpoint.py, Tribler/Test/Community/popularity/test_repository.py, Tribler/community/popularity/repository.py
Resolves https://github.com/Tribler/tribler/issues/3985 (at least partially).
Adds some commit statements in higher-level functions, so data would be safe and immediately available from DB even when Dispersy is not around. We don't add them to low-level functions because we don't want to interfere with Dispersy commit patterns too much.
=> Add some commit_now() statements in important points

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Modules/restapi/torrentinfo_endpoint.py, Tribler/Core/Modules/restapi/torrents_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_torrents_endpoint.py
And subscribe to the downloaded channel by default.
=> Fix chant-related DHT timeout error handling in torrents endpoint

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Test/Community/Tunnel/FullSession/test_tunnel_base.py, Tribler/Test/Community/Tunnel/test_community.py, Tribler/Test/Community/popularity/test_repository.py
This pointer update also requires references to `DiscoveryCommunity` to be refactored and `TestBase` subclasses to return the value of `super( ... , self).tearDown()`.
=> Updated ipv8 pointer

Tribler/Core/Modules/restapi/rest_manager.py, Tribler/Core/Session.py, Tribler/Test/Core/Modules/RestApi/test_rest_manager.py
No new REST requests are processed after the shutdown sequence is initiated. This prevents any error from GUI requests while the core is shutting down.
=> No new REST requests are processed after shutdown is initiated

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/MetadataStore/store.py, Tribler/Test/Community/gigachannel/test_community.py, Tribler/Test/Community/gigachannel/test_community_fullsession.py, Tribler/Test/Community/gigachannel/test_sync_strategy.py, Tribler/Test/mocking/channel.py, Tribler/Test/mocking/download.py, Tribler/Test/mocking/session.py, Tribler/community/gigachannel/community.py, Tribler/community/gigachannel/payload.py, Tribler/community/gigachannel/sync_strategy.py
Fixes #3997.
For graphs see: https://github.com/Tribler/gumby/pull/383.
This PR implements the most naive gossip protocol for GigaChannels. The selection algorithm is one line:
```python
db.ChannelMetadata.select(lambda g: g.subscribed==True).random(limit)
```
The remaining community code simply gossips these randomly selected subscribed channels (up to 7) to neighbors. Upon receipt of such gossiped channels, they will be queued and each channel will downloaded once the previous download finished or 10 seconds have passed.
This PR also enables libtorrent's LSD (when DHT is enabled) for 0 hop downloads, which is essential for channel downloading between nodes in the same NAT layer.
=> GigaChannel Gossip

Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py, Tribler/Test/Core/Modules/MetadataStore/test_torrent_metadata.py
By default, Pony[ converts everything into Unicode](https://docs.ponyorm.com/api_reference.html#attribute-types) when putting it into a database. Therefore, strings should not be `.encode('utf-8')`-ed when received from it.
Fixes #4023
=> Fixed double unicode encoding for Pony

TriblerGUI/widgets/downloadsdetailstabwidget.py
Copying (ctrl+c) of the name, info hash and download location is now supported in the downloads page.
=> Support copy selection in download details tab

Tribler/Core/leveldbstore.py, Tribler/Core/plyveladapter.py, Tribler/Test/Core/test_leveldb_store.py
Fixes https://github.com/Tribler/tribler/issues/3955
Two important changes in this PR:
1. sync and transaction parameters in write_batch are set to True for Windows. This helps in preventing corruption.
2. Retry mechanism for up to 3 times is implemented. In windows, there could be the case where index file is not available during read operation because it is being merged. In such case, retry helps.
=> Fixed LevelDB issue

Tribler/Core/DownloadState.py, Tribler/Test/Core/test_downloadstate.py
It could be that different peers report a different number of total pieces. With this change, Tribler should not crash on it anymore.
Fixes #4046
=> Fixed error when calculating availability

TriblerGUI/tribler_window.py
This PR fixed the homepage items running off the screen (requiring a scrollbar) for widescreens.
=> Fixed homepage items running off screen

Tribler/Test/Community/Search/FullSession/test_search_community.py, Tribler/Test/Core/Modules/RestApi/test_search_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_settings_endpoint.py, Tribler/Test/Core/test_sqlitecachedbhandler_preferences.py
In Tribler/Test:
* __from six import unichr__
* Change __basestring__ --> __six.string_types__
=> Fix basestring and unichr in Tribler/Test

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
[Caught by the application tester](https://jenkins-ci.tribler.org/job/Deployment-Tests/job/Run_Tribler_Release/job/Run_Win7_32bit/65/console). It seems that `torrent_info` is removed while the interpreter executes a for-loop. To solve this, I've added a check in every loop for the existence of torrent info.
=> Fixed bug where torrent_info was removed in loop

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Category/Category.py, Tribler/Core/Category/init_category.py, Tribler/Core/CreditMining/CreditMiningSource.py, Tribler/Core/DownloadConfig.py, Tribler/Core/Modules/restapi/channels/base_channels_endpoint.py, Tribler/Core/Modules/restapi/debug_endpoint.py, Tribler/Core/Modules/restapi/downloads_endpoint.py, Tribler/Core/Modules/restapi/torrentinfo_endpoint.py, Tribler/Core/Modules/search_manager.py, Tribler/Core/TorrentDef.py, Tribler/Core/Upgrade/config_converter.py, Tribler/Core/Upgrade/pickle_converter.py, Tribler/Core/Utilities/configparser.py, Tribler/Core/Utilities/instrumentation.py, Tribler/Core/Utilities/tracker_utils.py, Tribler/Core/Utilities/utilities.py, Tribler/Core/Video/VideoServer.py, Tribler/Test/test_as_server.py, Tribler/community/market/community.py, Tribler/util.py
In this PR, I made the minimal required changes to at least start executing the nosetests on Python 3. These changes should not break compatibility with the old Python 2 code. If the tests in this PR pass, this will give @cclauss a stable basis to work on.
I made a few changes to prevent us from porting Dispersy/pymdht. In particular, I made the imports that import either Dispersy or pymdht local. There were only a few of these and I think this is acceptable to do so we do not have to wait for these submodules to be removed.
All dependencies except for Meliae are available for Python 3, either via `pip` or `apt`.
Fixes #4092 
Related to #3883
=> Minimal changes to pass the imports on Python 3

Tribler/Core/Config/config.spec, Tribler/Core/Config/tribler_config.py, Tribler/Core/Modules/restapi/rest_manager.py, Tribler/Test/Core/Config/test_tribler_config.py, Tribler/Test/Core/Modules/RestApi/base_api_test.py, TriblerGUI/code_executor.py
This should fix the nasty win64 error we occasionally observe when running unit tests.
I also log the code being executed when the remote code execution unit fails. This should help me to debug errors like in https://jenkins-ci.tribler.org/job/Deployment-Tests/job/Run_Tribler_Release/job/Run_Win7_64bit/68/.
=> Retrying REST API initialization on failure

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Config/tribler_config.py, Tribler/Core/CreditMining/CreditMiningManager.py, Tribler/Core/DownloadConfig.py, Tribler/Core/Session.py, Tribler/Core/Upgrade/torrent_upgrade64.py, Tribler/Core/__init__.py, Tribler/Core/osutils.py, Tribler/Core/statistics.py
This PR proposes fixes to files in Tribler/Core that are _not_ contained in:
* Tribler/Core/CacheDB
* Tribler/Core/Modules
* Tribler/Core/Libtorrent + TorrentChecker + TorrentDef.py
* Tribler/Core/Utilities --> #4115
=> Python3 fixes in miscellaneous Tribler/Core files

Tribler/Test/Core/Upgrade/test_config_upgrade_70_71.py
For compatibility with both Python 2 and Python 3
=> from six.moves.configparser import RawConfigParser

TriblerGUI/widgets/marketpage.py
For clarity, I now show the details of the price of each market order.
Related to #4131
=> Added price details to GUI list with asks/bids

Tribler/Test/Community/Market/test_block.py, Tribler/Test/Community/Market/test_community.py, Tribler/community/market/block.py, Tribler/community/market/community.py, Tribler/community/market/core/wallet_address.py
The timeout can now be at most one day, which I think is reasonable. Orders with a negative timeout, or a timeout that is higher than one day will be considered invalid and not be added to the orderbook.
@MattSkala I also added some more information when the initialization of a `WalletAddress` is failing. This might help you to debug #4148.
Fixes #4147
=> Market timeout fix

Tribler/community/market/__init__.py, Tribler/community/market/block.py, Tribler/community/market/community.py, Tribler/community/market/core/tick.py
This should prevent orders with an invalid timeout from being inserted in the local order book.
=> Added additional timeout check

TriblerGUI/code_executor.py
Sending invalid code to the Tribler core should not crash Tribler.
=> Ignoring errors during remote code execution

Tribler/community/triblertunnel/dispatcher.py
The destinations set is modified within a while loop. The iteritems method constructs an iterator which will fail if the dictionary changes size during iteration. I changed the iteritems to items, so it makes a copy instead. This method is not invoked frequently (only when a circuit breaks) so it should not impact anonymous download performance.
Fixes #4175
=> Fixed dict change error during iteration

Tribler/Core/RemoteTorrentHandler.py, Tribler/Core/exceptions.py, Tribler/Core/leveldbstore.py
Should not crash Tribler in case LevelDB crashes.
Fixes #4179
=> Should not crash Tribler in case LevelDB crashes

Tribler/Core/Session.py
Already called twisted error is captured and logged in session handler instead of crashing Tribler
=> Already called twisted error captured in session instead of crashing Tribler

Tribler/Test/Community/Tunnel/test_community.py
After the change that randomly picks the first relay node, it is possible to have an e2e circuit that goes like 0 (downloader) -> 2 -> 0 -> 2 (seeder). In this case, node 1 will remain with a balance of zero after payouts.
=> Fixed e2e payout test

setup.py
This fixes the build on Debian and Arch, see https://jenkins-ci.tribler.org/job/Build-Tribler_release/job/Build-Custom/
=> Removed non-existing directory from setup.py

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Test/Community/Tunnel/test_discovery.py, Tribler/community/triblertunnel/community.py, Tribler/community/triblertunnel/discovery.py
This strategy attempts to maintain a ratio of:
`exit node` : `non-exit node` = `7` : `9`
=> Added exit node ratio strategy

logger.conf
Also removed an unused logger entry in `logger.conf`.
Fixes #4243
=> Fixed double logging

Tribler/Core/Modules/wallet/bandwidth_block.py, Tribler/Test/Community/Tunnel/test_community.py, Tribler/community/triblertunnel/community.py
Not validating this block could lead to bandwidth being transferred by a relay while not counter-signing a payout block they received.
Fixes #4247
=> Validating payout block when receiving it

Tribler/community/triblertunnel/community.py
The Tunnel object (Relay/Circuit) already provides us with a Peer.
=> Removed unnecessary check in payouts

TriblerGUI/widgets/settingspage.py
Without the double slash, it would do a float division. The text input for libtorrent max upload/download speed would end up as 0.0, which is obviously not an integer.
=> Fixed division in settings

Tribler/community/triblertunnel/community.py
This PR implements my proposed solution 1 in #4234. In essence, we only continue the payout process when (parts of) the chain of the transaction counterparty can successfully be validated. This should prevent circuit peers from making payments to the next hop with funds they have not fully claimed yet.
Fixes #4234
=> Quick fix for negative payouts

Tribler/community/gigachannel/community.py
This little patch solves the problem https://github.com/Tribler/tribler/issues/4246 that makes Tribler crash if GigaChannel community received a damaged/wrong format mdblob.
=> Add exception handling to GigaChannel community

Tribler/Test/GUI/test_gui.py
Using these subscribe/unsubscribe signals is not reliable on Windows. Instead, I use a `qWait` and take a screenshot afterwards.
=> Fixed test_subscriptions

Tribler/Core/Modules/MetadataStore/store.py, Tribler/Core/TorrentChecker/session.py, Tribler/Core/TorrentChecker/torrent_checker.py
This PR solves #4228 by removing `INFO`-level logging with full tracebacks in the TorrentChecker, and fixing the single-line twisted tracebacks there to be really single-line, e.g.:
**Before:**
```
INFO    1551286977.55                   session:266  (HttpTrackerSession)  Error when querying http tracker: [Failure instance: Traceback: <class 'twisted.internet.error.DNSLookupError'>: DNS lookup failed: no results for hostname lookup: tracker.thepiratebay.org.
/home/vader/.local/lib/python2.7/site-packages/twisted/internet/_resolver.py:137:deliverResults
/home/vader/.local/lib/python2.7/site-packages/twisted/internet/endpoints.py:921:resolutionComplete
/home/vader/.local/lib/python2.7/site-packages/twisted/internet/defer.py:459:callback …
```
=> Fix TorrentChecker timeout logging

TriblerGUI/tribler_request_manager.py
Fixes #4208 
We should at one point discuss whether we want to ignore _all_ errors during shutdown. This will at least ignore the errors originating from HTTP requests during shutdown.
=> Ignoring errors during Tribler shutdown

Tribler/community/market/core/tick.py
Is __buffer__ --> __Tribler.pyipv8.ipv8.database.database_blob__ still the preferred conversion?
=> unicode --> six.text_type and buffer --> database_blob in tick.py

Tribler/Core/TorrentDef.py
Ready for review.
Please ignore the flake8 _undefined name_ on Python 3 only because the follow-up PR will target fixing instances of __unicode(s, encoding)__.
I have no idea what the __Combined coverage diff__ is trying to say.
=> unicode(s) --> six.text_type(s) in TorrentDef.py

TriblerGUI/vlc.py
This will replace the current VLC bindings with the generated ones from upstream. Partially addresses #3883. I copied over the (heavily modified) `find_lib` method from our old `vlc.py` and added some code so Tribler is able to find VLC in a Mac developer environment.
Fixes #4093
=> Added VLC 3.0.6 bindings

Tribler/Core/Modules/restapi/create_torrent_endpoint.py, Tribler/Core/TorrentDef.py, Tribler/Core/Utilities/torrent_utils.py, Tribler/Core/Utilities/unicode.py
As discussed in https://github.com/Tribler/tribler/issues/3883
In _Tribler/Core/Utilities/unicode.py_, __ensure_unicode()__ is defined to be like [__six.ensure_text()__](https://six.readthedocs.io/#six.ensure_text) except that encoding parameter is not optional.  See [__six>=1.12.0__](https://github.com/benjaminp/six/blob/master/CHANGES).
=> READY: unicode(s, enc) --> ensure_unicode(s, enc)

Tribler/Core/Utilities/instrumentation.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
=> print() is a function in Python 3

Tribler/Test/Core/test_unicode.py
```
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/test_as_server.py", line 62, in check
result = fun(*argv, **kwargs)
File …
```
=> binascii.b2a_uu() requires bytes, not str

Tribler/Core/Utilities/utilities.py
```
ERROR: test_valid_torrent_file_announce_list_empty
StopIteration
During handling of the above exception, another exception occurred:
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/python/compat.py", line 464, …
```
=> dict.iteritems() --> dict.items() for Python 3

Tribler/Test/Core/test_launch_many_cores.py
```
ERROR: Test whether we are resuming downloads after loading checkpoint
File …
```
=> state_file.write() requires bytes, not str

Tribler/Test/GUI/test_util.py
```
ERROR: Failure: ImportError (cannot import name 'unquote_plus')
File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
raise self.exc_val.with_traceback(self.tb)
File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
addr.filename, addr.module)
File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
return self.importFromDir(dir_path, fqname)
File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
mod = load_module(part_fqname, fh, filename, desc)
File "/usr/lib/python3.5/imp.py", line 234, in load_module
return load_source(name, filename, file)
File "/usr/lib/python3.5/imp.py", …
```
=> from six.moves.urllib.parse import unquote_plus

Tribler/Test/Integration/test_live_downloads.py
```
ERROR: Failure: ImportError (cannot import name 'pathname2url')
File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
raise self.exc_val.with_traceback(self.tb)
File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
addr.filename, addr.module)
File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
return self.importFromDir(dir_path, fqname)
File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
mod = load_module(part_fqname, fh, filename, desc)
File "/usr/lib/python3.5/imp.py", line 234, in load_module
return load_source(name, filename, file)
File "/usr/lib/python3.5/imp.py", …
```
=> from six.moves.urllib.request import pathname2url

Tribler/Test/Core/test_torrent_def.py
```
FAIL: Add a single dir to a TorrentDef
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/t …
```
=> Test for bytes, not str

Tribler/Core/Libtorrent/LibtorrentMgr.py
```
ERROR: Testing whether some errors are ignored (like socket errors)
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Core/test_session.py", line 23, in setUp
yield super(TestSessionAsServer, self).setUp()
result = …
```
=> mid.encode('hex') --> hexlify(mid) for Python 3

Tribler/Core/Utilities/maketorrent.py
```
ERROR: test_get_index
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/test_as_server.py" …
```
=> str are already Unicode utf-8 by default in Python 3

Tribler/Core/Config/config.spec
We had not defined boolean spec for version checker which is why version checked seemed to be always enabled in dev mode.
=> Version checker in config

Tribler/Core/APIImplementation/LaunchManyCore.py
```
ERROR: Test whether the balance of peers is correctly updated
File …
```
=> s.encode('hex') --> hexlify(s) & s.decode('hex') --> unhexlify(s)

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, TriblerGUI/utilities.py, TriblerGUI/widgets/tablecontentmodel.py
Also not crashing the `pretty_date` method when an invalid time is passed to the method.
Fixes #4326
=> Using torrent_date instead of timestamp for channel metadata update time

Tribler/community/triblertunnel/community.py
* https://docs.python.org/3.1/whatsnew/3.0.html#integers
* https://docs.python.org/3.1/library/sys.html#sys.maxsize
=> sys.maxint removed Py3 because int are of infinite precision

Tribler/community/triblertunnel/community.py
```
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/pyipv8/ipv8/test/base.py", line 61, in tearDown
node.unload()
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/pyipv8/ipv8/test/mocking/ipv8.py", line 52, in unload
self.overlay.unload()
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
return _cancellableInlineCallbacks(gen)
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
_inlineCallbacks(None, g, status)
--- <exception caught here> ---
File …
```
=> open(self.exitnode_cache, 'w' --> 'wb') for Python 3

Tribler/Test/Community/gigachannel/test_community.py
A low timeout could result in the test proceeding while incoming metadata items were not fully processed yet.
=> Increased deliver_messages timeout in gigachannel community tests

Tribler/Core/Video/VideoServer.py, Tribler/Test/Integration/test_live_downloads.py
```
ERROR: Testing whether the right VOD stream is returned
File …
```
=> dict.has_key() was removed in Python 3

Tribler/Core/Libtorrent/LibtorrentMgr.py
```
ERROR: test_combined
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Core/Video/test_video_server.py", line 117, in setUp
yield super(TestVideoServerSession, self).setUp()
File …
```
=> 'Tribler/' + version_id + '/' + str(hexlify(mid))

Tribler/Test/Core/test_downloadconfig.py
```
ERROR: test_default_download_startup_config_load
StopIteration
During handling of the above exception, another exception occurred:
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/python/compat.py", line 464, in …
```
=> write bytes in test_default_download_startup_config_load()

Tribler/Core/Modules/restapi/util.py
```
ERROR: Testing the fix of a unicode array
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Tes …
```
=> Only bytes has .decode() in Python 3

TriblerGUI/debug_window.py
* https://pypi.org/project/meliae/
* https://launchpad.net/meliae
```
ERROR: Failure: ImportError (No module named 'meliae')
File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
raise self.exc_val.with_traceback(self.tb)
File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
addr.filename, addr.module)
File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
return self.importFromDir(dir_path, fqname)
File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
mod = load_module(part_fqname, fh, filename, desc)
File "/usr/lib/python3.5/imp.py", line 234, in load_module
return …
```
=> Deal gracefully with failure to import meliae

Tribler/Test/Community/Market/test_tick.py
```
ERROR: Test the to dictionary method of a tick
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Community/Market/test_tick.py", line 81, in test_to_dictionary
"block_hash": hexlify('0' * 32)
TypeError: a bytes-like object is required, not 'str'
```
=> hexlify() takes bytes, not str

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
It could be that torrent_info is set to None while looping over the bytes. This additional check should prevent Tribler from crashing when this happens.
Fixes #4360
=> Added additional check for torrent_info existence

Tribler/Test/Community/Market/test_block.py, Tribler/Test/Community/Market/test_community.py, Tribler/Test/Community/Market/test_database.py, Tribler/Test/Community/Market/test_matching_engine.py, Tribler/Test/Community/Market/test_message.py, Tribler/Test/Community/Market/test_order.py, Tribler/Test/Community/Market/test_order_repository.py, Tribler/Test/Community/Market/test_orderbook.py, Tribler/Test/Community/Market/test_payment.py, Tribler/Test/Community/Market/test_portfolio.py, Tribler/Test/Community/Market/test_pricelevel.py, Tribler/Test/Community/Market/test_side.py, Tribler/Test/Community/Market/test_tick.py, Tribler/Test/Community/Market/test_tickentry.py, Tribler/Test/Community/Market/test_trade.py, Tribler/Test/Community/Market/test_transaction.py, Tribler/Test/Community/Market/test_transaction_manager.py, Tribler/Test/Community/Market/test_transaction_repository.py, Tribler/Test/Core/Modules/RestApi/test_market_endpoint.py, Tribler/community/market/community.py, Tribler/community/market/core/message.py, Tribler/community/market/core/order.py, Tribler/community/market/core/payment.py, Tribler/community/market/core/tick.py, Tribler/community/market/core/transaction.py, Tribler/community/market/database.py
Opposite approach to #4351
```python
class TraderId(object):
def __init__(self, trader_id):
```
https://mypy.readthedocs.io/en/latest/cheat_sheet.html#classes
```
ERROR: Test whether an order is unreserved when address resolution fails
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Community/Market/test_community.py", line 279, in test_address_resolv_fail
yield self.introduce_nodes()
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/pyipv8/ipv8/test/base.py", line 160, in introduce_nodes …
```
=> TraderId() takes bytes, not str

Tribler/Core/Config/tribler_config.py, Tribler/Core/Modules/restapi/create_torrent_endpoint.py, Tribler/Core/Modules/restapi/settings_endpoint.py, Tribler/Test/Core/Modules/RestApi/base_api_test.py, Tribler/Test/Core/Modules/RestApi/test_create_torrent_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_rest_manager.py, Tribler/Test/Core/Modules/RestApi/test_settings_endpoint.py, Tribler/Test/test_as_server.py, TriblerGUI/tribler_request_manager.py
This PR implements proper, Twisted `http.parse_qs`-compatible encoding of URL arguments and makes our test suite use the same way of encoding URLs that we use in Tribler. Also, it changes Tribler config file encoding to `utf-8`. This change is necessary to conform with the "unicode sandwich" ideology and accommodate the changes in the endpoints data encoding.
Fixes #4365
=> Proper lists URL encoding and UTF-8 fixes

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Core/Socks5/connection.py, Tribler/Test/API/test_download.py, Tribler/Test/Community/Tunnel/test_community.py, Tribler/community/triblertunnel/community.py
Two months ago, libtorrent 1.2.0 has been released with many fixes and improvements. This PR should make Tribler compatible with 1.2.0.
While having overlap with #3437, this PR ensures that Tribler still works with libtorrent versions between 1.0.0 and 1.1.0 (in contrast to #3437).
**Important:** this PR drops support for libtorrent 0.16.19 and older. Since 0.16.19 has been released almost four years ago, I think we can safely drop support for these old versions of libtorrent.
=> Made Tribler compatible with libtorrent 1.2.0

Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/MetadataStore/store.py, Tribler/Core/Modules/gigachannel_manager.py, Tribler/Core/Modules/restapi/downloads_endpoint.py, Tribler/Core/Modules/restapi/metadata_endpoint.py, Tribler/Core/Modules/restapi/search_endpoint.py, Tribler/Core/Session.py, Tribler/Core/TorrentChecker/session.py, Tribler/Core/Upgrade/db72_to_pony.py, Tribler/Core/Upgrade/upgrade.py, Tribler/Test/Core/Modules/MetadataStore/test_store.py, Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_metadata_endpoint.py, Tribler/Test/Core/Upgrade/test_db72_to_pony.py, Tribler/Test/Core/Upgrade/test_upgrader.py, TriblerGUI/tribler_window.py
This PR moves the processing of GigaChannel data downloaded with libtorrent to a background thread spawned with `deferToThread`. Holding DB lock for a long time **severely** affects Twisted reactor performance. Thus, this PR implements a congestion-control algorithm to dynamically break the workload into smaller batches. The default target time for processing a single batch - **100ms** - was devised by experimentation. If the routine runs in the background thread, 50ms `sleep` intervals are inserted between batches, so that other threads got a chance to acquire the DB lock. Again, this proved to be necessary by hands-on experience.
Community payloads are still processed on the main thread.
=> Move channel dir processing to a separate thread

doc/development/development_on_linux.rst
Currently Tribler 7.2.2 does not start on Arch Linux, because of few missing Python 2 modules.
This change adds these missing modules to the documentation.
=> Update dependencies for Arch Linux

Tribler/Core/Utilities/utilities.py
```
ERROR: Test if http_get is working properly if url redirects to a magnet link.
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Core/Utilities/utilities.py", line 82, in http_get
deferred = agent.request('GET', uri, headers, None)
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/web/client.py", line 1649, in request
parsedURI = URI.fromBytes(uri)
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/web/client.py", line 638, in fromBytes
scheme, netloc, path, params, query, fragment = http.urlparse(uri)
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/web/http.py", line 181, in urlparse
raise TypeError("url must be bytes, not …
```
=> uri = uri.encode('utf-8')  # Try converting uri to bytes

Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py
This mechanism was originally meant as a workaround for an issue where the DHT did not bootstrap correctly. I believe that after six years, this workaround can be removed since I observed that DHT bootstrapping is very stable (it finds initial nodes within a few seconds after startup). Also see https://github.com/Tribler/tribler/commit/a786cf71e5ea8f590bd973157da4da48b5f4bf73.
=> Removed DHT retry mechanism

Tribler/Core/Utilities/maketorrent.py, Tribler/Core/Utilities/unicode.py
As discussed in #4318  __Can't mix strings and bytes in path components__
```
ERROR: test_pathlist2filename_not_utf8
result = f(*a, …
```
=> Refactor pathlist2filename()

Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Test/GUI/test_gui.py
big_number got removed in libtorrent 1.2.0 so we use sha1_hash instead.
=> Changed lt.big_number to lt.sha1_hash

Tribler/Core/Category/category.conf, Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/MetadataStore/OrmBindings/channel_node.py, Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py, Tribler/Core/Modules/MetadataStore/store.py, Tribler/Core/Modules/restapi/metadata_endpoint.py, Tribler/Core/Modules/restapi/mychannel_endpoint.py, Tribler/Test/Core/Modules/MetadataStore/test_store.py, Tribler/Test/Core/Modules/MetadataStore/test_torrent_metadata.py, Tribler/Test/Core/Modules/RestApi/test_metadata_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_mychannel_endpoint.py, Tribler/community/gigachannel/community.py, TriblerGUI/defs.py, TriblerGUI/qt_resources/mainwindow.ui, TriblerGUI/widgets/channelpage.py, TriblerGUI/widgets/discoveredpage.py, TriblerGUI/widgets/editchannelpage.py, TriblerGUI/widgets/lazytableview.py, TriblerGUI/widgets/searchresultspage.py, TriblerGUI/widgets/subscribedchannelspage.py, TriblerGUI/widgets/subscriptionswidget.py, TriblerGUI/widgets/tablecontentdelegate.py, TriblerGUI/widgets/tablecontentmodel.py, TriblerGUI/widgets/triblertablecontrollers.py
This PR adds the ability to edit a GigaChannel entry through the GUI. The editing is done inline in the MyChannel table. The user can change the torrent's category by selecting one from a combo box. Torrent's title can also be edited by double-clicking on it.
Also, this PR changes Legacy entries status label from 6 to 1000, and removes FTS indexing from `tags` column, so the database format is not fully compatible with the previous versions.
This PR is really important for 7.3 release, as it provides a basis for crowdsourcing the torrents channels.
EDIT:
Also, this PR includes a refactoring of `triblertablecontrollers.py` and **breaking changes to DB schema** (removing unused tables and properties).
=> Add title and category editing to the GUI

Tribler/Core/Libtorrent/LibtorrentMgr.py, Tribler/Core/Modules/dht_health_manager.py, Tribler/Core/TorrentChecker/session.py, Tribler/Core/TorrentChecker/torrent_checker.py, Tribler/Core/Utilities/utilities.py, Tribler/Test/Core/Modules/RestApi/test_metadata_endpoint.py, Tribler/Test/Core/Modules/test_dht_health_manager.py, Tribler/Test/Core/TorrentChecker/test_torrentchecker.py, Tribler/Test/Core/TorrentChecker/test_torrentchecker_session.py
Fixes #4321 
By default, BEP33 checks are disabled and it is checked whether ones libtorrent core has support for it. If not, the user cannot perform these checks.
Since BEP33 support is not enabled on the testing machines, there are a few uncovered lines.
=> Added BEP33 DHT health check

Tribler/Test/Community/Market/test_community.py
__x.find_all()__ will return a __list__ in Python 2 and an __iterator__ in Python 3.  Force the result into a list for __bool()__, __len()__, and indexing.
```
ERROR: Test creating an ask and sending it to others
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Community/Market/test_community.py", line 76, in test_create_ask
self.assertTrue(orders[0].verified)
TypeError: 'dict_values' object does not support indexing
```
=> Cast the results of x.find_all() to a list for Python 3

Tribler/Test/Community/popularity/test_payload.py
Tribler.pyipv8.ipv8.messaging.serialization.PackError: Could not pack item 0: ('20s', 'aaaaaaaaaaaaaaaaaaaa')
error: argument for 's' must be a bytes object
```
ERROR: Test serialization/deserialization of Torrent health payload
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 264, in pack_multiple
packed, packed_size = self.pack(*packable)
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 248, in pack
return self._packers[format].pack(*data)
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 171, …
```
=> infohash should be bytes

Tribler/Test/Community/Market/test_message.py
```
ERROR: test_init (Tribler.Test.Community.Market.test_message.TraderIdTestSuite)
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Community/Market/test_message.py", line 18, in test_init
TraderId(1.0)
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/community/market/core/message.py", line 19, in __init__
trader_id = trader_id if isinstance(trader_id, bytes) else binary_type(trader_id)
TypeError: 'float' object is not iterable
```
=> TraderId(1.0) will raise a TypeError in Python 3

Tribler/Test/Community/Market/test_matching_engine.py
Like #4398
```
test_match_order_ask ... ERROR
test_match_order_bid ... ERROR
Test a matching with multiple price levels ... ERROR
Test matching when there are asks in multiple price levels ... ERROR
Test matching when there are bids in multiple price levels ... ERROR
Test whether there is no match when we already reserved some quantity ... ERROR
Test whether the price-time priority works correctly ... ERROR
Test whether the price-time priority works correctly ... ERROR
Test whether an ask tick is not matched when blocked for matching ... ERROR
Test whether a bid tick is not matched when blocked for matching ... ERROR
Test for match order with an empty order book ... ERROR
Test for match ask order ... ERROR
Test for match bid order ... ERROR
Test for match order divided over two ticks ... …
```
=> Convert matching_engine.match() to list

Tribler/Test/Community/Market/test_matching_engine.py
Reverts Tribler/tribler#4402  Those changes did nothing to fix the errors in question.
We should implement the `__iter__` method in `PriceLevel` to fix these errors.
=> Revert "Convert matching_engine.match() to list"

Tribler/Test/Core/CreditMining/test_credit_mining_policies.py
* https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertItemsEqual -->
* https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertCountEqual
```
ERROR: test_random_policy
StopIteration
During handling of the above exception, another exception occurred:
StopIteration
During …
```
=> unittest.TestCase().assertItemsEqual() --> assertCountEqual()

Tribler/Core/Socks5/conversion.py
```
ERROR: Test whether no data is sent to the SOCKS5 server when we receive data from the tunnels
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/utils.py", line …
```
=> Join bytes, not strings

Tribler/community/triblertunnel/community.py
```
ERROR: Test whether we remove peers from the PEX info when a download is stopped
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/internet/utils.py", line 197, in …
```
=> TypeError: unsupported operand type for +: 'dict_keys' and 'dict_keys'

doc/development/development_on_osx.rst
Fix max os development guide that work now with `brew`
=> Update mac os development guide

Tribler/community/market/core/pricelevel_list.py
@devos50 @qstokkink @ichorid Just to get the sense of the changes required to add __typing__ to a file that is causing us some type-related issues...
__Tests on Mac__ is failing because we would need to __pip install typing__ on Python 2 (it is built-in in Python 3) and then add a __mypy__ test run to our builds.  https://mypy.readthedocs.io/en/latest/cheat_sheet.html
=> Add typing to pricelevel_list.py

tribler.spec
Also see https://stackoverflow.com/questions/47468705/pyinstaller-could-not-find-or-load-the-qt-platform-plugin-windows
=> Make sure qwindows.dll is in the right location

Tribler/Test/Core/Modules/RestApi/base_api_test.py
This raise 18 ERRORS like...
```
ERROR: Failure: TypeError (Class advice impossible in Python3.  Use the @implementer class decorator instead.)
File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
raise self.exc_val.with_traceback(self.tb)
File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
addr.filename, addr.module)
File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
return self.importFromDir(dir_path, fqname)
File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
mod = load_module(part_fqname, fh, …
```
=> Class advice impossible in Python3.  Use @implementer class decorator

Tribler/community/market/core/order.py, Tribler/community/market/core/transaction.py
Fixes #4403
```
FAIL: test_str (Tribler.Test.Community.Market.test_order.OrderIDTestSuite)
File "/home/jenkins/workspace/test_tribler_python3@2/tribler/Tribler/Test/Community/Market/test_order.py", line 198, in test_str
self.assertEquals('0.1', str(self.order_id))
AssertionError: '0.1' != "b'0'.1"
- 0.1
+ b'0'.1
FAIL: test_conversion (Tribler.Test.Community.Market.test_transaction.TransactionIdTestSuite)
File …
```
=> Fix str representation of OrderId and TransactionId

Tribler/Core/Session.py, Tribler/Core/TorrentChecker/torrent_checker.py, Tribler/Test/Core/TorrentChecker/test_torrentchecker.py
In this PR, I added a loop that checks the health of a random torrent every 2 minutes. This ensures that the health of trackless torrents is also determined eventually. Addresses #4256.
I Also refactored some attributes in the TorrentChecker class.
=> Added random torrent health check to TorrentChecker

TriblerGUI/qt_resources/torrent_details_container.ui, TriblerGUI/widgets/torrentdetailstabwidget.py, TriblerGUI/widgets/triblertablecontrollers.py
- Torrent details tab is hidden when no torrents are selected
- Infohash is now shown in torrent details tab and it can be copied to the clipboard as well
=> Fixes on torrent details tab

Tribler/Test/Core/Modules/RestApi/test_wallets_endpoint.py
It was making connections to the bootstrap servers and listening for TrustChain blocks.
=> Disabling IPv8 during wallet tests

Tribler/Core/Modules/restapi/rest_manager.py, Tribler/Test/Core/Modules/RestApi/test_rest_manager.py
This will return more helpful messages when fixing the REST API tests under Python 3.
```
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Core/Modules/restapi/rest_manager.py", line 114, in process
server.Request.process(self)
File "/home/jenkins/.local/lib/python3.5/site-packages/twisted/web/server.py", line 201, in process
self.processingFailed(failure.Failure())
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Core/Modules/restapi/rest_manager.py", line 85, in processingFailed
u"message": failure.value.message
builtins.AttributeError: 'KeyError' object has no attribute 'message'
```
=> Message does not exist on Exceptions in Python 3

Tribler/Core/Utilities/configparser.py
```
jenkins@python3-tester:~/tribler$ nosetests3 Tribler/Test/Core/test_configparser.py 
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: to-Python converter for boost::shared_ptr<libtorrent::alert> already registered; second conversion method ignored.
return f(*args, **kwds)
.......
Ran 7 tests in 1.500s
OK
```
=> Fixed Python 3 compatibility for configparser.py

TriblerGUI/widgets/settingspage.py
This change, where I hide the widgets that show settings data, should prevent users from changing the settings while they are not initialized yet.
Fixes #4455
=> Hide widgets when loading settings

Tribler/Core/Modules/MetadataStore/store.py, Tribler/Core/Modules/restapi/events_endpoint.py, Tribler/Core/Modules/restapi/root_endpoint.py, Tribler/Core/Modules/restapi/upgrader_endpoint.py, Tribler/Core/Session.py, Tribler/Core/Upgrade/db72_to_pony.py, Tribler/Core/Upgrade/upgrade.py, Tribler/Core/simpledefs.py, Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_upgrader_endpoint.py, Tribler/Test/Core/Upgrade/test_upgrader.py, TriblerGUI/core_manager.py, TriblerGUI/event_request_manager.py, TriblerGUI/qt_resources/mainwindow.ui, TriblerGUI/tribler_window.py, TriblerGUI/widgets/loadingpage.py
This PR moves 72 -> 73(Pony) upgrader out of the background thread to be run in the foreground at Tribler startup instead.
This greatly speed-ups the process by as we can use larger batches and **disable disk synchronization** during the upgrade process for the newly created DB. This is safe to do, since the old DB is read-only, and the conversion process can always be started from a clean slate if power fails during the upgrade process.
Disabling sync makes the upgrade process **run on an HDD as fast as on an SSD**. On my machine, a 400Mb `tribler.sdb` is converted in less than 1 minute.
To give users some control over the process, a "skip" button along with a text indicator of the state of the upgrade process are added to the "spinning gears" screen. Pressing the button produces a …
=> READY: Foreground DB upgrader

Tribler/Core/Modules/restapi/trustview_endpoint.py, TriblerGUI/defs.py, TriblerGUI/qt_resources/mainwindow.ui, TriblerGUI/utilities.py, TriblerGUI/widgets/trustgraphpage.py
This PR includes the Trust Graph with basic interaction like node selection and dragging the graph at root node. The details of the selected node is also shown at the bottom of the graph. Here is a screenshot showing how it looks.
=> Interactive Trust Graph

Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py, Tribler/Test/Core/Modules/MetadataStore/test_torrent_metadata.py
This little patch adds `GROUP BY` - based deduplication of metadata search results in SQL based on infohash. Note that it does not deduplicate the *entries* in the database, but only the results displayed (or the results sent over the Search community).
=> Deduplication of SQL search results based on infohash

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/MetadataStore/OrmBindings/channel_peer.py, Tribler/Core/Modules/MetadataStore/OrmBindings/channel_vote.py, Tribler/Core/Modules/MetadataStore/OrmBindings/vsids.py, Tribler/Core/Modules/MetadataStore/store.py, Tribler/Core/Modules/resource_monitor.py, Tribler/Core/Modules/restapi/metadata_endpoint.py, Tribler/Core/Upgrade/db72_to_pony.py, Tribler/Test/Core/Modules/MetadataStore/test_channel_metadata.py, Tribler/community/gigachannel/community.py, TriblerGUI/widgets/channelpage.py, TriblerGUI/widgets/discoveredpage.py, TriblerGUI/widgets/lazytableview.py, TriblerGUI/widgets/subscriptionswidget.py, TriblerGUI/widgets/tablecontentmodel.py
This PR implements a [VSIDS](https://arxiv.org/pdf/1506.08905.pdf)-like heuristics for channel popularity.
In short, whenever a gossip with a channel is received, the corresponding vote count is increased by +1, and then *all the other votes* are **multiplied** by a constant *decay factor*. As a result, the heuristic works like a temporal PageRank, bumping the most actively spread around channels to the top.
The decay factor for this version is 2.71 per 24 hours of Tribler online time. This means that when some channel gets a vote today, tomorrow by the same time the vote will be 2.71x times smaller. The decay is performed on per-vote basis, meaning that it happens gradually over time, as the votes come in. The algorithm is O(1) in regards to the number of DB calls for each vote update. …
=> READY: VSIDS-based channel rating system

TriblerGUI/widgets/tablecontentmodel.py
Fixes #4525 
The crash happened when hovering over the "State" column for a non-legacy **torrent** entry in the Search tab.
=> Fix GUI state column tooltip crash

Tribler/Core/Config/tribler_config.py, Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
This PR contains some fixes to make Tribler working directory path and `.state` files support non-ASCII characters.
=> READY: Unicode-related fixes for 7.3

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py, Tribler/Core/Modules/restapi/torrentinfo_endpoint.py, Tribler/Test/Core/Modules/MetadataStore/test_torrent_metadata.py, Tribler/Test/Core/Modules/RestApi/test_torrentinfo_endpoint.py, TriblerGUI/tribler_window.py
Whenever the user checks out a magnet link or opens a torrent, a corresponding is added to free-for-all channel. These entries are only spread around via remote search requests.
=> Automatically add torrents to free-for-all channels

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Session.py
Fixes #4558 by moving the call to GigaChannel Manager startup method into Session deferred callback.
Now it will run *after* resuming torrents from checkpoints.
=> Start GigaChanMan after resuming downloads

Tribler/Test/GUI/test_gui.py, TriblerGUI/dialogs/confirmationdialog.py, TriblerGUI/dialogs/startdownloaddialog.py, TriblerGUI/qt_resources/mainwindow.ui, TriblerGUI/qt_resources/startdownloaddialog.ui, TriblerGUI/tribler_window.py, TriblerGUI/widgets/ClickableLineEdit.py, TriblerGUI/widgets/clickablewidgets.py, TriblerGUI/widgets/editchannelpage.py, run_tribler.py
This PR fixes the issues mentioned in https://github.com/Tribler/tribler/issues/4438.
Fixes the failure to load torrent or magnet link when Trible is already running. Additionally, adds an option to retry fetching the meta info in download dialog if it times out to load the files on the first request.
=> Fix for loading torrent or magnet link in Tribler via external click

Tribler/Core/Config/tribler_config.py, Tribler/Core/CreditMining/CreditMiningManager.py, Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py, Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/restapi/downloads_endpoint.py, Tribler/Core/Modules/restapi/search_endpoint.py, Tribler/Core/Modules/restapi/torrentinfo_endpoint.py, Tribler/Core/Modules/watch_folder.py, Tribler/Core/TorrentDef.py, Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py, Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_torrentinfo_endpoint.py, Tribler/Test/Core/Modules/test_watch_folder.py, Tribler/Test/Core/Upgrade/test_config_upgrade_70_71.py, Tribler/Test/test_as_server.py
This PR is a continuation of https://github.com/Tribler/tribler/pull/4562
Initially, I added some Unicode characters to Tribler test directory names, tmp directories, etc. I was able to fix about a dozen bugs in that mode. There was only one left (watch folder related), but solving it would require too much effort. Moving to Python3 (and/or Pathlib) would solve that. So, I omitted the patch that introduced Unicode characters into test dirs paths.
Nonetheless, this solves some Unicode-related problems.
Fixes #4524
=> READY: Unicode-related fixes

Tribler/Core/TorrentDef.py
Fixes #4569 
Really, this only brings the code back to the state it was before. I don't know what kind of arguments Libtorrent wrappers is supposed to get, so I just pass it through if it is not dict.
We're going to refactor the wrapper soon anyway.
=> READY: Workaround for broken tdef metainfo argument

Tribler/Core/CreditMining/CreditMiningSource.py, Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/MetadataStore/store.py, Tribler/Core/Modules/restapi/mychannel_endpoint.py, Tribler/Core/Upgrade/db72_to_pony.py, Tribler/Test/Core/Modules/MetadataStore/test_channel_download.py, Tribler/Test/Core/Modules/MetadataStore/test_channel_metadata.py
This PR adds further support for nested channel feature. Before, user's channel always got a 0 `id_`. This is compatible with the planned nested channels scheme, but is inconvenient, because after moving to nested channels users will have their personal channels contents right at their root channel. Instead, we're now creating a nested personal channel with timestamp-based `id_` that resides in the user's root (`id_==0`) channel.
There is no real change in the database schema, but we still have to clean the previous beta database, because otherwise, our beta testers will end up with messy channels after the transition to nested channels in 7.4.
=> READY: Make personal channel use timestamp for id_

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/gigachannel_manager.py, Tribler/Core/Upgrade/db72_to_pony.py
This adds conversion of the health info from 7.2.2 database to Pony. Also, it fixes a bug with torrents conversion introduced in #4572 that resulted in skipping conversion of most entries.
=> Fix torrent health conversion

Tribler/Core/Modules/MetadataStore/store.py, Tribler/Core/Upgrade/db72_to_pony.py
Converter query for getting old entries from the legacy database creates and deletes several temporary files in /tmp/var/etilqs* for each row read from the old DB.
This results in gigabytes of useless disk writes on Linux during conversion of big databases.
This patch disables usage of temporary files by Sqlite3 wrapper during conversion.
=> READY: Fix horrible disk churn in converter

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Test/Community/gigachannel/test_community.py, Tribler/community/gigachannel/community.py
Fixes #4579 
If the channel's `local_version` is non-zero, that means it was at least partially added from a downloaded torrent. This means the swarm is reachable.
=> Make GigaChan community spread only downloaded channels

TriblerGUI/qt_resources/mainwindow.ui, TriblerGUI/widgets/home_recommended_item.py, TriblerGUI/widgets/homepage.py
Fixes the annoying streching of tiles on tab switch:
Fixes #4588.
=> Fixed issues with homepage tiles

TriblerGUI/widgets/triblertablecontrollers.py
This fixes the list view not resizing when deselecting a torrent in the discovered channel exploration list.
For the naming I stuck with @ichorid's original description.
=> Fixed discovered list not resizing

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/MetadataStore/store.py, Tribler/Core/Modules/gigachannel_manager.py, Tribler/Test/Core/Modules/MetadataStore/test_channel_download.py, Tribler/Test/Core/Modules/test_gigachannel_manager.py
Before, if a channel was downloaded, but never processed, it would become stuck in `DOWNLOADING` state and never be processed by MetadataStore. This PR fixes this problem by introducing a channel dir processing queue in GigaChannel Manager and adding an additional check for downloaded, but unprocessed channels. Coincidentally, introducing this queue fixes potential race conditions and launching of more than one background channel-processing thread at a time.
Also, fixes #4578
=> READY: Restart channel processing if it was stopped abruptly

Tribler/Core/TorrentChecker/torrent_checker.py, TriblerGUI/widgets/tablecontentmodel.py
Fixes:
- Not sending a response on torrent checking failure.
- Not updating row 0.
=> Fixed torrent checker events not propagating

tribler.spec
=> Removing redundant IPv8 submodule when building

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py, Tribler/Core/Modules/MetadataStore/store.py, Tribler/Core/Modules/gigachannel_manager.py, Tribler/Core/Modules/restapi/metadata_endpoint.py, Tribler/Core/Modules/restapi/mychannel_endpoint.py, Tribler/Core/Modules/restapi/search_endpoint.py, Tribler/Core/Upgrade/db72_to_pony.py, Tribler/Test/Core/Modules/MetadataStore/test_channel_metadata.py, Tribler/Test/Core/Modules/MetadataStore/test_torrent_metadata.py, Tribler/Test/Core/Modules/RestApi/test_metadata_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_mychannel_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_search_endpoint.py, Tribler/Test/Core/Modules/test_gigachannel_manager.py, Tribler/Test/Core/Upgrade/test_db72_to_pony.py, Tribler/Test/GUI/FakeTriblerAPI/endpoints/metadata_endpoint.py, Tribler/Test/GUI/FakeTriblerAPI/endpoints/mychannel_endpoint.py, Tribler/Test/GUI/FakeTriblerAPI/endpoints/search_endpoint.py, Tribler/Test/GUI/test_gui.py, Tribler/community/gigachannel/community.py, TriblerGUI/tribler_window.py, TriblerGUI/widgets/channelpage.py, TriblerGUI/widgets/downloadwidgetitem.py, TriblerGUI/widgets/editchannelpage.py, TriblerGUI/widgets/searchresultspage.py, TriblerGUI/widgets/tablecontentmodel.py, TriblerGUI/widgets/triblertablecontrollers.py
Fixes #4592  by removing and minimizing some SQL queries and REST requests.
Fixes #4593 (fixes slowdown).
Fixes #4610 
Fixes #4620 
Fixes #4613 
Fixes #4598 
This PR now also refactors GigaChannel Manager to use a dict-base queue for channel torrent related actions such as cruft channel torrents dir removal and processing already downloaded dirs. This should make it much safer, as this things are now never done simultaneously.
=> READY: Speed up channels view by removing unnecessary SQL queries

Tribler/Test/Community/gigachannel/test_community.py, Tribler/community/gigachannel/community.py
This makes GigaChannel Community cache the results of the SQL query that selects the channel contents to gossip around. The resulting blob is then saved for reuse in the Community object. The blob will be sent to 30 peers, and then the new query will be performed. This significantly reduces the background DB activity.
Fixes #4636
=> READY: GigaChannel Community gossip caching

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/MetadataStore/OrmBindings/channel_node.py, Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py, Tribler/Core/Modules/MetadataStore/store.py, Tribler/Core/Modules/gigachannel_manager.py, Tribler/Core/Upgrade/db72_to_pony.py, Tribler/Test/Community/gigachannel/test_community.py, Tribler/Test/Core/CreditMining/test_credit_mining_sources.py, Tribler/Test/Core/Modules/MetadataStore/test_channel_metadata.py, Tribler/Test/Core/Modules/MetadataStore/test_store.py, Tribler/Test/Core/Modules/test_gigachannel_manager.py, Tribler/Test/Core/Upgrade/test_db72_to_pony.py
Timestamps of incoming GigaChannel payloads are now checked against the parent channel's `local_version`. This allows us to stop getting old deleted results from previous channel versions.
Also, fixed a severe bug in channel commit procedure. When committing the personal channel, mdblob files should only contain entries with timestamps <= to the mdblob filename, but the last mdblob must have the same timestamp as the channel entry itself. Before, this was only true if the channel entry was never edited (e.g. renamed) before commit.
Now we assign filenames based on the timestamp of the last entry in the mdblob, except for the last file. For this, we create a new timestamp and then assign it to _both_ the filename and the updated channel entry.
Fixes #4639 properly.
=> READY: Check timestamp of entry against the channel ver

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/MetadataStore/OrmBindings/channel_node.py, Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py, Tribler/Core/Modules/MetadataStore/store.py, Tribler/Core/Modules/restapi/mychannel_endpoint.py, TriblerGUI/widgets/editchannelpage.py, TriblerGUI/widgets/lazytableview.py, TriblerGUI/widgets/triblertablecontrollers.py
To determine if user modifications to their channel leave it in the "dirty" state that should be committed to torrent, we scan all the contents of the personal channel. This operation is very slow on big channels and should be avoided. The query is served each time the `.dirty` property of ChannelMetadata is accessed.
Previously, we used to do this scan on each query into MyChannel endpoint, which made scrolling through big personal channels very slow. This PR solves the problem by only querying the `.dirty` property if really necessary, making channel state tracking responsibility of the GUI.
Also, this adds some more indexes to the database to speed up common queries.
=> READY: Remove redundant dirty channel queries

TriblerGUI/debug_window.py
This adds support for showing non-printable characters in the "Requests" list of the Debug panel.
=> Make requests window show non-printable characters

Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py, Tribler/Test/Core/Modules/RestApi/test_metadata_endpoint.py, TriblerGUI/widgets/triblertablecontrollers.py
Fixes #4669 
Fixes #4667  by introducing a workaround for buggy URL handling.
Also, adds a test for querying REST enpoint for an FFA channel.
=> Small fixes for beta6

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py, Tribler/Core/Modules/restapi/downloads_endpoint.py, Tribler/Core/Modules/restapi/mychannel_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_mychannel_endpoint.py, TriblerGUI/dialogs/createtorrentdialog.py
Fixes #4674 by doing two things:
1. when showing downloads, tries to replace the downloads' names by searching the local DB;
2. when creating a torrent, uses the title given by the user to add it to the personal channel.
=> READY: Torrent titles from GigaChannel

debian/tribler.postinst
Since we need the latest version of pip for the `ensure_str` method.
=> Installing pip from six

Tribler/Test/Core/Modules/RestApi/base_api_test.py
Fixes #4694
The proper way to fix this, is to have a shared module that both the core and GUI can use. I consider this more like a short-term solution.
=> Copied tribler_urlencode into core

Tribler/Core/DownloadState.py
If there is no handle, we do not report file completion of individual files.
Fixes #4698
=> Fixed crash when getting file completion

TriblerGUI/qt_resources/mainwindow.ui
This should hopefully fix the 'ascii' decoding crash. While I do not consider this as a long-term solution, we can at least see whether this fixes the issue.
Addresses #4666
=> Replace down/up arrows with text

Tribler/Test/GUI/test_gui.py
It could possibly be that the filter is reset, which results in more items being displayed in a list than asserted for. Since we display at most 50 items in a batch, I changed the assert accordingly.
=> (Hopefully) fixed sorting assert in GUI tests

debian/tribler.postinst
Users who have an older version of six installed will not get the latest version without the --upgrade flag.
Fixes #4695
=> Fixed six upgrade on linux

Tribler/Core/Upgrade/upgrade.py, Tribler/Test/Core/data/noncompliant_state_dir/dlcheckpoints/3efb7e9157110e1a259d3a207403388fffffffff.state
Fixes #4725
I don't know the reason why reading these files fails. However, if parsing fails for any reason for a torrent config during upgrading, this config should be deleted so it will not poison the torrents dir. This is especially safe in case of GigaChannels, as infohashes are in the DB and restored as necessary.
=> Delete unreadable channel torrents on upgrading

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py
At the personal channel entry creation its status should be NEW and if the title is edited it should become UPDATED. However, the channel status was always COMMITTED. We never noticed it because there was always only a single personal channel entry. On refactoring for nested channels this problem became apparent.
=> Fix personal channel status not changing on creation/edit/commit

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py
Before, we could be gossiping channels in semi-complete state. This meant more dead channels propagating through the network.
This little change ensures that the channel will be gossiped only in case its current version was completely downloaded.
=> Make GigaChannel gossip only complete channels

TriblerGUI/qt_resources/createtorrentdialog.ui
Fixed various layout inconsistencies, including a typo. Also moved the cancel button to the bottom of the dialog, which is more consistent with the layout in our other dialogs.
=> Polished torrent creation dialog

Tribler/Core/Modules/gigachannel_manager.py, Tribler/Core/Modules/restapi/downloads_endpoint.py
Channel downloads are now hidden, however, they are still sent to the GUI (since they are displayed in the channels tab on the downloads page).
Fixes #4744
=> Disable finished notification for channel download

Tribler/Core/APIImplementation/LaunchManyCore.py
This prevents channels from testnet leaking to mainnet, and vice versa.
Fixes #4746
=> Using different metadata db on testnet

Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
This crash will prevent Tribler from crashing when bdecoding metainfo fails in libtorrent 1.2.0.0. This is quite hard to test since it requires replacement of the bdecode method so it throws a RuntimeError. I tested it manually and the crash seems to be fixed.
Fixes #4741
=> Catch RuntimeError when bdecoding metainfo

TriblerGUI/widgets/downloadspage.py
During shutdown, it can happen that the dictionary sent over the REST API is empty (as indicated by the error report).
=> Fixed GUI crash during shutdown

Tribler/Core/TorrentDef.py, Tribler/Test/Core/test_torrent_def.py
=> Allow for NoneType metainfo in TorrentDef

Tribler/Core/Modules/MetadataStore/store.py, Tribler/Test/Core/Modules/MetadataStore/test_store.py
This fixes the `Broken DB state!` false warnings fos some corner-case metadata update scenarios.
=> Fix false broken db warning in logger

TriblerGUI/tribler_app.py
Fixes the issue with loading torrent with Unicode characters in the name while loading by clicking the torrent file. The crash happened for the case when Tribler was not running already.
=> READY: Fixed issue with loading torrent with Unicode characters

Tribler/Core/Modules/restapi/shutdown_endpoint.py
With the use of memory handler, the logging is efficient but when shutting down it causes some of the logs not being written to the file because the memory handler is not full. This will flush the logs so it is safely written to the file while shutting down.
=> Flush logs before shutting down

debian/tribler.postinst, debian/tribler.prerm
Installing pip packages with `--user` with `sudo` previlege during installation is causing these packages to be installed for only root, while user simply runs tribler in user mode. This causes those packages not being available in user mode. With this PR, I'm removing the `--user` flag so it is installed globally and should be available to all users. Moreover, `wheel` pip dependency is also added which is necessary for systems with older version of pip.
Fixes https://github.com/Tribler/tribler/issues/4767
=> Fixed pip package issues

.flake8, .isort.cfg, .pre-commit-config.yaml, pyproject.toml
This commit adds config files necessary to enable Python `pre-commit` package-based pre-commit hooks. The hooks include automatic removal of unused imports, customized `isort` version [hosted at Tribler GitHub](https://github.com/Tribler/isort), "black" Python code formatter and Flake8 checks.
Fixes #4104 
To use the hooks, one needs to install the `pre-commit` package by doing `pip install pre-commit` and then enable the hooks in the current (Tribler) repository by doing `pre-commit install`. Otherwise, the files from this PR have no effect.
=> Add flake8/black/isort pre-commit hooks

Tribler/Core/Session.py, Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
fixes #4789 
This was tricky. When we create a personal channel, commit it to disk and add to Libtorrent session, sometimes Libtorrent is slow to release the contents. I.e. our wrapper reports that it has shut down, but Libtorrent still holds the files. Then, sometimes, Python tester can't delete the file on Windows because it is still locked by Libtorrent.
I solved the problem by stopping creating a real personal channel in the test. Creating a fictitious channel is enough for this test. However, we should be aware of this Libtorrent behavior in the future.
Also, deleted some unused code in the Session.
=> Fix race condition in GigaChannel tests

TriblerGUI/qt_resources/mainwindow.ui, TriblerGUI/qt_resources/torrent_details_container.ui
Some versions of Python 3.7 show wrong background colors for some widgets in PyQt 5.13.0.
Setting CSS properties explicitly makes for a workaround on this problem.
=> Fix white background on downloads page in Python 3

TriblerGUI/widgets/videoplayerpage.py, check_os.py
When removing a download and resetting the player.
Fixes #4775
=> Checking for existence of mediaplayer object

Tribler/Core/Modules/gigachannel_manager.py, Tribler/Test/Core/Modules/test_gigachannel_manager.py
fixes #4811 for Python2. Python3 works fine with these.
=> Fix GigaChanMan not seeing already downloaded channel torrents

.pre-commit-config.yaml, pyproject.toml
`black` [ignores](https://github.com/psf/black/issues/395) `include` and `exclude` config entries when running on a single exact file path. This is exactly how `pre-commit` works: running singular checks on singular changed files one-by-one. This means that to really exclude something from `black` scope we need to specify it in `.pre-commit-config.yaml`.
=> Fix black-related pre-commit config

TriblerGUI/tribler_window.py
Made + button context menu position relative to the parent widget. This should likely fix https://github.com/Tribler/tribler/issues/4735
=> Plus menu position update

Tribler/Core/Modules/restapi/root_endpoint.py, Tribler/Core/Modules/restapi/trustview_endpoint.py, Tribler/Core/exceptions.py, Tribler/Test/Core/Modules/RestApi/test_trustview_endpoint.py
Set max nodes to 500 and max transactions to 2500 for trust graph rendering.
=> Limited trust graph

Tribler/dependencies.py, check_os.py, run_tribler.py
I have updated `run_tribler.py` to check for missing dependencies before anything else is loaded. This will help us find out dependency issues. Note that, I added a `dependencies.py` file which includes a list of all dependencies. We should keep this file updated whenever we change any dependency.
Also, note that for each dependency `scope` and `optional` fields are set. This separates where the dependency is used ('gui', 'core' or 'both') and if it is optional so both GUI and Core can be separately tested for the dependencies.
Missing dependencies will be shown in a system popup as shown below:
=> Added check for dependencies during startup

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Core/Session.py, Tribler/Core/bootstrap.py, Tribler/Test/Core/test_launch_many_cores.py
Removes old bootstrap files when trying to resume downloads and always loads the latest bootstrap from the infohash present in the config file. This prevents the bootstrap file from being overridden by the old content and potentially fixes related SQL issues.
Fixes #4757 
Fixes #4847
=> Multiple bootstrap files

Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py, Tribler/Test/Community/gigachannel/test_community.py, Tribler/community/gigachannel/community.py
This  PR makes GigaChannel community send two packets on each walk step instead of one:
the first packet contains gossip with the user's personal channel, the second one contains a random subscribed channel. The format remains the same, everything is compatible with the previous version of the GigaChannel community.
During the last month, observation of GigaChannel dynamics showed that the original content propagates slowly. One reason for that is that if a user subscribes for several channels, their personal channel has a really low chance to sent to others. User's personal channel should always get the highest priority in gossip. This is how interpersonal relationships work: we ask "How are *you* doing?" and tell others of things that matter to *us* first.
=> READY: Prioritize gossiping personal channel

Tribler/Test/test_as_server.py
Added `random.seed(123)` to the base test class to make everything as deterministic as possible.
On `tearDown` random generator is re-seeded with the system default generator.
=> READY: Fix non-deterministic results in squash_mdblobs tests

Tribler/Test/Core/Modules/MetadataStore/test_channel_metadata.py
The `sleep` statement should have been placed between the bump calls because the bump amount is increased on the time that passed *between* bump calls.
=> Fix VSIDS test on Windows

Tribler/Core/Upgrade/upgrade.py
Added a debug level logging statement to the exception of a malformed .pstate file as per bug  #4891
=> READY: Added debug level logging to pstate parsing exception

Tribler/Core/Upgrade/config_converter.py
The result received from `iglob` has been iterated through `enumerate`. The need for an index has at some point been rendered not needed, and the index variable replaced with an underscore, so there's no need for `enumerate` and the result can be iterated directly. Fixes bug #4897.
=> Iterate iglob result directly

TriblerGUI/tribler_window.py
Auto screen scaling factor for high resolution screens set to 1.
Reference: https://doc.qt.io/qt-5/highdpi.html
Fixes partially https://github.com/Tribler/tribler/issues/2748
=> Auto screen scaling for high resolution screens

Tribler/Core/Modules/gigachannel_manager.py, Tribler/Test/Core/Modules/MetadataStore/test_channel_download.py, Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py, Tribler/Test/Core/Modules/test_gigachannel_manager.py
Fix mismatch in text types in Python3 in GigaChannel Manager routine that checks channels for correction. Without this fix, all channels would be rejected in Python3 as incorrect.
=> Fix channels not downloading on Python3

Tribler/Main/Build/Win/tribler.nsi, win/makedist_win.bat
Builder script update - Windows
- removed old vc redistributables
- removed separate copying of openssl dlls, not necessary anymore
=> Builder script update - Windows

Tribler/Core/Config/tribler_config.py, Tribler/Core/Config/tribler_config.spec, Tribler/Core/Upgrade/upgrade.py, Tribler/Core/osutils.py, Tribler/Test/Core/Config/test_tribler_config.py, Tribler/Test/Core/Upgrade/test_upgrader.py, Tribler/Test/Core/test_osutils.py
Whenever the code version (present in `version.py`) and config version (present in `triblerd.conf`) are different, state directory is backed up. This is done by copying the current `.Tribler` directory under the version name present in `triblerd.conf`, also inside the `.Tribler` directory. Since only the copy of the state directory is done, the state directory remains always forward compatible. When Tribler starts it tries to load the state directory from the versioned path. If it cannot find the version path then it falls back to `.Tribler`. 
The directory structure for backing up the state directory looks like the following:
*For stable release, eg. 7.4.0*
```
/home/<user>/.Tribler/7.4.0
```
*For pre-release, eg. 7.4.0-exp1*
```
/home/<user>/.Tribler/7.4.0/exp1
```
=> State directory update for rollback support

Tribler/Core/Modules/restapi/metadata_endpoint.py, doc/restapi/introduction.rst, doc/restapi/mychannel.rst
Fixed documentation build issues.
- Escaped underscore in docstring variables. Might not be necessary later (https://github.com/sphinx-doc/sphinx/pull/6460)
- Removed references to obsolete `mychannel_endpoint` references
=> Fixed documentation build issues

Tribler/Core/Libtorrent/LibtorrentMgr.py
Fixed infohash logging for existing downloads.
Fixes https://github.com/Tribler/tribler/issues/4961
=> Fixed infohash logging for existing downloads

Tribler/community/gigachannel/community.py
Well, empty channels should not be gossiped around. This is the fix for the problem.
=> READY: Stop gossiping empty personal channels

Tribler/Core/Upgrade/db72_to_pony.py
Added logging to exceptions.
Exceptions are now `except Exception` instead of bare exceptions to prevent catching errors such as `SystemExit`. This prevents unexpected behavior.
Replaces #5011.
=> Log exceptions

Tribler/Core/Modules/restapi/downloads_endpoint.py, Tribler/util.py
~~Before a lambda was assigned to a variable. This made the whole point of lambdas being anonymous functions moot. Instead python 2 support was dropped, and the lambda was refractored to a function.~~
~~In addition instead of checking the type inside the function, single dispatch is used.~~
File held only a single lambda, and said lambda was a one-liner. In addition it was used only in one place. Hence the file the lambda was in was removed and the one-liner copied to the location it was used in.
Fixes #5022
=> READY: Remove lambda and file

src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py
Removed enumerate since the index value is no longer used. Closes #5061
=> READY: Remove enumerate

src/tribler-core/tribler_core/modules/libtorrent/download_config.py, src/tribler-core/tribler_core/modules/libtorrent/tests/test_libtorrent_mgr.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_metadata.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_node.py, src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py, src/tribler-core/tribler_core/upgrade/db72_to_pony.py, src/tribler-core/tribler_core/upgrade/tests/test_upgrader.py, src/tribler-core/tribler_core/upgrade/upgrade.py, src/tribler-core/tribler_core/utilities/install_dir.py, src/tribler-core/tribler_core/utilities/path_util.py
This PR basically provides a utility function called `str_path()` that creates path which addresses long path issue in windows by consistently passing the result obtained with `str_path()` instead of simply using Path or string in os/filesystem operations like `makedirs`, `unlink` etc.
=> Fixed long path issue in tests

src/tribler-core/run_market_helper.py, src/tribler-core/run_tribler_headless.py, src/tribler-core/run_tunnel_helper.py, src/tribler-core/tribler_core/config/test_tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.py, src/tribler-core/tribler_core/modules/libtorrent/download_config.py, src/tribler-core/tribler_core/modules/libtorrent/tests/test_downloadconfig.py, src/tribler-core/tribler_core/modules/tests/test_process_checker.py, src/tribler-core/tribler_core/modules/torrent_checker/test_torrentchecker_session.py, src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_base.py, src/tribler-core/tribler_core/restapi/tests/test_util.py, src/tribler-core/tribler_core/tests/tools/test_as_server.py, src/tribler-core/tribler_core/upgrade/config_converter.py, src/tribler-core/tribler_core/upgrade/tests/test_upgrader.py, src/tribler-core/tribler_core/upgrade/upgrade_base.py
Introducing `.Tribler` as root state directory to support multiple tribler version. Now each new version will have a separate state directory located inside `.Tribler` directory with the same name as the version.
=> Root state directory and version support

src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_download.py
The test works as it is. Sandip fixed it along with the other tests. This PR just enables it.
=> re-enable failing channel download test on Windows

src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py
This improves search results over multiple tries
=> Use random sampling of remote search peers

src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/metadata_node.py, src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_torrent_metadata.py, src/tribler-core/tribler_core/session.py
RemoteQuery Community's purpose is to serve remote DB queries for metadata stored by GigaChannel. The community remotely sends JSON-serialized arguments for get_entries method of MetadataNode ORM class. The receiving side processes the query and sends back the results. Eventually, this community should replace the first-generation GigaChannel Community, as RemoteQuery Communtiy is more general.
Note that this community does no actions on its own now. The plan is to first test it as a part of an experimental release and then add an aggressive walker that will be used to do fast bootstraps of Tribler Channels system as stated in #3615. Also, the current version imposes no limits on query size on the receiving side, which is fine for experiments but unacceptable for the final release.
=> GigaChannel RemoteQuery Community

src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_metadata.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/metadata_node.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_torrent_metadata.py
This enables RemoteQuery Community to query remotely for e.g. subscribed channels only, or for updates of some certain channel entry.
=> READY: Support querying by id_ and subscribed attributes

src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/vsids.py, src/tribler-core/tribler_core/modules/metadata_store/store.py
fixes #4927 
Channels ratings will now decay even when Tribler is offline, but this will happen (decay period is 3 days now instead of 1 day).
=> Make VSIDS decay offline

src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/sync_strategy.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_metadata.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/collection_node.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/metadata_node.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/torrent_metadata.py, src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-core/tribler_core/session.py, src/tribler-gui/tribler_gui/tribler_window.py
This adds a trigger for the introduction of new nodes in RemoteQueryCommunity. The idea is that on every introduction the community will query the remote host for its subscribed channels and update its local database accordingly.
Note that we add remote peers to a "queried" peers set in the community to prevent duplicate queries. The set is cleaned every 1000 entries. In the future, I would prefer a more elegant, Bloom filter-based solution. However, for the moment the auto-clearing set will do the job.
Also, we track the request manually so we only allow up to 10 packets back. This is another protection from spam. Note that there are no limits for query size on the answering side. This is intentional for testing purposes, and should be changed before rolling out a production release.
=> Query for channels on RemoteQueryCommunity introductions

src/tribler-gui/tribler_gui/tribler_window.py
The problem is that the feedback reporter sends reports as `None` version if the Tribler core had not indicated that it completed the startup sequence. This results in every crash during the startup sequence being reported with `None` version_id, which is really bad.
This quick hack fixes that problem. The proper solution of this problem would include sending the version_id by Core along with other crash-related data with each crash event **and** maintaining a separate GUI version_id.
Details in #5197
=> Fix reporter using None as version_id for some crashes

src/tribler-core/tribler_core/modules/credit_mining/credit_mining_manager.py, src/tribler-core/tribler_core/modules/libtorrent/tests/test_download.py
This fixes a broken (always positive) test. Also, it adds a complementary check for properly *saving* a checkpoint file.
=> Fix checkpoint save tests

src/tribler-core/tribler_core/__init__.py, src/tribler-gui/tribler_gui/__init__.py, tribler.spec
In a frozen environment, the path to `logger.yaml` is different than when running Tribler from source. We should check for this and adjust the path accordingly.
Fixes #5230
=> Fixed logger.yaml loading in frozen environments

src/tribler-core/tribler_core/session.py, src/tribler-core/tribler_core/tests/test_session.py
This includes the full `context` in the error report. Debugging complex asynchronous code is basically impossible without this.
=> Include full exception context in report

src/tribler-gui/tribler_gui/code_executor.py
This error would not send the stack trace back to the application tester.
This PR is critical for the application tester, as it will not reliably report stack traces otherwise.
=> Encoding stack trace before sending it

src/tribler-gui/tribler_gui/widgets/videoplayerpage.py
Fixes https://github.com/Tribler/tribler/issues/5237.
=> Stop videoplayer crash when clicking the slider with no video loaded

tribler.spec
Fixes https://github.com/Tribler/tribler/issues/5229.
I've only tested Windows 32/64 installers, as I don't have access to a Mac.
=> READY: Fix core not starting when running from binaries

src/tribler-core/tribler_core/modules/tunnel/community/dispatcher.py
It could be that the list of destinations is changed while we are iterating over it (e.g., when receiving SOCKS5 data from a circuit for the first time).
Fixes #5266
=> Converting destinations map to list before iterating over the items

doc/contributing.rst, src/tribler-gui/tribler_gui/qt_resources/mainwindow.ui, src/tribler-gui/tribler_gui/qt_resources/torrents_list.ui, src/tribler-gui/tribler_gui/tribler_window.py, src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py, src/tribler-gui/tribler_gui/widgets/lazytableview.py, src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
In this PR, I made the following changes:
- Made sure that the width of all tables in the GUI match the window width.
- Moved the 'new channel' and 'channel options' button to the right of the screen.
- Renamed 'Personal channel root' to 'My channels'.
- Removed unnecessary margin around the discovered channels table.
- Customized the `QComboBox` dropdown and the 'new channel' buttons.
- Renamed 'results' to 'items' (the label left to the filter).
I also updated the contribution guidelines to include the rule that screenshots have to be attached when making GUI changes.
=> Various minor GUI fixes

src/tribler-gui/tribler_gui/debug_window.py, src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py, src/tribler-gui/tribler_gui/tribler_request_manager.py
We did never set the status code after a request has been completed. Unfortunately, I cannot reuse the QNetworkRequest.reply attribute since that seems to be a different object that is not correctly updated after a request has been finished.
Fixes #5269
=> Fixed status code in debug pane

src/tribler-gui/tribler_gui/tribler_window.py
We forgot to indicate that the core manager is shutting down if Tribler closes for any reason besides an unhandled exception (e.g., when running low on disk space). This could result in an inconsistent state.
=> Fixed a bug during shutdown

src/tribler-gui/tribler_gui/dialogs/addtopersonalchanneldialog.py
This fixes AddToChannelDialog not shown in some cases, due to incorrect size.
=> Fix AddToChannelDialog not showing

src/tribler-core/run_market_helper.py, src/tribler-core/run_tribler_headless.py, src/tribler-core/run_tunnel_helper.py
This fixes `run_tribler_headless.py` and other "headless" scripts not reading the config and overwriting it with the default one.
=> Fix reading config in headless Core runner scripts

src/tribler-core/tribler_core/modules/libtorrent/download_manager.py
It could be that one of the accessed dictionary keys is missing. Tribler should not crash in this scenario.
Fixes #5276
=> Also catching KeyError when loading checkpoint

build/debian/tribler/DEBIAN/tribler.prerm, src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_hidden_services.py
This PR ensures that the content of the `/usr/share/tribler` directory is removed when Tribler is being uninstalled. Removal of this directory should be safe since no user-generated content is saved in `/usr/share/tribler`.
Please test out this PR to see if it does not break anything. I tested it on Ubuntu 18.04 and it seems to surpress the warning.
Fixes #5193
=> Remove content of tribler dir on dpkg uninstall

src/tribler-core/tribler_core/modules/metadata_store/restapi/metadata_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_metadata_endpoint.py, src/tribler-core/tribler_core/tests/tools/tracker/http_tracker.py, src/tribler-core/tribler_core/tests/tools/tracker/udp_tracker.py
This commit fixes the bug where torrentchecker endpoint sends a string
type timeout value to the TorrentChecker class,
If this variable is string then a suppressed error accours in each query
with the hidden trace below. This causes all torrenct health checks
requested from the endpoint to fail, since the argument is passed over
querystrings and query string arguments always are string types.
With this change timeout value is used when arguemnt is passed and a
number.
```
File "/home/boogie/src/tribler/src/tribler-core/tribler_core/modules/torrent_checker/torrentchecker_session.py",
line 137, in connect_to_tracker
async with
self._session.get(url.encode(\'ascii\').decode(\'utf-8\')) as response:
File "/home/boogie/.local/lib/python3.7/site-packages/aiohttp/client.py",
line 1012, in …
```
=> Fix torrent checker timeout value is sent from the rest endpoint as string 

src/tribler-gui/tribler_gui/tribler_window.py
When opening Tribler, the discovered menu button was unselected and could be selected again by users. This PR fixes that behaviour. The button is now checked when opening Tribler.
=> Fixed a GUI bug when opening Tribler

src/tribler-gui/tribler_gui/tribler_window.py
When clicking on a menu item in the left bar again, it resets the view. Note that this only happens if the user is already on the view, otherwise it does nothing.
=> Click on menu items again now resets the view

src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
When clicking the "Discovered" button, this makes the channel view drop the current filter/sorting mode which is expected intuitively.
=> Make Channels reset sorting/filtering

src/tribler-core/tribler_core/modules/libtorrent/download_manager.py, src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_torrentinfo_endpoint.py, src/tribler-core/tribler_core/modules/libtorrent/restapi/torrentinfo_endpoint.py, src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py
When unchecking :ballot_box_with_check:  "Download anonymously", trigger direct metainfo fetch, and vice-versa. Modify status label text accordingly to indicate in what mode the metainfo is being fetched currently.
Partially solves #4854
=> Load metainfo directly when unchecking 'anonymous' checkbox

src/tribler-core/tribler_core/logger.yaml, src/tribler-core/tribler_core/modules/libtorrent/download_manager.py, src/tribler-core/tribler_core/modules/libtorrent/tests/test_download_manager.py, src/tribler-core/tribler_core/modules/metadata_store/gigachannel_manager.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_metadata.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/collection_node.py, src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_gigachannel_manager.py
fixes #5295 by:
* fixing the root cause of the corruption as described in #5295 by moving delete entries to the last mdblobs in the committing sequence and assigning them necessary timestamps;
* enabling checks for personal channels torrents consistency, re-committing the damaged channels completely. Note that this happens some 10 seconds after the GUI starts and is not reflected in the GUI in any way. For owners of *really BIG* channels, Tribler could appear to become frozen. We will indicate this condition in the Readme (which is definitely read by owners of BIG channels).
=> Fix channel corruption by delete entries

src/tribler-core/tribler_core/modules/libtorrent/__init__.py, src/tribler-core/tribler_core/modules/libtorrent/download.py, src/tribler-core/tribler_core/modules/libtorrent/download_manager.py, src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py, src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_downloads_endpoint.py, src/tribler-core/tribler_core/modules/libtorrent/stream.py, src/tribler-core/tribler_core/modules/libtorrent/tests/test_stream.py, src/tribler-gui/tribler_gui/qt_resources/mainwindow.ui, src/tribler-gui/tribler_gui/qt_resources/video_info_popup.ui, src/tribler-gui/tribler_gui/tribler_window.py, src/tribler-gui/tribler_gui/widgets/downloadspage.py, src/tribler-gui/tribler_gui/widgets/videoplayerinfopopup.py, src/tribler-gui/tribler_gui/widgets/videoplayerpage.py
This is the initial working version of new streamer mentioned in 
https://github.com/Tribler/tribler/issues/5249
This is still an early version, there some log spams ui things to handle, but the core functionality should work.
Please igonre any linter, flake, or test cases issues at the moment, i will request a review when the work is finished.
Nevertheless you can still check it out how it works as of, and i have to admit i really liked the results :)
**stream.py** completely rewritten with new advanced methods with support
- A custom piece priority mehanism isntead of handle.set_sequential_download
- Concurrent Streaming
- Seeking (only with an external player, embedded vlc still does not support seeking to keep the existing behaviour)
- Stopping
- Pausing (adaptive buffering when the …
=> Streaming Improvements

src/tribler-core/tribler_core/session.py
A group of students is currently working to fix compatibility with `bitcoinlib`. Therefore, disabling the BTC wallet for the moment being.
Fixes #5367
=> Disable BTC wallet

src/tribler-gui/tribler_gui/debug_window.py, src/tribler-gui/tribler_gui/qt_resources/debugwindow.ui, src/tribler-gui/tribler_gui/widgets/ipv8health.py
This new tab shows how congested the main thread is, for debugging.
Disclaimer: could this have just been an overview of keys and values? Yes. In my defense, the average user will now also be able to visually spot when something is wrong with the core without any technical expertise.
=> Added IPv8 health monitor to debug window

src/tribler-gui/tribler_gui/tribler_window.py
This fixes an obscure bug on Mac, where the Tribler core would crash if VLC is loaded and instantiated before the subprocess is created. It should also speed up the overall Tribler startup since the VLC libs are now only loaded after Tribler has started.
Fixes #5420
=> Delaying video player initialization

src/tribler-core/tribler_core/modules/tests/test_tracker_manager.py, src/tribler-core/tribler_core/modules/torrent_checker/test_torrentchecker.py, src/tribler-core/tribler_core/modules/torrent_checker/torrent_checker.py, src/tribler-core/tribler_core/modules/tracker_manager.py
- Fixed a potential tracker check schedule on shutdown, fixes #5418. Also added a test for this.
- Made `check_random_tracker` return a boolean, indicating success or failure of the check. I added this since I noticed that we were not asserting anything in the torrent checker tests.
- Removed a unnecessary database fetch.
- Updated IPv8 pointer.
=> Minor torrent checker fixes

src/tribler-gui/tribler_gui/widgets/graphs/timeseriesplot.py
Fixes the loops and extra lines in the token balance graph.
Fixes #5255 
Related https://github.com/Tribler/tribler/issues/5119 but likely the underlying issue is different.
=> Fix token balance graph

tribler.spec
Workaround PyInstaller & SetupTools, 
https://github.com/pypa/setuptools/issues/1963
The current build is probably working because SetupTools is of version 44.0 or less. Incase this PR is merged, the builder will need to be updated and tested. I have tested locally building the deb package and running on Ubuntu 20.04 and it is working fine.
=> Workaround for latest SetupTools issue with PyInstaller

src/tribler-gui/tribler_gui/vlc.py
In Python 3.8, it is required to explicitly whitelist DLL directories. This PR ensures that the VLC libraries can be loaded.
I've tested the PR by making a win32 build and testing it on our deployment machines.
I also added the VLC plugins/codecs, and some other missing DLLs to the 32-bit builder. Fixes #5385
=> Fixed loading VLC libraries on Windows with Python 3.8

src/tribler-core/tribler_core/session.py
Since the Bootstrap module is relying on the DHTCommunity, we have to shut it down before IPv8.
=> Shutting down Bootstrap before IPv8

src/tribler-core/tribler_core/session.py
This makes debugging when running Tribler headless much easier.
=> Logging unhandled exceptions also in stdout

src/tribler-core/run_tunnel_helper.py
Tunnel helpers (relay and exit nodes) are more likely to create new blocks. I found that the current limit of 1 million blocks is somewhat on the lower side. Therefore, I'm increasing it.
=> Tunnel helpers now store more TrustChain blocks

src/tribler-core/tribler_core/modules/libtorrent/download_manager.py, src/tribler-core/tribler_core/modules/libtorrent/tests/test_download.py
When applying new libtorrent settings. This will help us to debug future OverflowErrors that occur, either because of a bug or a config modified by users.
I consider this enough to fix #5369 for the moment being. First, it only happened once on Windows 32-bit so it's not a severe issue. Second, this is most likely the result of users tampering with their configuration files since we have a built-in check whether the integers added in the settings screen are not overflowing. This PR will now help us to catch this kind of errors in the future, enabling us to make a call whether we should ignore it or fix it.
Fixes #5369
=> Added more info to OverflowError

build/debian/build-snap.sh
Add build parameters on snap build script so LXD can be used where multipass is not supported
=> Add build parameters on snap build script

src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py, src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py, src/tribler-gui/tribler_gui/tribler_window.py, src/tribler-gui/tribler_gui/widgets/settingspage.py
fixes #5470 by adding the redefined default download path to the list of the most recently used download dirs.
=> Add default download path to recently used dirs cache

src/tribler-gui/tribler_gui/tests/test_gui.py, src/tribler-gui/tribler_gui/widgets/videoplayerpage.py
We disabled VLC loading for the moment being, due to a crash when parsing media which can cause the Tribler GUI to freeze. See issue #5483 for more information.
=> Disable VLC library loading

src/tribler-core/tribler_core/config/test_tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.spec, src/tribler-core/tribler_core/session.py, src/tribler-gui/tribler_gui/tribler_app.py
For the application tester I would like to "mix and match" my testnet settings. For example, I want to download using exit nodes on the testnet but use the channels discovered in the chant mainnet. To do so, I split the testnet settings into multiple ones, which can be enabled separately. To fully enable the testnet, you can pass the --testnet flag to Tribler and all communities will automatically load the testnet version.
=> Split testnet settings into multiple ones

src/tribler-gui/tribler_gui/tests/conftest.py, src/tribler-gui/tribler_gui/tests/test_gui.py, src/tribler-gui/tribler_gui/tests/test_util.py
This PR ports the GUI tests so it's now using the `pytest` library as test executor. In addition to providing us better and more thorough debug output, this will address #5494.
I have tested the correctness of this PR in some personal jobs [on Mac](https://jenkins-ci.tribler.org/job/pers/job/pytest_gui_mac_devos50/) and [on Windows](https://jenkins-ci.tribler.org/job/pers/job/pytest_gui_win64_devos50/).
=> Ported the GUI tests to pytest

src/tribler-core/tribler_core/modules/libtorrent/download.py, src/tribler-core/tribler_core/modules/libtorrent/download_manager.py, src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py, src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_downloads_endpoint.py, src/tribler-core/tribler_core/modules/libtorrent/tests/test_download.py, src/tribler-core/tribler_core/modules/libtorrent/tests/test_download_manager.py, src/tribler-core/tribler_core/modules/libtorrent/torrentdef.py, src/tribler-core/tribler_core/restapi/rest_manager.py
This PR fixes the failing tests on Mac, where shutting down a libtorrent session takes considerably longer after the upgrade to libtorrent 1.2.7, triggering timeouts and causing deadlocks. This PR specifically modifies the download tests such that we are not starting a libtorrent session anymore. Instead, we mock a Download/DownloadState/TorrentDef where applicable. This should make these tests faster and more reliable. This PR will also pave the way for a potential migration to `pytest`.
Note that there are many more locations in the tests where we are unnecessarily starting a libtorrent session.
In addition, I made the following changes:
- Logging exceptions in the REST API to ease debugging.
- Created a `get_torrent` method in the `Download` class that returns a bdecoded torrent …
=> Not starting libtorrent session in download tests

src/tribler-core/tribler_core/modules/tests/test_versioncheck.py, src/tribler-core/tribler_core/modules/versioncheck_manager.py
With this PR, a new release URL (https://release.tribler.org) is added to the version check manager. Swagger docs for the currently available endpoints are available at /docs.
Fixes https://github.com/Tribler/tribler/issues/5523
=> Add release url in the version check manager

build/debian/makedist_debian.sh
Jenkins by default uses sh to run its scripts. However, sh does not have the source command, which is needed to enter a virtual environment. Therefore, I added a VENV option to the build script (on Linux).
=> Added a venv option when building Tribler

src/tribler-core/tribler_core/dependencies.py
It is better to not eat exceptions silently, as it can mask some problems.
=> READY: Should not eat exception silently

src/tribler-gui/tribler_gui/core_manager.py, src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py, src/tribler-gui/tribler_gui/tribler_request_manager.py, src/tribler-gui/tribler_gui/tribler_window.py, src/tribler-gui/tribler_gui/widgets/torrentdetailstabwidget.py
Beware!
Calls to PyQT signal callbacks **drop unexpected arguments**!
E.g.
```
s = Signal(int, int)
def foo(a):
print(a)
s.connect(foo)
s.emit(1,2)
```
will perfectly print `1` and just **ignore** the second argument :exploding_head: 
I should probably report it to PyQT list...
=> Move TriblerRequestManager error callback to a separate slot

src/tribler-gui/tribler_gui/qt_resources/mainwindow.ui, src/tribler-gui/tribler_gui/tribler_window.py, src/tribler-gui/tribler_gui/widgets/clickable_line_edit.py
Instead, one can click the top search bar to go to the screen with search results. This only works when a query is provided and there are search results already. This change cleans up the left menu.
Fixes #5559
=> Removed search results button from left menu

build/debian/makedist_debian.sh, src/tribler-core/tribler_core/dependencies.py
These commits are on `devel` already, but not in the `release-7.5` branch. The `VENV` option is required to build Tribler on our Ubuntu 18.04 machine and to fix #5533.
=> Added venv build option, fixed installation name of PIL in dependencies

src/tribler-core/tribler_core/modules/torrent_checker/test_torrentchecker.py, src/tribler-core/tribler_core/modules/torrent_checker/torrent_checker.py, src/tribler-core/tribler_core/session.py
- Fixes a bug on that popularity community was not receiving torrent checker instance because of which no popular torrents are shared in the community.
- Now the popularity community only shares alive torrents
=> Fix popularity community

src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py, src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_community.py
In this PR, I'm using the `flaky` library to mark a few tests as flaky. A test that is marked as flaky is automatically executed again, and won't fail the entire run if it succeeds on the second try. I marked the following tests in particular:
- The tunnel tests. At this point, we had so much trouble with these tests that I decided to mark them as flaky. Making these tests non-flaky seems close to impossible with so many moving parts and Tribler sessions.
-The mdblob squash tests. However, I still believe we should address #5392 and make this test non-flaky.
=> Marked a few tests as flaky

src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py, src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_community.py
[Due to a critical bug](https://github.com/box/flaky/issues/166), the flaky tool is not working with `pytest-asyncio`. Therefore, I'm removing the flaky marks again.
=> Revert flaky mark

src/tribler-core/tribler_core/config/test_tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.spec, src/tribler-core/tribler_core/modules/ipv8_health_monitor.py, src/tribler-core/tribler_core/modules/tests/test_ipv8_health_manager.py, src/tribler-core/tribler_core/session.py, src/tribler-gui/tribler_gui/widgets/ipv8health.py
Fixes #5384 
This PR addresses scaling back IPv8's bandwidth and CPU use while the main thread is congested. Concretely, this PR makes the following changes:
- Adds a configuration option for enabling IPv8 auto scaling (enabled by default).
- Adds a configuration option for the IPv8 `walk_interval`.
- Adds a configuration option for the upper limit the `walk_interval` may grow to, if scaling is enabled.
- Adds the `IPv8Monitor` class (and tests), to measure the main thread choking and scale the `walk_interval` accordingly.
- Adds the `IPv8Monitor` to the `Session` IPv8 initialization.
- Updates the IPv8 initialization in `Session` to use the new `ConfigBuilder`.
- Updates the IPv8 health debug screen to show the current target `walk_interval`.
- Updates the IPv8 pointer (fixes a bug where …
=> Added ipv8 walk_interval scaling

src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py, src/tribler-core/tribler_core/modules/tunnel/test_full_session/conftest.py, src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_community.py
In this PR, I've created a separate decorator for the tunnel tests. This allows us to run these tests in a dedicated run, hopefully  improving their stability and making it easier to debug (`pytest-xdist` eats logging output apparently). I also modified the Jenkins jobs to run the full tunnel tests in a separate command.
Also, I disabled the flaky mdblob squash tests since both `flake-rerunfailures` and `flaky` libraries do not play nicely with our libraries (specifically, `pytest-asyncio`/`pytest-timeout`). Related to #5392
=> Added tunneltests config option, disabled flaky tests

experiment/popularity_community/initial_filling/initial_filling.py, experiment/popularity_community/initial_filling/readme.md
Issue: https://github.com/Tribler/tribler/issues/5580
Raw result data from the last build: [result.csv](https://jenkins-ci.tribler.org/job/popularity_experiments/job/Initial_filling_velocity/lastSuccessfulBuild/artifact/result.csv/*view*/)
Build-to-build visualisation: [plot in Jenkins](https://jenkins-ci.tribler.org/job/popularity_experiments/job/Initial_filling_velocity/plot/)
Jenkins [job](https://jenkins-ci.tribler.org/job/popularity_experiments/job/Initial_filling_velocity/) is scheduled to run every day at 8:00.
[initial_filling.py](initial_filling.py)
This script calculate velocity of torrents list filling.
Given: the real network.
Action: 
* add a new node
* every `N` seconds check how long torrent's list are
Result will be stored in a csv file.
Example:
``` …
```
=> Experiment 1.1

src/tribler-core/tribler_core/modules/metadata_store/gigachannel_manager.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_gigachannel_manager.py
fixes #5602 
Well, it does not push the thing into a separate thread, but it fixes the problem nonetheless. If it appears again, I'll have to push it to a background thread \*sigh\*
=> Make channel regen into task

src/tribler.sh
PyQtGraph [prefers PyQt4](https://github.com/pyqtgraph/pyqtgraph/blob/0a8ad6b1aae733a2dbd5026b6b1011238aa75548/pyqtgraph/Qt.py#L29) when it and PyQt5 are installed side-by-side.
[This variable overrides](https://github.com/pyqtgraph/pyqtgraph/blob/0a8ad6b1aae733a2dbd5026b6b1011238aa75548/pyqtgraph/Qt.py#L22) that preference to PyQt5 as required by Tribler.
Resolves issue #5605.
=> Set PYQTGRAPH_QT_LIB="PyQt5"

src/README.md, src/requirements-test.txt
We have two environments: 
* Pure Tribler
* Test Tribler
Pure Tribler installs only necessary dependencies, they located in [src/requirements.txt](https://github.com/drew2a/tribler/blob/requirements-dev/src/requirements.txt).
But there is no documentation and no `requirements.txt` for the Test Tribler.
I've added [src/requirements-dev.txt](https://github.com/drew2a/tribler/blob/requirements-dev/src/requirements-dev.txt) and [small instruction](https://github.com/drew2a/tribler/blob/requirements-dev/src/README.md) on how to run tests.
Maybe `requirements-dev.txt` is a bad name, and better to use `requirements-test.txt`.
What do you think?
=> Add requirements-test.txt

src/tribler-gui/tribler_gui/utilities.py
Added solar year precision to download ETAs, and labelled downloads that will take over a century as “Forever.” 
Users won’t see these labels except under exceptionally poor network conditions, or for stalled transfers. The following screenshot is from a stalled transfer:
I didn’t add months (m) to avoid confusion with minutes (m). Although, maybe that’s not a problem when the m is displayed after a y or in front of a w?
=> Add years and “Forever” (1c+) ETAs

src/tribler-core/tribler_core/config/test_tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.spec, src/tribler-core/tribler_core/conftest.py, src/tribler-core/tribler_core/modules/ipv8_module_catalog.py, src/tribler-core/tribler_core/tests/test_session.py
By default, the launch of the DiscoveryCommunity is now disabled in the tests. Furthermore, this enables Gumby to also disable the DiscoveryCommunity, since Gumby usually starts isolated communities.
Fixes #5634
=> Added option to disable the discovery community

src/tribler-core/tribler_core/modules/ipv8_module_catalog.py, src/tribler-core/tribler_core/session.py
Fixes #5613
This allows Community loading/overwriting without subclassing the Session (or, god forbid, loading the Session first and then hooking in custom Communities after starting), example from #5613:
```python
session = Session(config)
session.ipv8_community_loader.community_launchers.clear()  # Remove all default launchers.
session.ipv8_community_loader.set_launcher(my_community_launcher)  # Load (or overwrite existing) custom launcher.
await session.start()
```
=> Moved CommunityLauncher registration to Session init

experiment/popularity_community/README.md, experiment/popularity_community/analyze_crawled_data.py, experiment/popularity_community/crawl_torrents.py, experiment/popularity_community/initial_filling.py
This PR contains:
1. Improvements for `crawl_torrents.py`:
1. Crawler speed has been improved
1. Console output informativeness has been increased
1. Added `select limit per request = 20` for preventing overloading
1. Small improvements for `initial_filling_velocity.py` 
1. `analyze_crawled_data.py`
It solves #5625 
Source: [analyze_crawled_data.py](https://github.com/drew2a/tribler/blob/experiment3/experiment/popularity_community/analyze_crawled_data.py)
This script analyzes the crawled data.
As an input, it takes `sqlite db`, produced by [crawl_torrents.py](https://github.com/drew2a/tribler/blob/experiment3/experiment/popularity_community/crawl_torrents.py).
The result will be stored in a `json` file:
```
[
{
"hash": "3f93ae6aabbba6d07176e778d9cbff088e9fbf1d",
"title": "Ubuntu", …
```
=> Experiment 3

src/tribler-core/tribler_core/modules/ipv8_module_catalog.py
This PR converts the `tribler_core/modules/ipv8_module_catalog.py` to the new `CommunityLauncher` decorator format, getting rid of 37% of the lines in the file.
Even the `RandomWalk` and `EdgeWalk` strategies are now lazy-loaded.
I recommend clicking [`View File`](https://github.com/Tribler/tribler/blob/ed42b5d469ea6e34243c03988d253f83b9c85823/src/tribler-core/tribler_core/modules/ipv8_module_catalog.py) to check out the finished product. The diff is slightly annoying to read.
=> Use new CommunityLauncher decorators

src/tribler-gui/tribler_gui/debug_window.py
Adds an entry in the Debug Pane's General tab showing whether or not the build supports BEP33.
=> Show BEP33 support indicator in the Debug Pane

src/tribler-core/tribler_core/modules/torrent_checker/test_torrentchecker.py, src/tribler-core/tribler_core/modules/torrent_checker/test_torrentchecker_session.py, src/tribler-core/tribler_core/modules/torrent_checker/torrent_checker.py, src/tribler-core/tribler_core/modules/torrent_checker/torrentchecker_session.py, src/tribler-core/tribler_core/modules/tunnel/community/dispatcher.py, src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py, src/tribler-core/tribler_core/modules/tunnel/socks5/aiohttp_connector.py, src/tribler-core/tribler_core/modules/tunnel/socks5/client.py, src/tribler-core/tribler_core/modules/tunnel/socks5/connection.py, src/tribler-core/tribler_core/modules/tunnel/socks5/conversion.py, src/tribler-core/tribler_core/modules/tunnel/socks5/tests/test_connection.py, src/tribler-core/tribler_core/modules/tunnel/socks5/tests/test_conversion.py, src/tribler-core/tribler_core/modules/tunnel/socks5/tests/test_server.py, src/tribler-core/tribler_core/modules/tunnel/socks5/tests/test_udp_connection.py, src/tribler-core/tribler_core/modules/tunnel/socks5/udp_connection.py, src/tribler-core/tribler_core/modules/tunnel/tests/test_dispatcher.py, src/tribler-core/tribler_core/utilities/tracker_utils.py
Fixes https://github.com/Tribler/tribler/issues/5262.
This PR:
* Updates `Dispatcher` to allow multiple simultaneous connections to the tunnel SOCKS server. To achieve this, circuits are reserved for a particular SOCKS session.
* Adds `Socks5Client` that can be used for connecting to our `Socks5Server`. Both TCP and UDP are supported.
* Adds `Socks5Connector` that allows anonymous HTTP connections to be established using `aiohttp`.
* Adds anonymization support to `TorrentChecker`. The `TorrentChecker` now uses the default hop count for all traffic.
* Updates SOCKS5 client/server to use the IPv8 serializer.
=> Added anonymization support to TorrentChecker

src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_community.py, src/tribler-core/tribler_core/restapi/tests/test_statistics_endpoint.py, src/tribler-core/tribler_core/restapi/tests/test_trustchain_endpoint.py, src/tribler-core/tribler_core/restapi/tests/test_trustview_endpoint.py
Modified the tunnel tests to not start a real IPv8 instance (we are starting a `MockIPv8` instance instead).
Fixes #5660
=> Fix tunnel tests shutdown

src/tribler-core/tribler_core/modules/ipv8_module_catalog.py
Fixes #5641.
This PR reorders the IPv8 modules' decorators as follows:
1. `@after`
2. `@precondition`
3. `@set_in_session`
4. `@overlay`
5. `@kwargs`
6. `@walk_strategy`
=> Reordered IPv8 module decorators

src/tribler-core/tribler_core/modules/popularity/popularity_community.py, src/tribler-core/tribler_core/modules/popularity/test_popularity_community.py
Resolves #5658 
New `PopularityCommunity` behavior: it gossips only healthy torrents. 
Here healthy means have `seeders>0`.
Note: gossiping is for checked torrents only.
##
Select torrent logic is isolated in `select_torrents_to_gossip` function:
```python
class PopularityCommunity(Community):
@staticmethod
def select_torrents_to_gossip(torrents):
alive = set((_, seeders, *rest) for (_, seeders, *rest) in torrents if seeders > 0)
count = PopularityCommunity.GOSSIP_POPULAR_TORRENT_COUNT
popular = set(heapq.nlargest(count, alive, key=lambda t: t[1]))
rest = alive - popular
count = min(PopularityCommunity.GOSSIP_RANDOM_TORRENT_COUNT, len(rest))
rand = set(random.sample(rest, count))
return popular, rand
```
##
As part of refactoring, `PopularityCommunity.process_torrents_health` has been …
=> Gossip only healthy torrents

src/tribler-core/run_tribler_headless.py, src/tribler-core/run_tunnel_helper.py
The `set_testnet` option got removed, and TrustChain is not used anymore.
=> Fixed tunnel helper script

src/tribler-gui/tribler_gui/widgets/trustpage.py
`total_up` and `total_down` have been replaced by `total_given` and `total_taken`, respectively.
=> Fixed bug when displaying trust statistics

src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py, src/tribler-core/tribler_core/tests/tools/test_as_server.py
I wrapped `on_remote_select` by try-except.
For now, it seems like the easiest and strongest way to solve the corresponding problem.
I've tested it locally, it works. If you have an idea on how to test this change by `pytest` — welcome to comments.
=> Fix RQC wrong query vulnerability

src/tribler-gui/tribler_gui/tests/test_gui.py
This PR adds a supplementary test to https://github.com/Tribler/tribler/pull/5695 to sufficiently address https://github.com/Tribler/tribler/issues/5670
=> Add test for multiple version checker popup

src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/sync_strategy.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_sync_strategy.py, src/tribler-core/tribler_core/session.py
Fixes #5699
Changes:
- Isolated the walking of the `RemoteQueryCommunity` in its own `Network` instance.
- Added a `RemovePeers` strategy to actively cycle peers in the `RemoteQueryCommunity`.
- Fixed the `SyncChannels` strategy only running when there are less than 20 peers.
=> READY: Isolated RemoteQueryCommunity

src/tribler-common/tribler_common/simpledefs.py, src/tribler-core/tribler_core/config/test_tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.py, src/tribler-core/tribler_core/restapi/tests/test_settings_endpoint.py, src/tribler-gui/tribler_gui/widgets/settingspage.py
This PR sets a max values for download and upload rate limit parameters. The maximum is set to `2^31 - 1` to avoid overflow error.
Fixes https://github.com/Tribler/tribler/issues/5680
=> Set libtorrent max upload/download rate limit

src/tribler-gui/tribler_gui/qt_resources/mainwindow.ui, src/tribler-gui/tribler_gui/tribler_window.py
This PR moves the :heavy_plus_sign:  download button to the left menu. Also, it makes the "Add torrent" menu to only be created once, as recommended by QT guidelines.
There are several reasons to move the button:
* the original position in the right top corner was too close to "Close X" button on some OSes and to "Settings" button. It was easy to misclick.
* the original button was too small and not intuitive, lacking a textual description.
* the position on the left menu follows the style of known services (e.g. Google Drive)
=> Move Download button to the left menu

src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_gigachannel_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py
Fixes #5683
NOTE: anything outside of TestBase will still hide these types of exceptions. This, for example, will still have a hidden error:
```python
def test_a_thing():
import asyncio
def this_is_bad():
raise Exception()
asyncio.get_event_loop().call_soon(this_is_bad)
```
This will not:
```python
class MyBeautifulTestCase(TestBase):
def test_a_thing(self):
import asyncio
def this_is_bad():
raise Exception()
asyncio.get_event_loop().call_soon(this_is_bad)
```
This PR uncovers and fixes two tests that were secretly failing:
```
FAILED src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_gigachannel_community.py::TestGigaChannelUnits::test_gigachannel_search
FAILED src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py::TestR …
```
=> READY: Updated IPv8 pointer

experiment/README.md, experiment/popularity_community/analyze_crawled_data.py, experiment/popularity_community/crawl_torrents.py, experiment/popularity_community/initial_filling.py, experiment/requirements.txt, experiment/tool/tiny_tribler_service.py
This PR fixes the following error in https://jenkins-ci.tribler.org/job/popularity_experiments/job/Initial_filling_velocity/86/console
```
AttributeError: 'TriblerConfig' object has no attribute 'set_market_community_enabled'
```
Also, it adds Sentry support to the following experiments:
1. Initial Filling Velocity
1. Popular Torrents Distribution
=> Fix AttributeError: 'TriblerConfig' object has no attribute 'set_market_community_enabled'

src/tribler-gui/tribler_gui/tribler_window.py
Call setWindowIcon() to get rid of the default icon...
Under debian/mate tribler has a default icon in the task panel, and it was bugging me. I have no experience on other platforms.
This is my first day on github, and I have not learned my way around tribler, yet. There is probably a better place to put this, but it works for me as is. It seems pretty safe. I stole the icon from the system tray code.
Fixes #5606
=> Update tribler_window.py call setWindowIcon

build/systemd/bandwidth-crawler.service, src/tribler-core/run_bandwidth_crawler.py, src/tribler-core/tribler_core/modules/bandwidth_accounting/community.py, src/tribler-core/tribler_core/modules/bandwidth_accounting/database.py, src/tribler-core/tribler_core/modules/bandwidth_accounting/payload.py, src/tribler-core/tribler_core/modules/bandwidth_accounting/settings.py, src/tribler-core/tribler_core/modules/bandwidth_accounting/transaction.py, src/tribler-core/tribler_core/modules/tests/bandwidth_accounting/test_community.py, src/tribler-core/tribler_core/modules/tests/bandwidth_accounting/test_database.py
This PR extends the bandwidth accounting mechanism with a basic query mechanism. Specifically, this PR:
- Adds a new query message.
- Adds a separate settings object where we can quickly change the different parameters of the mechanism. Right now, we do not know what the preferred values of many parameters are, e.g., the speed at which we send out queries. Deployment results will help us to answer this question but for now, I picked a value that I see reasonable.
- Adds functionality where the transactions of a random peer are periodically queried.
- Added a setting to store _all_ incoming transactions in the database, even when they belong to the same pair of users. This setting is used by our network crawler.
- Added a crawler and an accompanying `systemd` file.
We have verified whether …
=> Added basic query functionality to bandwidth accounting

src/tribler-core/tribler_core/modules/metadata_store/store.py
I spend some time profiling the database access code and noticed that the Tribler application spends most of the time inside `db_session` wrapped around the `process_payload` method of MetadataStore.
As it turns out, MetadataStore split objects into batches of very small size, and on my machine typical batch size was just two metadata objects.
MetadataStore determines batch size dynamically depending on the duration of the previous batch execution, but the calculation includes sleep time between batches as well, which skewed results.
I fixed the formula and also restricted the minimum and maximum batch size.
After the changes presented in this pull request, the rate of metadata objects insertion on my machine increased by 23%, from 60.63 objects/seconds to 74.84 objects/seconds for the …
=> Fix batch size handling during metadata during channel content upload

src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_node.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/torrent_metadata.py, src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py
This PR removes obsolete checks from `process_payload`. The changes result in 10x-20x speedup of channels processing for clients using DBs *created* by 7.5.x series (previous versions still use the obsolete index used by obsolete checks, so the speedup should be much less for those).
Also, we remove the unused public_key+id_+infohash unique index from DB and bump its version to `9`. Note we do not include the database upgrade procedure, because it will require rebuilding the whole DB. New DBs will be created without the index. The impact on old DBs should be negligible. This will be automatically solved by any other possible DB upgrade in the future.
=> Refactor channels payload processing

src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py
This commit fixes a defect introduced in https://github.com/Tribler/tribler/pull/5732, which prevents channels being voted more than one time.
=> Fix process payload return values

src/tribler-core/tribler_core/modules/ipv8_module_catalog.py
This was part of the fixes on `release-7.5`, but apparently it did not make its way into `devel`:
https://github.com/Tribler/tribler/blob/1c4335c98b9e7121ba0175b91879a2bd5f4b088b/src/tribler-core/tribler_core/session.py#L248
=> READY: Cherry-picked release-7.5 SyncChannels target_peers fix

src/tribler-core/tribler_core/modules/ipv8_module_catalog.py
You can now use `target_peers=INFINITE`, which is equivalent to `target_peers=-1`.
=> Added constant for infinite amount of walk strategy target peers

src/tribler-gui/tribler_gui/tribler_request_manager.py
This fixes compatibility with Python 3.9.
Fixes #5744
=> Removed encoding from json loads call

build/update_version_from_git.py, src/README.md, src/requirements.txt, src/run_tribler.py, src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py, src/tribler-common/tribler_common/sentry_reporter/sentry_scrubber.py, src/tribler-common/tribler_common/sentry_reporter/sentry_tools.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_reporter.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_scrubber.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_tools.py, src/tribler-core/tribler_core/restapi/events_endpoint.py, src/tribler-core/tribler_core/restapi/state_endpoint.py, src/tribler-core/tribler_core/restapi/tests/test_events_endpoint.py, src/tribler-core/tribler_core/restapi/tests/test_state_endpoint.py, src/tribler-core/tribler_core/session.py, src/tribler-core/tribler_core/version.py, src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py, src/tribler-gui/tribler_gui/event_request_manager.py, src/tribler-gui/tribler_gui/tribler_window.py
Resolves #5727
This PR adds Sentry support to Tribler Client.
The UX keeps unchanged.
The main concept: suppress (but store) all Sentry events until a user clicked on the "send report" button.
There are two new entities:
1. `SentryReporter`(singleton) for managing work with Sentry
1. `SentryScrubber` for scrubbing sensitive and redundant information.
Basically, Sentry-based reporting works the same way the old Reporter did:
* catch the error in the Core (or in the GUI)
* send it to the GUI over the Events endpoint (GUI errors are handled directly)
* present the "report error" dialog to the user
* send the report when the user clicks the "send report" button
A user will now be assigned a unique pseudonym (e.g.Jonh Doe) based on the `hash` of their `public_key`.
Note. The current …
=> Add sentry

pyproject.toml, src/tribler-core/tribler_core/modules/ipv8_module_catalog.py, src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_gigachannel_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_metadata.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_node.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/metadata_node.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/remote_query_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_remote_query_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_torrent_metadata.py, src/tribler-core/tribler_core/modules/popularity/popularity_community.py, src/tribler-core/tribler_core/modules/popularity/test_popularity_community.py, src/tribler-core/tribler_core/modules/tests/test_ipv8_module_catalog.py, src/tribler-core/tribler_core/session.py, src/tribler-core/tribler_core/tests/test_session.py, src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
EDITED: 24.11.20
This PR refactors RemoteQueryCommunity into a base class that is now inherited by PopularityCommunity and GigaChannelCommunity. The class enables rich communication via the RQC protocol, e.g. allowing PopC to query back the sender of popularity gossip for metadata of unknown infohashes.
In addition, whenever RQC receives a previously unknown Channel entry, it will query the sender for four entries from it. This guarantees that at least some preview content will be available for any channel.
To circumvent the problem of no new content for new clients, as suggested by @egbertbouman,  I added `extra_bytes` field to the renewed introduction request. This allows the new version to distinguish its folk from the previous versions and do not send them requests that will crash …
=> READY: Enable RemoteQueryCommunity to query channel senders for preview content

src/tribler-core/tribler_core/modules/popularity/popularity_community.py
Resolves https://github.com/Tribler/tribler/issues/5642
Fortunately, all the work has been done by @ichorid in https://github.com/Tribler/tribler/pull/5736
In this PR I just removed the obsolete `enable_resolve_unknown_torrents_feature` flag.
=> Remove enable_resolve_unknown_torrents_feature

src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py, src/tribler-core/tribler_core/session.py
Fixes #5748
The new IPv8 should only be launched in IPv4 mode, or it will crash Tribler 😃 
Thanks to @egbertbouman for helping with inserting DHT test data.
=> Launch IPv8 with an IPv4 UDP endpoint only

src/tribler-core/tribler_core/modules/ipv8_module_catalog.py, src/tribler-core/tribler_core/modules/tests/test_ipv8_module_catalog.py
This PR replaces some strings from `ipv8_module_catalog.py` which represents `Class.__module__` and `Class.__name__` by corresponding special attributes.
It makes navigation in IDE easy and will save us from changing them manually in case of class names changes or location changes.
What do you think?
=> ipv8 module catalog refactoring

src/run_tribler.py, src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py
Two changes:
1. `excepthook` has been removed
1. The SentryReporter function call has been fixed.
Description of 2:
While refactoring, the one file has not been affected.
It causes the sending report to fail.
=> Fix Reporter

src/run_tribler.py, src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_reporter.py, src/tribler-core/tribler_core/session.py, src/tribler-gui/tribler_gui/tribler_window.py
This PR restores https://github.com/Tribler/tribler/pull/5747 by capturing all unhandled exceptions with mandatory confirmation before sending.
https://github.com/Tribler/tribler/pull/5747 handles all types of exceptions, which caused false reports. Because of that, it has been temporarily disabled.
Сapturing all unhandled exceptions with mandatory confirmation before sending has been added.
Now Sentry can operate in three modes:
1. Send reports are allowed
1. Send reports are allowed with a confirmation dialog
1. Send reports are suppressed (disallowed, but the last event will be stored)
By default, it works in the second mode.
Exception filtering for unhandled exceptions has been added as well: 
```python
ignored_exceptions = [KeyboardInterrupt, SystemExit]
```
=> Add unhandled exceptions catching 

src/tribler-core/tribler_core/modules/bandwidth_accounting/database.py, src/tribler-core/tribler_core/modules/tests/bandwidth_accounting/test_database.py, src/tribler-core/tribler_core/modules/trust_calculation/trust_graph.py, src/tribler-core/tribler_core/restapi/tests/test_trustview_endpoint.py, src/tribler-core/tribler_core/restapi/trustview_endpoint.py, src/tribler-gui/tribler_gui/widgets/trustgraphpage.py
Fixes https://github.com/Tribler/tribler/issues/5675
This PR updates the Trust graph previously based on Trustchain blocks to use new bandwidth accounting transaction blocks.
Major changes
- The graph only compose two layers, layer 1 (friends), layer 2 (friend of friends)
- GUI and REST API removes the depth parameter
- Auto refreshing on the GUI is removed
- Test fixes
=> Fix trust graph

.pre-commit-config.yaml, src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-core/tribler_core/session.py, src/tribler-core/tribler_core/upgrade/db8_to_db10.py, src/tribler-core/tribler_core/upgrade/tests/test_upgrader.py, src/tribler-core/tribler_core/upgrade/upgrade.py, src/tribler-core/tribler_core/upgrade/version_manager.py, src/tribler-core/tribler_core/version.py, src/tribler-gui/tribler_gui/core_manager.py, src/tribler-gui/tribler_gui/event_request_manager.py, src/tribler-gui/tribler_gui/tribler_window.py, src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py, src/tribler-gui/tribler_gui/widgets/loadingpage.py
The upgrade procedure creates a temporary Channels DB and directly dumps the old Channels tables into the corresponding tables in the new DB.
If the upgrade finishes correctly, the new DB replaces the old one.
If the upgrade is skipped by the user, the old DB is removed
If the upgrade crashes, at the next Tribler startup it will be tried anew.
The main reason to upgrade is the removal of unused unique indexes that mess up the new DB logic. Unfortunately, it is impossible to remove them without recreating the whole database.
5 GB database converts in 5 minutes on my PC.
=> Add upgrade procedure for Channels DB v8 to v10

src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-core/tribler_core/upgrade/db8_to_db10.py, src/tribler-core/tribler_core/upgrade/upgrade.py
In this PR I delay the creation of usual indexes and FTS index until all data are loaded to the database. This lead to about 4x speed improvement of the upgrade process.
=> Improve upgrade speed by creating indexes at separate stage

build/update_version_from_git.py, src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py
This PR contains two changes:
1. Disallowing sentry to send events while logging an error
1. Allow `update_version_from_git.py` has an empty SENTRY_URL
These changes were requested during the release testing.
=> Sentry fixes for release

src/tribler-core/tribler_core/session.py
I've changed the line of `SentryReporter.capture_exception` call to keep log output clean.
Related to https://github.com/Tribler/tribler/issues/4880#issuecomment-737187275
=> Change capture_exception call order

src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_reporter.py, src/tribler-core/tribler_core/session.py, src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py, src/tribler-gui/tribler_gui/tribler_window.py
Additions:
1. Method `SentryReporter.event_from_exception(exception)` has been added.
Changes:
1. `unhandled_error_observer` from session.py now use `SentryReporter.event_from_exception(exception)`. This is more straightforward than was before
1. `unhandled_error_observer`'s own exceptions now captured
1. GUI exception handler for sentry has been restored
=> Refactoring SentryReporter

src/tribler-core/tribler_core/modules/libtorrent/download.py
In LibTorrent auto_managed flag is now on by default, and as a result, any torrent's state can change from Stopped to Downloading at any time. Here I unset this flag to prevent auto-resuming of stopped torrents.
=> Fixes #5762: unset 'auto_managed' flag to prevent torrents resuming automatically

src/tribler-gui/tribler_gui/tribler_window.py
This PR hides the token balance from the GUI, at least until 7.6.1 has been released.
=> Hide token balance

src/tribler-core/tribler_core/upgrade/config_converter.py, src/tribler-core/tribler_core/upgrade/tests/test_config_upgrade_to_74.py, src/tribler-core/tribler_core/upgrade/tests/test_config_upgrade_to_75.py
In this PR parse error if happens during the conversion, the error is caught and the faulty config is removed so the conversion can continue. There are only a few reports of the issue and we don't know the actual cause of the issue, neither we can reproduce yet. So, this is only a temporary fix.
Related issue: https://github.com/Tribler/tribler/issues/5778
=> Catch ParseError on config conversion

src/tribler-gui/tribler_gui/widgets/downloadspage.py
Fixes #5754 (again 😃). See issue for steps to reproduce.
This is the conclusion of running through **every single instance of using `TriblerNetworkRequest` manually**. Now there should be absolutely nothing left.
=> Fixed move file callback function

src/tribler-core/tribler_core/modules/torrent_checker/torrentchecker_session.py, src/tribler-core/tribler_core/tests/test_utilities.py, src/tribler-core/tribler_core/utilities/tracker_utils.py
The `add_url_params()` function has been in the IPv8 deprecated folder for over 2 years and is finally about to be removed. It is time to adopt this in the Tribler codebase to allow IPv8 pointer updates.
=> Migrate add_url_params over from IPv8

.pre-commit-config.yaml
On Mac pre-commit flake8 hook currently gives an error when running on Python 3.8 or later:
```
multiprocessing.pool.RemoteTraceback: 
"""
File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/Users/kozlovsky/.cache/pre-commit/repogu4fw2mp/py_env-python3.8/lib/python3.8/site-packages/flake8/checker.py", line 677, in _run_checks
return checker.run_checks()
File "/Users/kozlovsky/.cache/pre-commit/repogu4fw2mp/py_env-python3.8/lib/python3.8/site-packages/flake8/checker.py", line 616, in run_checks
self.run_ast_checks()
File "/Users/kozlovsky/.cache/pre-commit/repogu4fw2mp/py_env-python3.8/lib/python3.8/site-packages/flake8/checker.py", …
```
=> Fix broken pre-commit on Mac

src/tribler-core/tribler_core/config/tribler_config.py
This PR fixes #5831 by adding the argument `exist_ok=True` to  `os.makedirs` call.
It is not obvious how this code could produce "FileExistsError":
```python
if not self.get_state_dir().exists():
os.makedirs(self.get_state_dir())
```
But adding `exist_ok=True` solves the issue and looks safe.
=> Add to makedirs the argument `exist_ok=True`

src/tribler-core/tribler_core/dependencies.py
Fixes #5832 by adding try-except block.
Fix uses broad exception handling as a savest way to catch all exceptions. 
It can't cause any harm in an unobvious way, to further Tribler's execution, because, at the step, when the dependency message box is shown, Tribler stops his work.
=> Add try-except block to dependency message box

src/tribler-gui/tribler_gui/event_request_manager.py, src/tribler-gui/tribler_gui/tribler_window.py
This PR fixes #5845 by rolling back to the old version "Tribler starts on event mechanism".
I don't like this version, because it looks like a tricky way to solve some unknown problem.
Probably we can spend some time on "unwinding the clew of Tribler's starting logic" in the future.
=> Rollback to "Tribler starts on events start received" logic

experiment/popularity_community/initial_filling.py
This PR fixes #5849
This is the change that broke initial filling velocity experiment:
https://github.com/Tribler/tribler/pull/5736/files#diff-3b8a863c5e5d3d8d32101a33bbc9606b6c237d8eb9af4fc16e9d5b9d96d46fd6L33
=> Use mds instead of metadata_store

src/run_tribler.py, src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py, src/tribler-common/tribler_common/sentry_reporter/sentry_scrubber.py, src/tribler-common/tribler_common/sentry_reporter/sentry_tools.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_reporter.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_tools.py
This PR enables [the Sentry release](https://docs.sentry.io/product/releases/) feature for Tribler.
All versions that contain 'GIT' will be recognized as 'dev-versions' and skipped by Sentry.
=> Add release for Sentry

src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py, src/tribler-core/tribler_core/modules/tunnel/tests/test_triblertunnel_community.py
When a relay initiates a payout to the next hop in the circuit, the values were computed incorrectly. This PR fixes the behaviour and extends the payout tests to capture such bugs.
At this point, the damage is already done but we should at least fix it to reduce the impact of this bug.
Fixes #5789
=> Fixed bug in relay payouts

src/tribler-core/tribler_core/modules/torrent_checker/test_torrentchecker.py, src/tribler-core/tribler_core/modules/torrent_checker/torrent_checker.py
To improve the sharing of the popular torrents via popularity community, this PR adds local popular torrents in the list to be checked periodically and be eventually shared via the community. 
Note, no changes in the popularity community is needed (yet) to include popular torrents for sharing. It is because the community only makes use of `torrents_checked` set which is updated when torrent health check is processed.
This will follow another PR to store the information about who did the torrent check so the recent torrent checks data can be reused to populate the popularity community message.
=> Add popular torrents in torrent checker periodic loop

src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py
Tribler common is required by the core where it is best not to include PyQt dependency. I had an issue finding & resolving all required dependencies of PyQt5 while running in headless mode.
=> Convert PyQt5 to local import in tribler common

src/tribler-core/tribler_core/modules/trust_calculation/trust_graph.py, src/tribler-core/tribler_core/restapi/tests/test_trustview_endpoint.py, src/tribler-core/tribler_core/restapi/trustview_endpoint.py, src/tribler-gui/tribler_gui/widgets/trustgraphpage.py
- It fixes the crash on clicking a node in the Trust graph. The issue was because of reorganization of the arguments in pyqtsignal. The list of items where user clicked was splited to a single top point and a list of rest points. (Qt signal is magic).
Fixes https://github.com/Tribler/tribler/issues/5858
- It fixes the crash occurring when there are nodes more than the max value. There was a test for that but the failure was suppressed as failure. The removal inheritance of unnecessary `TaskManager` fixes that apparently. Additionally, added separate tests for max nodes and max transactions.
- The query parameter was removed in the last refactor. It is fixed now. A test is added as well. The refresh from the GUI should work nicely now.
- Increased the size of nodes slightly.
**Screenshot**
=> Fix trust graph node click and max node issue

src/run_tribler.py, src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_reporter.py, src/tribler-core/tribler_core/config/test_tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.spec
Partially resolves #5799 by adding an option to send unhandled exceptions automatically.
To enable or disable this option you need to change "tribler.conf":
```
[error_handling]
error_reporting_requires_user_consent=boolean(default=True)
```
It is turn on or turn off mechanism for sending unhandled exceptions **only**. 
Ordinary crash reports will not be affected.
This change has entailed SentryReporter refactoring:
* `this_sentry_strategy` context manager has been extracted 
* ContextVar's strategy has been extended by global strategy
=> Add an option to automatically send exceptions

src/tribler-core/tribler_core/modules/metadata_store/community/discovery_booster.py, src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_discovery_booster.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_gigachannel_community.py
This PR resolves #5828 
At a startup, a user will be "bombarded with newly discovered channels" for 30 seconds.
The new channels' appearance speed: 1-3 channels per second.
The user will receive only "subscribed" channels to prevent "propagation of junk" (@ichorid)
This code will be invoked on each run.
=> Fast channel discovery

src/tribler-core/tribler_core/restapi/events_endpoint.py, src/tribler-core/tribler_core/restapi/tests/test_events_endpoint.py, src/tribler-core/tribler_core/session.py, src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py, src/tribler-gui/tribler_gui/event_request_manager.py, src/tribler-gui/tribler_gui/tribler_window.py
This PR partially resolves #5799, #5857 by extending https://github.com/Tribler/tribler/pull/5870
Now, setting `error_reporting_requires_user_consent` covers all "core" errors. It will not be used by a regular Tribler user and will set to 'True' by default:
```
[error_handling]
error_reporting_requires_user_consent=boolean(default=True)
```
Note: this value does not affect errors that occurred in GUI.
=> Apply `error_reporting_requires_user_consent` to all core's errors

src/run_tribler.py
This PR is referred to #5857 
It adds an option to run a Tribler client in test mode and send all the crash reports automatically.
To enable it you have to specify TEST_SENTRY_URL:
```bash
export TEST_SENTRY_URL=<some_url>
```
And enable crash reports auto-send in "triblerd.conf":
```
[error_handling]
error_reporting_requires_user_consent=False
```
=> Add an option to run Tribler with sentry URL for tests

src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/metadata_node.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_channels_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_torrent_metadata.py
This PR fixes a problem when folders are not displayed in the channel content view after sorting by "health".
The essence of the fix is in replacing INNER JOIN to LEFT JOIN in SQL query, so ChannelNode objects without TorrentState corresponding objects are still returned by the query. 
Also, in this PR I add default ordering by `rowid` to all queries which return ChannelNode objects, to have guaranteed stable sorting order in tests.
Some tests are marked with FIXME as they are not returning totally correct results. Namely, full-text search queries don't return more than one folder. This is a separate bug in full-text search queries and will be fixed in a separate PR.
=> Fix sorting search result by health

src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/metadata_node.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py
This PR fixes a bug in full-text search queries where FTS query could not return more than one object without infohash (for example, no more than one folder in a channel).
=> Fix full-text search query

src/tribler-core/tribler_core/upgrade/tests/test_config_upgrade_to_75.py
Sometimes we see this error in window's tests console output:
```
_________________________ test_download_load_corrupt __________________________
[gw6] win32 -- Python 3.8.4 c:\users\tribler\appdata\local\programs\python\python38\python.exe
download_config = <tribler_core.modules.libtorrent.download_config.DownloadConfig object at 0x00000000294F2A90>
def test_download_load_corrupt(download_config):
with pytest.raises(ConfigObjError):
>           download_config.load(CONFIG_FILES_DIR / "corrupt_download_config.conf")
E           TypeError: load() takes from 0 to 1 positional arguments but 2 were given
```
The example: https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_win64_pytest/793/console
This fixture overrides `DownloadConfig.load` method: …
=> Change mocked config to corrupted source file

src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/metadata_node.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py
This PR sorts full-text search results by default in the following order:
1. Channels
2. Folders
3. Torrents with seeders
4. Other torrents
=> Fixes #5887: fix default search order for FTS queries

src/tribler-gui/tribler_gui/widgets/downloadspage.py
Partially fixes #5886 
The progress will only be updated when the user clicks on the "Downloads" tab,, at the background downloads polling interval (about 15 seconds), and on special events, e.g. torrent completion.
=> Update torrent progress in channels on download table polls

src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py
This PR resolves #5843
The cause of the bug very close to https://github.com/Tribler/tribler/pull/5888
=> Return from "on_received_metainfo" if the dialog closed

src/run_tribler.py, src/tribler-core/tribler_core/config/test_tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.spec, src/tribler-core/tribler_core/session.py, src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py
This PR adds an ability to send handled exceptions to the reporter automatically in case `TEST_SENTRY_URL` is defined.
Requested by @xoriole for using in 24/7 Tribler instance tester.
=> Add ability to send exceptions automatically in case `TEST_SENTRY_URL` is defined

src/tribler-gui/tribler_gui/tribler_window.py
Fixes #5898 Issue with handling of pyqtsignal on low storage
The original issue was that the signal handler was receiving an object with storage info which was not handled and that was crashing Tribler under low storage condition. 
The fix seemed like a single line by fixing the argument parameter but it uncovered another issue that Tribler was not closing on clicking the popup button. This PR fixes that by terminating the leftover Qt GUI separately on dialog close callback.
=> Fix pyqtsignal handling on low storage

src/tribler-gui/tribler_gui/widgets/downloadsdetailstabwidget.py
This PR fixes #5901 by changing signatures of
```python
def on_files_included(self, *args):
```
```python
def on_files_excluded(self, *args):
```
Because they are called with a Boolean argument.
=> Change on_files_included/excluded signature

src/tribler-gui/tribler_gui/tests/test_util.py, src/tribler-gui/tribler_gui/utilities.py, src/tribler-gui/tribler_gui/widgets/triblertablecontrollers.py
This PR resolves #5909 by adding a check on the existing of `infohash` key.
The root cause of the issue is too general an inaccurate design of `ContentTableViewController`.
My proposal: to schedule a refactoring for `ContentTableViewController`.
=> Add check on infohash key existing

src/tribler-gui/tribler_gui/dialogs/confirmationdialog.py
This PR resolves #5915 by adding a check for the presence of the 'escape_pressed' attribute.
Fixes TRIBLER-5Z
Fixes SENTRY-FOR-760-21
=> Check on 'escape_pressed' attribute

src/tribler-common/tribler_common/sentry_reporter/sentry_scrubber.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_scrubber.py
This PR adds  the following improvements to the Sentry Scrubber:
1. Allows an event to have multiple user names (Eg: `user_name`, and `USERNAM~1`)
2. `C:\Users` folder as a pattern to recognize the user name
3. Explicit sensitive information detection for OS vars: 
* `USERNAME: <user_name>`
* `USERDOMAIN: <user_domain>`
4. Detects user names that contain spaces
The example of a partial scrubbed event: https://sentry.tribler.org/organizations/tribler/issues/400
=> Improve scrubber

src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py, src/tribler-gui/tribler_gui/qt_resources/feedback_dialog.ui
This PR starts to solve https://github.com/Tribler/tribler/discussions/5938 by changing the meaning of additional information, provided by a user.
Instead of asking "comment", we explicitly ask "what were you doing before this crash happened?"
=> Replace "comments" field by "what were you doing before" question.

tribler.spec
Pyinstaller build is missing Pillow dependency so here the dependency is added as hidden imports. 
Fixes https://github.com/Tribler/tribler/issues/5943
=> Fix Pillow missing dependency

src/tribler-common/tribler_common/sentry_reporter/sentry_scrubber.py, src/tribler-common/tribler_common/sentry_reporter/sentry_tools.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_tools.py
This PR fixes the issue of unnecessary multiplication of "release version" during a deployment test:
https://sentry.tribler.org/organizations/tribler/releases/?project=7
=> Skip all the versions produced by the deployment tester

doc/development_methodology.rst
This PR updates the document that describes a release cycle.
The goal: to clarify a process. 
Linked to the last dev discussion.
=> Update info about release cycle

src/tribler-gui/tribler_gui/widgets/downloadspage.py
Fixes #5934 
The moral of the story: if you connect a QT signal to a QT object, don't expect it to be GCed in PyQT until you disconnect the signal manually (or better yet, just reuse the object).
=> Fix memory leak in Downloads page

src/tribler-gui/tribler_gui/core_manager.py, src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py, src/tribler-gui/tribler_gui/error_handler.py, src/tribler-gui/tribler_gui/event_request_manager.py, src/tribler-gui/tribler_gui/tribler_window.py
This PR addresses _problem1_ from https://github.com/Tribler/tribler/discussions/5938 and starts to solve it.
In this PR refactoring was made to explicitly split GUI errors and Core errors.
* In the case of Core errors, we always kill the application.
* In the case of GUI errors, we only kill the application when `CoreConnectTimeoutError` will occur.
Tribler will report only the first occurred GUI exception (filtered by Type).
Repetitive exceptions will be ignored.
=> Stop crash an application when GUI raise an exception

src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py
This PR implements the current Sentry Scrubber all values presented in Feedback Dialog to explicitly let users know that no personal information will be sent.
Linked to https://github.com/Tribler/tribler/issues/5952
=> Scrub values in Feedback Dialog

src/requirements.txt, src/tribler-core/tribler_core/modules/resource_monitor/core.py, src/tribler-core/tribler_core/modules/resource_monitor/profiler.py, src/tribler-core/tribler_core/modules/tests/test_resource_monitor.py, src/tribler-core/tribler_core/restapi/debug_endpoint.py, src/tribler-core/tribler_core/restapi/tests/test_debug_endpoint.py, src/tribler-gui/tribler_gui/debug_window.py
Fixes system/profiler in the Debug Pane. Also, makes Yappi a pip dependency so availability need not be checked anymore since it should be bundled by PyInstaller.
=> Fix profiler functionality of the Debug Pane

src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py
This PR set DiscoveryBooster timeout to 30 seconds as it was described in https://github.com/Tribler/tribler/issues/5828
=> Specify timeout for the DiscoveryBooster

src/tribler-core/tribler_core/modules/metadata_store/community/discovery_booster.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_discovery_booster.py
This PR removes the `max_peers` argument from `DiscoveryBooster` because it has no effect on discovery boosting.
Linked to the dev morning meeting.
=> Remove max_peers from DiscoveryBooster

src/tribler-core/tribler_core/modules/ipv8_module_catalog.py, src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py, src/tribler-gui/tribler_gui/debug_window.py
Note that this needs to go to devel since we didn't want to move the IPv8 pointer too far (https://github.com/Tribler/tribler/pull/5955#issuecomment-768202925)
=> Remove hard-coded peer limits from DebugWindow

src/tribler-core/tribler_core/check_os.py, src/tribler-core/tribler_core/tests/test_osutils.py
This PR linked with #5547 and fixes an issue with the "killing Tribler on restart" mechanism.
The problem was in keywords. They can't handle processes named "Python".
=> Fix kill Tribler on restart mechanism

src/tribler-gui/tribler_gui/single_application.py
This PR replaced the abstract invocation of `logfunc()` to explicit invocation of `self.logger.info()`.
Also, it removes some unnecessary logging.
It will change logs outputs from:
```
[PID:18411] 2021-02-10 16:20:13,900- INFO - TriblerApplication(23) - Start Tribler application. Win id: "triblerapp". Sys argv: "['/Users/<user>/Projects/github.com/Tribler/tribler/src/run_tribler.py']"
[PID:18411] 2021-02-10 16:20:13,906 - INFO - root(29) - __init__()
[PID:18411] 2021-02-10 16:20:13,998 - INFO - root(55) -   self._outSocket.error() = '2'
[PID:18411] 2021-02-10 16:20:14,373 - INFO - root(65) - __init__(): returning
```
to:
```
[PID:18868] 2021-02-10 16:34:07,740 - INFO - TriblerApplication(23) - Start Tribler application. Win id: "triblerapp". Sys argv: …
```
=> Replace logfunc() by self.logger.info()

src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_reporter.py, src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py, src/tribler-gui/tribler_gui/error_handler.py
This PR adds a `source` tag for the "core" and "GUI" errors.
Also, a refactoring for `SentryReporter` tests has been made. 
An example of a sentry report: https://sentry.tribler.org/organizations/tribler/issues/524/?project=3&query=is%3Aunresolved
=> Sentry: additional tags

README.rst, build/debian/snap/snapcraft.yaml, doc/contributing.rst, doc/development_methodology.rst, doc/trustchain.rst
This PR updates documentation regarding "devel"->"main" renaming.
Closes https://github.com/Tribler/tribler/issues/5569
=> Replace "devel" by "main"

src/tribler-core/tribler_core/modules/dht_health_manager.py, src/tribler-core/tribler_core/modules/libtorrent/download.py, src/tribler-core/tribler_core/modules/libtorrent/download_config.py, src/tribler-core/tribler_core/modules/libtorrent/download_manager.py, src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py, src/tribler-core/tribler_core/modules/libtorrent/restapi/torrentinfo_endpoint.py, src/tribler-core/tribler_core/modules/libtorrent/torrentdef.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_metadata.py, src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py, src/tribler-core/tribler_core/upgrade/config_converter.py, src/tribler-core/tribler_core/utilities/bencodecheck.py, src/tribler-core/tribler_core/utilities/libtorrent_helper.py, src/tribler-core/tribler_core/utilities/tests/test_bencodecheck.py, src/tribler-core/tribler_core/utilities/torrent_utils.py, src/tribler-core/tribler_core/utilities/utilities.py
This PR allows running the `run_tunnel_helper.py` script without libtorrent installing.
Currently, many modules import `libtorrent` even if it is not necessary. `run_tunnel_helper.py` script even [sets `libtorrent_enabled` option to `False`](https://github.com/Tribler/tribler/blob/devel/src/tribler-core/run_tunnel_helper.py#L124), but still imports `libtorrent` library. As installing libtorrent from sources may be a non-trivial task, it is better to allow running `run_tunnel_helper.py` without `libtorrent` installed.
This PR does two things:
1. Refactor imports to import libtorrent not directly, but from `tribler_core.utils.libtorrent_helper`. When `libtorrent` is not installed, the `libtorrent_helper` module returns a fallback object instead, which raises `ImportError` on any attempt to …
=> Allow exitnodes to run without libtorrent installed

README.rst, doc/trustchain.rst
This PR fixes #6007 by replacing all "main" occurrences for readthedocs links.
=> Replace "main" by "latest" for all readthedocs.io links

src/tribler-gui/tribler_gui/widgets/downloadspage.py
Fix channel processing progress bar incorrectly updating to 100% from the corresponding download.
=> Fix incorrectly updating channel progress from downloads

src/tribler-core/tribler_core/modules/libtorrent/download.py
This PR resolves #6008 by extending the try-except block from a single line to the whole function.
=> Fix "UnicodeDecodeError: invalid continuation byte" issue

src/tribler-core/tribler_core/modules/bandwidth_accounting/community.py
Hopefully this will help to debug a bug where there is a ping-pong of bandwidth transactions between two peers.
=> Enriched log entry with peer info

src/tribler-core/tribler_core/modules/metadata_store/community/eva_protocol.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_eva_protocol.py
This PR makes it possible to transfer big binary data over ipv8.
Closes https://github.com/Tribler/tribler/issues/6003
The protocol based on TFTP with windowsize (RFC 7440).
Features:
* timeout
* retransmit
* dynamic window size
The maximum data size that can be transferred through the protocol can be calculated as "block_size * 4294967295" where 4294967295 is the max segment number (4B unsigned int). But the protocol is slow by design, so try to send less rather than more.
```python
class MyCommunity(EVAProtocolMixin, Community):
community_id = b'0' * 20
def __init__(self, *args, **kwargs):
super().__init__(*args, **kwargs)
self.eva_init()
self.eva_register_receive_callback(self.on_receive)
self.eva_register_send_complete_callback(self.on_send_complete) …
```
=> Binary data transfer protocol over ipv8.

src/tribler-core/tribler_core/modules/bandwidth_accounting/transaction.py, src/tribler-core/tribler_core/modules/tests/bandwidth_accounting/test_community.py
We are using a dataclass for the container class BandwidthTransactionData and we were using a default value for the timestamp. However, this default value is not updated when a new dataclass is instantiated, resulting in erroneous timestamps in LedgerZero. This PR explicitly adds an __init__ method which should ensure correctness when creating new transactions.
=> Fixed a bug with LedgerZero timestamps

src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/torrent_metadata.py
Forcing usage of EVA for RQC replies is another step towards reliable real-time previews (Channels 2.5)
=> Enable forcing EVA usage for RQC queries

src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_gigachannel_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_metadata.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/remote_query_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_remote_query_endpoint.py, src/tribler-gui/tribler_gui/debug_window.py, src/tribler-gui/tribler_gui/qt_resources/debugwindow.ui
This PR adds tracking of the last 10 peers who introduced us to a channel, for each channel. If a peer does not respond to our queries, it is dropped. Also, it adds a convenient debug endpoint and a corresponding Channels debug tab.
This is another step towards live previews in Channels 2.5
=> Add tracking of peers subscribed to channels

src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_eva_protocol.py
This PR fixes sporadic test fails caused by not necessary assertion.
This assertion doesn't work properly for some cases for the last packet. 
Seems like a "naive test design issue".
=> Fix test_dynamically_changed_window_size

src/tribler-core/tribler_core/modules/dht_health_manager.py, src/tribler-core/tribler_core/modules/libtorrent/download_manager.py, src/tribler-core/tribler_core/modules/tests/test_dht_health_manager.py, src/tribler-core/tribler_core/modules/torrent_checker/torrentchecker_session.py
This PR fixes an issue with increased peer counts being returned by the `DHTHealthManager`. The problem is that when we send BEP33 responses for active downloads, they are picked up by the `DHTHealthManager` and added to the nearest infohash. A similar issue could present when we receive BEP33 responses for active downloads.
To fix the issue we keep track of transaction_id -> infohash. Unfortunately, this means that we have to process all incoming and outgoing DHT messages. Note that I'm assuming that transaction_ids for in-flight requests are unique.
=> Fix for DHTHealthManager returning incorrect results

src/tribler-core/tribler_core/tests/test_network_utils.py
This PR fixes #6042.
I was not able to reproduce the actual issue.
My guess is the cause of the issue was simultaneously running tests. 
The fix is simple: to use a randomly picked port instead of a fixed one.
=> Fix test_get_first_free_port

src/tribler-gui/tribler_gui/debug_window.py, src/tribler-gui/tribler_gui/tribler_window.py
With this PR the Debug Pane -> General tab now shows information about the GUI Qt settings.
MacOS
Windows
Linux
=> Show GUI settings in Debug Panel

src/tribler-core/tribler_core/conftest.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/metadata_endpoint_base.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/search_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_search_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py, src/tribler-gui/tribler_gui/widgets/triblertablecontrollers.py
This PR places healthy torrents on top of the search result list. Previously, remote results with unknown health were constantly adding to the top of the search result list, obstructing the view and making it harder to see healthy torrents.
Currently, only local results contain health information. After #6053 become merged, it would be possible to add remote results with good health at the top of the search result list as well.
=> Place healthy torrents on top of search result

src/tribler-core/tribler_core/modules/metadata_store/restapi/channels_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_channels_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_torrent_metadata.py
Fixes incorrect and overly strict checks introduced in #6064
=> Fix popularity page

src/tribler-common/tribler_common/sentry_reporter/sentry_scrubber.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_scrubber.py
This PR should improve scrubbing of sensitive information by adding a second pass of scrubbing.
It needs in rare cases, where sensitive information is unexpectedly formatted and located in the first parts of the event.
See the test as an example: https://github.com/Tribler/tribler/pull/6060/files#diff-26702280a5708819383ad8010a8557895b16c41a59a3f31add3451aa0b3d90dfR140
=> Add second pass of scrubbing

src/tribler-gui/tribler_gui/defs.py, src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py, src/tribler-gui/tribler_gui/qt_resources/mainwindow.ui, src/tribler-gui/tribler_gui/tribler_window.py, src/tribler-gui/tribler_gui/utilities.py, src/tribler-gui/tribler_gui/widgets/settingspage.py, src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
This adds an option in Settings to minimize Tribler GUI to system tray. Users asked for it repeatedly over the years:
fixes #3631
fixes #1054 
related to #5972 
recent [forum post](https://forum.tribler.org/t/minimize-to-system-tray/5047/7)
p.s.
for some reason the newly adde checkbox looks different than the older checkboxes. I looked basically everywhere, but AFAICT there is no difference in definition of the new and old checkboxes :face_with_head_bandage: 
@devos50 , @xoriole , maybe you guys know something about this checkbox mystery?
Also, dear Mac :apple: users, could you please test it out? I only tested it on Windows and on Linux, works as expected.
[Qt reference for TrayIcon](https://doc.qt.io/qt-5/qsystemtrayicon.html#details)
EDIT:
I guess it [makes not …
=> READY: Add GUI options to minimize to tray

src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/remote_query_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_remote_query_endpoint.py, src/tribler-gui/tribler_gui/qt_resources/mainwindow.ui, src/tribler-gui/tribler_gui/qt_resources/search_results.ui, src/tribler-gui/tribler_gui/tests/test_gui.py, src/tribler-gui/tribler_gui/tribler_window.py, src/tribler-gui/tribler_gui/utilities.py, src/tribler-gui/tribler_gui/widgets/searchresultswidget.py, src/tribler-gui/tribler_gui/widgets/settingspage.py, src/tribler-gui/tribler_gui/widgets/timeoutprogressbar.py
This PR adds an intermediary "Waiting for remote search results" page.
After the user starts a remote search, "Search Loading" Page is shown now. The page contains the number of remote responses/request, the timeout progress bar and "Show now" button.
The regular Channels-based search results page is shown when at least one of the following events happen:
1. Tribler receives all (5 out of 5) remote responses
2. The timeout progress bar runs to 100% (30 seconds)
3. The user clicks the "Show now" button.
The Loading page is a separate widget now, so it will be easy to change it in the future by e.g. adding dynamic search criteria, etc.
=> READY: Add search loading page

src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_gigachannel_community.py, src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/channels_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/metadata_endpoint_base.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/remote_query_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_channels_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_remote_query_endpoint.py, src/tribler-core/tribler_core/modules/metadata_store/store.py, src/tribler-core/tribler_core/modules/metadata_store/utils.py, src/tribler-core/tribler_core/modules/popularity/popularity_community.py, src/tribler-gui/tribler_gui/qt_resources/torrents_list.ui, src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py, src/tribler-gui/tribler_gui/widgets/searchresultswidget.py, src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
This change affects how non-subscribed channels are shown to the user. Now _all_ the results are shown from a remote peer that is known to host the channel.
=> READY: Add live channel preview feature

src/tribler-gui/tribler_gui/widgets/settingspage.py
This PR fixes the problems with disabling the "Save" button in the settings after the first click.
=> Fix settings page save button not working

src/tribler-core/tribler_core/modules/ipv8_module_catalog.py, src/tribler-core/tribler_core/modules/popularity/popularity_community.py, src/tribler-core/tribler_core/modules/popularity/test_popularity_community.py
Two changes:
- Popular and random torrents are gossiped separately in two different intervals (popular: 2 mins, random: 5 seconds)
- Popularity community now uses a separate Network instance
=> Update Popularity community

src/tribler-gui/tribler_gui/qt_resources/mainwindow.ui, src/tribler-gui/tribler_gui/tests/test_gui.py, src/tribler-gui/tribler_gui/tribler_window.py, src/tribler-gui/tribler_gui/widgets/settingspage.py
This PR changes some aspects of the GUI: 
* the Trust Graph button is moved from the left menu to Trust Page to avoid confusing new users
* the Debug button is moved to the top right corner of the app to maintain the menu uniformity
* Channels-related items are now grouped under a separate label
* the color for the left and top panel is swapped with the main panel color. This brings the GUI more in line with modern standards, accentuating the content instead of the controls.
Overall, this PR takes our GUI even closer to standards, even more "total ripoff"-style :wink:
=> Rearrange left menu

src/tribler-gui/tribler_gui/qt_resources/mainwindow.ui, src/tribler-gui/tribler_gui/widgets/channelsmenulistwidget.py
The changes are based on @drew2a 's mockup:
It took me 3 (three) hours to figure out that the channels list never shrinking to less than 3 rows is a Qt bug :rage:
=> Move add channel button under channels list

src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/collection_node.py, src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py, src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py, src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
This makes folders(collections) inherit status from parent channels. Otherwise, multi-level channels always open sub-collections in preview mode.
Also, remove some obsolete preview-related code.
Also, fix the bug with reverting to the root of the channels view.
=> Fix collection always in preview state

src/tribler-common/tests/test_network_utils.py, src/tribler-common/tribler_common/network_utils.py, src/tribler-gui/tribler_gui/tribler_window.py
This PR contains refactoring of `test_get_first_free_port`. Fixes #6042
Suggestions have been implemented:
* Split test into `get_first_free_port` and `get_first_free_port_none_available`
* Move the tests into the right folder.
* Refactor the function in `network_utils.py` into a `NetworkUtils`-type class
Credits to @qstokkink
=> Refactoring of test_get_first_free_port

src/tribler-core/tribler_core/modules/bandwidth_accounting/community.py, src/tribler-core/tribler_core/modules/bandwidth_accounting/database.py, src/tribler-core/tribler_core/modules/bandwidth_accounting/transaction.py
Basically, OptimisticCheckError was raised incorrectly by PonyORM: the current transaction tries to delete a BandwidthTransaction instance, but it was somehow already deleted outside of the current db_session. Pony thinks this is suspicious and raises the error.
I don't quite understand at this moment when the BandwidthTransaction instance was actually deleted (and why it happened outside of the current transaction), but the exception looks like an overreaction from PonyORM: if we want for an object to be deleted after the end of the transaction, and it was already deleted, then the final result will be what we expect to have.
In the next release of PonyORM, I plan to remove this optimistic check, and currently, I just turned off all optimistic checks for db_session in …
=> Fixes #6076: Object BandwidthTransaction was deleted outside of current transaction

src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py, src/tribler-common/tribler_common/sentry_reporter/sentry_scrubber.py, src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_reporter.py, src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py, src/tribler-gui/tribler_gui/error_handler.py
This PR uncover the real exception from `CoreConnectTimeoutError`'s event.
Now the `CoreConnectTimeoutError` shows the biggest count of issues in `7.9.0` release:
The problem for us as developers is that `CoreConnectTimeoutError` just covers a real exception. 
This PR uncover the real exception by retrieving it from a stacktrace. 
An issue before the PR: https://sentry.tribler.org/organizations/tribler/issues/270
An issue after the PR: https://sentry.tribler.org/organizations/tribler/issues/739
=> Uncover the real exception from CoreConnectTimeoutError's event

src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
Mismatched disconnects result in non-fatal, but annoying error message pop-ups in the GUI
=> Fix mismatched channel disconnects

src/tribler-gui/tribler_gui/dialogs/createtorrentdialog.py, src/tribler-gui/tribler_gui/tribler_window.py
"Add to personal channel" checkbox in the "Create torrent" dialog does nothing.  This PR fixes the problem.
=> Fix adding torrent to personal channel after creating torrent

src/tribler-common/tests/test_network_utils.py, src/tribler-common/tribler_common/network_utils.py, src/tribler-core/tribler_core/config/test_tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.py, src/tribler-core/tribler_core/config/tribler_config.spec, src/tribler-core/tribler_core/conftest.py, src/tribler-core/tribler_core/modules/libtorrent/download_manager.py, src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py, src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_community.py, src/tribler-core/tribler_core/modules/tunnel/tests/test_triblertunnel_community.py, src/tribler-core/tribler_core/restapi/settings_endpoint.py, src/tribler-core/tribler_core/restapi/tests/test_settings_endpoint.py, src/tribler-core/tribler_core/session.py, src/tribler-gui/tribler_gui/tests/test_gui.py
This PR removes random port assignation from Tribler config and places it to the corresponding modules. It also reduces the time between port checking and port using.
Fixes #6148
=> Refactor random ports assignation in tribler config

tribler.spec
* Change app bundle name to “Tribler.app”.
* Set CFBundleName and CFBundleDisplayName to “Tribler”.
The changes ensures the app is displayed as “Tribler” rather than “tribler” throughout macOS.
=> [macOS] Fix display name capitalization

src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_eva_protocol.py
This PR fixes #6166 by disabling EVA timeout in the test.
As we see in full logs (thanks @qstokkink), the core issue of the test's failure is:
```python
DEBUG    EVA:eva_protocol.py:437 Acknowledgement (450). Window size: 43. Peer hash: 233461499389175895
INFO     EVA:eva_protocol.py:494 Finish. Peer hash: 1909838577825146852. Transfer: Type: TransferType.OUTGOING. Info: b'?'. Block: 409(1024). Window size: 41. Updated: 1624017632.813049
WARNING  EVA:eva_protocol.py:507 Exception.Peer hash 1909838577825146852: "Terminated by timeout. Timeout is: 1 sec"
```
So it would be enough to just disable this timeout in this particular test.
=> Disable EVA timeout in test_dynamically_changed_window_size
