Tribler/tribler

- Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py
- TriblerGUI/utilities.py
- TriblerGUI/widgets/lazytableview.py
- TriblerGUI/widgets/tablecontentmodel.py
Also improved the pretty_date function to return a singular when applicable.
Fixes #4276
> Added updated field to list with channels

- Tribler/Test/Community/Tunnel/FullSession/test_tunnel_base.py
- TriblerGUI/tribler_request_manager.py
- TriblerGUI/utilities.py
Fixes #4284 
This should fix the application testers, see https://jenkins-ci.tribler.org/job/Deployment-Tests/job/Run_Tribler_Custom/5/
> Fixed pretty_date method, hidden services test and window variable in TriblerRequestManager

- Tribler/Test/Community/Tunnel/FullSession/test_tunnel_base.py
- Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py
- Tribler/Test/test_as_server.py
During execution of the tests.
> Disabled credit mining manager/resource monitor

- Tribler/Test/Community/Market/Reputation/test_reputation_base.py
- Tribler/Test/Community/Market/Reputation/test_reputation_pagerank.py
- Tribler/Test/common.py
As reported by https://jenkins-ci.tribler.org/job/test_tribler_python3/2/consoleFull
> Minor Python 3 stuff

- Tribler/Test/Community/Market/test_order_repository.py
- Tribler/Test/Community/Market/test_transaction_manager.py
- Tribler/Test/Community/Market/test_transaction_repository.py
```
FAIL: test_add (Tribler.Test.Community.Market.test_order_repository.MemoryOrderRepositoryTestSuite)
File "/home/jenkins/workspace/test_tribler_python3/tribler/Tribler/Test/Community/Market/test_order_repository.py", line 31, in test_add
self.assertEquals([], self.memory_order_repository.find_all())
AssertionError: [] != dict_values([])
-------------------- >> begin captured logging << --------------------
MemoryOrderRepository: INFO: Memory order repository used
--------------------- >> end captured logging << ---------------------
```
> Create a list from a generator in Python 3

- Tribler/Core/Libtorrent/LibtorrentMgr.py
Revert #4316 because it causes #4328
> Revert #4316 because it causes #4328

- Tribler/community/market/core/side.py
In Python 3 __dict.keys()__ is an iterator, not a __list__.
> Py3: Make a list of the keys

- TriblerGUI/widgets/tokenminingpage.py
Free matplotlib memory in Token Mining page.
This might fix @synctext memory leak issue.
Fixes #3944
> Free matplotlib memory in Token Mining page

- debian/tribler.postinst
- debian/tribler.prerm
> READY: Fixed Ubuntu deployment issue

- LICENSE
> Remove the byte-order-mark

- Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py
- Tribler/Core/Modules/restapi/metadata_endpoint.py
- Tribler/community/gigachannel/community.py
- TriblerGUI/widgets/lazytableview.py
- TriblerGUI/widgets/searchresultspage.py
- TriblerGUI/widgets/tablecontentdelegate.py
- TriblerGUI/widgets/tablecontentmodel.py
- TriblerGUI/widgets/triblertablecontrollers.py
This PR contains several fixes for GUI problems regarding GigaChannel:
* Fixes #4347 
* Fixes #4352 
and some others.
> READY: Various GUI channel view fixes

- Tribler/Core/Utilities/utilities.py
As discussed at https://github.com/Tribler/tribler/pull/4382#issuecomment-473809894
> Binary on verbs: agent.request(b'GET', uri, headers, None)

- Tribler/Test/Core/Modules/RestApi/base_api_test.py
- Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py
> Try converting agent.request(req_type) to bytes

- Tribler/community/market/community.py
As suggested at https://github.com/Tribler/py-ipv8/pull/462
> block_type must be bytes

- Tribler/Test/Community/Market/test_message.py
- Tribler/community/market/core/message.py
- Tribler/community/market/core/order.py
- Tribler/community/market/core/payment.py
- Tribler/community/market/core/tick.py
- Tribler/community/market/core/transaction.py
- Tribler/community/market/database.py
- Tribler/community/market/payload.py
> Rename TraderId.to_string() --> TraderId.to_bytes()

- Tribler/community/market/payload.py
> Revert a bytes literal change made in  #4394

- Tribler/Core/Modules/restapi/search_endpoint.py
- Tribler/Test/Core/Modules/RestApi/test_search_endpoint.py
- Tribler/community/gigachannel/community.py
- Tribler/community/gigachannel/request.py
- TriblerGUI/widgets/triblertablecontrollers.py
Unique search identifier for each request helps to identify the response.
> Unique search identifier for each request

- Tribler/Core/Modules/bitcoinlib_main.py
Fixed bitcoinlib compatibility with version 0.4.5
> Fixed bitcoinlib compatibility with version 0.4.5

- Tribler/Test/Core/Modules/RestApi/test_wallets_endpoint.py
- Tribler/Test/Core/Modules/Wallet/test_btc_wallet.py
> Fixed failing wallet tests

- Tribler/community/gigachannel/community.py
- TriblerGUI/widgets/discoveredpage.py
- TriblerGUI/widgets/searchresultspage.py
- TriblerGUI/widgets/tablecontentmodel.py
- TriblerGUI/widgets/triblertablecontrollers.py
Discovered channels are updated in the GUI as they are received from the network. Also, the way new items are added to the table in the GUI is refactored.
> Update GUI with discovered channels in real time

- Tribler/Core/APIImplementation/LaunchManyCore.py
- Tribler/Core/TorrentChecker/session.py
- Tribler/Core/TorrentChecker/torrent_checker.py
- Tribler/Test/Core/TorrentChecker/test_torrentchecker.py
- TriblerGUI/tribler_window.py
Fixes #4422, fixes #4395, fixes #4391, fixes #4380, fixes #4370
> Various fixes for Tribler 7.3

- win/makedist_win.bat
Fixes video player not loading issue in windows 32.
> Fix VLC DLLs conflict loading in Windows

- Tribler/Core/TorrentChecker/session.py
- Tribler/community/popularity/community.py
Side effects of Python3 porting
Fixes #4431 
Fixes #4430
> Fixes torrent health packing and typing issues

- check_os.py
> Fixed Tribler crashing other processes in Ubuntu

- Tribler/Core/Utilities/utilities.py
- Tribler/Test/Core/Utilities/test_utilities.py
- Tribler/Test/GUI/test_util.py
- TriblerGUI/utilities.py
- TriblerGUI/widgets/downloadsdetailstabwidget.py
- TriblerGUI/widgets/torrentdetailstabwidget.py
Fixed a GUI reference import in Core
> Fixed a GUI reference import in Core

- Tribler/Core/Modules/restapi/downloads_endpoint.py
- Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
Fixes file selection issue raised in https://github.com/Tribler/tribler/issues/4438
> Fixed issue with file selection in torrent download

- Tribler/Core/Modules/TrustCalculation/local_view.py
- Tribler/Core/Modules/restapi/trustview_endpoint.py
- TriblerGUI/widgets/trustgraphpage.py
Fixes https://github.com/Tribler/tribler/issues/4479 TypeError: unhashable type: 'dict'
Fixes https://github.com/Tribler/tribler/issues/4482
> Fixed networkx compatibility issue

- Tribler/Core/Libtorrent/LibtorrentMgr.py
- Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py
Fixes https://github.com/Tribler/tribler/issues/4490
> Fixed issue with fetching metainfo of existing download

- Tribler/Core/Modules/restapi/downloads_endpoint.py
- Tribler/Core/Modules/restapi/mychannel_endpoint.py
- Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
- TriblerGUI/defs.py
- TriblerGUI/tribler_action_menu.py
- TriblerGUI/widgets/downloadspage.py
- TriblerGUI/widgets/lazytableview.py
- TriblerGUI/widgets/triblertablecontrollers.py
- Add torrents in downloads page to My channel with a right click
- Support multiple torrents selection in My Channel to delete
- Move downloaded torrent to a different location
> Added support for adding/moving/removing torrents in My Channel

- Tribler/Core/Utilities/tracker_utils.py
- Tribler/Test/Core/Utilities/test_tracker_utils.py
> Fix tracker URL sanitizer choking on None

- Tribler/community/triblertunnel/community.py
Fixes https://github.com/Tribler/tribler/issues/4508.
> Change community ID of tunnel testnet

- TriblerGUI/widgets/trustgraphpage.py
> Trust graph node size is based on their balance

- Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py
- Tribler/Core/Modules/MetadataStore/store.py
- Tribler/Core/Modules/gigachannel_manager.py
- Tribler/Core/Upgrade/db72_to_pony.py
- Tribler/Core/Upgrade/upgrade.py
- Tribler/Test/Core/Upgrade/test_db72_to_pony.py
Small fixes for the latest beta
Fixes #4506 
Fixes #4510
> READY: Fixes for beta3

- TriblerGUI/widgets/trustgraphpage.py
> Fixed issue with clicking on empty Trust graph

- Tribler/Core/Modules/MetadataStore/OrmBindings/vsids.py
Change VSIDS scaling to max of all votes.
> Change VSIDS scaling

- Tribler/Core/Libtorrent/LibtorrentMgr.py
> Fixed bdecode None issue in processing alerts

- TriblerGUI/qt_resources/mainwindow.ui
- TriblerGUI/utilities.py
- TriblerGUI/widgets/channelpage.py
- TriblerGUI/widgets/lazytableview.py
- TriblerGUI/widgets/searchresultspage.py
- TriblerGUI/widgets/subscriptionswidget.py
- TriblerGUI/widgets/tablecontentdelegate.py
- TriblerGUI/widgets/tablecontentmodel.py
Added star ratings in the channel list display.
> READY: Five star ratings to channel

- Tribler/Core/Modules/MetadataStore/OrmBindings/vsids.py
- Tribler/Core/Modules/MetadataStore/store.py
This little commit fixes some minor potential problems in VSIDS
> READY: Small fixes to VSIDS

- Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py
- TriblerGUI/defs.py
- TriblerGUI/widgets/lazytableview.py
- TriblerGUI/widgets/searchresultspage.py
- TriblerGUI/widgets/tablecontentmodel.py
Added torrent updated field in channel torrents
> Added torrent updated field in channel torrents

- Tribler/Core/Modules/MetadataStore/store.py
Small fix for VSIDS votes scaling problem
> Fix wrong votes scaling on Tribler startup

- Tribler/Core/Utilities/utilities.py
> Fix copying torrent with unicode name to personal channel

- Tribler/Core/Modules/wallet/tc_wallet.py
- Tribler/Test/Community/Market/test_bloomfilter.py
- Tribler/community/market/community.py
- Tribler/community/market/core/bloomfilter.py
- Tribler/community/market/payload.py
> Integrated Bloomfilter in market, updated IPv8 pointer

- Tribler/Test/Community/Tunnel/test_discovery.py
- Tribler/community/triblertunnel/discovery.py
Fixes https://github.com/Tribler/tribler/issues/4549.
> Fix Tunnel discovery strategy

- TriblerGUI/utilities.py
- TriblerGUI/widgets/lazytableview.py
- TriblerGUI/widgets/subscriptionswidget.py
- TriblerGUI/widgets/tablecontentmodel.py
- TriblerGUI/widgets/triblertablecontrollers.py
Fixes #4537 Issue with checkboxes in windows
Fixes #4544 TriblerGUI crashes when trying to add another channel to personal channel
Fixes issue with click on subscription icon in channel page
> Post 7.3 beta4 fixes

- Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py
> READY: Re-create channel folder on channel consolidation

- Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py
- Tribler/Core/Modules/MetadataStore/store.py
- Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
- Tribler/Core/Upgrade/db72_to_pony.py
- Tribler/Test/Community/gigachannel/test_community.py
- Tribler/Test/Core/Modules/MetadataStore/test_store.py
- Tribler/Test/Core/Modules/MetadataStore/test_torrent_metadata.py
> READY: Fix a problem with creating FFA entries

- TriblerGUI/widgets/tablecontentmodel.py
Fixes https://github.com/Tribler/tribler/issues/4557
> READY: Fixed right click on channel or torrent issue introduced in earlier PR

- TriblerGUI/widgets/tablecontentmodel.py
This PR adds a detailed text tooltip to "Votes" column. In addition, it introduces a more general method of adding tooltips to columns.
> READY: Add tooltip to votes column

- Tribler/Core/Upgrade/db72_to_pony.py
- Tribler/Test/Core/Upgrade/test_upgrader.py
- TriblerGUI/tribler_window.py
This adds progress notifications to the personal channel conversion process, the same as we use for converting legacy torrents to FFA entries.
> READY: Add GUI notifications to personal channel conversion process

- TriblerGUI/defs.py
- TriblerGUI/dialogs/startdownloaddialog.py
Added auto retry for metainfo loading
Fixes https://github.com/Tribler/tribler/issues/4438
> Auto retry for metainfo loading

- TriblerGUI/widgets/torrentdetailstabwidget.py
> Fix rows overwriting in the GUI

- Tribler/Core/APIImplementation/LaunchManyCore.py
- Tribler/Test/Core/test_launch_many_cores.py
> READY: Fixed issue with loading checkpoint when metainfo is None

- Tribler/Core/Modules/MetadataStore/store.py
- Tribler/Core/Modules/gigachannel_manager.py
- Tribler/Core/Modules/restapi/metadata_endpoint.py
- Tribler/Test/Core/Modules/MetadataStore/test_channel_download.py
- Tribler/Test/Core/Modules/MetadataStore/test_store.py
Another fix to support recent changes in channel addressing.
> READY: Fix get() queries to support nested channels

- TriblerGUI/widgets/channelpage.py
- TriblerGUI/widgets/triblertablecontrollers.py
> Fixed torrent list not resizing with details

- TriblerGUI/qt_resources/createtorrentdialog.ui
> Fixed color in createtorrentdialog

- TriblerGUI/widgets/channelpage.py
- TriblerGUI/widgets/searchresultspage.py
- TriblerGUI/widgets/triblertablecontrollers.py
Fixes issue with showing torrent health in the details tab.
Fixes https://github.com/Tribler/tribler/issues/4597
> Torrent health update in details tab

- TriblerGUI/defs.py
- TriblerGUI/qt_resources/mainwindow.ui
- Fixed issue with Trust graph node icon labelling
- Fixed issue with progress bar in Trust graph
Fixes partly #4601
> Trust graph GUI issues

- TriblerGUI/qt_resources/mainwindow.ui
> Moved tray icon checkbox

- Tribler/Core/Modules/MetadataStore/store.py
Fixes #4608 
Well, we can't really test if it fixes it. We can only hope it will help, since this stuff is extremely hard to debug and trigger.
> READY: Increase Pony DB lock timeout

- Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py
- Tribler/Test/Core/Modules/MetadataStore/test_torrent_metadata.py
> Sanitize torrent date when adding to GigaChannel

- TriblerGUI/widgets/downloadspage.py
> Fixed added popup message

- Tribler/Core/DownloadConfig.py
> Fixed issue with copying download config

- Tribler/Test/GUI/test_gui.py
- run_tribler.py
> Fixed test issue with second Tribler instance

- Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py
- Tribler/Core/Modules/MetadataStore/store.py
- Tribler/Test/Core/Modules/MetadataStore/test_store.py
- TriblerGUI/widgets/channelpage.py
- TriblerGUI/widgets/tablecontentmodel.py
- TriblerGUI/widgets/triblertablecontrollers.py
Various Giga channel fixes:
- Refresh button for personal channel is not shown anymore
- Shows if the channel is outdated and caps the torrents count to max available
- Removed 'Add to My Channel' option from personal channel showed in discovered page
- Added unsortable columns in different table views
Fixes https://github.com/Tribler/tribler/issues/4639
Fixes https://github.com/Tribler/tribler/issues/4627
Fixes https://github.com/Tribler/tribler/issues/4601
> Various Giga channel fixes

- Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py
- Tribler/Core/Modules/restapi/search_endpoint.py
- Tribler/community/gigachannel/community.py
- TriblerGUI/widgets/tablecontentmodel.py
- TriblerGUI/widgets/triblertablecontrollers.py
Fixed right-click crash issue in search results
> Fixed right-click crash issue in search results

- .sonar/analyse.py
Fixes https://github.com/Tribler/tribler/issues/4652
> Sonar Cloud analysis

- Tribler/community/gigachannel/community.py
Fixed conflicting type field in notifying the discovered channel
> Fixed issue with notifying discovered channel

- Tribler/Core/Libtorrent/LibtorrentMgr.py
- Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
- Fixes TypeError in adding a torrent with infohash to fetch metainfo
- Fixes double finish_request() incase of metainfo error
> Metainfo fixes

- TriblerGUI/event_request_manager.py
> Increase wait for core to 60 sec

- TriblerGUI/widgets/downloadspage.py
> Default sorting downloads by addition time

- Tribler/Core/APIImplementation/LaunchManyCore.py
> Handle metainfo not being dict on torrent resume

- TriblerGUI/tribler_window.py
> Fixed crash when adding unicode torrent from dir

- Tribler/Core/Category/Category.py
- Tribler/Test/Core/Category/test_category.py
Fixes https://github.com/Tribler/tribler/issues/4706.
> Fix category

- Tribler/Core/APIImplementation/LaunchManyCore.py
- Tribler/Core/DownloadConfig.py
- Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
- Tribler/Core/defaults.py
- Tribler/Test/Core/Modules/RestApi/test_trustview_endpoint.py
- Tribler/Test/Core/test_downloadconfig.py
Issues fixed:
- Bootstrap remains hidden when adding new torrents [#4701 ]
- Bootstrap download starts on init [#4702]
> Fix bootstrap download issue

- Tribler/Core/Upgrade/upgrade.py
Fixes https://github.com/Tribler/tribler/issues/4711.
> Fix upgrader

- Tribler/Core/APIImplementation/LaunchManyCore.py
- Tribler/Core/Config/config.spec
- Tribler/Core/Utilities/bootstrap_util.py
- Tribler/Core/bootstrap.py
- Tribler/Test/Core/test_launch_many_cores.py
Now peers will share bootstrap blocks of top 400 peers, that allow to quickly build trustchain graph.
Related issue: Issue #4704
> Meaningful bootstrap content

- TriblerGUI/widgets/tokenminingpage.py
- TriblerGUI/widgets/triblertablecontrollers.py
> Fixed GUI NoneType response handling

- debian/tribler.postinst
> Workaround for compatibility with older versions of six

- Tribler/Core/TorrentChecker/torrent_checker.py
- Tribler/Test/Core/TorrentChecker/test_torrentchecker.py
> Fixed crash when health response is None

- Tribler/Core/bootstrap.py
> Fix bootstrap log for seeder

- Tribler/Core/APIImplementation/LaunchManyCore.py
> Fixed metadata store db name

- Tribler/community/gigachannel/community.py
Updated Giga channel community key in main and test net - preparing for release.
> Updated Giga channel community ID

- check_os.py
Added pip dependencies check during startup
> Added pip dependencies check during startup

- TriblerGUI/widgets/downloadwidgetitem.py
> Remove broken personal channel download highlightning in the GUI

- Tribler/Core/Libtorrent/LibtorrentMgr.py
Fixes https://github.com/Tribler/tribler/issues/4765
> Fixed metainfo issue for torrents already in credit mining mode

- Tribler/Test/GUI/FakeTriblerAPI/endpoints/debug_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/downloads_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/events_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/ipv8_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/libtorrent_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/market_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/metadata_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/mychannel_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/root_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/search_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/settings_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/shutdown_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/state_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/statistics_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/torrentinfo_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/trustchain_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/endpoints/wallets_endpoint.py
- Tribler/Test/GUI/FakeTriblerAPI/models/channel.py
- Tribler/Test/GUI/FakeTriblerAPI/models/download.py
- Tribler/Test/GUI/FakeTriblerAPI/models/torrent.py
- Tribler/Test/GUI/FakeTriblerAPI/models/trustchain_block.py
- Tribler/Test/GUI/FakeTriblerAPI/tribler_data.py
- TriblerGUI/tribler_request_manager.py
- TriblerGUI/widgets/subscriptionswidget.py
> Python3 fixes for GUI tests

- Tribler/Core/Utilities/random_utils.py
- Tribler/Core/bootstrap.py
- Tribler/Test/API/test_download.py
- Tribler/Test/Core/Modules/RestApi/base_api_test.py
- Tribler/Test/Core/Utilities/test_random_utils.py
- Tribler/Test/Core/test_bootstrap.py
- Tribler/Test/Core/test_launch_many_cores.py
- Tribler/Test/util/Tracker/HTTPTracker.py
- Tribler/community/gigachannel/request.py
- Tribler/community/market/core/bloomfilter.py
- Tribler/community/popularity/community.py
- Tribler/community/triblertunnel/community.py
- TriblerGUI/tribler_request_manager.py
- TriblerGUI/tribler_window.py
Fixes for some bugs found while making #4759 compatible with Python 3. The fixes were collected, separated into this PR and removed from #4759.
> Python 3 compatibility fixes

- Tribler/Core/TorrentDef.py
- TriblerGUI/qt_resources/mainwindow.ui
- TriblerGUI/tribler_window.py
- TriblerGUI/widgets/trustpage.py
Fixes #4800, fixes #4792, fixes #4790.
> Various py3 fixes

- Tribler/Core/TorrentChecker/session.py
- Tribler/Test/Core/TorrentChecker/test_torrentchecker_session.py
Fixes https://github.com/Tribler/tribler/issues/4802
> Metainfo python3 fixes

- check_os.py
Python3 fixes for tkinter in check os module
> READY: Python3 fixes for tkinter in check os module

- TriblerGUI/widgets/editchannelpage.py
- TriblerGUI/widgets/lazytableview.py
> Fix race condition in lazytableview

- check_os.py
> Removed tkinter

- twisted/plugins/tunnel_helper_plugin.py
> Disabling bootstrap for anontunnel helpers

- Tribler/Core/Modules/restapi/metadata_endpoint.py
- Tribler/Test/Core/Modules/RestApi/test_metadata_endpoint.py
> Fix REST subscribe endpoint problem

- tribler.spec
- win/makedist_win.bat
- win/tools/reset-keepid.bat
- win/tools/reset.bat
> Python3 builder windows

- Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
- Tribler/Core/Libtorrent/LibtorrentMgr.py
- Tribler/Test/Community/Tunnel/FullSession/test_tunnel_base.py
- TriblerGUI/widgets/settingspage.py
Fixes https://github.com/Tribler/tribler/issues/4795, fixes https://github.com/Tribler/tribler/issues/4808, fixes https://github.com/Tribler/tribler/issues/4830, fixes #4814.
> Python 3 fixes

- .pylintrc
- TriblerGUI/widgets/downloadsdetailstabwidget.py
- TriblerGUI/widgets/downloadwidgetitem.py
Removed a few usage of eval in GUI
> Removed a few usage of eval in GUI

- mac/makedistmac_64bit.sh
- tribler.spec
- Fixes pyinstaller script for building on macOS.
- Removes Tk as dependency
> Fixed build on macOS

- Tribler/Core/bootstrap.py
Fixes https://github.com/Tribler/tribler/issues/4849.
> Fix for crash while fetching bootstrap peers

- Tribler/Core/Upgrade/upgrade.py
Otherwise, for big databases memory used  by db_session can overflow
> READY: Break DB upgrade 6->7 into chunks

- Tribler/Core/Modules/gigachannel_manager.py
- Tribler/Test/Core/Modules/MetadataStore/test_channel_download.py
- Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
- Tribler/Test/Core/Modules/test_gigachannel_manager.py
> READY: Add verification of channel dir structure before download

- TriblerGUI/widgets/subscriptionswidget.py
- TriblerGUI/widgets/trustpage.py
> Fixed issue with disabling mining button depending on the settings

- Tribler/Core/Libtorrent/LibtorrentMgr.py
Fixes https://github.com/Tribler/tribler/issues/4883
> Fixed already called error on removing torrent

- Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
- Tribler/Core/Modules/versioncheck_manager.py
- Tribler/Test/Core/Modules/test_versioncheck.py
- TriblerGUI/debug_window.py
- TriblerGUI/dialogs/startdownloaddialog.py
- TriblerGUI/tribler_window.py
- TriblerGUI/widgets/homepage.py
- TriblerGUI/widgets/tokenminingpage.py
- Fixes #4851 
- Fixes #4843 
- Fixes #4842 
- Fixes #4779
- Adds python version to Debug/General
- Adds libtorrent version to Deug/General
- Fixes #4859
- Fixes #4869
- Fixes #4868
> Various fixes for 7.4.0

- TriblerGUI/widgets/graphs/timeseriesplot.py
- TriblerGUI/widgets/trustgraphpage.py
- Fixes multiple lines in the time series graph
- Fixed node size issue in trust graph. Fixes https://github.com/Tribler/tribler/issues/4904
> Fixed graph issues

- Tribler/Main/Build/update_version_from_git.py
Fixed version string
Fixes https://github.com/Tribler/tribler/issues/4914
> Fixed version string

- TriblerGUI/tribler_app.py
- TriblerGUI/tribler_window.py
Set Qt core app settings before initialization
> Set Qt core app settings before initialization

- Tribler/Core/DownloadState.py
- Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
- Tribler/Core/Utilities/json_util.py
- Tribler/__init__.py
Fixed reference to six.ensure_text with IPv8 custom implementation
Fixes #4923
> Fixed reference to six.ensure_text with IPv8 custom implementation

- Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
- Tribler/Core/Socks5/conversion.py
- Tribler/Core/TorrentDef.py
- Tribler/Core/Utilities/utilities.py
- Tribler/Test/Core/Modules/test_versioncheck.py
- Tribler/Test/Core/Upgrade/test_config_upgrade_70_71.py
> Fixed six 1.11 missing imports issues

- Tribler/Core/Upgrade/config_converter.py
- Tribler/Core/Utilities/unicode.py
Fixes #4933 with some dumb magic
> Fix tstate corruption during conversion

- TriblerGUI/tribler_request_manager.py
> Fixed issue with exporting torrent

- Tribler/Core/Upgrade/config_converter.py
Properly based #4960 
Fixes #4959
> Fix config convert for 7.4

- Tribler/Core/Socks5/conversion.py
- Tribler/Core/Socks5/udp_connection.py
- Tribler/Test/Core/Socks5/test_conversion.py
- Tribler/Test/Core/Socks5/test_udp_connection.py
Fixes Unicode decode error in socks conversion.
> Fix Unicode decode error in socks conversion

- Tribler/Core/APIImplementation/LaunchManyCore.py
- Tribler/Core/Modules/MetadataStore/OrmBindings/torrent_metadata.py
- Tribler/Core/Modules/restapi/downloads_endpoint.py
- Tribler/Core/Modules/restapi/mychannel_endpoint.py
- Tribler/Core/TorrentDef.py
- TriblerGUI/dialogs/createtorrentdialog.py
- TriblerGUI/tribler_window.py
Fixes #4958 
Fixes #4942 
Fixes #4919
> Fix some unicode errors for 7.4.0

- Tribler/Core/Modules/resource_monitor.py
Fixes #3345 by remembering the last error code and skipping the subsequent errors with the same code.
> READY: Skip resource_monitor spamming psutil errors

- Tribler/Core/Libtorrent/LibtorrentMgr.py
- Tribler/Core/Modules/restapi/create_torrent_endpoint.py
- Tribler/Core/TorrentChecker/session.py
Fixes #4844 
Fixes #4954 
And an Unicode problem in create_torrent_endpoint that prevented the newly created torrent from being seeded.
> READY: More unicode-related fixes

- Tribler/Core/Config/download_config.py
- Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
- Tribler/Core/Libtorrent/LibtorrentMgr.py
- Tribler/Core/Modules/restapi/create_torrent_endpoint.py
- Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
- Tribler/Core/TorrentChecker/session.py
- Tribler/Core/TorrentDef.py
- Tribler/Core/Utilities/utilities.py
- Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py
- Tribler/Test/Core/test_torrent_def.py
Python3 libtorrent bdecode compat utility.
Fixes https://github.com/Tribler/tribler/issues/4956
> Python3 libtorrent bdecode compat utility

- README.rst
Added downloads badge for 7.3.2
> Added downloads badge for 7.3.2

- Tribler/community/triblertunnel/community.py
Fixes https://github.com/Tribler/tribler/issues/4940.
> READY: Fix crash if there is no socks connection

- TriblerGUI/tribler_app.py
Fixed issue of loading torrents with Unicode name by clicking it.
Fixes #4974
> Fixed issue with loading unicode torrents

- TriblerGUI/dialogs/startdownloaddialog.py
> READY: Fix unicode escapes in download dialog

- Tribler/Core/Libtorrent/LibtorrentMgr.py
> Fix misleading VOD message

- Tribler/Core/Libtorrent/LibtorrentMgr.py
- Tribler/Core/Modules/restapi/libtorrent_endpoint.py
- Tribler/Core/Video/VideoServer.py
- Tribler/Test/Core/Video/test_video_server.py
Fixes https://github.com/Tribler/tribler/issues/4986, https://github.com/Tribler/tribler/issues/4985.
> READY: Small fixes

- Tribler/Core/Modules/restapi/trustview_endpoint.py
Fixes https://github.com/Tribler/tribler/issues/4988
> Trustgraph networkx compatibility

- Tribler/Core/Modules/restapi/downloads_endpoint.py
> READY: Fix safe_exteneded_peer_info dumps crash

- Tribler/Core/TorrentDef.py
> Fix encoding of encoding entry in torrent files

- TriblerGUI/dialogs/createtorrentdialog.py
- TriblerGUI/tribler_window.py
Fixes #4995 
The notification is still shown, and the download is added as expected
> Fix wrong behaviour of dl dialog with add to channel checkbox

- Tribler/Core/Category/FamilyFilter.py
- Tribler/Core/Utilities/network_utils.py
- Tribler/Main/Build/update_version_from_git.py
- Tribler/Test/API/test_seeding.py
- Tribler/Test/Core/Libtorrent/test_libtorrent_mgr.py
- Tribler/Test/Core/Modules/test_resource_monitor.py
- Tribler/Test/Core/Upgrade/test_db72_to_pony.py
- Tribler/Test/Core/Video/test_video_server.py
- Tribler/Test/GUI/FakeTriblerAPI/utils/network.py
- Tribler/Test/test_as_server.py
- TriblerGUI/debug_window.py
Closes #4890 and replaces #4895
> READY: F handle resources with statement

- Tribler/Core/Upgrade/db72_to_pony.py
- Tribler/Test/Core/Upgrade/test_db72_to_pony.py
As mentioned in #5014 , this PR is about migrating sqlite3 db connections to be used with "with" statements instead of being handled manually.
> Handle db with conn manager

- TriblerGUI/core_manager.py
- TriblerGUI/debug_window.py
- TriblerGUI/dialogs/addtopersonalchanneldialog.py
- TriblerGUI/dialogs/createtorrentdialog.py
- TriblerGUI/dialogs/feedbackdialog.py
- TriblerGUI/dialogs/startdownloaddialog.py
- TriblerGUI/tribler_request_manager.py
- TriblerGUI/tribler_window.py
- TriblerGUI/widgets/channelcontentswidget.py
- TriblerGUI/widgets/createtorrentpage.py
- TriblerGUI/widgets/downloadsdetailstabwidget.py
- TriblerGUI/widgets/downloadspage.py
- TriblerGUI/widgets/homepage.py
- TriblerGUI/widgets/leftmenuplaylist.py
- TriblerGUI/widgets/marketorderspage.py
- TriblerGUI/widgets/marketpage.py
- TriblerGUI/widgets/markettransactionspage.py
- TriblerGUI/widgets/marketwalletspage.py
- TriblerGUI/widgets/settingspage.py
- TriblerGUI/widgets/subscriptionswidget.py
- TriblerGUI/widgets/tablecontentmodel.py
- TriblerGUI/widgets/tokenminingpage.py
- TriblerGUI/widgets/torrentdetailstabwidget.py
- TriblerGUI/widgets/triblertablecontrollers.py
- TriblerGUI/widgets/trustgraphpage.py
- TriblerGUI/widgets/trustpage.py
This PR completely rewrites TriblerRequestManager into a singleton. This is necessary to support #4750 in sane way. Also, it makes writing requests a bit easier.
> WIP: RequestManager refactor

- Tribler/Test/GUI/FakeTriblerAPI/models/channel.py
Remove old_round since it is no longer necessary. Fixes #5024 .
> Remove old_round

- src/tribler-core/tribler_core/logger.conf
- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/gigachannel_manager.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/search_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/store.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_gigachannel_manager.py
- src/tribler-core/tribler_core/tests/tools/test_as_server.py
- src/tribler-core/tribler_core/tests/tools/util.py
- src/tribler-core/tribler_core/upgrade/db72_to_pony.py
- src/tribler-gui/tribler_gui/tests/fake_tribler_api/endpoints/debug_endpoint.py
> Fix Gigachannel Manager processing

- Tribler/dependencies.py
Added missing dependencies. Closes #5027
> READY: Add missing dependencies

- doc/conf.py
- doc/restapi/createtorrent.rst
- doc/restapi/debug.rst
- doc/restapi/downloads.rst
- doc/restapi/events.rst
- doc/restapi/libtorrent.rst
- doc/restapi/metadata.rst
- doc/restapi/search.rst
- doc/restapi/settings.rst
- doc/restapi/shutdown.rst
- doc/restapi/state.rst
- doc/restapi/statistics.rst
- doc/restapi/torrentinfo.rst
- doc/restapi/trustchain.rst
- doc/restapi/trustview.rst
- doc/restapi/upgrader.rst
- src/tribler-gui/tribler_gui/tests/test_gui.py
- src/tribler.sh
- Fixed tribler.sh script. Supports running tribler from any directory.
- Fixed GUI tester
- Fixed documentation builder
> Fixes for post-renaming issues

- src/tribler-common/tribler_common/simpledefs.py
- src/tribler-core/tribler_core/restapi/events_endpoint.py
- src/tribler-core/tribler_core/restapi/tests/test_events_endpoint.py
- src/tribler-gui/tribler_gui/event_request_manager.py
Notifier refactoring breaked events endpoint. Damn lambdas...
> Fix some problems with events endpoint

- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
> READY: Fix race condition in GUI

- src/tribler-core/tribler_core/modules/libtorrent/download_config.py
- src/tribler-core/tribler_core/modules/libtorrent/libtorrent_download_impl.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/tests/test_downloadconfig.py
- src/tribler-core/tribler_core/modules/tests/test_video_server.py
- src/tribler-core/tribler_core/modules/video_server.py
Correct variable name. In addition rename functions to avoid future confusion with their usage. Closes #5050
> READY: Correct variable name

- src/integration_tests/test_live_downloads.py
- src/run_tribler.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/collection_node.py
- src/tribler-core/tribler_core/modules/resource_monitor.py
- src/tribler-core/tribler_core/modules/video_server.py
- src/tribler-core/tribler_core/tests/test_network_utils.py
- src/tribler-gui/tribler_gui/tests/test_gui.py
Partially deals with #5030 . Accidentally closed #5047 when pushed a clean branch.
> WIP: Clean path_util usages

- src/tribler-core/tribler_core/modules/torrent_checker/torrent_checker.py
- src/tribler-gui/tribler_gui/dialogs/addtopersonalchanneldialog.py
- src/tribler-gui/tribler_gui/qt_resources/addtochanneldialog.ui
- src/tribler-gui/tribler_gui/qt_resources/torrents_list.ui
- src/tribler-gui/tribler_gui/tribler_request_manager.py
- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
- src/tribler-gui/tribler_gui/widgets/downloadspage.py
- src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
- src/tribler-gui/tribler_gui/widgets/triblertablecontrollers.py
Adds breadcrumbs for navigation and fixes some bugs.
> Nested-channels related GUI improvements

- Tribler/Core/Config/tribler_config.py
- Tribler/Core/Upgrade/config_converter.py
- Tribler/Core/Upgrade/upgrade.py
- Tribler/Core/Upgrade/version_manager.py
- Tribler/Core/osutils.py
- Tribler/Test/Community/Tunnel/FullSession/test_tunnel_base.py
- Tribler/Test/Core/Config/test_tribler_config.py
- Tribler/Test/Core/Libtorrent/test_libtorrent_download_impl.py
- Tribler/Test/Core/Modules/RestApi/test_util.py
- Tribler/Test/Core/Modules/test_process_checker.py
- Tribler/Test/Core/TorrentChecker/test_torrentchecker_session.py
- Tribler/Test/Core/Upgrade/test_upgrader.py
- Tribler/Test/Core/Upgrade/test_version_manager.py
- Tribler/Test/Core/Upgrade/upgrade_base.py
- Tribler/Test/Core/test_osutils.py
- Tribler/Test/test_as_server.py
- Tribler/dependencies.py
- debian/tribler.postinst
- debian/tribler.prerm
- twisted/plugins/market_plugin.py
- twisted/plugins/tribler_plugin.py
- twisted/plugins/tunnel_helper_plugin.py
Implements forward copy and upgrade as backup mechanism on state directory. This supports rollback to any version (after 7.3.0).
> [7.4.0] READY: State directory backup mechanism

- Tribler/Core/Session.py
Fix #5069 
Catch the error and hope for the best...
> Fix socket error msg

- src/tribler-core/tribler_core/config/test_tribler_config.py
- src/tribler-core/tribler_core/config/tribler_config.py
- src/tribler-core/tribler_core/modules/credit_mining/credit_mining_manager.py
- src/tribler-core/tribler_core/modules/libtorrent/download_config.py
- src/tribler-core/tribler_core/modules/libtorrent/libtorrent_download_impl.py
- src/tribler-core/tribler_core/modules/libtorrent/libtorrent_mgr.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/tests/test_download.py
- src/tribler-core/tribler_core/modules/metadata_store/gigachannel_manager.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/store.py
- src/tribler-core/tribler_core/modules/resource_monitor.py
- src/tribler-core/tribler_core/modules/tests/test_video_server.py
- src/tribler-core/tribler_core/modules/watch_folder.py
- src/tribler-core/tribler_core/session.py
- src/tribler-core/tribler_core/statistics.py
- src/tribler-core/tribler_core/tests/tools/test_as_server.py
- src/tribler-core/tribler_core/upgrade/config_converter.py
- src/tribler-core/tribler_core/upgrade/tests/test_config_upgrade_70_71.py
- src/tribler-core/tribler_core/upgrade/upgrade.py
- src/tribler-core/tribler_core/upgrade/upgrade_base.py
- src/tribler-core/tribler_core/utilities/osutils.py
- src/tribler-core/tribler_core/utilities/path_util.py
- src/tribler-core/tribler_core/utilities/torrent_utils.py
- Removed pathutil to_text() by replacing with Py3 str()
> Incremental Pathlib migration

- src/tribler-core/tribler_core/tests/test_osutils.py
- src/tribler-core/tribler_core/upgrade/tests/test_upgrader.py
- src/tribler-core/tribler_core/upgrade/tests/test_version_manager.py
- src/tribler-core/tribler_core/upgrade/upgrade.py
- src/tribler-core/tribler_core/upgrade/version_manager.py
- src/tribler-core/tribler_core/utilities/osutils.py
Implements forward copy and upgrade as backup mechanism on state directory. This supports rollback to any version (after 7.3.0).
> READY: State directory backup mechanism

- src/tribler-core/tribler_core/modules/libtorrent/libtorrent_download_impl.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/create_torrent_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/tests/test_libtorrent_download_impl.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/channels_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_channels_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_metadata_endpoint.py
- src/tribler-core/tribler_core/restapi/base_api_test.py
- src/tribler-core/tribler_core/restapi/events_endpoint.py
- src/tribler-core/tribler_core/restapi/tests/test_create_torrent_endpoint.py
- src/tribler-core/tribler_core/restapi/tests/test_events_endpoint.py
- src/tribler-core/tribler_core/restapi/tests/test_rest_manager.py
- src/tribler-core/tribler_core/restapi/tests/test_settings_endpoint.py
- src/tribler-core/tribler_core/tests/tools/tracker/http_tracker.py
- src/tribler-core/tribler_core/upgrade/upgrader_endpoint.py
- src/tribler-gui/tribler_gui/event_request_manager.py
- src/tribler-gui/tribler_gui/tests/fake_tribler_api/endpoints/events_endpoint.py
- src/tribler-gui/tribler_gui/tests/fake_tribler_api/endpoints/metadata_endpoint.py
- src/tribler-gui/tribler_gui/tribler_request_manager.py
This PR does the following:
* Ensures that all request bodies are JSON encoded (currently, some REST endpoints use JSON, while others use URL encoding).
* Allows the events endpoint to be accessed using the Javascript EventSource interface.
> Update REST API

- Tribler/Core/APIImplementation/LaunchManyCore.py
- Tribler/Core/Session.py
- Tribler/Core/Upgrade/upgrade.py
- Tribler/Test/Core/Upgrade/test_version_manager.py
> Fix wrong keypair regeneration on upgrade

- Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py
- Tribler/Core/Modules/restapi/metadata_endpoint.py
> Guard against subscribe/download of legacy channels

- TriblerGUI/widgets/videoplayerpage.py
> Fix race condition in videoplayer controls

- Tribler/Core/Modules/restapi/create_torrent_endpoint.py
- Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
- Tribler/Core/Session.py
- Tribler/Core/TorrentDef.py
- Tribler/Core/Utilities/unicode.py
- Tribler/Test/Community/Tunnel/test_community.py
- Tribler/Test/Core/Modules/RestApi/test_create_torrent_endpoint.py
- TriblerGUI/widgets/downloadsdetailstabwidget.py
- TriblerGUI/widgets/triblertablecontrollers.py
Fixes https://github.com/Tribler/tribler/issues/5090, fixes https://github.com/Tribler/tribler/issues/5086, fixes https://github.com/Tribler/tribler/issues/5088, possibly fixes https://github.com/Tribler/tribler/issues/5091, fixes https://github.com/Tribler/tribler/issues/5098 (by updating IPv8 pointer), fixes https://github.com/Tribler/tribler/issues/5096, fixes https://github.com/Tribler/tribler/issues/5087.
> READY: Various fixes for 7.4

- Tribler/Core/Utilities/tracker_utils.py
fixes bug reported in http://reporter.tribler.org/stacktrace/31130
> Fix getting non-sanitized tracker URLs

- Tribler/Core/APIImplementation/LaunchManyCore.py
- Tribler/Core/Modules/MetadataStore/OrmBindings/channel_metadata.py
- Tribler/Core/Modules/restapi/create_torrent_endpoint.py
- Tribler/Core/Modules/restapi/metadata_endpoint.py
- Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
- Tribler/Core/Session.py
- Tribler/Core/TorrentDef.py
- Tribler/Core/Upgrade/upgrade.py
- Tribler/Core/Utilities/tracker_utils.py
- Tribler/Core/Utilities/unicode.py
- Tribler/Test/Community/Tunnel/test_community.py
- Tribler/Test/Core/Modules/RestApi/test_create_torrent_endpoint.py
- Tribler/Test/Core/Upgrade/test_version_manager.py
- TriblerGUI/widgets/downloadsdetailstabwidget.py
- TriblerGUI/widgets/triblertablecontrollers.py
- TriblerGUI/widgets/videoplayerpage.py
This is a technical merge PR, putting changes from 7.4.1 back into 7.4.0 branch according to GitFlow methodology
> Merge release 7.4.1 into 7.4.0

- Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
- Tribler/community/triblertunnel/community.py
Fixes https://github.com/Tribler/tribler/issues/5110.
> Fix checkpoints getting stuck + speedup shutdown

- Tribler/Core/Modules/process_checker.py
> Fix PID checking on Windows

- Tribler/Core/Upgrade/version_manager.py
- Tribler/Test/Core/Upgrade/test_version_manager.py
This is a fix for a severe bug in version management // upgrade procedure in 7.4.2.
> Fix version manager

- TriblerGUI/utilities.py
> Fix dir writability check

- src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py
- src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_gigachannel_community.py
- src/tribler-core/tribler_core/modules/metadata_store/discrete_clock.py
- src/tribler-core/tribler_core/modules/metadata_store/gigachannel_manager.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_node.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/collection_node.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/metadata_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_channels_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_metadata_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/store.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py
- src/tribler-core/tribler_core/modules/popularity/popularity_community.py
- src/tribler-core/tribler_core/modules/torrent_checker/test_torrentchecker.py
- src/tribler-core/tribler_core/modules/torrent_checker/torrent_checker.py
- src/tribler-core/tribler_core/upgrade/db72_to_pony.py
- src/tribler-core/tribler_core/upgrade/tests/test_db72_to_pony.py
This series of commits greatly optimizes Tribler Channels performance for users with BIG channel databases. It includes optimizations for broken queries and moving queries to a background thread.
> SQL optimizations for Channels

- src/tribler-core/tribler_core/modules/torrent_checker/torrent_checker.py
- src/tribler-core/tribler_core/modules/tracker_manager.py
> Fix int overflow in TorrentChecker

- Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py
- Tribler/Core/Utilities/maketorrent.py
Fixes https://github.com/Tribler/tribler/issues/5141.
> Removed set_filepieceranges

- Tribler/Core/Modules/tracker_manager.py
- Tribler/Core/TorrentChecker/torrent_checker.py
- Tribler/Test/Core/TorrentChecker/test_torrentchecker.py
> TorrentChecker fixes backport from devel

- src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py
Used all of the latest IPv8 shortcuts to beautify the RemoteQueryCommunity, so it can serve as a reference/example to all future communities.
> Use latest IPv8 community features in RemoteQueryCommunity

- src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py
> READY: Fix reporter stuck on "Sending"

- src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler-gui/tribler_gui/widgets/downloadspage.py
Fixes https://github.com/Tribler/tribler/issues/5174.
> Fix issue with removing download data

- src/tribler-core/tribler_core/session.py
Apparently, we were still missing some information in the error reporter..
> Provide full exception information

- src/tribler-core/tribler_core/modules/libtorrent/download_config.py
- src/tribler-core/tribler_core/modules/libtorrent/tests/test_downloadconfig.py
Fixes https://github.com/Tribler/tribler/issues/5188.
> Fix DownloadConfig.copy

- src/tribler-core/tribler_core/modules/torrent_checker/torrentchecker_session.py
- src/tribler-core/tribler_core/session.py
Fixes https://github.com/Tribler/tribler/issues/5191, fixes https://github.com/Tribler/tribler/issues/5167. Also fixes a compatibily issue while running Tribler with Python 3.6
> Various fixes for 7.5-exp2

- src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_downloads_endpoint.py
Fixes the DownloadsEndpoint which is currently broken due to a bad rebase.
> Fix selecting files

- src/tribler-core/tribler_core/modules/torrent_checker/torrent_checker.py
`session_stop_task_list` was used to track the coroutines for stopping tracker sessions. The list was never emptied which resulted in a memory leak of about 50 MB/hour.
This PR deprecates `session_stop_task_list` in favour of TaskManager, which stops the leak and makes the code cleaner.
> Fix memory leak in TorrentChecker

- src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py
- src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py
This is the last step in preparation of RemoteQuery Community for release.
> Impose limits on remote SQL query size

- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
- src/tribler-gui/tribler_gui/widgets/triblertablecontrollers.py
Also, fix dialog option for playing a video showing for every torrent instead of video torrents only.
> Fix simplified personal channels view

- src/tribler-core/tribler_core/modules/libtorrent/download_manager.py
- src/tribler-core/tribler_core/modules/libtorrent/tests/test_download_manager.py
Fixes https://github.com/Tribler/tribler/issues/5213.
> Keep checkpoint on get_metainfo cancellation

- doc/development/development_on_linux.rst
I just did a fresh install on Ubuntu 19.10, this is what I required.
> Updated Ubuntu development docs

- src/tribler-core/tribler_core/modules/tunnel/community/caches.py
> Properly cancel future in BalanceRequestCache

- src/tribler-gui/tribler_gui/event_request_manager.py
2 characters!
I guess that's my shortest PR yet...
> Fix crash on upgrader done

- .isort.cfg
- src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/collection_node.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/torrent_metadata.py
- src/tribler-core/tribler_core/session.py
- src/tribler-core/tribler_core/tests/test_session.py
- src/tribler-gui/tribler_gui/tests/fake_tribler_api/models/torrent.py
fixes #5167 and adds proper tests for unhandled errors observer.
Also, fix GUI test.
Also, support gossip of Folders (Collections) through the old GigaChannel Community, so users will be able to see folders in channel previews.
> Refactor unhandled errors observer

- build/win/resources/tribler.nsi
Also updated the release info.
Fixes #5280
> Removed tstream associations from the Windows installer

- src/tribler-gui/tribler_gui/utilities.py
> Fix QVariant error when reading GUI settings

- src/tribler-gui/tribler_gui/widgets/triblertablecontrollers.py
Fixes a bug reported in 7.5-rc5
> Remove download option appearing on channel entries

- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
- Hiding the 'Complete' label in the GUI when a channel has been downloaded and processed.
- Updating the items label when new entries are received during the channel discovery process.
> Minor GUI changes

- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/gigachannel_manager.py
- src/tribler-core/tribler_core/modules/metadata_store/store.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_download.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_gigachannel_manager.py
* Reuse metadata from DHT as suggested by @egbertbouman
> GigaChannelManager improvements

- src/tribler-core/tribler_core/modules/libtorrent/download_manager.py
Fixes https://github.com/Tribler/tribler/issues/5306.
> Fix recheck after updating hop count

- doc/conf.py
- doc/extract_swagger.py
- doc/requirements.txt
- src/tribler-core/tribler_core/restapi/debug_endpoint.py
This PR convinces readthedocs to auto-generate swagger.yaml for us.
> Auto generate Swagger docs

- src/tribler-core/tribler_core/upgrade/config_converter.py
Fixes https://github.com/Tribler/tribler/issues/5300.
> Fix checkpoint upgrade

- src/tribler-core/tribler_core/modules/libtorrent/restapi/downloads_endpoint.py
Fixes https://github.com/Tribler/tribler/issues/5324.
> Fix unicode error in peer_info

- src/tribler-gui/tribler_gui/debug_window.py
> Fix exporting libtorrent stats

- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_downloads_endpoint.py
Fixes https://github.com/Tribler/tribler/issues/5338.
> Fix test_select_download_file

- src/tribler-core/tribler_core/config/tribler_config.py
- src/tribler-core/tribler_core/restapi/tests/test_settings_endpoint.py
> Define default downloads dir value

- src/tribler-core/tribler_core/modules/libtorrent/download_manager.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/gigachannel_manager.py
- src/tribler-gui/tribler_gui/debug_window.py
- src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py
> Small fixes

- src/tribler-gui/tribler_gui/core_manager.py
As part of the issue where ImportErrors in the core are not caught and forwarded to the GUI, I modified the CoreManager in the GUI. Specifically, I changed the way how we start the Tribler core subprocess, which is now using the QProcess class. QProcess has tight integration with PyQt and allows us to get rid of several timers where we check if the core is closed. I extended the logic to catch the situation where the Tribler core is unexpectedly closed.
Another change is that the stderr of the core is now forwarded to stdout, and the stdout is piped to the GUI process. The CoreManager reads the stdout, checks for occurrences of the string 'Traceback' and stores the lines if it finds it. This traceback is then logged when Tribler unexpectedly finishes. I'm open to suggestions on how to …
> Refactored subprocess to QProcess

- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
- src/tribler-gui/tribler_gui/widgets/subscriptionswidget.py
> Fix race condition in subscription widget

- src/tribler-gui/tribler_gui/tribler_request_manager.py
> Fix iteration on keys in request manager

- src/tribler-gui/tribler_gui/tribler_request_manager.py
> Fix iteration on keys in request manager. Again.

- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
> Fix race condition in tablecontentmodel

- src/tribler-core/tribler_core/config/tribler_config.spec
- src/tribler-gui/tribler_gui/qt_resources/mainwindow.ui
- src/tribler-gui/tribler_gui/widgets/settingspage.py
This PR disables the market by default and adds an option to the settings panel to enable it.
Fixes #5389
> Disable market by default, added GUI toggle

- src/tribler-gui/tribler_gui/core_manager.py
> Fixed UnicodeDecodeError in the GUI

- src/tribler-core/tribler_core/tests/test_session.py
We used _run_once to ensure that some exceptions are raised (and do not crash Tribler) before asserting that the exception handler has not been called. However, the behaviour of _run_once is not always such that it immediately cleans the events in the event loop. This results in unexpected behaviour (at least on Mac with Python 3.8) where the test starts to tear down before the exceptions are thrown and failing the test.
Fixes #5414
> Fixed test_error_observer_ignored_error

- src/tribler-core/tribler_core/modules/libtorrent/download_manager.py
> Fix wrong TimeoutError used in download_manager

- build/debian/snap/snapcraft.yaml
Update snap package core base from core18 to latest core20. With the core changed, the command script had to be slightly changed.
> Update snap core to core20

- src/tribler-core/run_tunnel_helper.py
> Fixed log reject

- src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py
- src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py
- src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py
> Fix gossiping zero-sized channels

- src/tribler-core/tribler_core/modules/tunnel/community/dispatcher.py
- src/tribler-core/tribler_core/modules/tunnel/tests/test_dispatcher.py
Fixes https://github.com/Tribler/tribler/issues/5463.
> Fix for http-request timeout

- build/debian/tribler/DEBIAN/control
Fix a minor comma issue in Debian control file
> Fix a minor comma issue in Debian control file

- src/tribler-core/tribler_core/modules/libtorrent/download_manager.py
- src/tribler-core/tribler_core/modules/tests/test_resource_monitor.py
- src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py
Fixes https://github.com/Tribler/tribler/issues/5474.
> Fix libtorrent 1.2.4+ compatibility

- src/tribler-core/tribler_core/session.py
- src/tribler-gui/tribler_gui/event_request_manager.py
- src/tribler-gui/tribler_gui/tribler_window.py
This should help with figuring out what causes timeout errors
> Make GUI send last traceback on core timeout error

- src/tribler-core/tribler_core/modules/libtorrent/download_manager.py
> READY: Add libtorrent 1.1.13 support for listen_succeeded_alert

- src/tribler-core/tribler_core/modules/torrent_checker/torrentchecker_session.py
Fixes https://github.com/Tribler/tribler/issues/4880.
> Let unhandled_error_observer deal with gaierrors

- src/tribler-core/tribler_core/session.py
- src/tribler-gui/tribler_gui/tests/test_gui.py
Fixes #4880 (hopefully forever!)
Fixes #5494
> Ignoring gaierror with errno -5

- src/tribler-core/tribler_core/session.py
- src/tribler-core/tribler_core/tests/test_session.py
> Totally ignore gaierrors

- src/tribler-core/tribler_core/modules/metadata_store/restapi/channels_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_channels_endpoint.py
> Fix add to channel error

- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py
> Fix mdblob squash test failing randomly

- src/tribler-core/tribler_core/modules/popularity/popularity_community.py
> Fix Pony unique transaction error

- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
> Fix RemoteQuery not using model properties

- src/tribler-gui/tribler_gui/i18n/README.md
Fixes https://github.com/Tribler/tribler/pull/5479#discussion_r459339167
> Fixed grammar in i18n README.md

- doc/conf.py
- doc/extract_swagger.py
- src/tribler-core/tribler_core/restapi/rest_manager.py
- src/tribler-gui/tribler_gui/tests/test_gui.py
Fixes https://github.com/Tribler/tribler/issues/5519.
> Fix for building REST API docs

- src/tribler-common/tribler_common/utilities.py
- src/tribler-core/tribler_core/utilities/install_dir.py
- src/tribler-gui/tribler_gui/core_manager.py
- src/tribler-gui/tribler_gui/utilities.py
- src/tribler-gui/tribler_gui/vlc.py
This implements  #5233.
It was a simple issue, but I don't think I fully understand the is_frozen function. I did some basic testing and it appears nothing changed but I would like someone else's perspective.
Fixes #5233
> Refactoring: moving multiple is_frozen definitions to tribler_common

- src/tribler-gui/tribler_gui/widgets/tableiconbuttons.py
- src/tribler-gui/tribler_gui/widgets/triblertablecontrollers.py
Disables video buttons in the GUI for 7.5.2, because our VLC player is disabled too.
> Disable video play buttons

- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_download.py
- src/tribler-core/tribler_core/tests/tools/test_as_server.py
> Disable bittorrent DHT during channel download test

- src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py
This should fix the "Database session is over" error.
The reason for the error was in calling `obj.to_simple_dict()` for objects belonging to finished `db_session`.
For some objects, it was necessary to load additional information from the database, and it was not possible to do as `db_session` was already over.
Now we remember ids of objects for which we want to call `to_simpe_dict()` and retrieve these objects again in a fresh db_session.
> Fixes #5568: DatabaseSessionIsOver

- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/collection_node.py
- src/tribler-core/tribler_core/modules/metadata_store/store.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_torrent_metadata.py
> Fix remote updating channel node with type change

- src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_community.py
> Increased timeout of hidden seeding test

- pytest.ini
- src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py
- src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_community.py
Also lowered the logging level of a particular statement from error to warning.
> Improved debugging capabilities of tunnel tests

- src/tribler-core/tribler_core/conftest.py
- src/tribler-core/tribler_core/modules/ipv8_module_catalog.py
- src/tribler-core/tribler_core/session.py
- src/tribler-core/tribler_core/tests/test_session.py
Fixes #5593
This is a straight port of Gumby's modular Community loading.
Community loading is now declarative, which inflates the codebase slightly. Session is now less of a god-class.
> READY: Ported Gumby's modular Community loading

- src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_community.py
Fixes https://github.com/Tribler/tribler/issues/5599.
> Mock IPv8 in tunnel tests

- src/tribler-core/tribler_core/modules/libtorrent/restapi/create_torrent_endpoint.py
- src/tribler-core/tribler_core/restapi/tests/test_create_torrent_endpoint.py
Fixes https://github.com/Tribler/tribler/issues/5614.
> Seed newly created torrents with default hop count

- README.rst
We usually do not hang out there...
> Removed IRC mention from readme

- src/tribler-core/tribler_core/modules/ipv8_module_catalog.py
- src/tribler-core/tribler_core/modules/tests/test_ipv8_module_catalog.py
- tribler.spec
> Detect hidden imports in IPv8 community catalog

- src/tribler-core/tribler_core/modules/tests/test_versioncheck.py
- src/tribler-core/tribler_core/modules/versioncheck_manager.py
This PR fixes broken version checker tests in the devel branch
> Fix version checker tests

- src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py
- src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_remote_query_community.py
Resolves #5677 by disabling #5642
> Disable #5642

- src/tribler-common/tribler_common/simpledefs.py
- src/tribler-core/tribler_core/session.py
- src/tribler-core/tribler_core/upgrade/tests/test_version_manager.py
- src/tribler-core/tribler_core/upgrade/version_manager.py
This directory is unused now that #5688 has been merged.
> Removed wallet directory creation

- src/tribler-gui/tribler_gui/dialogs/addtopersonalchanneldialog.py
Fix [reporter bug 36066](http://reporter.tribler.org/stacktrace/36066)
Fixes #5673
> Fix GUI crashing on race condition in addtochannel dialog

- src/tribler-core/tribler_core/modules/tests/test_versioncheck.py
- src/tribler-core/tribler_core/modules/versioncheck_manager.py
- src/tribler-gui/tribler_gui/tribler_window.py
- Fixes https://github.com/Tribler/tribler/issues/5678 : Referenced before assignment
- Fixes https://github.com/Tribler/tribler/issues/5670 : Multiple version checker popups
> Fix version checker issues

- src/tribler-core/tribler_core/modules/bandwidth_accounting/transaction.py
- src/tribler-core/tribler_core/modules/tests/bandwidth_accounting/test_database.py
> Converted bandwidth amount to BIGINT type

- src/tribler-core/tribler_core/modules/payout_manager.py
- src/tribler-core/tribler_core/modules/tests/test_payout_manager.py
> Fixed error when the DHT returns zero peers

- src/tribler-core/tribler_core/restapi/debug_endpoint.py
- src/tribler-core/tribler_core/restapi/tests/test_debug_endpoint.py
This PR fixes the log rendering in the Debug Pane. Some tests are refactored as well.
> Fix log rendering in the debug pane

- src/tribler-core/tribler_core/modules/bandwidth_accounting/database.py
- src/tribler-core/tribler_core/modules/metadata_store/store.py
Well, this _should_ help with DB performance...
> READY: Use WAL journal mode for sqlite connections

- src/run_tribler.py
Tested in a frozen environment on my Mac (both with Sierra and Big Sur). This seems to fix the issue.
Fixes #5728
> Fixed Qt bug in macOS Big Sur

- src/run_tribler.py
- src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py
- src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_reporter.py
- src/tribler-core/tribler_core/session.py
Resolves https://github.com/Tribler/tribler/issues/5715
This PR:
1. Adds unhandled error handling on startup (before "core-gui" interaction is established)
1. Adds error handling to the core error handler 🕵️ 
Two important places to review:
1. run_tribler.py
1. session.py
If there is an error occurs during startup, then two message boxes will appear:
> Better error handling

- src/tribler-gui/tribler_gui/debug_window.py
- src/tribler-gui/tribler_gui/widgets/downloadspage.py
Fixes #5754
I did attempt to add a GUI test for this, but it would require refactoring in the base class to expose the context menu in order to test reasonably. So, I used manual verification instead (see #5754 for steps to reproduce).
> Fixed exporting torrent TypeError

- tribler.spec
Fixes https://github.com/Tribler/tribler/issues/5766
> Add sentry hooks in pyinstaller spec file

- src/tribler-gui/tribler_gui/widgets/subscriptionswidget.py
- src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
> Fix channel vote rating font spacing on Windows

- src/tribler-core/tribler_core/modules/metadata_store/restapi/remote_query_endpoint.py
- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
> Fix remote search not updating on new results

- src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py
> Remove encoding kwarg when starting download

- src/tribler-common/tribler_common/sentry_reporter/sentry_mixin.py
- src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py
- src/tribler-common/tribler_common/sentry_reporter/sentry_scrubber.py
- src/tribler-common/tribler_common/sentry_reporter/sentry_tools.py
- src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_reporter.py
- src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_scrubber.py
- src/tribler-common/tribler_common/sentry_reporter/tests/test_sentry_tools.py
- src/tribler-core/tribler_core/restapi/events_endpoint.py
- src/tribler-core/tribler_core/session.py
- src/tribler-gui/tribler_gui/dialogs/dialogcontainer.py
- src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py
- src/tribler-gui/tribler_gui/event_request_manager.py
- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
- src/tribler-gui/tribler_gui/widgets/createtorrentpage.py
- src/tribler-gui/tribler_gui/widgets/discoveringpage.py
- src/tribler-gui/tribler_gui/widgets/downloadspage.py
- src/tribler-gui/tribler_gui/widgets/ipv8health.py
- src/tribler-gui/tribler_gui/widgets/loadingpage.py
- src/tribler-gui/tribler_gui/widgets/settingspage.py
- src/tribler-gui/tribler_gui/widgets/subscriptionswidget.py
- src/tribler-gui/tribler_gui/widgets/tabbuttonpanel.py
- src/tribler-gui/tribler_gui/widgets/trustgraphpage.py
- src/tribler-gui/tribler_gui/widgets/trustpage.py
This PR improves GUI error handling by adding:
1. A user identification based on the user's public key
1. Breadcrumbs for QWidget and QDialog 
An example of an issue with these improvements: https://sentry.tribler.org/organizations/tribler/issues/265
> Improve GUI error handling

- src/tribler-core/tribler_core/modules/metadata_store/community/sync_strategy.py
- src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_sync_strategy.py
Removes the obsolete `SyncChannels` strategy
> Remove unused sync_channels strategy

- src/tribler-gui/tribler_gui/dialogs/confirmationdialog.py
- src/tribler-gui/tribler_gui/tribler_request_manager.py
- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/widgets/clickable_line_edit.py
Fixes #5824 
Fixes #5840 
Fixes #5841 
Fixes #5859
> Fixes for GUI emit interface mismatches

- src/tribler-core/tribler_core/modules/metadata_store/store.py
- src/tribler-core/tribler_core/upgrade/tests/test_upgrader.py
- src/tribler-core/tribler_core/upgrade/upgrade.py
There were some bugs in the database upgrade process.
1. When it is necessary to perform a series of updates (versionA -> versionB -> versionC), first steps of this process may fail, as Python classes used on step versionA -> versionB are actually from the current version (versionC) of application code. It leads to two types of errors:
- Automatic check of columns may fail, as it currently checks for the actual version of code (versionC), whereas the database may be on version B instead.
- some selects may fail, as ORM expects all columns specified in a class definition are presented in the database.
2. When it is necessary to perform a series of updates (versionA -> versionB -> versionC), first step (versionA -> versionB) after completion updated database version number to current …
> Fix database upgrader & tests

- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
Fixes https://github.com/Tribler/tribler/issues/5864 as suggested by @qstokkink https://github.com/Tribler/tribler/issues/5864#issuecomment-747513200
> Fix crash on search

- .gitignore
- build/debian/tribler/DEBIAN/control
Fixes https://github.com/Tribler/tribler/issues/5877
> Add xinerama as debian dependency

- src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py
- src/tribler-gui/tribler_gui/widgets/clickablewidgets.py
> Change mousePressEvent signature

- src/tribler-gui/tribler_gui/widgets/triblertablecontrollers.py
This PR resolves #5779 by adding the range validation check.
> Check that a row number in the correct range

- src/tribler-core/tribler_core/upgrade/tests/test_version_manager.py
- src/tribler-core/tribler_core/upgrade/version_manager.py
*hopefully* fixes #5927 
There is a double check that should have prevented that scenario:
* the directory existence check
* the version check
This PR fixes the version check. Indeed, there was a problem (we did not ignore the patch number when considering if we should  upgrade the version.) Well, I still can't understand how the user pulled that off, 'cause the directory existence check seems to work (at least according to automated and manual tests). They could still trigger that if they manually deleted the directory during the upgrade procedure or something like that.
> Ignore patch version in upgrade scenarios

- src/tribler-core/tribler_core/dependencies.py
Fix missing sys reference on exit function call.
> Fix missing sys reference

- src/tribler-gui/tribler_gui/utilities.py
In this PR I preprocess creation traceback to avoid storing all frames with locals inside a signal handler.
> Fix memory leak in trackback_wrapper

- src/tribler-gui/tribler_gui/tribler_window.py
> Fix debug pane keyboard shortcut

- src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py
Fixes https://github.com/Tribler/tribler/issues/5846.
> Check for duplicate BalanceRequestCaches

- src/run_tribler.py
- src/tribler-core/tribler_core/check_os.py
- src/tribler-core/tribler_core/dependencies.py
- src/tribler-gui/tribler_gui/__init__.py
- src/tribler-gui/tribler_gui/single_application.py
This PR adds logging during the Application loading.
This should make it easier to investigate bugs like https://github.com/Tribler/tribler/issues/5547
Linked to https://github.com/Tribler/tribler/discussions/5938
> Extend boot logging

- src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py
Cleans up compatibility code for pre-7.6 GigaChannelCommunity
> Remove legacy GigaChannelCommunity compatibility

- src/tribler-core/tribler_core/restapi/rest_manager.py
- src/tribler-core/tribler_core/session.py
After merging this PR, developers can access a simple debug webapp under /debug-ui.
The webapp can be installed with `pip install tribler-debug-ui`
> Optionally attach the tribler-debug-ui webapp to the RootEndpoint

- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
Fixes Popular page showing torrent count
> Hide torrent count when no count info available

- experiment/tunnel_community/hidden_peer_discovery.py
- experiment/tunnel_community/hidden_peer_discovery.r
- experiment/tunnel_community/speed_test_e2e.py
- experiment/tunnel_community/speed_test_e2e.r
- experiment/tunnel_community/speed_test_exit.py
- experiment/tunnel_community/speed_test_exit.r
See [here](https://jenkins-ci.tribler.org/job/tunnel_experiments/) for the Jenkins jobs.
> Added tunnel experiments

- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/metadata_node.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/channels_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/conftest.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_torrent_metadata.py
- src/tribler-core/tribler_core/modules/popularity/popularity_community.py
- src/tribler-gui/tribler_gui/qt_resources/torrents_list.ui
- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
Make popular endpoint return torrent checked in the last 24 hrs.
> Fix popularity endpoint to limit selection by the last 24hrs

- .flake8
- .pre-commit-config.yaml
> Change flake8 and pre-commit configs

- src/tribler-core/tribler_core/modules/trust_calculation/trust_graph.py
- src/tribler-gui/tribler_gui/widgets/trustgraphpage.py
Fixes https://github.com/Tribler/tribler/issues/6057
> Fix Trust graph refresh issue

- src/tribler-gui/tribler_gui/dialogs/new_channel_dialog.py
- src/tribler-gui/tribler_gui/tribler_window.py
> Fix opening .torrent filenames with URL-encoded names

- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
> Remove channel edit controls by default

- src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py
Fixes https://github.com/Tribler/tribler/issues/5616
> Build e2e circuits while downloading metadata

- src/tribler-gui/tribler_gui/debug_window.py
> Fix wrong slot signature on events_tree_widget

- src/tribler-core/tribler_core/modules/tunnel/socks5/client.py
- src/tribler-core/tribler_core/modules/tunnel/socks5/conversion.py
Fixes https://github.com/Tribler/tribler/issues/6082.
> Ignore PackErrors in Socks5Client

- src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py
- src/tribler-core/tribler_core/modules/metadata_store/community/remote_query_community.py
- src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_gigachannel_community.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_node.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/collection_node.py
- src/tribler-core/tribler_core/modules/metadata_store/payload_checker.py
- src/tribler-core/tribler_core/modules/metadata_store/store.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py
Just an exercise in refactoring...
> Refactor Metadata Store

- src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py
This PR disables error reporting to the old reporter (reporter.tribler.org).
Tribler keeps only reporting to the new one (Sentry).
Related to #5727
> Disable the old reporter (reporter.tribler.org)

- src/tribler-common/tests/test_network_utils.py
- src/tribler-common/tribler_common/network_utils.py
- src/tribler-core/tribler_core/config/tribler_config.py
- src/tribler-core/tribler_core/conftest.py
- src/tribler-core/tribler_core/modules/tunnel/tests/test_triblertunnel_community.py
- src/tribler-gui/tribler_gui/tests/test_gui.py
- src/tribler-gui/tribler_gui/tribler_window.py
This PR contains refactoring for `network_utils.py`
Related to #6148, #6042
> Refactoring: network utils

- src/tribler-core/tribler_core/check_os.py
- src/tribler-core/tribler_core/config/tests/test_tribler_config.py
- src/tribler-core/tribler_core/modules/libtorrent/download.py
- src/tribler-core/tribler_core/modules/libtorrent/download_config.py
- src/tribler-core/tribler_core/modules/libtorrent/download_manager.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/tests/test_download_manager.py
- src/tribler-core/tribler_core/modules/libtorrent/torrentdef.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_node.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/channels_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/store.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py
- src/tribler-core/tribler_core/modules/process_checker.py
- src/tribler-core/tribler_core/modules/tracker_manager.py
- src/tribler-core/tribler_core/modules/tunnel/test_full_session/test_tunnel_community.py
- src/tribler-core/tribler_core/modules/tunnel/tests/test_triblertunnel_community.py
- src/tribler-core/tribler_core/restapi/tests/test_settings_endpoint.py
- src/tribler-core/tribler_core/statistics.py
- src/tribler-core/tribler_core/upgrade/legacy_to_pony.py
- src/tribler-core/tribler_core/utilities/install_dir.py
- src/tribler-core/tribler_core/utilities/maketorrent.py
- src/tribler-core/tribler_core/utilities/osutils.py
- src/tribler-core/tribler_core/utilities/path_util.py
- src/tribler-core/tribler_core/utilities/tests/test_path_utils.py
- src/tribler-core/tribler_core/utilities/tests/test_torrent_utils.py
- src/tribler-core/tribler_core/utilities/torrent_utils.py
This is a refactoring for `path_utils.py`.
> Refactoring: path_utils.py

- src/tribler-core/run_tunnel_helper.py
- src/tribler-core/tribler_core/modules/torrent_checker/torrent_checker.py
- src/tribler-core/tribler_core/modules/torrent_checker/torrentchecker_session.py
- src/tribler-core/tribler_core/modules/tunnel/socks5/client.py
- src/tribler-core/tribler_core/modules/tunnel/socks5/tests/test_server.py
Fixes https://github.com/Tribler/tribler/issues/6171.
> Fix DNS leak in TorrentChecker

- src/tribler-gui/tribler_gui/widgets/graphs/timeseriesplot.py
This one probably slipped through when changing the bandwidth accounting mechanism.
> Removed unused print statement

- doc/conf.py
- doc/requirements.txt
~~This is a sample PR to test the fix for https://github.com/Tribler/tribler/issues/6095.~~
It includes some missing dependencies which should be merged for successful building of the docs.
@devos50 thank you Martijn for pointing out the missing mock modules.
> Add missing documentation dependencies

- src/tribler-gui/tribler_gui/utilities.py
- src/tribler-gui/tribler_gui/widgets/graphs/dataplot.py
- src/tribler-gui/tribler_gui/widgets/graphs/timeseriesplot.py
- src/tribler-gui/tribler_gui/widgets/trustpage.py
Fixes https://github.com/Tribler/tribler/issues/6006
> Update token balance graph data axis

- src/tribler-core/tribler_core/dependencies.py
Fixes https://github.com/Tribler/tribler/issues/6188 (pydantic dependency check part)
> Add pydantic dependency check

- doc/build-docs.sh
- doc/requirements.txt
This PR adds bash script is added to mimic the execution of the ReadTheDocs build script.
> Bash script to build documentation

- src/tribler-core/tribler_core/components/base.py
> Fixes #6255: make `faifast` an option of the Session.start() method

- tribler.spec
Fixes https://github.com/Tribler/tribler/issues/6249 build issue
> Remove IPv8 hidden imports in tribler.spec

- src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/collection_node.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_channels_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py
As we're not going to release 7.10, merging these into `main`
> Merge fixes from 7.10 into main

- src/tribler-core/tribler_core/exception_handler.py
> Change gaierror import

- src/tribler-core/tribler_core/notifier.py
> Fix notifier not working from a thread

- src/tribler-core/tribler_core/components/implementation/bandwidth_accounting.py
- src/tribler-core/tribler_core/components/implementation/gigachannel.py
- src/tribler-core/tribler_core/components/implementation/ipv8.py
- src/tribler-core/tribler_core/components/implementation/popularity.py
- src/tribler-core/tribler_core/components/implementation/tunnels.py
> Switch to modern IPv8 Community addition

- src/tribler-common/tribler_common/simpledefs.py
- src/tribler-core/tribler_core/components/implementation/metadata_store.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler-core/tribler_core/modules/libtorrent/restapi/torrentinfo_endpoint.py
> Fix adding FFA entries on torrentinfo calls

- src/tribler-core/tribler_core/modules/metadata_store/store.py
- src/tribler-core/tribler_core/modules/popularity/community.py
- src/tribler-core/tribler_core/modules/remote_query_community/community.py
- src/tribler-core/tribler_core/modules/remote_query_community/eva_protocol.py
> Demote some logging messages to debug level

- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
> Fix crash on trying to go back on empty Channels stack in the GUI

- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py
> Fix random fails in chunk splitting test

- src/requirements-test.txt
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/vsids.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py
fixes #6192
`freezegun` is mighty useful...
> Fix corner-case bump amount problem in VSIDS

- experiment/popularity_community/initial_filling.py
- experiment/tunnel_community/hidden_peer_discovery.py
- experiment/tunnel_community/speed_test_exit.py
- src/tribler-core/tribler_core/utilities/tiny_tribler_service.py
Fixes https://github.com/Tribler/tribler/issues/6331 and partially fixes https://github.com/Tribler/tribler/issues/6373
The following experiments have been updated:
* initial_filling.py
* hidden_peer_discovery.py
* speed_test_exit.py
> Update experiments regarding to the latest changes in tribler-core

- src/tribler-core/tribler_core/components/bandwidth_accounting/bandwidth_accounting_component.py
- src/tribler-core/tribler_core/components/gigachannel/gigachannel_component.py
- src/tribler-core/tribler_core/components/gigachannel_manager/gigachannel_manager_component.py
- src/tribler-core/tribler_core/components/ipv8.py
- src/tribler-core/tribler_core/components/libtorrent.py
- src/tribler-core/tribler_core/components/metadata_store/metadata_store_component.py
- src/tribler-core/tribler_core/components/resource_monitor.py
- src/tribler-core/tribler_core/components/torrent_checker.py
- src/tribler-core/tribler_core/components/tunnels.py
- src/tribler-core/tribler_core/components/upgrade.py
- src/tribler-core/tribler_core/components/watch_folder.py
Minor fixes in components code:
* set missed readable status STATE_START_TORRENT_CHECKER in TorrentCheckerComponent
* remove unused imports in most components
> Components cleanup

- src/seedbox/disseminator.py
This PR fixes #6373 by applying to the `desseminator.py` the new components system.
> Fix disseminator.py

- src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
> Changed click box of 'create tags' message

- src/tribler-core/tribler_core/components/bandwidth_accounting/tests/test_bandwidth_endpoint.py
- src/tribler-core/tribler_core/components/bandwidth_accounting/tests/test_community.py
> Apply MockIPv8 key injection

- build/win/makedist_win.bat
- tribler.spec
This PR fixes different problems leading to incorrect build of Tribler release
> Fix one click release build

- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
This PR fixes #6513 by customizing categories for different pages.
> Customise categories for different pages

- src/tribler-common/tribler_common/tests/test_utils.py
- src/tribler-common/tribler_common/utilities.py
- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
> Fix bug with space inside filter field

- src/tribler-core/tribler_core/components/base.py
- src/tribler-core/tribler_core/components/tests/test_base_component.py
This PR adds the `maybe_component` function to the base component class.
It will help us simplify code with optional components.
> Add maybe_component

- src/tribler-core/tribler_core/components/metadata_store/remote_query_community/tests/test_remote_query_community.py
> Fix and speedup test_drop_silent_peers

- src/tribler-gui/tribler_gui/tribler_window.py
> Add the check on the empty completions_list

- src/tribler-core/tribler_core/components/libtorrent/download_manager/download_manager.py
> Fix key error on metainfo fetch

- src/tribler-core/tribler_core/components/reporter/exception_handler.py
- src/tribler-core/tribler_core/components/reporter/tests/test_exception_handler.py
- src/tribler-core/tribler_core/components/restapi/restapi_component.py
- src/tribler-gui/tribler_gui/event_request_manager.py
- src/tribler-gui/tribler_gui/exceptions.py
- src/tribler-gui/tribler_gui/tests/test_gui.py
- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/upgrade_manager.py
- src/tribler-gui/tribler_gui/widgets/discoveringpage.py
- src/tribler-gui/tribler_gui/widgets/loadingpage.py
- src/tribler-gui/tribler_gui/widgets/searchresultswidget.py
This PR adds some fixes related to #6582 
Also, fixes error buffering broken after startup refactoring.
> Fixes for GUI startup sequence

- src/tribler-gui/tribler_gui/debug_window.py
> Remove unused methods

- doc/requirements.txt
> Fixes #6624: specify the exact version of `mistune` library in doc/requirements.txt

- src/tribler-core/tribler_core/components/libtorrent/download_manager/download_manager.py
> Fix for #6627

- src/tribler-gui/tribler_gui/tests/test_gui.py
- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
fixes #6623  (courtesy of @devos50 )
I'll provide the test for the thing later on `main` - created[ an issue](#6631 ) for that.
> Fix for torrent renaming

- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
- src/tribler-gui/tribler_gui/widgets/searchresultswidget.py
> Refreshing viewport when showing search results

- src/tribler-gui/tribler_gui/tribler_request_manager.py
Fixes [a bug found by app tester](https://github.com/Tribler/tribler/blob/d0036df1e0c97a947fc3c5afb1cafdd60ed5bfd2/src/tribler-gui/tribler_gui/tribler_request_manager.py#L189)
> Fix rare race condition in TriblerRequestManager

- src/tribler-gui/tribler_gui/widgets/torrentfiletreewidget.py
> Fix incorrect comparison in FileTreeWidgetItem

- src/tribler-gui/tribler_gui/requirements.txt
> Fixes #6682 by specifying exact version of Numpy

- src/tribler-core/tribler_core/components/libtorrent/restapi/create_torrent_endpoint.py
- src/tribler-core/tribler_core/components/libtorrent/utils/torrent_utils.py
- src/tribler-core/tribler_core/utilities/tests/test_torrent_utils.py
fixes creating torrents from dir (reported by forum user)
related to #4674
> Fix creating torrent from dir

- doc/conf.py
- src/tribler-common/tribler_common/dependencies.py
> Add faker and sentry_sdk as common modules to mock during doc build

- src/tribler-core/tribler_core/components/metadata_store/db/store.py
Fixes #6721 by adding COLLATE NOCASE to column name in the ORDER BY section
> Make sorting by name case insensitive

- experiment/tunnel_community/speed_test_e2e.py
- experiment/tunnel_community/speed_test_exit.py
- src/tribler-core/tribler_core/components/restapi/restapi_component.py
Fixes #6471. This PR fixes tunnel experiments: ttps://jenkins-ci.tribler.org/job/tunnel_experiments/
Jenkins configuration was updated as well.
> Fix tunnel experiments

- src/tribler-core/tribler_core/components/metadata_store/remote_query_community/tests/test_remote_search_by_tags.py
- src/tribler-core/tribler_core/components/metadata_store/utils.py
- src/tribler-core/tribler_core/components/tag/db/tag_db.py
- src/tribler-core/tribler_core/components/tag/db/tests/test_tag_db.py
- src/tribler-core/tribler_core/components/tag/restapi/tests/test_tags_endpoint.py
As was shown by @devos50 in https://github.com/Tribler/tribler/issues/6214#issuecomment-1014579515 our current show threshold is too high.
So, this PR decreases this threshold and sets it to `1`
> Decrease show threshold for tags

- src/tribler-core/tribler_core/start_core.py
> Fixes #6745: Missed dependency: PopularityComponent requires TorrentCheckerComponent to be active

- src/tribler-gui/tribler_gui/start_gui.py
Fixes https://github.com/Tribler/tribler/issues/6701
> Fix Ubuntu 21.04+ startup issue

- .github/workflows/docker-image.yml
- Dockerfile
This PR should fix https://github.com/Tribler/tribler/actions/runs/1917000629
> Fix docker build

- src/README.md
This PR fixes the broken link at https://github.com/Tribler/tribler/blob/main/src/README.md and closes #6795
> Fix broken link

- src/tribler/gui/tribler_window.py
> Handle OSError in TriblerWindow.clicked_force_shutdown()

- src/tribler/gui/debug_window.py
> Fix a crash in the Events tab of the Debug pane

- src/tribler/gui/tribler_app.py
> Add NPE check to handle_uri

- src/tribler/core/components/metadata_store/restapi/tests/conftest.py
- src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py
This PR fixes #6616 by removing random (which could lead to some rarely occurred bugs) from `add_fake_torrents_channels` fixture.
> Refactor add_fake_torrents_channels fixture

- src/tribler/gui/tribler_window.py
- src/tribler/gui/utilities.py
This PR fixes #6834 by adding the check on existing folder with the following message box:
> Add `is_dir()` check to  `add_directory_dialog`

- src/tribler/core/components/libtorrent/download_manager/download.py
Fixes #6843 by adding logging for LibTorrent events in the `Download` class.
> Add logging for LibTorrent events

- .github/workflows/codacy.yml
> Use project-token for codacy

- README.rst
This PR adds codacy coverage badge to the `readme.rst`
Related to #6847
> Add coverage badge

- .github/workflows/upload_coverage.yml
This PR adds a step to `upload_coverage` to upload a coverage report to `codecov`.
https://docs.codecov.com/docs
Related to #6847
> Add codecov

- src/tribler/core/components/libtorrent/download_manager/download_config.py
- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/libtorrent/settings.py
- src/tribler/core/components/libtorrent/tests/test_download_api.py
- src/tribler/core/components/watch_folder/tests/test_watch_folder.py
- src/tribler/core/components/watch_folder/watch_folder.py
- src/tribler/core/components/watch_folder/watch_folder_component.py
- src/tribler/core/start_core.py
> Fix watch folder feature

- src/tribler/core/components/ipv8/eva_protocol.py
- src/tribler/core/components/ipv8/tests/test_eva_protocol.py
This PR addresses #6845 
1. Adds an array for incoming messages
2. Corrects calculating of `window_size` limits
3. Improves the final binary array calculation
> EVA: add incoming array

- src/tribler/gui/dialogs/dialogcontainer.py
- src/tribler/gui/tribler_window.py
> Handle `close_event` for `on_add_torrent_from_url`

- src/tribler/core/components/ipv8/eva/exceptions.py
- src/tribler/core/components/ipv8/eva/tests/test_protocol.py
- src/tribler/core/components/ipv8/eva/transfer/base.py
- src/tribler/core/components/ipv8/eva/transfer/incoming.py
- src/tribler/core/components/ipv8/eva/transfer/outgoing.py
- src/tribler/core/components/ipv8/eva/transfer/tests/test_base.py
- src/tribler/core/components/ipv8/eva/transfer/tests/test_incoming.py
- src/tribler/core/components/ipv8/eva/transfer/tests/test_outgoing.py
- src/tribler/core/components/ipv8/eva/transfer/tests/test_window.py
This PR fixes #6890 by adding correct handling of canceled future.
> EVA: Process future cancellation

- build/debian/makedist_debian.sh
- build/mac/makedist_macos.sh
- build/win/makedist_win.bat
- build/win/requirements.txt
- requirements-core.txt
- requirements-test.txt
- src/tribler/core/logger/logger.py
- src/tribler/core/logger/logger_streams.py
- src/tribler/gui/code_executor.py
- src/tribler/gui/tribler_app.py
- src/tribler/gui/tribler_window.py
- tribler.spec
This PR fixes various build problem for release 7.12
> Fix build for release 7.12

- build/debian/makedist_debian.sh
- requirements-build.txt
This PR updates the Debian build script to either user virtual env set via environment variable or create a new one. Using the existing venv leads to quicker build and using a new venv makes sure that there are no missing dependencies.
> Update Debian build

- .github/workflows/guitest.yml
> Add guitest.yml

- src/tribler/gui/widgets/downloadprogressbar.py
> Fix download progressbar paint issue

- src/tribler/core/utilities/async_group.py
This PR corrects outdated `AsyncGroup` documentation.
> Fix `AsyncGroup` documentation

- src/tribler/gui/tribler_window.py
Fixes #6979 and replaces unused arguments to underscore in some similar functions
> Fix TypeError in on_add_torrent_browse_file

- src/tribler/core/components/metadata_store/db/orm_bindings/torrent_metadata.py
Fixes https://github.com/Tribler/tribler/issues/6990
> Handle TypeError on tdef to metadata conversion

- src/tribler/core/components/gui_process_watcher/gui_process_watcher.py
- src/tribler/core/components/gui_process_watcher/gui_process_watcher_component.py
- src/tribler/core/components/gui_process_watcher/tests/test_gui_process_watcher.py
- src/tribler/core/components/gui_process_watcher/tests/test_gui_process_watcher_component.py
- src/tribler/core/start_core.py
- src/tribler/gui/core_manager.py
This PR cherrypicks #6995 to the release branch
> Cherrypick GuiProcessWatcher to the release branch

- .github/workflows/guitest.yml
This PR contains fix cherry-picked to main from #6982
> Fix failing GUI test on Linux Github action

- src/tribler/gui/core_manager.py
> EventManager's timeout should ignore the upgrade duration

- src/tribler/gui/tribler_window.py
This PR fixes #6973 by rewriting the logic of restoring Tribler window position and size.
Now if any part of the Tribler window is outside of screen boundaries, the window moves to the position (0, 0)
> Rewrite window geometry restoring

- src/tribler/core/components/libtorrent/tests/test_download.py
This PR closes #5833 by adding the test `test_on_save_resume_data_alert_permission_denied` (which proves that the core issue is fixed).
> Ensure that #5833 is fixed

- src/tribler/gui/event_request_manager.py
- src/tribler/gui/tribler_request_manager.py
> An attempt to fix QNetworkReply.UnknownNetworkError (99) when connecting to Core

- src/tribler/gui/core_manager.py
A small improvement for https://github.com/Tribler/tribler/pull/7022
> Change the category for core stderr breadcrumbs

- src/tribler/core/components/restapi/restapi_component.py
This PR cherry-picks #7044 to the release branch
> Fix initialization of Ipv8Endpoint in RESTComponent

- src/tribler/gui/tribler_window.py
> Hide token balance value

- src/tribler/gui/widgets/torrentfiletreewidget.py
> Fixes #7051 "Windows fatal exception: stack overflow" for a torrent with a deep directory structure

- Dockerfile
- README.rst
- doc/restapi/introduction.rst
- docker-compose.yml
- scripts/bandwidth_crawler/run_bandwidth_crawler.py
- scripts/exit_node/run_exit_node.py
- src/tribler/core/components/restapi/rest/events_endpoint.py
- src/tribler/core/utilities/network_utils.py
- src/tribler/gui/defs.py
- src/tribler/gui/i18n/pt_BR.ts
- src/tribler/gui/i18n/ru_RU.ts
- src/tribler/gui/i18n/zh_CN.ts
- src/tribler/gui/qt_resources/mainwindow.ui
This PR partially fixes #7065 by changing the default port number from `52194` to `20100`.
Ref:
* https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
* https://en.wikipedia.org/wiki/Ephemeral_port
> Change default port from 52194 to 20100

- src/tribler/core/version.py
This PR updates the Tribler version to `7.12.1`
> Update the Tribler version

- .gitignore
- scripts/exit_node/run_exit_node.py
- scripts/experiments/tunnel_community/hidden_peer_discovery.py
- scripts/experiments/tunnel_community/speed_test_e2e.py
- scripts/experiments/tunnel_community/speed_test_exit.py
- scripts/seedbox/disseminator.py
This PR fixes #7088
Also, I made a change to the Jenkins job:
https://jenkins-ci.tribler.org/job/tunnel_experiments/job/speed_test_e2e/
> Fix `speed_test_e2e.py`

- .github/actions/pyenv/action.yml
- .github/actions/windows_dependencies/action.yml
- .github/workflows/build_mac.yml
- .github/workflows/build_windows.yml
- .github/workflows/pytest_custom_ipv8.yml
This PR fixes #7085 by updating the following actions to the most latest version:
* `actions/setup-python`
* `andstor/file-existence-action`
> Update GitHub Actions versions

- src/tribler/core/components/gui_process_watcher/tests/test_gui_process_watcher.py
This PR fixes #7118 by removing `caplog` from async functions of `test_gui_process_watcher.py`. It seems that the logging sequence is not stable.
> Remove `caplog` from async functions `test_gui_process_watcher.py`

- src/tribler/core/components/gigachannel/community/tests/test_gigachannel_community.py
This PR fixes #7120 by increasing `EvaSelectRequest` timeout for test_remote_select_channel_contents_happy_eyeballs`
> Increase `EvaSelectRequest` timeout  for `test_remote_select_channel_contents_happy_eyeballs`

- src/tribler/core/components/metadata_store/restapi/channels_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py
- src/tribler/core/utilities/tests/test_utilities.py
- src/tribler/core/utilities/utilities.py
> Fix adding torrent with invalid magnet link to channel

- requirements-core.txt
- requirements-test.txt
This PR is related to https://github.com/Tribler/tribler/issues/7122 by updating dependencies.
> Update "io" and "pytest" dependencies

- .github/workflows/!PR.yml
> Disable macOS build

- src/tribler/gui/widgets/lazytableview.py
> Check whether index.model() is None

- src/tribler/core/components/gigachannel/community/tests/test_gigachannel_community.py
This PR fixes #7161 by refactoring the test.
> Refactoring of the `test_drop_silent_peer`

- src/tribler/core/components/restapi/rest/debug_endpoint.py
- src/tribler/core/utilities/path_util.py
- src/tribler/gui/debug_window.py
This PR fixes #7172 and closes #7067.
> Refactor get max_lines logic

- src/tribler/core/components/knowledge/knowledge_component.py
> Add shutdown for the Rules Processor

- src/tribler/core/components/ipv8/eva/transfer/tests/test_base.py
> Add task_group.wait()

- src/tribler/core/components/tunnel/tests/test_triblertunnel_community.py
- src/tribler/core/conftest.py
> Add `unload` for Tunnel Community

- src/tribler/core/components/restapi/rest/events_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_events_endpoint.py
- src/tribler/core/components/restapi/restapi_component.py
> Add `EventsEndpoint.shutdown()`

- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
Fixes https://github.com/Tribler/tribler/issues/7059
> Handle non-existing file in torrent info endpoint

- src/tribler.sh
> link detection fix

- src/tribler/core/utilities/tests/test_process_checker.py
This PR fixes #7164 by removing the following dependency on a real process from `ProcessChecker` tests:
```python
def idle():
sleep(1)
@pytest.fixture
def process():
process = Process(target=idle)
process.start()
yield psutil.Process(process.pid)
process.kill()
```
It also removes two tests that were too OS dependent (`test_check` and `test_check_zombie`).
> Remove the dependency on a real process from `ProcessChecker` tests

- src/tribler/gui/dialogs/startdownloaddialog.py
> Add check on empty folder

- src/tribler/gui/tribler_window.py
> Do not load Debug Window if settings is not available yet

- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/tests/test_download.py
> Fix UnicodeDecodeError in on_metadata_received_alert

- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
> Add the ClientConnectorError to the exceptions

- src/tribler/core/components/torrent_checker/torrent_checker/tests/test_torrentchecker.py
> Add session.cleanup()

- requirements-core.txt
> Update `yappi` version

- .github/workflows/!PR.yml
This PR implicitly specifies the ubuntu and windows version for binaries builds.
> Specify ubuntu and win versions

- .github/workflows/build_mac.yml
- .github/workflows/build_ubuntu.yml
- .github/workflows/build_windows.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
- .github/workflows/scripttest.yml
This PR add `github.ref` for the events: `push` and `workflow_dispatch`
> Add `github.ref` for the events: `push` and `workflow_dispatch`

- src/tribler/core/components/version_check/tests/test_versioncheck.py
This PR closes #5816, ensuring that the refactoring done in #7128 has fixed #5816
> Add `test_check_urls_error`

- src/tribler/core/components/gigachannel_manager/gigachannel_manager.py
- src/tribler/core/components/gigachannel_manager/tests/test_gigachannel_manager.py
- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/torrentdef.py
- src/tribler/core/components/metadata_store/db/tests/test_torrent_metadata.py
- src/tribler/core/components/metadata_store/restapi/tests/test_metadata_endpoint.py
- src/tribler/core/components/metadata_store/tests/test_channel_metadata.py
- src/tribler/core/components/restapi/rest/tests/test_debug_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_settings_endpoint.py
- src/tribler/core/components/torrent_checker/torrent_checker/tests/test_tracker_manager.py
- src/tribler/core/utilities/sentinels.py
- src/tribler/gui/widgets/downloadsdetailstabwidget.py
- src/tribler/gui/widgets/settingspage.py
> Fix medium issues reported by Codacy

- build/mac/makedist_macos.sh
> Pin pip version for the macOS build

- src/tribler/gui/dialogs/editmetadatadialog.py
> Check EditMetadataDialog on closed

- src/tribler/core/components/knowledge/rules/knowledge_rules_processor.py
Fixes https://github.com/Tribler/tribler/issues/7389. The solution was suggested by @kozlovsky.
> Add serializable on db_session for tags batch processing

- src/tribler/core/utilities/path_util.py
- src/tribler/core/utilities/tests/test_path_utils.py
- src/tribler/gui/widgets/settingspage.py
> Fix `FileNotFoundError`

- src/tribler/core/utilities/process_manager/process.py
- src/tribler/core/utilities/process_manager/tests/test_process.py
> Fix TriblerProcess.is_running()

- src/tribler/core/sentry_reporter/sentry_scrubber.py
- src/tribler/core/sentry_reporter/tests/test_sentry_scrubber.py
This PR fixes a bug in the Sentry Scrubber discovered by @kozlovsky 
See the example of the bug: https://sentry.tribler.org/organizations/tribler/issues/2105/
> Fix the space bug in the Sentry Scrubber

- requirements-test.txt
> Update libraries for testing to the latest versions.

- requirements-core.txt
This PR updates core requirements for Tribler.
> Update core requirements

- requirements-core.txt
> Bump the `ipv8` version

- requirements-test.txt
- src/tribler/core/components/libtorrent/conftest.py
- src/tribler/core/components/libtorrent/tests/conftest.py
- src/tribler/core/components/libtorrent/tests/test_download.py
- src/tribler/core/utilities/tests/test_utilities.py
This PR updates versions of test dependencies and removes unused ones.
> Actualize test dependencies

- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
- Fixes https://github.com/Tribler/tribler/issues/7547
> Catch TimeoutError on importing torrent from HTTP URL

- src/tribler/gui/dialogs/createtorrentdialog.py
- src/tribler/gui/dialogs/tests/test_createtorrentdialog.py
- src/tribler/gui/tests/test_utilities.py
- src/tribler/gui/utilities.py
- Fixes https://github.com/Tribler/tribler/issues/7531
> Fix creating torrent with name containing escape characters

- src/tribler/core/components/ipv8/discovery_booster.py
> Increase the default value of the `take_step_interval_in_sec`

- src/tribler/core/check_os.py
- src/tribler/core/tests/test_check_os.py
> Catch `AccessDenied` exception

- src/tribler/core/sentry_reporter/sentry_reporter.py
This PR fixes #7556 in the release branch. We decided to update the Sentry version in the main branch in a separate PR to avoid possible accident instability in the release branch.
> Fix "ConnectionResetError: connection lost"

- src/tribler/core/utilities/slow_coro_detection/watching_thread.py
> Fix race condition in SlowCoroWatchingThread

- src/tribler/core/utilities/slow_coro_detection/utils.py
> Fixes #7600: handle exceptions in task.print_stack()

- src/tribler/core/components/restapi/rest/rest_manager.py
This PR cleans up the remaining stuff after the wait_for removal in #7617
> Clean up rest_manager.py after removing wait_for in #7617

- src/tribler/core/utilities/process_manager/manager.py
- src/tribler/core/utilities/process_manager/tests/test_manager.py
> Add the reason for the OperationalError 'unable to open database file' when opening processes.sqlite

- src/tribler/core/utilities/tests/test_pony_utils.py
This PR should fix a flaky test `test_patched_db_session`:
https://github.com/Tribler/tribler/actions/runs/6530502005/job/17729909354?pr=7622#step:6:2735
> Fix flaky test_patched_db_session

- .github/workflows/!PR.yml
This PR adds the `gatekeeper` to the `scripttest`.
> Add the `gatekeeper` to the `scripttest`

- src/tribler/gui/tests/test_gui.py
This PR addresses [the following error](https://github.com/Tribler/tribler/actions/runs/6770856920/job/18400104463?pr=7667#step:10:313) by increasing timeout from 10 seconds to 20 seconds.
```python
ERROR src/tribler/gui/tests/test_gui.py::test_trust_page - tribler.gui.tests.test_gui.TimeoutException: 
Signal <bound PYQT_SIGNAL finished of QProcess object at 0x11cc55160> not raised within 10 seconds
``` 
Also, it disables `test_trust_page` and `test_big_negative_token_balance` as these elements are no longer in UI.
> Update GUI tests

- src/tribler/core/components/metadata_store/restapi/tests/test_search_endpoint.py
This PR adds a test for #7578 
Closes #7657
> Add test for #7578

- build/win/resources/tribler.nsi
Fixes #6221 (see https://github.com/Tribler/tribler/issues/6221#issuecomment-1798623853 for elaborate details)
Fixes #7475
> Write install dir to the registry in Windows installer

- src/tribler/core/upgrade/db8_to_db10.py
- src/tribler/core/upgrade/tests/test_db8_to_db10.py
> Handle an absent `db_version` for Upgrader.

- .github/workflows/!PR.yml
- .github/workflows/coverage.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
- requirements-test.txt
This PR is a possible fix for #7706, see: https://github.com/Tribler/tribler/issues/6606#issuecomment-1820768727
Related: #6606
> Remove `pytest-sentry`

- scripts/application_tester/tribler_apptester/action_selector.py
- scripts/application_tester/tribler_apptester/data/action_weights.txt
- scripts/application_tester/tribler_apptester/executor.py
This PR contains refactoring for the Application Tester aimed to simplify future work on #7750.
It adds a new `ActionSelector` class that is responsible for selecting a random action based on the probabilities given to each action. The `ActionSelector` class has been implemented in the file `action_selector.py`.
The `ActionSelector` class contains a dictionary of actions with their corresponding probabilities. Each action is associated with a lambda function that returns an instance of the action and its probability. The `get_random_action_with_probability()` method selects a random action from the dictionary based on the probabilities and returns an instance of that action.
The code in the `Executor` class has been modified to use the `ActionSelector` class for performing random actions. …
> Add ActionSelector class for selecting random actions

- .github/actions/add-pythonpath/action.yml
- .github/workflows/!PR.yml
- .github/workflows/application_tester.yml
- .github/workflows/scripttest.yml
- scripts/application_tester/tribler_apptester/action_selector.py
The PR introduces Application Tester as a mandatory check for pull requests (PRs) in the Tribler development workflow. It automates the execution of Application Tester for each PR, ensuring that the application undergoes functional testing before it can be merged into the codebase.
Specifically, the PR implements two distinct testing scenarios:
- **Draft PR Checks**: For each draft PR, Application Tester is executed for two minutes on the Ubuntu operating system. This initial testing phase provides early feedback on potential issues during the PR's development stage.
- **Ready PR Checks**: Once a PR reaches the "ready" status, indicating its completion, Application Tester is run for two minutes on three different operating systems: Ubuntu, Windows, and macOS. This comprehensive testing …
> Add the Application Tester to the PR checks

- scripts/application_tester/tribler_apptester/config/tribler_config.spec
- scripts/exit_node/run_exit_node.py
- src/tribler/core/components/restapi/rest/debug_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_debug_endpoint.py
This PR removes leftovers of competing slots configuration.
Related:
- #7798
> Remove leftovers of competing slots configuration.

- src/tribler/core/components/content_discovery/restapi/search_endpoint.py
> Fix an error in Swagger endpoint's description

- src/tribler/core/components/libtorrent/torrentdef.py
- src/tribler/core/utilities/maketorrent.py
This refactoring was carried out during the work on:
- https://github.com/Tribler/tribler/issues/7801
> Add typings for the TorrentDef class

- src/tribler/gui/i18n/es_ES.ts
- src/tribler/gui/i18n/pt_BR.ts
- src/tribler/gui/i18n/ru_RU.ts
- src/tribler/gui/i18n/zh_CN.ts
This PR fixes https://github.com/Tribler/tribler/issues/7809
> Remove `Bandwidth Accounting` string leftovers

- src/tribler/core/components/database/db/layers/knowledge_data_access_layer.py
- src/tribler/core/components/knowledge/community/knowledge_community.py
This PR updates outdated descriptions in `KnowledgeCommunity`. The fact that they are outdated became apparent while working on:
- #6214
> KnowledgeCommunity : Update outdated descriptions

- doc/restapi/introduction.rst
- src/tribler/gui/i18n/pt_BR.ts
Closes #7809. The removed lines are no longer in use.
> Remove trustview endpoint and Trust Graph translation

- scripts/application_tester/tribler_apptester/actions/change_download_files_action.py
Fixes https://github.com/Tribler/tribler/issues/7822 which is one of the issues where PR application tester check occasionally fails.
> Fix application tester bug on clicking torrent files to select in case of large torrent

- .github/actions/pyenv/action.yml
- .github/workflows/!PR.yml
- .github/workflows/!main.yml
- .github/workflows/application_tester.yml
- .github/workflows/build_mac.yml
- .github/workflows/build_ubuntu.yml
- .github/workflows/build_windows.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
- .github/workflows/pytest_custom_ipv8.yml
- .github/workflows/scripttest.yml
- .readthedocs.yml
- doc/development/development_on_windows.rst
> Upgrade Python version to `3.9`

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
> Fix download using magnetlink without metainfo

- README.rst
> Update README.rst with stats of latest release

- .github/actions/pyenv/action.yml
- .github/actions/windows_dependencies/action.yml
- .github/workflows/!PR.yml
- .github/workflows/application_tester.yml
- .github/workflows/build_mac.yml
- .github/workflows/build_ubuntu.yml
- .github/workflows/build_windows.yml
- .github/workflows/coverage.yml
- .github/workflows/docker-image.yml
- .github/workflows/documentation.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
- .github/workflows/pytest_custom_ipv8.yml
- .github/workflows/scripttest.yml
- .github/workflows/second_reviewer.yml
This PR addresses most of the warnings listed in
- #7881
For the results of the test run see: https://github.com/Tribler/tribler/actions/runs/7869311755
> Update GitHub Actions versions and dependencies

- requirements-core.txt
Fixes https://github.com/Tribler/tribler/issues/7922.
> Update ipv8-rust-tunnels to 0.1.16

- src/tribler/core/utilities/pony_utils.py
This PR fixes #7728 by closing all database connections after the db_session finishes.
If we plan to release a bugfix version for the current release, it is worth to cherry-pick this fix to the current release branch as well, as some reported access violations can be caused by this problem as well.
> Close database connections after exiting from the db_session to avoid access violation on Python 3.10

- requirements.txt
> Update requirements to be able to install them on Python 3.10

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/restapi/create_torrent_endpoint.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
- src/tribler/core/components/restapi/rest/tests/test_create_torrent_endpoint.py
This PR removes unused code from `Download Manager`.
Related: 
- https://github.com/Tribler/tribler/issues/7886
> Download Manager: remove unused code.

- .github/workflows/!PR.yml
Fixes #7238 
Ref:
* https://github.com/actions-cool/check-user-permission
* https://github.com/agilepathway/label-checker
* https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
> Update the `gatekeeper` job

- build/mac/makedist_macos.sh
> Fix binary building on Mac with PyInstaller

- src/tribler/gui/widgets/downloadwidgetitem.py
> Fix #8026 KeyError when sorting by the RATIO column

- src/tribler/gui/dialogs/feedbackdialog.py
> Fix sending user comments as part of a Sentry report

- .ruff.toml
- src/tribler/core/session.py
Fixes https://github.com/Tribler/tribler/issues/8090.
> Catch ClientConnectorError in _is_url_available

- src/tribler/ui/public/locales/en_US.json
- src/tribler/ui/public/locales/es_ES.json
- src/tribler/ui/public/locales/pt_BR.json
- src/tribler/ui/public/locales/ru_RU.json
- src/tribler/ui/public/locales/zh_CN.json
- src/tribler/ui/src/App.tsx
- src/tribler/ui/src/services/ipv8.service.ts
- src/tribler/ui/src/services/reporting.ts
- src/tribler/ui/src/services/tribler.service.ts
Fixes #8117
This PR:
- Adds an error reporting feature in the GUI.
> Added an error reporter

- .github/workflows/build.yml
- build/mac/makedist_macos.sh
Fixes #5382
This PR:
- Updates the build Action to remove non-essential files, like tests.
> Remove non-essential files for build

- .github/workflows/build_docker.yml
Fixes #8125
This PR:
- Fixes the Docker tags not being lowercase.
> Made Docker tags lowercase

- src/tribler/core/restapi/events_endpoint.py
- src/tribler/core/session.py
- src/tribler/test_unit/core/restapi/test_events_endpoint.py
- src/tribler/ui/src/services/reporting.ts
- src/tribler/ui/src/services/tribler.service.ts
Fixes #8137
This PR:
- Adds uncaught exception forwarding to the GUI.
> Reintroduced general exception handler

- src/tribler/ui/src/components/layouts/Header.tsx
Fixes https://github.com/Tribler/tribler/issues/8147.
> Make shutdown logs scrollable

- build/mac/entitlements.plist
I made one untested change to my test file. Now corrected.
> Fixed entitlements comment

- doc/building/linux.rst
This PR:
- Fixes Linux build requirements
> Fixed Linux build requirements

- src/tribler/ui/src/pages/Downloads/Details.tsx
- src/tribler/ui/src/pages/Downloads/Pieces.tsx
This PR:
- Fixes the progress bar being too long for torrents with less than modulo 8 pieces.
> Fixed rendering b64 total pieces decoding

- src/run_unit_tests.py
- src/tribler/core/components.py
- src/tribler/core/recommender/community.py
- src/tribler/core/recommender/manager.py
- src/tribler/core/recommender/orm_query.py
- src/tribler/core/recommender/payload.py
- src/tribler/core/recommender/restapi/endpoint.py
- src/tribler/core/session.py
- src/tribler/test_unit/core/recommender/test_community.py
- src/tribler/test_unit/core/recommender/test_manager.py
- src/tribler/test_unit/core/recommender/test_payload.py
- src/tribler/tribler_config.py
- src/tribler/ui/src/pages/Search/index.tsx
- src/tribler/ui/src/services/tribler.service.ts
Fixes #8183
This PR:
- Adds a new recommender component, to gather infohash hierarchy information to serve as a basis for future AI result ranking.
- Updates the `Session` to log uncaught exceptions in the core.
For some reason, this PR pushed the Mac over the edge and it started failling consistently due to `getaddrinfo` blocking. So, I also fixed that in this PR.
> Added recommender component

- src/tribler/core/components.py
This PR:
- Adds active walking to the `RecommenderComponent` to make it faster.
> Add more active recommender walking

- src/tribler/core/content_discovery/community.py
- src/tribler/core/libtorrent/restapi/create_torrent_endpoint.py
- src/tribler/core/restapi/events_endpoint.py
- src/tribler/core/restapi/rest_manager.py
- src/tribler/test_unit/core/content_discovery/test_community.py
- src/tribler/test_unit/core/restapi/test_events_endpoint.py
Fixes #8223
This PR:
- Updates `Tribler Experimental` strings to reflect the running version.
> Updated instances of 'Tribler Experimental'

- src/tribler/ui/src/components/ui/simple-table.tsx
- src/tribler/ui/src/pages/Debug/Asyncio/index.tsx
- src/tribler/ui/src/pages/Debug/DHT/index.tsx
- src/tribler/ui/src/pages/Debug/IPv8/Overlays.tsx
- src/tribler/ui/src/pages/Debug/IPv8/index.tsx
- src/tribler/ui/src/pages/Debug/Libtorrent/index.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/index.tsx
- src/tribler/ui/src/pages/Downloads/Details.tsx
This PR fixes a number of small issues with the UI, including a scrolling issue in the `DownloadDetails` panel.
> Fix DownloadDetails scroll issue

- src/tribler/ui/src/dialogs/SelectRemotePath.tsx
- src/tribler/ui/src/pages/Downloads/index.tsx
- src/tribler/ui/src/pages/Popular/index.tsx
- src/tribler/ui/src/pages/Search/index.tsx
Fixes https://github.com/Tribler/tribler/issues/8260.
> Fix dealing with large swarm names

- src/tribler/upgrade_script.py
Fixes #8270
Fixes #8271
This PR:
- Fixes all old config values importing as strings.
> Fixed all old config values being strings

- src/tribler/core/libtorrent/download_manager/download_manager.py
Fixes #8286
This PR:
- Fixes a locally added torrent not appearing in the search results.
> Notify updated metadata after starting handle

- src/tribler/ui/src/contexts/ThemeContext.tsx
- src/tribler/ui/src/models/settings.model.tsx
Fixes https://github.com/Tribler/tribler/issues/8310.
> Move theme setting to guiSettings

- src/tribler/ui/package-lock.json
- src/tribler/ui/package.json
- src/tribler/ui/src/components/ui/simple-table.tsx
- src/tribler/ui/src/lib/utils.ts
Fixes https://github.com/Tribler/tribler/issues/8370.
> Allow use of shift/control keys while changing row selection

- src/tribler/ui/src/lib/utils.ts
- src/tribler/ui/src/pages/Downloads/Actions.tsx
Fixes https://github.com/Tribler/tribler/issues/8385.
> Support changing the storage folder for multiple torrents at once

- src/tribler/ui/src/pages/Search/index.tsx
Fixes https://github.com/Tribler/tribler/issues/8378.
Fixes https://github.com/Tribler/tribler/issues/8397.
> Fix for processing search events

- src/run_tribler.py
This PR:
- Fixes some minor typing issues in `run_tribler`.
These light up my PyCharm like a Christmas tree and I'm tired of looking at them :-)
> Fixed typing warnings in run_tribler

- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/download_manager/download_config.py
- src/tribler/core/libtorrent/restapi/downloads_endpoint.py
- src/tribler/ui/public/locales/en_US.json
- src/tribler/ui/public/locales/es_ES.json
- src/tribler/ui/public/locales/ko_KR.json
- src/tribler/ui/public/locales/pt_BR.json
- src/tribler/ui/public/locales/ru_RU.json
- src/tribler/ui/public/locales/zh_CN.json
- src/tribler/ui/src/components/path-input.tsx
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/ui/src/models/download.model.tsx
- src/tribler/ui/src/models/downloadconfig.model.tsx
- src/tribler/ui/src/models/settings.model.tsx
- src/tribler/ui/src/pages/Downloads/Details.tsx
- src/tribler/ui/src/pages/Settings/General.tsx
Fixes https://github.com/Tribler/tribler/issues/2901.
> Add option to move completed downloads to a different folder

- doc/basics/docker.rst
This PR:
- Updates the main Docker "Running" command to work with the latest Docker image.
> Updated docker running docs

- src/tribler/ui/src/components/ui/simple-table.tsx
Fixes https://github.com/Tribler/tribler/issues/8475.
> Fix for initializing column visibility

- src/tribler/ui/src/components/ui/simple-table.tsx
Fix storing/loading the sorting state, which I broke in https://github.com/Tribler/tribler/pull/8480.
> Fix for storing the sorting state

- src/tribler/core/database/store.py
- src/tribler/core/recommender/manager.py
- src/tribler/core/rendezvous/database.py
Fixes #8511 halfway: the other half is in https://github.com/flathub/org.tribler.Tribler/pull/28
This PR:
- Fixes Tribler crashing if the database directory does not exist.
> Ensure db directories exist

- src/tribler/ui/src/components/ui/simple-table.tsx
Fixes https://github.com/Tribler/tribler/issues/8517.
> Fix multi select

- src/tribler/ui/src/pages/Downloads/index.tsx
Fixes https://github.com/Tribler/tribler/issues/8452.
> Add button to clear download filter

- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/torrents.py
- src/tribler/test_unit/core/libtorrent/test_torrents.py
This PR:
- Updates `check_handle` and `require_handle` to pass valid handles, avoiding `cast()` everywhere.
> Updated handle decorators to pass valid handles

- src/tribler/ui/src/lib/utils.ts
- src/tribler/ui/src/pages/Downloads/Files.tsx
Fixes https://github.com/Tribler/tribler/issues/8579.
> Fix file tree

- src/tribler/core/libtorrent/download_manager/download_manager.py
Currently, downloads can get stuck in the "Loading" state indefinitely when the DHT fails to get nodes. This could happen e.g. when you're behind a VPN.
There's a `timeout` that cancels the `DownloadManager.dht_ready_task`, which ensures that a single download starts. However, all remaining downloads remain stuck (awaiting a cancelled task throws a `CancelledError`, so `_async_add_torrent` never completes).
Note that this wasn't an issue until recently, when we started using `timeout`, which actually cancels the task itself. Before, the task kept running until shutdown (or enough nodes were discovered).
This PR:
* Fixes the above mentioned behaviour.
* Changes the check such that once the timeout passes, all subsequent downloads won't have to wait anymore.
* Ensures that we're checking …
> Fix DHT readiness check

- .github/workflows/build_docker.yml
Should fix the failing build https://github.com/Tribler/tribler/actions/runs/15164331490/job/42638058587
> Fixed Docker ghcr tag names

- src/tribler/core/libtorrent/download_manager/download_manager.py
Fixes https://github.com/Tribler/tribler/issues/8596 which can occur due to poorly managed metainfo downloads. To be safe, I'll also limit the maximum download rate of metainfo downloads, but I'll do this in a separate PR.
This PR:
* Fixes an issue where if a download can get metainfo after the timeout, it will fully download to the temp folder without ever being removed. It has been part of our code base for 2 years now (https://github.com/Tribler/tribler/commit/81c4bb839b0a8215040d844aa680e75fee8685dc). To fix this, I've added a `finally` clause to `get_metainfo`.
* Fixes an issue where if `get_metainfo` gets called without the DHT being ready yet, it will timeout and remove the download. However, it won't remove the handle from the session, since there's no handle available yet. If the …
> Fix ghost downloads

- src/tribler/core/components.py
- src/tribler/core/database/orm_bindings/misc.py
- src/tribler/core/database/store.py
- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/core/libtorrent/download_manager/stream.py
- src/tribler/core/libtorrent/restapi/create_torrent_endpoint.py
- src/tribler/core/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/libtorrent/restapi/libtorrent_endpoint.py
- src/tribler/core/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler/core/libtorrent/trackers.py
- src/tribler/core/recommender/community.py
- src/tribler/core/restapi/events_endpoint.py
- src/tribler/core/restapi/rest_endpoint.py
- src/tribler/core/restapi/rest_manager.py
- src/tribler/core/socks5/aiohttp_connector.py
- src/tribler/core/socks5/udp_connection.py
- src/tribler/core/torrent_checker/torrent_checker.py
- src/tribler/core/torrent_checker/torrentchecker_session.py
- src/tribler/core/torrent_checker/tracker_manager.py
- src/tribler/test_unit/core/content_discovery/test_community.py
- src/tribler/test_unit/core/recommender/test_community.py
- src/tribler/upgrade_script.py
This PR:
- Fixes some type issues found by `typeshed` (ignoring false positives).
- Fixes all style issues found by `ruff`.
> Minor style and typing fixes

- src/tribler/ui/src/pages/Settings/Seeding.tsx
Fixes https://github.com/Tribler/tribler/issues/8680.
> Fix incorrect seeding mode value
