Tribler/tribler

- src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_eva_protocol.py
This PR fixes #6167 by disabling terminating EVA session by timeout in `test_multiply_duplex`
> Disable EVA terminate by timeout in test_multiply_duplex

- src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_gigachannel_community.py
- src/tribler-core/tribler_core/modules/popularity/tests/test_popularity_community.py
- src/tribler-core/tribler_core/modules/remote_query_community/tests/test_remote_query_community.py
This PR fixes #6158 by adding shutdown call to each `mds` instance created.
```python
async def tearDown(self):
self.mds.shutdown()
await super().tearDown()
```
For the history, if you want to use tmpdir from pytest, you could use this trick:
```python
class MyTest(TestBase):
@pytest.fixture(autouse=True)
def init_tmpdir(self, tmpdir):
self.tmpdir = tmpdir
```
> Add shutdown call to each mds instance created inside RQC tests

- src/tribler-core/tribler_core/modules/popularity/popularity_community.py
- src/tribler-core/tribler_core/modules/popularity/test_version_community_mixin.py
- src/tribler-core/tribler_core/modules/popularity/version_community_mixin.py
This community mixin add two messages to request and receive Tribler version and platform of the peer.
- VersionRequest: 101
- VersionResponse: 102
These community messages are not used for the normal operation of Tribler but will be useful for network experiments. Currently, Popularity community is implementing this mixin.
> Add version community mixin

- src/run_tribler.py
- src/tribler-core/run_bandwidth_crawler.py
- src/tribler-core/tribler_core/modules/bandwidth_accounting/launcher.py
- src/tribler-core/tribler_core/modules/bandwidth_accounting/settings.py
- src/tribler-core/tribler_core/modules/community_loader.py
- src/tribler-core/tribler_core/modules/ipv8_module_catalog.py
- src/tribler-core/tribler_core/modules/metadata_store/community/launcher.py
- src/tribler-core/tribler_core/modules/metadata_store/settings.py
- src/tribler-core/tribler_core/modules/popularity/launcher.py
- src/tribler-core/tribler_core/modules/settings.py
- src/tribler-core/tribler_core/modules/tests/test_community_loader.py
- src/tribler-core/tribler_core/modules/tunnel/community/launcher.py
- src/tribler-core/tribler_core/modules/tunnel/community/settings.py
- src/tribler-core/tribler_core/session.py
- src/tribler-core/tribler_core/settings.py
- src/tribler-core/tribler_core/tests/test_session.py
- src/tribler-core/tribler_core/utilities/tiny_tribler_service.py
One step closer to the atomic community: introduction of `launcher.py`
I've extracted `IPv8CommunityLauncher` for each Tribler's community from `ipv8_module_catalog.py` and put them into `launcher.py` next to corresponding communities. 
`Preconditions` have been separated from `Launcher` definition to `Loader` implementation:
`community_loader.py`
```python
def create_default_loader(config: TriblerConfig, tunnel_testnet: bool = False,
bandwidth_testnet: bool = False, chant_testnet: bool = False):
loader = IPv8CommunityLoader()
loader.set_launcher(IPv8DiscoveryCommunityLauncher())
loader.set_launcher(DHTCommunityLauncher())
if bandwidth_testnet:
from tribler_core.modules.bandwidth_accounting.launcher import BandwidthTestnetCommunityLauncher …
```
> Extract loaders from ipv8_module_catalog.py

- .flake8
- src/tribler-core/tribler_core/conftest.py
- src/tribler-core/tribler_core/modules/bandwidth_accounting/transaction.py
- src/tribler-core/tribler_core/modules/metadata_store/community/tests/test_gigachannel_community.py
- src/tribler-core/tribler_core/modules/metadata_store/gigachannel_manager.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_node.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/channel_peer.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/collection_node.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/torrent_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/torrent_state.py
- src/tribler-core/tribler_core/modules/metadata_store/payload_checker.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/channels_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/metadata_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/serialization.py
- src/tribler-core/tribler_core/modules/metadata_store/store.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_download.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_gigachannel_manager.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_metadata.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_store.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_torrent_metadata.py
- src/tribler-core/tribler_core/modules/torrent_checker/torrent_checker.py
fixes #6097  with some `bowler` magic:
<details>
```python
import mmap
import re
from lib2to3.pgen2.parse import ParseError
from pathlib import Path
from bowler.query import Query
fun_name = "database_blob"
dbblob = re.compile(fun_name.encode())
def modify_file(filename):
(
Query(filename).
select_function(fun_name).
is_call().
modify(remove_call).execute(interactive=False, write=True)
)
def remove_call(ast_node, capture, _):
args = capture.get('function_arguments')
parent = ast_node.parent
children_list = parent.children
for ind, leaf in enumerate(children_list):
if leaf is ast_node:
children_list[ind] = args[0].clone()
if __name__ == "__main__":
for file in Path("src/tribler-core").rglob("*.py"):
try:
with open(file, "r+") as f:
data = mmap.mmap(f.fileno(), 0)
if not re.search(dbblob, …
```
> Remove obsolete database_blob type

- src/tribler-core/tribler_core/modules/remote_query_community/tests/test_eva_protocol.py
This PR fixes #6195 by disabling timeout in `test_duplex` test function.
> Disable EVA timeout in test_duplex

- src/tribler-core/tribler_core/modules/metadata_store/community/gigachannel_community.py
This PR fixes the bug that results in removing _all_ the peers serving a channel from channels<->peers mapping in GigaChannel Community. The result was lower quality online browsing of channels.
> Fix removing all peers for channel instead of the failing one

- src/tribler-core/tribler_core/modules/metadata_store/orm_bindings/collection_node.py
- src/tribler-core/tribler_core/modules/metadata_store/restapi/tests/test_channels_endpoint.py
- src/tribler-core/tribler_core/modules/metadata_store/tests/test_channel_metadata.py
Stops bugging the user with endless "Duplicate torrent" popups when trying to repeatedly add multiple torrents to a personal channel by using "Add torrent" action.
[Reported by forum user.](https://forum.tribler.org/t/metainfo-timeout-after-adding-torrents-to-my-channel/6790/2)
> Silently pass when user tries to add duplicate torrents to channel

- src/tribler-core/tribler_core/components/implementation/ipv8.py
Fixes #6245. This PR fixes a regression appeared after the incorrect refactoring when splitting Tribler code into components.
> Fixes #6245: Wrong target peers for DiscoveryCommunity

- src/tribler-core/tribler_core/components/implementation/bandwidth_accounting.py
- src/tribler-core/tribler_core/components/implementation/gigachannel.py
- src/tribler-core/tribler_core/components/implementation/ipv8.py
- src/tribler-core/tribler_core/components/implementation/popularity.py
- src/tribler-core/tribler_core/components/implementation/tunnels.py
- src/tribler-core/tribler_core/components/interfaces/ipv8.py
Fixes #6250 and #6251.
Adds `Ipv8Component.make_bootstrapper()` factory and uses it for each community
> Fixes #6250, fixes #6251: each community should use a separate bootstrapper

- .pylintrc
This PR restores lint checks for tests that were turned off during the refactoring of Tribler core in #6206
> Fixes #6257: restore lint checks for tests

- src/tribler-core/tribler_core/components/implementation/libtorrent.py
- src/tribler-core/tribler_core/components/implementation/metadata_store.py
- src/tribler-core/tribler_core/components/implementation/torrent_checker.py
- src/tribler-core/tribler_core/components/interfaces/metadata_store.py
- src/tribler-core/tribler_core/restapi/rest_manager.py
This PR fixes incorrect initialization of REST endpoints, which causes issues #6262 and #6268.
Currently, a REST endpoint needs to be created before the corresponding component, so the component needs to inject the necessary data to the endpoint later. The mapping between some components and REST endpoints is "many-to-many". If some component was disabled in the config, the corresponding REST endpoint is not created, so other components should not inject their data into the missing endpoint.
This is achieved by using a new helper method of the REST manager, which skips assigning attributes to the missing endpoints.
> Fixes #6262, fixes #6268: correct delayed initialization of endpoints

- src/tribler-core/tribler_core/components/interfaces/gigachannel.py
This PR fixes #6265 issue. When IPv8 component is disabled, the gigachannel channels component should be disabled as well
> Fixes #6265: start Tribler with ipv8 disabled

- src/tribler-core/tribler_core/components/interfaces/socks_configurator.py
This PR fixes #6266: the download manager uses socks server even if tunnels are disabled
> Fixes #6266: uncaught error when starting with tunnel_community disabled

- src/tribler-core/tribler_core/components/implementation/popularity.py
This PR fixes #6267: Popularity community should work even if the torrent checker is disabled
> Fixes #6267: crash when clicking in channel with torrent_checking disabled

- src/tribler-core/tribler_core/components/implementation/ipv8.py
- src/tribler-core/tribler_core/components/tests/test_components.py
This PR resolves #6269 and #6270.
It fixes the incorrect initialization of Ipv8Component.
> Fixes #6269, fixes #6270: DiscoveryCommunity and DHTDiscoveryCommunity disregards config setting

- src/tribler-core/tribler_core/modules/category_filter/filter_terms.filter
The keyword filter list is discriminating.
Some searches that aren’t allowed with the current filter:
* belgian waffles
* asian tv, asian cousine, asuan culture
* scandianvian nature, scandinavian architecture
* gay interest (a common label for media with LGBTQ characters)
* turkish movies
* danish children tv (watch [John Dillermand](https://www.youtube.com/watch?v=A51mJjFyG_w))
I’ve removed the groups of people (but left in slurs) I could identify from the list. I was surprised that there were so many given names are on the list. I understand these may be adult performers, but blocking every artist or creator named Alexis, Charlie, or one of the hundred other names on the list is crazy. These should be removed as well, but let’s address those in a separate pr.
> Don’t filter any groups of people out of existence

- build/win/resources/tribler.nsi
Install the Tribler shortcut directly into the root of the Start Menu. A subfolder adds an unnecessary extra click to open Tribler. This has been the [best practice](https://www.ctrl.blog/entry/windows-start-menu-folders.html) since Windows 8 when Windows stopped listing folders above icons in the Start Menu. This also gives Tribler a better appearance and brand recognition in the start menu as the listing will feature Tribler’s icon instead of a generic folder icon.
Don’t create a shortcut to uninstall Tribler in the Start Menu. The entry shows up when searching for Tribler in the Start Menu, and it’s easy to missclick on it from Search (as results rearrange as they pop in) and in the Start Menu. Rely on the regular uninstallation flow instead. (Right-clicking on the icon the Start Menu …
> Don’t create a Tribler subfolder in the Start

- src/tribler-core/run_tunnel_helper.py
This PR fixes `run_tunnel_helper.py` scripts so it can work with component architecture.
It depends on #6291 and can be merged after #6291 is merged.
> Fix run tunnel helper

- src/tribler-core/run_tunnel_helper.py
This PR fixes missed the first argument when raising the `ArgumentError` exception, and also it creates an `ipaddress.IPv4Address` instance instead of calling the `inet_aton()` function.
Also, it reformats the code a bit to satisfy the linter.
> Fix tunnel helper arguments

- src/tribler-core/tribler_core/components/implementation/tunnels.py
Exit node cache path is not currently set on initialization of the Tunnel Community because of which the cache is not saved during shutdown
> Set exit node cache path on Tunnel community

- .readthedocs.yml
- doc/extract_swagger.py
- Fixes https://github.com/Tribler/tribler/issues/6328
- Fixes https://github.com/Tribler/tribler/issues/6261 by specifying the `.readthedocs.yml` file to use Python 3.8
> Fix documentation build issue

- src/tribler-core/tribler_core/modules/remote_query_community/tests/test_eva_protocol.py
This PR fixes #6327 
All occurrences of failing tests have been presented on MAC machine only.
My assumption is it can be possible because tests take longer to complete on this specific machine (only).
As a fix for now I propose to just increase pytest timeouts and disable inner EVA timeouts as well.
> Increase EVA tests timeouts

- src/tribler-core/tribler_core/components/implementation/bandwidth_accounting.py
- src/tribler-core/tribler_core/components/implementation/gigachannel.py
- src/tribler-core/tribler_core/components/implementation/ipv8.py
- src/tribler-core/tribler_core/components/implementation/popularity.py
- src/tribler-core/tribler_core/components/implementation/tunnels.py
- src/tribler-core/tribler_core/components/interfaces/bandwidth_accounting.py
- src/tribler-core/tribler_core/components/interfaces/gigachannel.py
- src/tribler-core/tribler_core/components/interfaces/popularity.py
- src/tribler-core/tribler_core/components/interfaces/tunnels.py
> Fix community component shutdown leaving stuff behind

- src/tribler-gui/tribler_gui/tests/test_gui.py
> Fixed on_report_sent callback in GUI tests

- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
Very minor issue, but this has been bothering me for some time. The text is now always vertically aligned in the center of the available space. Also, I slightly increased the size of the 'subscribed' column.
Before:
After:
> Fixed width and vertical text alignment in table headers

- src/tribler-core/tribler_core/restapi/rest_endpoint.py
fixes #6301 by increasing the maximum request size to 2MB. It should be enough to open even the biggest torrents out there, such as [the GeoCities archive](https://academictorrents.com/details/2dc18f47afee0307e138dab3015ee7e5154766f6)
> Increase maximum request size for AIOHTTP to 2MB

- src/tribler-gui/tribler_gui/widgets/searchresultswidget.py
> Fix crash on race condition on show results button in GUI

- src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py
- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/utilities.py
- src/tribler-gui/tribler_gui/widgets/downloadspage.py
- src/tribler-gui/tribler_gui/widgets/lazytableview.py
- src/tribler-gui/tribler_gui/widgets/searchresultswidget.py
- src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
- src/tribler-gui/tribler_gui/widgets/triblertablecontrollers.py
fixes #6369 
fixes #6366 
fixes #6368 
fixes #6083 
fixes #6213 
fixes #5886
>  Various small fixes

- src/tribler-gui/tribler_gui/widgets/channelcontentswidget.py
- src/tribler-gui/tribler_gui/widgets/lazytableview.py
- src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
When the mouse leaves the table, it should deselect the currently selected row. This PR implements this behaviour. It also captures the event when moving the mouse through the (top) header of the table, which required the implementation of an event filter. Note that sometimes rows remain selected when moving the mouse quickly out of the viewport, but I believe this is acceptable for now.
I also removed the redundant `hoverrow` variable in the table delegate.
> Implement row deselection on mouse leave

- src/tribler-gui/tribler_gui/widgets/lazytableview.py
- src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
We used to repaint all (visible) rows when moving the mouse through the table with content. This PR significantly reduces the number of repaints by only repainting the index that has been changed in the table. In GUI test mode, scrolling through the table of content feels much smoother now.
Fixes #6377
> Significantly reduced the number of redraws in GUI tables

- src/tribler-core/tribler_core/components/metadata_store/utils.py
- src/tribler-gui/tribler_gui/tests/test_gui.py
Specifically, added some content to the 'popular torrents' page by adding health information to generated torrents when in GUI test mode.
Fixes #6386
> Fixed test_popular_page

- src/tribler-core/tribler_core/components/bandwidth_accounting/bandwidth_accounting_component.py
- src/tribler-core/tribler_core/components/bandwidth_accounting/restapi/bandwidth_endpoint.py
- src/tribler-core/tribler_core/components/bandwidth_accounting/tests/test_bandwidth_accounting_component.py
- src/tribler-core/tribler_core/components/base.py
- src/tribler-core/tribler_core/components/gigachannel/gigachannel_component.py
- src/tribler-core/tribler_core/components/gigachannel/tests/test_gigachannel_component.py
- src/tribler-core/tribler_core/components/gigachannel_manager/gigachannel_manager_component.py
- src/tribler-core/tribler_core/components/gigachannel_manager/tests/test_gigachannel_manager_component.py
- src/tribler-core/tribler_core/components/ipv8.py
- src/tribler-core/tribler_core/components/libtorrent.py
- src/tribler-core/tribler_core/components/metadata_store/metadata_store_component.py
- src/tribler-core/tribler_core/components/metadata_store/tests/test_metadata_store_component.py
- src/tribler-core/tribler_core/components/resource_monitor.py
- src/tribler-core/tribler_core/components/restapi.py
- src/tribler-core/tribler_core/components/tests/test_tribler_components.py
- src/tribler-core/tribler_core/components/torrent_checker.py
- src/tribler-core/tribler_core/components/tunnels.py
- src/tribler-core/tribler_core/components/upgrade.py
- src/tribler-core/tribler_core/components/watch_folder.py
- src/tribler-core/tribler_core/restapi/rest_manager.py
- src/tribler-core/tribler_core/restapi/trustview_endpoint.py
This PR makes the dependency of components on REST manager optional. It adds a base class `RestfulComponent`, which provides three methods:
The `init_endpoints` method simplifies endpoint initialization and can be used inside a component's `run` method to inject values to REST endpoints:
```python
async def run(self):
...
await self.init_endpoints(
["endpoint_name1", "endpoint_name2"]
[(attr_name1, value1), (attr_name2, value2)]
)
```
The method sets specified attributes to all enlisted endpoints. If RESTComponent or some specific endpoint is not available, it just skipped silently.
It also is possible to initialize `ipv8` endpoints as well by specifying the `ipv8` instance.
```python
await self.init_ipv8_endpoints(self._ipv8, ['tunnel'])
```
This way it becomes not necessary to …
> Fixes #6360: Optional dependency on REST manager in components

- src/tribler-core/tribler_core/components/bandwidth_accounting/tests/test_bandwidth_accounting_component.py
- src/tribler-core/tribler_core/components/gigachannel/tests/test_gigachannel_component.py
- src/tribler-core/tribler_core/components/gigachannel_manager/tests/test_gigachannel_manager_component.py
- src/tribler-core/tribler_core/components/metadata_store/tests/test_metadata_store_component.py
- src/tribler-core/tribler_core/components/tests/test_base_component.py
This PR fixes #6382 by adding `@pytest.mark.asyncio` to all components-related test functions.
> Add @pytest.mark.asyncio to test functions

- src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
- src/tribler-gui/tribler_gui/widgets/tableiconbuttons.py
It seems that we missed that a QTableView issues a repaint when hovering over a new cell automatically. As such, the manual redraw operations are not strictly necessary, except for when we are deselecting rows when the mouse leaves the table. Especially now that the `paint` operations are becoming more intensive with tags, we cannot afford to do unnecessary redraws. I've tested it in various settings and it seems to work correctly.
> Remove table redraw on mouse movement

- doc/contributing.rst
We have come to an agreement on the dev meeting:
* We use [rebase + merge –no–ff](https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow#option-3-rebase-merge-no-ff) for merging a branch
* Responsibility for merging the PR is on the creator of the PR
Recommendations:
* Follow the [conventional comments practice](https://conventionalcomments.org/)
* Keep in mind [The Standard of Code Review](https://google.github.io/eng-practices/review/reviewer/standard.html)
> Add PR policies

- src/tribler-core/tribler_core/components/bandwidth_accounting/tests/test_bandwidth_accounting_component.py
- src/tribler-core/tribler_core/components/base.py
- src/tribler-core/tribler_core/components/gigachannel/tests/test_gigachannel_component.py
- src/tribler-core/tribler_core/components/gigachannel_manager/tests/test_gigachannel_manager_component.py
- src/tribler-core/tribler_core/components/metadata_store/tests/test_metadata_store_component.py
- src/tribler-core/tribler_core/components/tests/test_base_component.py
- src/tribler-core/tribler_core/components/tests/test_tribler_components.py
This PR:
* Fixes issue #6359: an exception in component's `shutdown()` method can prevent correct shutdown of other components.
* Fixes incorrect component tests
* Fixes a bug when component's `unused` event was always set, and component `shutdown()` method could start before all reverse dependencies were released
* Also it renames some component's attributes to make it more readable (`components_used_by_me` -> `dependencies`) and to avoid possible confusion of events with bool flags
> Component fixes

- src/tribler-gui/tribler_gui/core_manager.py
Remove empty comment. Closes #6272
> Remove empty comment

- src/tribler-core/tribler_core/components/bandwidth_accounting/bandwidth_accounting_component.py
- src/tribler-core/tribler_core/components/bandwidth_accounting/tests/test_bandwidth_accounting_component.py
- src/tribler-core/tribler_core/components/gigachannel/gigachannel_component.py
- src/tribler-core/tribler_core/components/gigachannel/tests/test_gigachannel_component.py
- src/tribler-core/tribler_core/components/ipv8.py
- src/tribler-core/tribler_core/components/popularity.py
- src/tribler-core/tribler_core/components/tests/test_tribler_components.py
- src/tribler-core/tribler_core/components/tunnels.py
Based on https://github.com/Tribler/tribler/pull/6396
```python
class Ipv8Component(RestfulComponent):
ipv8: IPv8
def initialise_community_by_default(self, community):
community.bootstrappers.append(self.make_bootstrapper())
random_walk_max_peers = max(10, community.max_peers - 10)
self.ipv8.add_strategy(community, RandomWalk(community), random_walk_max_peers)
async def unload_community(self, community):
await self.ipv8.unload_overlay(community)
```
> Introduce "default init" and "unload" methods for Ipv8Component

- src/tribler-core/tribler_core/components/gigachannel/community/gigachannel_community.py
- src/tribler-core/tribler_core/components/gigachannel/gigachannel_component.py
- src/tribler-core/tribler_core/components/popularity.py
- src/tribler-core/tribler_core/modules/popularity/community.py
@qstokkink 
> We're injecting self._ipv8_component.ipv8.network as a dependency and then the component itself is overwriting its input with a Network() of its own creation. We should, at some point (probably not this PR) move the Network() overwrite to this file (same for PopularityCommunity).
The `Network() overwrite` has been moved for:
* `PopularityCommunity`
* `GigachannelCommunity`
For `BandwidthAccountingCommunity` I didn't find any place with `Network()` overwriting.
> Move Network overwrite from community to component

- src/tribler-gui/tribler_gui/qt_resources/mainwindow.ui
- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
- Added focus on the search box focus. Fixes #6260.
- Slightly increased the width of the 'health' column in the GUI. Fixes #6409.
> Added search box focus, increased width of 'health' column in GUI

- src/tribler-core/tribler_core/components/metadata_store/restapi/metadata_endpoint.py
/channels seems to be a root endpoint and is not part of /metadata anymore.
> Removed channels from metadata endpoint docstring

- src/tribler-common/tribler_common/tests/test_utils.py
- src/tribler-common/tribler_common/utilities.py
- src/tribler-core/tribler_core/components/metadata_store/restapi/tests/test_search_endpoint.py
- src/tribler-gui/tribler_gui/utilities.py
- src/tribler-gui/tribler_gui/widgets/searchresultswidget.py
- src/tribler-gui/tribler_gui/widgets/tablecontentmodel.py
This PR should fix failing test_tribler_main job by fixing incorrect imports
> Fixes #6514: Move to_fts_query function from tribler_gui.utilities to tribler_common.utilities

- src/tribler-gui/tribler_gui/core_manager.py
Currently, GUI accidentally opens two parallel connections to the `/events` endpoint when communicating with Core. The first connection is opened [here](https://github.com/Tribler/tribler/blob/c67298f5df0a89886a3e3bfa49788b36f915862c/src/tribler-gui/tribler_gui/core_manager.py#L104), and the second is [here](https://github.com/Tribler/tribler/blob/c67298f5df0a89886a3e3bfa49788b36f915862c/src/tribler-gui/tribler_gui/core_manager.py#L194). Only one connection is actually necessary. In this PR, I remove the second unnecessary connection.
> Remove an unnecessary second connection to the `/events` endpoint from GUI

- src/tribler-common/tribler_common/reported_error.py
- src/tribler-common/tribler_common/sentry_reporter/sentry_tools.py
- src/tribler-core/tribler_core/components/reporter/exception_handler.py
- src/tribler-core/tribler_core/components/reporter/tests/test_exception_handler.py
- src/tribler-core/tribler_core/components/restapi/rest/events_endpoint.py
- src/tribler-core/tribler_core/components/restapi/rest/state_endpoint.py
- src/tribler-core/tribler_core/components/restapi/rest/tests/test_events_endpoint.py
- src/tribler-core/tribler_core/components/restapi/rest/tests/test_state_endpoint.py
- src/tribler-core/tribler_core/components/restapi/restapi_component.py
- src/tribler-core/tribler_core/components/restapi/tests/test_restapi_component.py
- src/tribler-core/tribler_core/start_core.py
- src/tribler-core/tribler_core/tests/test_start_core.py
- src/tribler-gui/tribler_gui/dialogs/addtagsdialog.py
- src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py
- src/tribler-gui/tribler_gui/error_handler.py
- src/tribler-gui/tribler_gui/event_request_manager.py
- src/tribler-gui/tribler_gui/tests/test_error_handler.py
- src/tribler-gui/tribler_gui/tests/test_gui.py
This PR fixes #6509 by refactoring the error reporting chain.
This PR introduces `ReportedError` class for sending errors from `core` to `gui` instead of using `dict`.
```python
@dataclass
class ReportedError:
type: str
text: str
event: dict
requires_user_consent: bool
long_text: str = ''
context: str = ''
should_stop: Optional[bool] = None
```
It also adds missed `requires_user_consent` field that has been removed (probably) during #6206
> Refactor the error reporting chain

- src/tribler-core/tribler_core/components/restapi/rest/events_endpoint.py
- src/tribler-core/tribler_core/components/restapi/rest/tests/test_events_endpoint.py
- src/tribler-gui/tribler_gui/event_request_manager.py
Fixes #6263. The error that happened too early during the core startup process may get lost if GUI connects to Core after Core processes the exception. This PR remembers the last error and reports it to GUI on connect. Also, it refactors the code of `EventsEndpoint` to make it more readable.
> Fixes #6263 - Tribler should open FeedbackDialog if error happend in Core during startup

- src/tribler-core/tribler_core/components/tunnel/tests/test_full_session/conftest.py
- src/tribler-core/tribler_core/conftest.py
We use a `SelectorEventLoop` on all platforms so our test suite should use a similar event loop.
Fixes #6456
> Using SelectorEventLoop during tests

- doc/development/development_on_linux.rst
> Update development on linux

- src/tribler-core/tribler_core/components/bandwidth_accounting/tests/test_community.py
This PR fixes #6273 by removing the forgotten code block.
> Apply MockIPv8 key injection

- src/run_tribler.py
- src/tribler-common/tribler_common/reported_error.py
- src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py
- src/tribler-core/tribler_core/components/reporter/exception_handler.py
- src/tribler-core/tribler_core/components/reporter/tests/test_exception_handler.py
- src/tribler-core/tribler_core/config/tribler_config_sections.py
- src/tribler-core/tribler_core/start_core.py
- src/tribler-core/tribler_core/tests/test_start_core.py
- src/tribler-gui/tribler_gui/dialogs/feedbackdialog.py
- src/tribler-gui/tribler_gui/error_handler.py
The intention of this PR is to simplify the Application Tester's error reporting by removing `requires_user_consent` field.
Initially, `requires_user_consent` has been introduced to prevent mis-switching to the test mode, which sends error messages automatically (without user participation) and it works in tandem with `TEST_SENTRY_URL` like:
```python
@staticmethod
def can_send_automatically(error_reporting_requires_user_consent):
test_sentry_url_is_defined = os.environ.get('TEST_SENTRY_URL', None) is not None
return test_sentry_url_is_defined and not error_reporting_requires_user_consent
```
This PR renames `TEST_SENTRY_URL` to `TRIBLER_TEST_SENTRY_URL` which should be enough for preventing mis-switching to test mode without specifying `error_reporting_requires_user_consent`.
> Make TEST_SENTRY_URL the single source of sentry test mode information

- src/tribler-gui/tribler_gui/tests/test_gui.py
It can take some time for the GUI to remove a tag after clicking the cross button, and this action is not instantly. Therefore, if the machine is busy, the tag could not have been removed correctly and the assert will fail. Adding a small timeout between the mouseclick and the assert should address this issue.
As much as I dislike hard-coded timeouts in tests, I believe this one is reasonable and necessary since Qt events are processed asynchronously.
Fixes #6541
> Added small delay after mouse click in GUI test

- src/tribler-core/tribler_core/components/reporter/exception_handler.py
- src/tribler-core/tribler_core/components/reporter/tests/test_exception_handler.py
- src/tribler-core/tribler_core/components/restapi/restapi_component.py
- src/tribler-core/tribler_core/components/restapi/tests/test_restapi_component.py
- src/tribler-core/tribler_core/start_core.py
This PR fixes #6542 by making CoreExceptionHandler just an instance class (instead of singleton). It will allow us to test `CoreExceptionHandler` properly and will increase the stability of tests.
> Make CoreExceptionHandler scope-dependent

- src/tribler-core/tribler_core/components/restapi/rest/tests/test_events_endpoint.py
This PR fixes #6539 by removing `AsyncMock` from `encode_message` patch because `encode_message` uses only in synchronized calls.
As a consequence of doing this: removed warning and fixed `test_set_rate_settings` test. 
```python
sys:1: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
See full explanations here:  #6539
> Change mock type for encode_message

- src/tribler-gui/tribler_gui/widgets/tagslineedit.py
When pressing the home/end button when there were no tags entered, Tribler would crash. I've added a few conditionals that should address this.
Fixes #6549
> Fixed crash when editing tag

- src/tribler-gui/tribler_gui/__init__.py
- src/tribler-gui/tribler_gui/core_manager.py
- src/tribler-gui/tribler_gui/error_handler.py
- src/tribler-gui/tribler_gui/event_request_manager.py
- src/tribler-gui/tribler_gui/exceptions.py
- src/tribler-gui/tribler_gui/tests/test_core_manager.py
- src/tribler-gui/tribler_gui/tests/test_error_handler.py
This PR fixes #6521 by introducing CoreRuntimeError and adding this error to the list that causes Tribler shutdown.
> Add CoreRuntimeError to the error list that causes Tribler shutdown 

- src/tribler-common/tribler_common/patch_import.py
- src/tribler-common/tribler_common/tests/test_patch_import.py
- src/tribler-core/tribler_core/check_os.py
- src/tribler-core/tribler_core/tests/test_check_os.py
This PR fixes #6157
It also extends `patch_import` function by adding two new arguments:
* **strict:** If `strict` is equal to True, then whenever importing module exists or not, it will be replaced
by MagicMock. If `strict` is equal to False, then the real module will be return in case it is exist, and
MagicMock in case the module doesn't exist.
* **always_raise_exception_on_import:** if set to True, then the import of the particular module always will raise
the ImportError
These improvements to the `patch_import` are necessary to properly test `enable_fault_handler` function.
> Add exist_ok=True to mkdir

- src/tribler-gui/tribler_gui/core_manager.py
- src/tribler-gui/tribler_gui/error_handler.py
- src/tribler-gui/tribler_gui/tests/test_core_manager.py
This PR fixes #6566 by replacing attempting to `extract core_traceback` from the core output to saving just `last_core_output`.
Also, the way of printing a core output has been changed to the following:
```python
print(f'\t{self.last_core_output}') 
```
It gives more visual hints while reading the output log (GUI output without tab, Core output with tab)
```python
[PID:80545] 2021-11-19 12:44:42,585 - INFO - TriblerGUI(80) - Got Tribler core error: 1
INFO:__main__:Sentry has been initialised in normal mode
INFO:__main__:Root state dir: /Users/<user>/.Tribler
INFO:__main__:Running in "core" mode
[PID:80545] 2021-11-19 12:44:43,061 - INFO - TriblerGUI(136) - Will connect to events endpoint
[PID:80545] 2021-11-19 12:44:43,062 - INFO - TriblerGUI(80) - Got Tribler core error: 1 …
```
> Replace core_traceback by last_core_output

- build/win/makedist_win.bat
- src/run_tribler.py
- src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py
- src/tribler-core/tribler_core/check_os.py
- src/tribler-core/tribler_core/start_core.py
- src/tribler-core/tribler_core/tests/test_check_os.py
- src/tribler-gui/tribler_gui/core_manager.py
- src/tribler-gui/tribler_gui/error_handler.py
- src/tribler-gui/tribler_gui/tests/test_core_manager.py
- src/tribler-gui/tribler_gui/tests/test_error_handler.py
- src/tribler-gui/tribler_gui/tribler_window.py
- tribler.spec
This PR together with #6545 contains fixes for various problems with Tribler builds.
With this fixes, 1-Click release Jenkins job is able to assemble executables and test them with application tester
> Fixes 1-Click release for 7.11

- build/debian/makedist_debian.sh
- build/mac/makedist_macos.sh
- build/win/makedist_win.bat
Fixes https://github.com/Tribler/tribler/issues/6518
> Install pip dependencies during the build

- build/win/makedist_win.bat
- build/win/requirements.txt
This PR fixes #6569 by adding requrements.txt for the windows build.
The documentation about how to specify `--no-binary` for the requrements.txt: https://pip.pypa.io/en/latest/reference/requirements-file-format/#structure
> Add requirements.txt

- src/tribler-core/tribler_core/components/tag/tag_component.py
It is more efficient and convenient to use an in-memory SQLite database for testing.
> Use in-memory SQLite DB for Tags in GUI test mode

- .coveragerc
`.coveragerc` is a config file for [coverage.py](https://coverage.readthedocs.io/en/6.1.1/config.html).
Now we don't use `coverage.py`and using [diff-cover](https://diff-cover.readthedocs.io/en/latest/README.html) instead (for creating coverage reports during [Coverage Check](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_coverage_check/configure)).
Therefore there is no longer a need for `.coveragerc`.
> Remove .coveragerc

- src/tribler-common/tribler_common/tests/test_patch_import.py
This PR introduces two improvements for `patch_import.py`:
1. It adds a test for Magic methods usage inside a patched library
2. It adds (unnecessary) calls for tested libraries to prevent removing them during IDE autoformatting.
> Improve tests for patch_import.py

- src/tribler-core/tribler_core/components/metadata_store/utils.py
This PR affects only Tribler's work in GUI test mode.
This PR replaces random char generation by fake words:
> Replace random char generation by fake words

- src/tribler-core/tribler_core/components/gigachannel/community/tests/test_gigachannel_community.py
- src/tribler-core/tribler_core/components/gigachannel_manager/tests/test_gigachannel_manager.py
- src/tribler-core/tribler_core/components/metadata_store/db/orm_bindings/channel_metadata.py
- src/tribler-core/tribler_core/components/metadata_store/db/orm_bindings/collection_node.py
- src/tribler-core/tribler_core/components/metadata_store/db/tests/test_store.py
- src/tribler-core/tribler_core/components/metadata_store/db/tests/test_torrent_metadata.py
- src/tribler-core/tribler_core/components/metadata_store/remote_query_community/tests/test_remote_query_community.py
- src/tribler-core/tribler_core/components/metadata_store/restapi/tests/conftest.py
- src/tribler-core/tribler_core/components/metadata_store/restapi/tests/test_channels_endpoint.py
- src/tribler-core/tribler_core/components/metadata_store/restapi/tests/test_metadata_endpoint.py
- src/tribler-core/tribler_core/components/metadata_store/restapi/tests/test_remote_query_endpoint.py
- src/tribler-core/tribler_core/components/metadata_store/restapi/tests/test_search_endpoint.py
- src/tribler-core/tribler_core/components/metadata_store/tests/test_channel_metadata.py
- src/tribler-core/tribler_core/components/metadata_store/utils.py
- src/tribler-core/tribler_core/components/popularity/community/tests/test_popularity_community.py
- src/tribler-core/tribler_core/utilities/random_utils.py
- src/tribler-core/tribler_core/utilities/tests/test_random_utils.py
- src/tribler-core/tribler_core/utilities/tests/test_utilities2.py
- src/tribler-core/tribler_core/utilities/utilities.py
This PR is the next step after #6592 
It removes unnecessary code from `random_utils.py`
> Removing random_utils.py

- build/debian/makedist_debian.sh
The current changelog generation script does not work when the current tag and HEAD are the same. This PR reverts the git commit based changelog and uses a generic log pointing to Github tag URL.
> Revert changelog based on git commit

- src/run_tribler.py
- src/tribler-gui/tribler_gui/tests/test_gui.py
Fixes #6601
Both GUI and Core processes should receive `--gui-test-mode` flag to handle it correctly
> Make --core and --gui-test-mode separate flags with all combinations possible

- src/tribler-gui/tribler_gui/core_manager.py
- src/tribler-gui/tribler_gui/event_request_manager.py
- src/tribler-gui/tribler_gui/tests/test_gui.py
- src/tribler-gui/tribler_gui/tribler_request_manager.py
- src/tribler-gui/tribler_gui/tribler_window.py
This PR fixes #6607 by fixing encoding/decoding of `api_key`.
> Fix api_key encoding/decoding

- src/tribler-gui/tribler_gui/tribler_window.py
Currently, gui_settings (which is an instance of QSettings) can store api_key as bytes instead of str. We need to decode it to str in that case.
> Decode api_key if gui_settings returns it as bytes

- src/tribler-gui/tribler_gui/debug_window.py
Previously GUI process stores `api_key` value mostly as bytes (and sometimes as str, which caused problems), and now it after #6608 and #6611, it is always stored as str. When displaying `api_key` in DebugWindow, the conversion from bytes to str is not needed anymore, as `api_key` is already str.
> Fix api_key conversion in DebugWindow

- src/tribler-core/tribler_core/components/metadata_store/utils.py
> Make sure generated tags have a valid length

- pytest.ini
- src/tribler-core/tribler_core/components/metadata_store/db/tests/test_store.py
- src/tribler-core/tribler_core/components/popularity/community/popularity_community.py
- src/tribler-core/tribler_core/components/tests/test_base_component.py
- src/tribler-core/tribler_core/components/tunnel/community/discovery.py
- src/tribler-core/tribler_core/components/tunnel/community/tunnel_community.py
- src/tribler-gui/tribler_gui/dialogs/dialogcontainer.py
- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/widgets/lazytableview.py
- src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
- src/tribler-gui/tribler_gui/widgets/tagslineedit.py
- src/tribler-gui/tribler_gui/widgets/togglebutton.py
- src/tribler-gui/tribler_gui/widgets/torrentfiletreewidget.py
Currently, pytest output has many unimportant warnings from third-party libraries. We can safely ignore all of them. Displaying all these warnings makes understanding pytest results more complex than necessary. It is essential that if we get some new and important warning one day, we can easily miss it in this wall of existing warnings.
In this PR, I update the `pytest.ini` config file to suppress all unimportant warnings and also I suppress warnings in code when necessary.
Also, I switched the default logging level in tests from DEBUG to INFO. In most cases, DEBUG output is not helpful, as it mainly consists of spam generated by internal PyQt modules. So, most of the time, it makes test results harder to understand. If necessary, we can always switch it back to DEBUG level later when …
> Remove spam in pytest output

- src/run_tribler.py
- src/tribler-core/tribler_core/start_core.py
- src/tribler-core/tribler_core/tests/test_start_core.py
- src/tribler-gui/tribler_gui/core_manager.py
- src/tribler-gui/tribler_gui/error_handler.py
- src/tribler-gui/tribler_gui/tests/test_core_manager.py
- src/tribler-gui/tribler_gui/tribler_window.py
In this PR, I rewrote the logic of `CoreManager` to fix the shutdown process sequence and make the logic of `CoreManager` easier to understand.
With these changes, I was able to get completely stable GUI tests on my Windows machine. Previously I often got the following error (reported in #6039):
```python
File "C:\dev\tribler\src\tribler-gui\tribler_gui\utilities.py", line 375, in trackback_wrapper
raise exc from CreationTraceback(traceback_str)
File "C:\dev\tribler\src\tribler-gui\tribler_gui\utilities.py", line 372, in trackback_wrapper
callback(*args, **kwargs)
File "C:\dev\tribler\src\tribler-gui\tribler_gui\core_manager.py", line 67, in on_core_finished
self.on_finished()
File "C:\dev\tribler\src\tribler-gui\tribler_gui\core_manager.py", line 132, …
```
> Fix gui tests stability

- src/tribler-core/tribler_core/components/libtorrent/download_manager/download_manager.py
- src/tribler-core/tribler_core/components/libtorrent/tests/test_download_manager.py
- src/tribler-core/tribler_core/components/metadata_store/tests/test_channel_download.py
- src/tribler-core/tribler_core/components/tunnel/tests/test_full_session/test_tunnel_community.py
- src/tribler-core/tribler_core/conftest.py
This PR fixes #6603.
`metadata_tmpdir` now passes through the constructor of `DownloadManager` for each test.
> Fix for #6603

- src/tribler-gui/tribler_gui/tests/test_gui.py
The test now first sorts on the 'subscribed' column to make sure that we have non-personal channels at the top. It then subscribes and unsubscribes, to restore the state after the test has finished.
Most likely fixes #6630
> Fixed channel subscribe GUI test

- src/tribler-gui/tribler_gui/tests/test_util.py
- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/utilities.py
In #6608 and #6611 `api_key` value type was changed from bytes to str. As it turns out, it can break previous releases, as previous releases expect that the value of `api_key` in GUI settings is stored as bytes. So, if a user installs the next release of Tribler (7.12+), or run Tribler from the `main` branch, and then attempts to run a previous version of Tribler (for example, release 7.11), the Tribler will crash on reading `api_key` value from settings.
The PR fixes this problem: `api_key` is now stored in GUI settings as bytes. New function `set_api_key` should correctly handle all possible scenarios when `api_key` was set in bytes or str, or not set at all.
> GUI settings should store api_key as bytes for compatibility with previous versions of Tribler

- src/tribler-common/tribler_common/network_utils.py
- src/tribler-core/tribler_core/components/base.py
- src/tribler-core/tribler_core/components/libtorrent/download_manager/download_manager.py
- src/tribler-core/tribler_core/components/restapi/rest/settings_endpoint.py
- src/tribler-core/tribler_core/components/socks_servers/socks_servers_component.py
- src/tribler-core/tribler_core/conftest.py
- src/tribler-gui/tribler_gui/tests/test_gui.py
- src/tribler-gui/tribler_gui/tribler_window.py
fixes #6650 by creating a default instance of NetworkUtils, reserving ports through its `remember` method, and using its `get_random_free_port` method to get free ports for SOCKS servers.
> Reserve ports to prevent accidental ports capture

- src/tribler-core/tribler_core/components/libtorrent/libtorrent_component.py
- src/tribler-core/tribler_core/start_core.py
Should fix once-in-a-blue-moon flapping tests, such as #6650
> Remove SOCKS component from GUI test mode requirements

- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/widgets/searchresultswidget.py
This fixes the problem with unexpected resets of the Search results page that happen when one uses "show immediately" button.
> Fix Search results page resetting unexpectedly

- src/tribler-gui/tribler_gui/defs.py
- src/tribler-gui/tribler_gui/widgets/trustpage.py
First proper PR so do bare with me.
Raises the "Token Balance over time" graph maximum from 1 Terabyte to 1 Petabyte. This is achieved by making a new "PB" GUI definition for the graph
.
> Fixes #6665 - Graph can now go higher than TB. New PB Definition added.

- src/tribler-common/tribler_common/requirements.txt
- src/tribler-common/tribler_common/tests/test_dependencies.py
Fixes https://github.com/Tribler/tribler/issues/6655
Additional to `faker`, `sentry-sdk` is required.
Tested buid here: https://jenkins-ci.tribler.org/job/pers/job/TRIBLER-PR-JOBS/job/PR_build_docs/9/
> Add Faker and sentry as common dependency

- src/tribler-core/tribler_core/config/tests/test_tribler_config.py
- src/tribler-core/tribler_core/config/tribler_config.py
Some fields of TriblerConfig can contain non-ASCII symbols. For example, the name of the directory to save downloads. For this, we need to specify `utf-8` encoding for the `ConfigObj` instance.
This encoding will only affect the writing of config data to the file. Reading of `utf-8`-encoded data is supported even without specifying the `utf-8` encoding.
> Fixes #6633 UnicodeEncodeError "ascii codec can't encode characters in position" when saving TriblerConfig with non-ascii symbols

- src/tribler-common/tribler_common/logger/config.yaml
- src/tribler-common/tribler_common/logger/streams.py
- src/tribler-common/tribler_common/tests/test_logger.py
- src/tribler-core/tribler_core/logger.yaml
- src/tribler-gui/tribler_gui/logger.yaml
This PR fixes #6671 by adding wrappers around `stdout` & `stderr` that can handle `UnicodeEncodeError`.
> Handle UnicodeDecodeError in logger when console encoding is not utf-8

- src/tribler-gui/tribler_gui/dialogs/dialogcontainer.py
- src/tribler-gui/tribler_gui/tribler_window.py
- src/tribler-gui/tribler_gui/widgets/downloadprogressbar.py
- src/tribler-gui/tribler_gui/widgets/downloadsdetailstabwidget.py
- src/tribler-gui/tribler_gui/widgets/lazytableview.py
- src/tribler-gui/tribler_gui/widgets/tablecontentdelegate.py
- src/tribler-gui/tribler_gui/widgets/tableiconbuttons.py
- src/tribler-gui/tribler_gui/widgets/tagslineedit.py
- src/tribler-gui/tribler_gui/widgets/torrentfiletreewidget.py
related to #6686 
The only reasonable solution is to disable the progress bars completely
Also, fixes #6688
> Disable progressbars for individual files

- src/tribler-core/tribler_core/components/gigachannel/community/gigachannel_community.py
- src/tribler-core/tribler_core/components/gigachannel_manager/gigachannel_manager.py
- src/tribler-core/tribler_core/components/libtorrent/download_manager/download.py
- src/tribler-core/tribler_core/components/libtorrent/download_manager/download_manager.py
- src/tribler-core/tribler_core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler-core/tribler_core/components/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler-core/tribler_core/components/resource_monitor/implementation/core.py
- src/tribler-core/tribler_core/components/resource_monitor/implementation/tests/test_resource_monitor.py
- src/tribler-core/tribler_core/components/torrent_checker/torrent_checker/torrent_checker.py
- src/tribler-core/tribler_core/components/version_check/versioncheck_manager.py
- src/tribler-core/tribler_core/components/watch_folder/watch_folder.py
- src/tribler-core/tribler_core/notifier.py
- src/tribler-core/tribler_core/start_core.py
- src/tribler-core/tribler_core/tests/test_notifier.py
> Make notifier more generic

- src/tribler-common/tribler_common/tests/test_utils.py
- src/tribler-common/tribler_common/utilities.py
- src/tribler-core/tribler_core/components/gigachannel/gigachannel_component.py
- src/tribler-core/tribler_core/components/metadata_store/remote_query_community/remote_query_community.py
- src/tribler-core/tribler_core/components/metadata_store/remote_query_community/tests/test_remote_query_community.py
- src/tribler-core/tribler_core/components/metadata_store/remote_query_community/tests/test_remote_search_by_tags.py
- src/tribler-core/tribler_core/components/metadata_store/restapi/remote_query_endpoint.py
- src/tribler-core/tribler_core/components/metadata_store/restapi/search_endpoint.py
- src/tribler-core/tribler_core/components/tag/community/tag_validator.py
- src/tribler-core/tribler_core/components/tag/community/tests/test_tag_validator.py
- src/tribler-core/tribler_core/components/tag/db/tests/test_tag_db.py
- src/tribler-gui/tribler_gui/widgets/searchresultswidget.py
This PR is a part of #6214. 
It introduces remote search by tags.
It was implemented as an extension of `RemoteQueryCommunity`
This PR also changes `TestTagDB` in such a way that it is can be used in other tests for creating sets of tags operations.
> Remote search by tags

- build/debian/tribler/usr/share/metainfo/org.tribler.Tribler.metainfo.xml
- build/update_version_from_git.py
In `update_version_from_git.py` the current version is written into `metainfo.xml`. Unfortunately, the XML declaration is not generated after inserting the current version.
> Fix missing XML declaration

- .dockerignore
- Dockerfile
- README.rst
- docker-compose.yml
- src/run_tribler.py
- src/tribler-core/tribler_core/components/restapi/rest/rest_manager.py
This PR adds support for running Tribler core using Docker and Docker Compose.
> Add docker support

- src/tribler-gui/tribler_gui/qt_resources/startdownloaddialog.ui
Fixes #6712. The order of the buttons in the start download dialog is now consistent with the button order in other dialogs.
Before:
After:
> Swapped 'cancel' and 'download' buttons

- src/tribler-core/run_bandwidth_crawler.py
- src/tribler-core/run_tribler_headless.py
- src/tribler-core/run_tunnel_helper.py
- src/tribler-core/tribler_core/components/bandwidth_accounting/tests/test_bandwidth_accounting_component.py
- src/tribler-core/tribler_core/components/base.py
- src/tribler-core/tribler_core/components/gigachannel/tests/test_gigachannel_component.py
- src/tribler-core/tribler_core/components/gigachannel_manager/tests/test_gigachannel_manager_component.py
- src/tribler-core/tribler_core/components/ipv8/tests/test_ipv8_component.py
- src/tribler-core/tribler_core/components/key/tests/test_key_component.py
- src/tribler-core/tribler_core/components/libtorrent/tests/test_libtorrent_component.py
- src/tribler-core/tribler_core/components/metadata_store/tests/test_metadata_store_component.py
- src/tribler-core/tribler_core/components/payout/tests/test_payout_component.py
- src/tribler-core/tribler_core/components/popularity/tests/test_popularity_component.py
- src/tribler-core/tribler_core/components/reporter/tests/test_reporter_component.py
- src/tribler-core/tribler_core/components/resource_monitor/tests/test_resource_monitor_component.py
- src/tribler-core/tribler_core/components/restapi/tests/test_restapi_component.py
- src/tribler-core/tribler_core/components/socks_servers/tests/test_socks_servers_component.py
- src/tribler-core/tribler_core/components/tag/tests/test_tag_component.py
- src/tribler-core/tribler_core/components/tests/test_base_component.py
- src/tribler-core/tribler_core/components/torrent_checker/tests/test_torrent_checker_component.py
- src/tribler-core/tribler_core/components/tunnel/tests/test_tunnel_component.py
- src/tribler-core/tribler_core/components/version_check/tests/test_version_check_component.py
- src/tribler-core/tribler_core/components/watch_folder/tests/test_watch_folder_component.py
- src/tribler-core/tribler_core/start_core.py
- src/tribler-core/tribler_core/utilities/tiny_tribler_service.py
During the implementation of #6718 I came up with the idea of simplification component's tests.
Instead of writing tests like 
```python
@pytest.mark.asyncio
async def test_bandwidth_accounting_component(tribler_config):
components = [KeyComponent(), Ipv8Component(), BandwidthAccountingComponent()]
session = Session(tribler_config, components)
with session:
await session.start()
comp = BandwidthAccountingComponent.instance()
assert comp.started_event.is_set() and not comp.failed
assert comp.community
assert comp._ipv8_component
await session.shutdown()
```
We could write:
```python
@pytest.mark.asyncio
async def test_bandwidth_accounting_component(tribler_config):
components = [KeyComponent(), Ipv8Component(), BandwidthAccountingComponent()]
with Session(tribler_config, components) as …
```
> Add session context manager

- src/tribler-core/tribler_core/components/gigachannel/community/tests/test_gigachannel_community.py
On fast machine, the test `[test_channels_peers_mapping_drop_excess_peers](https://github.com/Tribler/tribler/blob/0ee609e142956b7d0c47054e1d9259450a1a20cc/src/tribler-core/tribler_core/components/gigachannel/community/tests/test_gigachannel_community.py#L231)` sometimes sets `peer.last_response` time to the same value for all peers, and fails after that. In this fix, I explicitly set a different time for each peer to avoid this type of failure.
> Fix unstable test_channels_peers_mapping_drop_excess_peers

- src/tribler-core/run_bandwidth_crawler.py
- src/tribler-core/tribler_core/components/bandwidth_accounting/bandwidth_accounting_component.py
In this PR I fix the script to run bandwidth crawler. It initializes BandwidthDatabase and BandwidthAccountingCommunity in a bit different way comparing to Tribler itself, so I added `crawler_mode` flag to `BandwidthAccountingComponent`. Another options was to add an option to BandwidthAccounting section of TriblerConfig, but the option does not look important enough to complicate the general config.
> Fix run_bandwidth_crawler script

- src/tribler-core/tribler_core/components/simple_storage/simple_storage.py
- src/tribler-core/tribler_core/components/simple_storage/simple_storage_component.py
- src/tribler-core/tribler_core/components/simple_storage/tests/test_simple_storage.py
- src/tribler-core/tribler_core/components/simple_storage/tests/test_simple_storage_component.py
**Note** this PR has been rebased to #6724 and contains 6724's commits as well.
This PR is a part of #6718. It introduces the Simple Storage Component.
The reason to introduce this component: in #6718 I need persistent storage for the `last_processed_torrent_id` that is used by `TagComponent` during rules processing. 
Normal Tribler's approach is either to store values in SQL or to store values in separate files.
The SQL approach includes:
https://github.com/Tribler/tribler/blob/eed41c7d132f5f6709c8d89d8b25ae5b26700cdb/src/tribler-core/tribler_core/components/metadata_store/db/orm_bindings/misc.py#L5-L13
With actual data:
```
db_version,13
```
The file approach includes using a single file like `exitnode_cache.dat` to store a small amount of persistent data. 
Another example: sometimes …
> Add Simple Storage Component

- src/tribler-gui/tribler_gui/qt_resources/mainwindow.ui
- src/tribler-gui/tribler_gui/widgets/settingspage.py
Based on yesterday's discussion, this PR removes allow_exit_node_checkbox from UI as potentially dangerous for a user.
> Remove allow_exit_node_checkbox

- src/tribler-common/tribler_common/rest_utils.py
- src/tribler-common/tribler_common/tests/test_rest_utils.py
- src/tribler-gui/tribler_gui/tribler_window.py
> Fixes #6747: OSError "The filename, directory name, or volume label syntax is incorrect" in dragEnterEvent

- src/tribler-core/tribler_core/components/metadata_store/remote_query_community/tests/test_remote_search_by_tags.py
- src/tribler-core/tribler_core/components/tag/db/tag_db.py
- src/tribler-core/tribler_core/components/tag/db/tests/test_tag_db.py
This PR is related to #6708 and introduces a bit different logic for tag search than it was before.
As @kozlovsky suggested earlier, we should return 'intersection' of search results instead of 'union' in the case that more than one tag is specified in the search query.
This test that should clarify what I mean:
```python
@db_session
async def test_get_infohashes(self):
self.add_operation_set(
self.db,
{
b'infohash1': [
Tag(name='tag1', count=SHOW_THRESHOLD),
Tag(name='tag2', count=SHOW_THRESHOLD)
],
b'infohash2': [
Tag(name='tag1', count=SHOW_THRESHOLD)
],
b'infohash3': [
Tag(name='tag2', count=SHOW_THRESHOLD)
]
}
)
assert self.db.get_infohashes({'tag1', 'tag2'}) == [b'infohash1']
```
> Change tag search condition from `or` to `and`

- src/tribler-core/run_tunnel_helper.py
- src/tribler-core/tribler_core/components/payout/payout_component.py
- src/tribler-core/tribler_core/components/restapi/rest/events_endpoint.py
- src/tribler-core/tribler_core/components/restapi/rest/tests/test_events_endpoint.py
Fixes https://github.com/Tribler/tribler/issues/6751
> Add missing notifier topic observers based on enum values

- src/tribler-core/tribler_core/components/key/tests/test_key_component.py
- src/tribler-core/tribler_core/components/tag/rules/tag_rules_processor.py
- src/tribler-core/tribler_core/components/tag/rules/tests/test_tag_rules_processor.py
I discovered the reason for unstable tests. It was caused by an interaction between one broken fixture, one broken test, and the aiohttp async plugin. The fix is simple, but the actual sequence of events that led to the error was amazing.
Initially, there was no error on my local machine, as the error is unstable and caused by a specific order of tests. I added the following pytest option to my local configuration to reproduce the error: `--randomly-seed=1`. It created a stable pseudo-random test sequence that failed stably on my machine, and then I could debug the reason for the error.
The failed test looked pretty innocent, and the error does not seem to be related to the test code:
```python
async def test_get_private_key_filename(tribler_config):
private_key_file_name = …
```
> Fix unstable tests

- .github/workflows/docker-image.yml
- Dockerfile
- docker-compose.yml
- Run docker as non-root user
- Map local `.Tribler` to docker container so that downloads runs inside the container.
- Add a Github action to build and publish docker container to docker registry whenever the `main` branch is updated. The built image is published to 
https://hub.docker.com/r/triblercore/triblercore
> Docker support

- src/tribler-core/tribler_core/utilities/process_checker.py
> Handle race condition when deleting lock file

- doc/requirements.txt
> Specify exact version of MarkupSafe in doc requirements

- src/tribler-core/tribler_core/components/libtorrent/download_manager/download.py
> Fixes #6777: suppress PermissionError in on_save_resume_data_alert

- .gitmodules
- doc/build-docs.sh
- doc/building/building_on_osx.rst
- doc/building/building_on_windows.rst
- doc/development/development_on_linux.rst
- doc/development/development_on_osx.rst
- src/seedbox/README.md
- src/tribler-core/tribler_core/requirements.txt
This PR is a part of #6505.
It changes the way the `ipv8` module is used in Tribler from "sub-module" to "external dependency".
I've requested a review from the involved participants. In case, the participants agree with the change, I will continue with the implementation.
The future steps will be:
1. Merging this branch into the main
2. Changing corresponding Jenkins jobs
**The question**: I'm not sure about the ordering of the future steps. Should I merge the branch first, and change the corresponding Jenkins jobs second, or the opposite?
> Use ipv8 as an external dependency

- README.rst
This PR adds two new badges to the readme:
* python 3.8
* python 3.9
Also, this PR splits the badge set on sections divided by `<br>`.
How it looks:
Closes #6794
> Add python 3.9 and python 3.9 badges

- src/tribler-gui/tribler_gui/dialogs/addtopersonalchanneldialog.py
> Add null check to confirm_clicked_callback

- src/tribler-core/tribler_core/components/bandwidth_accounting/tests/test_bandwidth_accounting_component.py
- src/tribler-core/tribler_core/components/gigachannel/tests/test_gigachannel_component.py
- src/tribler-core/tribler_core/components/gigachannel_manager/tests/test_gigachannel_manager_component.py
- src/tribler-core/tribler_core/components/ipv8/tests/test_ipv8_component.py
- src/tribler-core/tribler_core/components/libtorrent/tests/test_libtorrent_component.py
- src/tribler-core/tribler_core/components/metadata_store/tests/test_metadata_store_component.py
- src/tribler-core/tribler_core/components/payout/tests/test_payout_component.py
- src/tribler-core/tribler_core/components/popularity/tests/test_popularity_component.py
- src/tribler-core/tribler_core/components/restapi/tests/test_restapi_component.py
- src/tribler-core/tribler_core/components/socks_servers/tests/test_socks_servers_component.py
- src/tribler-core/tribler_core/components/tag/tests/test_tag_component.py
- src/tribler-core/tribler_core/components/torrent_checker/tests/test_torrent_checker_component.py
- src/tribler-core/tribler_core/components/tunnel/tests/test_tunnel_component.py
- src/tribler-core/tribler_core/components/watch_folder/tests/test_watch_folder_component.py
- src/tribler-core/tribler_core/conftest.py
This PR fixes #6709 by introducing the `no_parallel` pytest's mark.
All tests that have this mark will be excluded from normal "parallel" Jenkins's run. But they will be run sequentially instead (like tunnel tests do).
In case this PR will be approved, I will merge it to the main and then modify corresponding Jenkins' jobs.
> Add "no_parallel" pytest's mark

- pytest.ini
- src/conftest.py
- src/tribler-core/tribler_core/conftest.py
This PR should fix test run failures that happens in https://github.com/Tribler/tribler/pull/6716
> Add no_parallel to pytest.ini

- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
> Handle ValueError "Data is not a bencoded string" in TorrentInfoEndpoint.get_torrent_info()

- src/tribler/core/components/libtorrent/download_manager/download.py
> Wrap Download.on_metadata_received_alert() with @check_handle decorator

- src/tribler/core/components/tag/community/tag_community.py
> Escape non-ASCII symbols when writing the tag value to the log

- src/conftest.py
Tribler's tests have been executed in Jenkins by the following commands:
```shell
pytest src/tribler/core -v --tx '12*popen//execmodel=eventlet' --cov=tribler --cov-report=xml:../output/coverage.xml --junitxml=test_report.xml
pytest src/tribler/core -v --no_parallel --cov=tribler --cov-report=xml:../output/coverage.xml --cov-append
```
1. During the first run, all tests that have the `@no_parallel` mark should be excluded from the execution.
2. During the second run, all tests that don't have the `@no_parallel` mark should be excluded from the execution.
This PR makes the second statement correct.
> For test run with '--no-parallel' argument, skip all "normal" tests

- src/run_tribler.py
After extracting upgrader from core process, some arguments were missing in `RunTriblerArgsParser`. As a result, Application tester cannot run Tribler with arguments `--allow-code-injection --tunnel-testnet --trustchain-testnet`. This PR fixes the problem.
> Add missed arguments to RunTriblerArgsParser

- src/tribler/core/components/bandwidth_accounting/db/database.py
This PR fixes #6802.
It seems possible to create a multiple transactions for the given pair or `public_key_a` and `public_key_b` by setting `bandwidth_database.store_all_transactions` to `True`:
https://github.com/Tribler/tribler/blob/ec35106cc618ef60f73a1925a78812cc1549f515/src/tribler/core/components/bandwidth_accounting/db/transaction.py#L151-L161
That's why `BandwidthDatabase.get_latest_transaction` should be ready for this situation.
> Replace `get` by `select.limit` in BandwidthDatabase.get_latest_transaction

- src/tribler/gui/single_application.py
- src/tribler/gui/start_gui.py
- src/tribler/gui/tests/test_gui.py
- src/tribler/gui/tribler_app.py
- src/tribler/gui/tribler_window.py
This is a PR with refactoring requested by @kozlovsky in #6829
> Rename QtSingleApplication.activation_window() to tribler_window

- src/tribler/gui/utilities.py
This PR fixes #6832 by adding `UnicodeEncodeError` to the except block of the `is_dir_writable` function.
Also `is_dir_writable` has been refactored by switching `os.path` to `Path`.
> Add `UnicodeEncodeError` to the except block

- .flake8
- requirements-core.txt
- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/libtorrent_component.py
- src/tribler/core/components/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler/core/components/libtorrent/tests/test_download_api.py
- src/tribler/core/utilities/rest_utils.py
- src/tribler/core/utilities/tests/test_rest_utils.py
- src/tribler/gui/dialogs/startdownloaddialog.py
- src/tribler/gui/start_gui.py
- src/tribler/gui/tests/test_gui.py
- src/tribler/gui/tribler_app.py
- src/tribler/gui/tribler_window.py
This PR improves the work of rest_utils and finished fix #6738
> Refactor rest utils

- pytest.ini
- src/tribler/core/components/base.py
- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/libtorrent_component.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
This PR fixes #6822 by increasing a default pytest timeout.
Also this PR:
1. Extends logging for base Component and Download Manager.
2. Refactors shutdown function of Download Manager.
> Fix terminated by timeout exception

- .github/workflows/upload_coverage.yml
This PR fixes the broken `upload_coverage` workflow https://github.com/Tribler/tribler/actions/runs/2153685742
> Fix upload_coverage.yml

- .github/workflows/upload_coverage.yml
This PR fixes https://github.com/Tribler/tribler/runs/5988192162?check_suite_focus=true by swapping download action due to limitations of https://github.com/actions/download-artifact.
The `action-download-artifact@v2` action description: https://github.com/dawidd6/action-download-artifact
> Swap download action by dawidd6/action-download-artifact@v2

- .github/workflows/pytest.yml
This PR fixes https://github.com/Tribler/tribler/runs/5988610597?check_suite_focus=true by increasing windows' timeout for a pytest run.
> Override `windows-latest` pytest timeout

- src/tribler/core/components/ipv8/eva_protocol.py
- src/tribler/core/components/ipv8/tests/test_eva_protocol.py
- src/tribler/core/components/metadata_store/remote_query_community/remote_query_community.py
- src/tribler/core/components/metadata_store/remote_query_community/tests/test_remote_query_community.py
During the ultimate stress test of the EVA protocol made by @devos50 we figured out some improvements that could be done to the EVA protocol.
During massive use of binary transfers provided by EVA protocol, some packets seem to be dropped by a socket. 
EVA protocol has been designed as an abstract protocol, that uses ipv8 as a transport layer. That means EVA doesn't care much about balancing socket load. 
However, it seems like a good idea to add a tool to the protocol to have the ability to limit ipv8 and socket load.
This tool will be variable `max_simultaneous_transfers` and it will be set to `10` by default.
EVA doesn't support handling lost WriteRequest packets and performs only one attempt to send WriteRequest.
@devos50 added this support in …
> Improve the EVA protocol: devos50 edition

- src/tribler/core/components/ipv8/eva_protocol.py
- src/tribler/core/components/ipv8/tests/test_eva_protocol.py
This PR addresses https://github.com/Tribler/tribler/issues/6845
> EVA: refactor transfer class

- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/utils/torrent_utils.py
- src/tribler/core/utilities/tests/test_torrent_utils.py
This PR adds typings to the `Download` class.
This is done during the estimation of #6792
> Add typings to the `Download` class

- src/tribler/gui/core_manager.py
- src/tribler/gui/tests/test_core_manager.py
This PR addresses #6810
This PR changes the error formatting style in "`on_core_finished` with an error".
Two changes:
1. Added translation from `err_code` to `strerror`
2. Added quoting for the last core output
An example of an error message:
```
The Tribler core has unexpectedly finished with exit code 2 and status: 2.
Error message: No such file or directory
Last core output:
> ERROR <loggingstuff:8> root.print_error(): Something went wrong!
> Traceback (most recent call last):,
>   File "ipv8  askmanager.py", line 131, in done_cb,
>   File "ipv8\messagingnonymization\hidden_services.py", line 366, in on_create_e2e,
>   File "ipv8\messagingnonymization\hidden_services.py", line 378, in create_created_e2e,
> KeyError: 1030643827
```
Ref:
* https://docs.python.org/3/library/errno.html
* …
> Add `format_error_message` function

- src/run_tribler.py
- src/tribler/core/sentry_reporter/sentry_reporter.py
- src/tribler/core/sentry_reporter/sentry_tools.py
- src/tribler/core/sentry_reporter/tests/test_sentry_reporter.py
- src/tribler/core/sentry_reporter/tests/test_sentry_tools.py
If you want to use Sentry as a developer, you have to specify the following env:
```bash
export TRIBLER_SENTRY_URL=<sentry_url>
```
I do recommend using [this](https://sentry.tribler.org/organizations/tribler/projects/tmp) project for dev's error reports.
After doing that all reported errors will be sent to this URL and be placed into `dev` [release](https://sentry.tribler.org/organizations/tribler/releases/dev/?project=3).
These are two examples of errors:
* https://sentry.tribler.org/organizations/tribler/issues/1220
* https://sentry.tribler.org/organizations/tribler/issues/1221
> Add an ability to send Sentry reports for developers

- src/tribler/core/components/ipv8/eva_protocol.py
- src/tribler/core/components/ipv8/protocol_decorator.py
- src/tribler/core/components/ipv8/tests/test_eva_protocol.py
- src/tribler/core/components/metadata_store/remote_query_community/remote_query_community.py
This PR addresses https://github.com/Tribler/tribler/issues/6845
> EVA: refactor the `Transfer` class

- .github/workflows/coverage.yml
- .github/workflows/pytest.yml
- requirements-test.txt
This PR adds [looptime](https://github.com/nolar/looptime)
`Looptime` should decrease test execution and simplify some tests that use `asyncio.sleep`.
> Add looptime

- requirements-core.txt
- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/tests/test_download.py
Fixes #6875
This PR fixes two independent problems. 
First is an incorrect test `test_get_pieces_bitmask`.
This test used `[True * 16]` as an array initialization which is lead to the following array
```python
assert [True * 16] == [16]
```
Another problem is `get_pieces_base64` itself, which could be rewritten as:
```python
def get_pieces_base64(self) -> bytes:
binary_gen = (int(boolean) for boolean in self.handle.status().pieces)
bits = bitarray(binary_gen)
return base64.b64encode(bits.tobytes())
```
Refs:
* https://www.libtorrent.org/reference-Torrent_Status.html#torrent_status
* https://github.com/ilanschnell/bitarray
> Simplify base64 conversion in `get_pieces_base64`

- src/tribler/core/components/libtorrent/download_manager/download_config.py
- src/tribler/core/components/libtorrent/tests/test_download.py
- src/tribler/core/components/libtorrent/tests/test_download_config.py
- src/tribler/core/utilities/utilities.py
This PR fixes #6833
Refs:
* https://stackoverflow.com/questions/2941995/python-ignore-incorrect-padding-error-when-base64-decoding
* https://docs.python.org/3/library/base64.html
> Avoid incorrect padding

- src/tribler/gui/event_request_manager.py
This PR fixes an incorrect error message for CoreConnectTimeoutError that reports milliseconds as seconds.
The constant `RECONNECT_INTERVAL_MS` stores the number of milliseconds, so to display seconds, the result of the expression needs to be divided by 1000.
> Fix an error message that reports milliseconds as seconds

- src/tribler/gui/core_manager.py
- src/tribler/gui/tests/test_core_manager.py
> Handle non-utf8 Tribler Core output in Tribler GUI

- .github/workflows/!PR.yml
- .github/workflows/build_ubuntu.yml
This PR fixes the PR event type (which has been introduced here: https://github.com/Tribler/tribler/pull/6913) by adding the type "opened". This makes it possible to run all the checks immediately after a PR is created.
Also, it adds `python-version` as a parameter to Ubuntu build.
Ref:
* https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
> Fix PR event

- .github/actions/pyenv/action.yml
- .github/workflows/!PR.yml
- .github/workflows/build_ubuntu.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
This PR adds cache for pip python dependencies. It should decrease the time of job runs.
(this improvement saves ~1m for each run)
Ref:
* https://github.com/actions/setup-python/issues/330
* https://docs.github.com/en/actions/creating-actions/about-custom-actions#composite-actions
* https://github.com/syphar/restore-virtualenv
> Add pip cache for GitHub Actions

- .github/actions/windows_dependencies/action.yml
- .github/workflows/pytest.yml
This PR adds the `windows_dependencies` action to our GitHub Workflows. This functionality has been extracted from https://github.com/Tribler/tribler/pull/6920.
(it saves ~ 10s for each win run and generalises logic of win jobs)
Ref:
* https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
> Add `windows_dependencies` action

- .github/workflows/build_ubuntu.yml
This PR makes it possible to invoke ubuntu build manually from this page: https://github.com/Tribler/tribler/actions/workflows/build_ubuntu.yml
The following screens will be available after merge:
Ref:
* https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
* https://github.community/t/inconsistent-inputs-context-for-workflow-dispatch-and-workflow-call/207835/7
> Add `workflow_dispatch` for ubuntu build

- .github/workflows/build_ubuntu.yml
- .github/workflows/build_windows.yml
- build/win/makedist_win.bat
- build/win/replace_nsi.py
This PR adds the `build_windows.yml` workflow that can be run manually.
GitHub windows build skips signing part:
```
signtool.exe sign /f C:\build\certs\certificate.pfx /p "%PASSWORD%" /d "Tribler" /t "http://timestamp.digicert.com" tribler.exe
```
The reason for skipping is that signing by itself is a highly discussible topic (particularly how we should sign Tribler binaries in GitHub). But the build itself will be very helpful for investigating virus alerts that we see in our Jenkins.
---
Also, this PR performs the second step of `update_version_from_git.py` refactoring: extracting `replace_nsi.py`.
When I add a build workflow for macOS, `update_version_from_git.py` could be deleted.
This change is backward-compatible with Jenkins one-click-release, but we must add the following lines …
> Build Tribler binaries for win

- .github/workflows/build_ubuntu.yml
- .github/workflows/build_windows.yml
This PR changes the position of the "Upload" checkbox:
And makes all Ubuntu inputs optional.
> GitHub Actions: Change order of upload value

- src/tribler/gui/core_manager.py
This PR fixes https://github.com/Tribler/tribler/issues/6929
@kozlovsky:
I debugged the problem and found the reason for the error. It is in [this line](https://github.com/Tribler/tribler/blob/410fb735d3758ccf8ac4745e0f2cd3c89a31f2e9/src/tribler/gui/core_manager.py#L98) of CoreManager:
```python
self.core_process.start(sys.executable, core_args)
```
There is a difference in arguments between a python script and a compiled executable. For script, arguments can look like
```python
["myscript.py", "arg1", "arg2"]
```
and sys.executable is something like C:/Python39/python.exe.
For the same code in the compiled executable, arguments will be
```python
["myscript.exe", "arg1", "arg2"]
```
and sys.executable is myscript.exe.
That means that when Tribler executes …
> Fixes #6929

- .github/workflows/coverage.yml
- src/run_tribler_headless.py
- src/tribler/core/check_os.py
- src/tribler/core/start_core.py
- src/tribler/core/tests/test_check_os.py
- src/tribler/core/utilities/process_checker.py
- src/tribler/core/utilities/tests/test_osutils.py
- src/tribler/core/utilities/tests/test_process_checker.py
- src/tribler/core/utilities/tiny_tribler_service.py
- src/tribler/gui/core_manager.py
- src/tribler/gui/tribler_window.py
This PR fixes #6874 by refactoring ProcessChecker implementation and adding a broad exception handling.
> ProcessChecker refactoring

- .github/workflows/!main.yml
- .github/workflows/build_ubuntu.yml
- .github/workflows/codacy.yml
- .github/workflows/coverage.yml
- .github/workflows/docker-image.yml
This PR fixes #6952, #6951 by passing secrets to callable workflows explicitly.
Also, this PR adds missed ubuntu build step for the "push to main" event and fixes a security issue with the docker image build.
Ref:
* https://github.community/t/reusable-workflows-secrets-and-environments/203695/40
> Pass secrets to callable workflows.

- src/tribler/core/utilities/tests/test_process_checker.py
Sometimes ProcessChecker tests become frozen for an unknown reason.
This PR makes an attempt to fix it.
See:
* https://github.com/Tribler/tribler/runs/7088824564?check_suite_focus=true
* https://github.com/Tribler/tribler/runs/7089778224?check_suite_focus=true
> Fix random frozen ProcessChecker tests

- src/tribler/core/components/restapi/rest/debug_endpoint.py
- src/tribler/core/components/restapi/restapi_component.py
- src/tribler/core/exceptions.py
- src/tribler/gui/exceptions.py
- src/tribler/gui/tribler_window.py
Sometimes it is very convenient to manually trigger an exception in Tribler to see how the exception is handled with the current configuration settings.
This PR adds a possibility to trigger a test exception in the "frontend" GUI process by pressing `Ctrl+Alt+Shift+Home`, as well as trigger another exception in the "backend" Core process by pressing `Ctrl+Alt+Shift+End`. The triggered exceptions are processed the same way "natural" exceptions are processed.
This functionality allows manually discovering and fixing bugs in error handling code with specific error reporting configuration settings.
> Add a posiibility to manually trigger GUI and Core exceptions in Tribler for debugging purposes

- src/tribler/core/components/restapi/rest/debug_endpoint.py
- src/tribler/gui/core_manager.py
- src/tribler/gui/dialogs/feedbackdialog.py
Currently, in case of exception, if SentryReporter is in test mode, after reporting an exception it calls [`AppManager.quit_application()`](https://github.com/Tribler/tribler/blob/da025dc5b5e651064bd4e54cfe2a2d29f367bf20/src/tribler/gui/dialogs/feedbackdialog.py#L199), which in turn calls `QApplication.quit()`.
This logic is incorrect, as the Tribler core process, managed by a `QProcess` instance, terminated immediately without any possibility to do cleanup work, like removing the `triblerd.lock` file or saving the libtorrent state.
The correct behavior is to stop the Core process the usual way and then shut down GUI. This PR fixes the shutdown logic, allowing the Core to shut down properly.
> Fix Tribler shutdown after closing of FeedbackDialog

- src/tribler/core/components/base.py
- src/tribler/core/components/restapi/rest/shutdown_endpoint.py
- src/tribler/core/start_core.py
- src/tribler/gui/core_manager.py
- src/tribler/gui/tribler_request_manager.py
> Re-send shutdown request from GUI to Core if the previous shutdown request was canceled

- src/run_tribler.py
- src/tribler/core/sentry_reporter/sentry_reporter.py
- src/tribler/core/sentry_reporter/sentry_tools.py
- src/tribler/core/sentry_reporter/tests/test_sentry_reporter.py
- src/tribler/core/sentry_reporter/tests/test_sentry_tools.py
(cherry picked from commit 01e814016c86f69dd5d196f44b52150f99c84c03)
This PR fixes #6974 by using only one of the two sentry reporters in each Tribler process
> Cherry-pick #6886 from main to release branch to fix #6974

- src/tribler/core/upgrade/version_manager.py
> Copy libtorrent session state when upgrading Tribler to a new version

- src/tribler/core/utilities/process_checker.py
[Recently](https://github.com/Tribler/tribler/commit/258fe001d9b1023f74a55dc2690b61ab6aebb5b8), the lock file name was changed in the main branch from `triblerd.lock` to `tribler.lock`. We need to have the same name of the lock file as in previous Tribler releases to ensure that lock works across releases.
Also, sometimes it may be convenient to have a constant with a file name on a module level (as we had before) and not just as a default value for a constructor argument.
With these changes, we can cherry-pick #6941 from the main branch to the release branch
> Restore name "triblerd.lock" for lock file

- .github/workflows/guitest.yml
PR job was missing some dependencies which is fulfilled by pyqt5-dev-tools.
This dependency might be because of the update of the base docker image
running on Github Action which is unclear.
Fixes https://github.com/Tribler/tribler/issues/6970
> Fix failing GUI test on Linux Github action

- src/tribler/core/components/gui_process_watcher/gui_process_watcher.py
- src/tribler/core/components/gui_process_watcher/gui_process_watcher_component.py
- src/tribler/core/components/gui_process_watcher/tests/test_gui_process_watcher.py
- src/tribler/core/components/gui_process_watcher/tests/test_gui_process_watcher_component.py
- src/tribler/core/start_core.py
- src/tribler/gui/core_manager.py
This PR fixes #6994 by adding `GuiProcessWatcher` and `GuiProcessWatcherComponent`.
With this PR, GUI passes an additional environment variable to Core with the PID of the GUI process. If GUI PID was passed to Core, it starts watching GUI process state with periodical checks. If the GUI process stops, the watcher calls `session.shutdown_event.set()` to shut down the Core process.
> Shut down the Tribler Core process if the GUI process crashes.

- src/run_tribler_headless.py
- src/tribler/core/check_os.py
- src/tribler/core/start_core.py
- src/tribler/core/tests/test_check_os.py
- src/tribler/core/utilities/process_checker.py
- src/tribler/core/utilities/tests/test_osutils.py
- src/tribler/core/utilities/tests/test_process_checker.py
- src/tribler/core/utilities/tiny_tribler_service.py
- src/tribler/gui/core_manager.py
- src/tribler/gui/tribler_window.py
This PR cherry-picks https://github.com/Tribler/tribler/issues/6874 to the release branch to improve the handling of the lock file and the hanging Tribler Core processes
> Cherrypick 6941 to release 7 12 1

- src/tribler/gui/dialogs/feedbackdialog.py
- src/tribler/gui/exceptions.py
- src/tribler/gui/upgrade_manager.py
This PR fixes #7003.
After I added exception handling for the error in the `UpgradeManager`, I discovered that Tribler GUI does not handle it properly. First, it considered the error as a GUI error by default, and the current Tribler policy is not to close on GUI errors. To fix this, I added an `UpgradeError` exception inherited from Core exception. This way GUI knows that the exception is serious enough to finish Tribler execution.
Second, the close button of the FeedbackDialog does not close it. The reason is the following: GUI thinks that Core is shutting down but not finished yet, so trying to wait until it is finished. Actually, Core was not even started, as the exception happened before the `start_tribler_core` method was called. Because of this, the logic of the `FeedbackDialog` …
> Handle exceptions in UpgradeManager

- .github/workflows/pytest.yml
- .pylintrc
- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/download_manager/download_config.py
- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/reporter/exception_handler.py
- src/tribler/core/components/watch_folder/tests/test_watch_folder.py
- src/tribler/core/components/watch_folder/watch_folder.py
- src/tribler/gui/error_handler.py
This PR contains refactoring of the Watch Folder.
Changes:
1. TaskManager has been swapped to AsyncGroup. 
2. All Watch Folders errors now have the type of `NoCrashException` meaning that these errors will not stop Tribler.
3. Logic of the Watch Folder has been simplified.
4. Core now has the same error handling logic that GUI has (only the first exception of a given type will be shown).
This PR prepared Watch Folder Component for future fixing of #5833.
> Refactor the WatchFolder

- .github/workflows/coverage.yml
- src/tribler/core/components/metadata_store/db/orm_bindings/torrent_metadata.py
- src/tribler/core/components/metadata_store/db/tests/test_torrent_metadata.py
This PR fixes #6987
In the case of wrong `get_tracker()` type (eg `["b'udp://tracker/announce'"']`) the result string for the `tracker_info` will be empty (which is better than an exception).
> Convert the result of `tdef.get_tracker()` to `str`

- src/tribler/gui/core_manager.py
- src/tribler/gui/tests/test_core_manager.py
This PR cherry-picks #6881 from main to the release branch. I need it to fix #7013 without merge conflicts between `main` and `release` branches
> Cherry-pick adding `format_error_message` function to CoreManager

- src/tribler/gui/event_request_manager.py
Currently, the exception message for timeout does not include the actual error received on the last attempt to connect to the Core. This PR fixes it. With the actual error presented, it should be easier to separate different categories of problems and understand the reason for the problem.
> Show the last error code and error name on timeout in EventRequestManager

- .github/actions/pyenv/action.yml
This PR fixes #7026 by adding the dedicated `requirements-key` parameter.
This parameter will be used in the `restore-virtualenv@v1.2.1` action as a value on which the cache key be generated.
```yml
- name: Restore virtual env
uses: drew2a/restore-virtualenv@v1.2.1
id: cache-virtualenv
with:
requirement_files: ${{inputs.requirements-key}}
```
The old parameter `requirements` is still be used for passing it into:
```yml
- name: Install pip dependencies
if: steps.cache-virtualenv.outputs.cache-hit != 'true' || inputs.invalidate-cache == 'true'
shell: bash
run: |
python -m pip install --upgrade pip
pip install -r ${{inputs.requirements}}
```
Therefore by default for the cache key generation, we use the pattern `**/requirements*.txt` which can be translated into:
```
requirements-build.txt …
```
> Add the `requirements-key` parameter to the pyenv GitHub Action

- .github/workflows/documentation.yml
This PR fixes `documentation.yml` by specifying the `requirements-key` parameter.
Otherwise, the virtual environment will not be restored properly.
Error: https://github.com/Tribler/tribler/runs/8135472947?check_suite_focus=true
Related: https://github.com/Tribler/tribler/pull/7028
> Specify the `requirements-key` parameter for `documentation.yml`

- requirements-core.txt
- src/tribler/core/sentry_reporter/sentry_scrubber.py
- src/tribler/core/sentry_reporter/sentry_tools.py
- src/tribler/core/sentry_reporter/tests/test_sentry_reporter.py
- src/tribler/core/sentry_reporter/tests/test_sentry_scrubber.py
- src/tribler/core/sentry_reporter/tests/test_sentry_tools.py
This PR implements the change for a sentry event processing requested by @kozlovsky 
There are three changes in this PR:
1.  `server_name` now is a part of the `self.dict_keys_for_scrub` which leads to scrubbing the server name from the corresponding field of the sentry event.
2. For all scrubbed values the `obfuscate_string` function has been applied instead of a static placeholder.
3. The `test_sentry_scrubber` file has been refactored.
Example: https://sentry.tribler.org/organizations/tribler/issues/1592
> Obfuscate machine name for Sentry events

- src/tribler/core/sentry_reporter/sentry_scrubber.py
- src/tribler/core/sentry_reporter/tests/test_sentry_scrubber.py
- src/tribler/gui/core_manager.py
- src/tribler/gui/error_handler.py
This PR changes the process of collecting CORE core breadcrumbs.
Instead of collecting them on the core side, they are added to the GUI Sentry Reported as they appear.
"Normal" error: https://sentry.tribler.org/organizations/tribler/issues/1599
CoreCrashError: https://sentry.tribler.org/organizations/tribler/issues/1546
The purpose of this improvement is to investigate `CoreConnectionError` issues like https://github.com/Tribler/tribler/issues/6989
> Add core stdout breadcrumb

- src/tribler/core/components/tunnel/community/tunnel_community.py
- src/tribler/core/components/tunnel/tests/test_triblertunnel_community.py
> Protect `cache_exitnodes_to_disk` from raising OSErrors

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/libtorrent_component.py
- src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
- src/tribler/core/conftest.py
- src/tribler/gui/event_request_manager.py
- src/tribler/gui/tests/test_core_manager.py
- src/tribler/gui/widgets/downloadspage.py
> Load checkpoints in background

- src/tribler/core/components/gui_process_watcher/tests/test_gui_process_watcher.py
This PR fixes a bug in `test_gui_process_watcher` tests that lead to the following warning:
```
RuntimeWarning: coroutine 'interval_runner' was never awaited
```
As `GuiProcessWatcher` is an instance of a `TaskManager`, it is necessary to call `watcher.stop()` at the end of the test to cancel all background tasks.
This PR adds a fixture for the `GuiProcessWatcher` instance that calls `await watcher.stop()` automatically at the end of the test.
> Fix GuiProcessWatcher tests

- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/tests/test_download.py
- src/tribler/gui/tribler_request_manager.py
- src/tribler/gui/tribler_window.py
This PR fixes #7036 
There are three independent places that cause three independent `UnicodeDecodeError`. 
Fixes are separated into different commits.
> Fix `UnicodeDecodeError`

- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
> Add `SSLError` to exceptions

- src/tribler/core/components/restapi/restapi_component.py
RESTComponent should not add `/ipv8` endpoint if Ipv8Component is not available.
The current code in the main branch has a bug - it tries to handle the situation, but still creates `/ipv8` endpoint in this case
> Fix initialization of Ipv8Endpoint in RESTComponent

- src/tribler/core/start_core.py
Currently, it is theoretically possible to run Tribler Core without `RESTComponent`. This PR unconditionally includes `RESTComponent` in the component list, as this component is necessary for GUI-Core communication.
> Unconditionally include RESTComponent when starting Tribler Core

- src/tribler/gui/error_handler.py
- src/tribler/gui/tests/test_error_handler.py
The current signature of the `gui_error` function is not strict enough. In practice, the function is always called with three arguments. Because of insufficient checks, inside the `gui_eror` function, PyCharm shows warnings "local variable might be referenced before assignment". This PR fixes PyCharm warnings and makes variable names for the exception and the exception type more "traditional".
Also, the PR uses the `caplog` pytest fixture to check log messages in tests.
> Stricter signature for ErrorHandler.gui_error()

- src/tribler/core/upgrade/version_manager.py
This PR fixes the source of #7002 by providing atomicity for state directory copying. To achieve that, it first copies the state into a temporary dir and then renames it to a correct name after the copying process is finished.
Also, it adds logging to the version manager, making it possible to see upgrade-related events in error reports.
> Provide atomicity of state dir copying

- src/tribler/gui/event_request_manager.py
> Fix CoreConnectTimeoutError by calculating the correct timeout for the request

- .github/actions/pyenv/action.yml
- src/tribler/core/components/knowledge/community/knowledge_community.py
- src/tribler/core/components/knowledge/community/tests/test_knowledge_community.py
- src/tribler/core/components/knowledge/db/knowledge_db.py
- src/tribler/core/components/knowledge/db/tests/test_knowledge_db.py
Remove the `time_delta` parameter from the `get_operations_for_gossip` function.
(Based on the morning dev meeting)
Related to https://github.com/Tribler/tribler/issues/6214
> Remove the `time_delta` parameter from the `get_operations_for_gossip` function

- .github/workflows/guitest.yml
This PR closes #7082 by adding the action for screenshots publishing. 
Refs:
* https://github.com/actions/upload-artifact
* https://stackoverflow.com/questions/58858429/how-to-run-a-github-actions-step-even-if-the-previous-step-fails-while-still-f
* https://github.com/orgs/community/discussions/26438
> Add the action for screenshots publishing

- src/tribler/gui/tribler_window.py
Inhibit showing new version notification for current GUI session after postpone button is clicked.
Resolves #7077
--
Not tried running it.
> Inhibit new version nag if postpone is pressed

- .github/actions/pyenv/action.yml
This PR fixes #7091 by adding `ref_name` of a GitHub event as a `custom_cache_key_element` for the `restore-virtualenv` action.
This should help to isolate caches between branches.
> Fix pyenv GitHub Action

- src/tribler/gui/i18n/pt_BR.ts
- src/tribler/gui/i18n/ru_RU.ts
- src/tribler/gui/i18n/zh_CN.ts
- src/tribler/gui/tribler_window.py
- src/tribler/gui/upgrade_manager.py
This PR adds a refactoring for #7077
The actions for the buttons are the following:
1. Ignore: ignore this version at all. During the next Tribler run, all notifications about this version will be silently ignored.
2. Later: ignore the version check for the current Tribler run.
3. Ok: go to the Tribler website. The next version check will be performed 6 hours later.
> Refactoring for the New Version Dialog

- src/tribler/gui/widgets/tablecontentdelegate.py
Update to use integer division to ensure the coordinates remain integer being passed to QRect.
Fixes #7107
> Fixes #7107

- .github/workflows/!PR.yml
- .github/workflows/guitest.yml
This PR closes #7086, closes #7087
To my great surprise, it worked out of the box.
The only one issue was "how to call a workflow with the custom matrix?".
The solution is to use `fromJson` for passing the matrix as a JSON object:
```yml
name: PR
on:
pull_request:
types:
- opened
- synchronize
- ready_for_review
jobs:
magic:
uses: ./.github/workflows/magic.yml
with:
matrix: '{"os":["macos-latest","ubuntu-latest"]}'}
```
```yml
name: Magic
on:
workflow_call:
matrix:
default: '{"os":["windows-latest"]}'
type: string
required: false
jobs:
run:
runs-on: ${{ matrix.os }}
strategy:
matrix: ${{fromJson(inputs.matrix)}}
```
Refs:
* https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os
* https://github.com/pyvista/setup-headless-display-action
* …
> Add Windows and macOS GUI tests to GitHub Actions

- .github/workflows/!PR.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
- pytest.ini
This PR continues work started in  https://github.com/Tribler/tribler/pull/7115 and divides pytest into two categories:
1. Ubuntu — for a draft PR
2. Ubuntu+Win+macOS — for a ready PR
> Divide `pytest` into two categories: for a draft PR and for a ready PR

- src/tribler/gui/widgets/torrentfiletreewidget.py
This PR fixes #6699 by adding unbreakable spaces to text of the Size column's cells
> Fix the width of the Size column on Windows when the display scaling is more than 100%

- .github/workflows/!PR.yml
- .github/workflows/build_mac.yml
- .github/workflows/build_ubuntu.yml
- .github/workflows/build_windows.yml
- requirements-build.txt
This PR follows https://github.com/Tribler/tribler/pull/7123 and adds Windows and macOS builds as PR checks.
As a side effect, it fixes the `macOS` build.
Also, this PR contains some cosmetic changes for https://github.com/Tribler/tribler/pull/7130.
> Add macOS and windows builds as PR checks

- src/tribler/core/components/version_check/tests/test_versioncheck.py
- src/tribler/core/components/version_check/versioncheck_manager.py
This PR fixes #7124 by refactoring `versioncheck_manager.py` and removing all usage of global variables from it.
> Refactor `versioncheck_manager.py`

- src/tribler/core/components/libtorrent/download_manager/download_state.py
- src/tribler/core/components/libtorrent/tests/test_download_state.py
Fixes https://github.com/Tribler/tribler/issues/7106
> Fix crash when file progress is empty

- .github/workflows/!PR.yml
This PR closes #7125
Please, note this PR adds complexity to the `!PR.yml`. I'm not sure that it is worth the benefits.
```python
- uses: dorny/paths-filter@v2
id: filter
with:
filters: |
src:
- '.github/workflows/pytest.yml'
- '.github/workflows/guitest.yml'
- '.github/workflows/coverage.yml'
- '.github/actions/**'
- 'src/**'
- 'requirements*'
scripts:
- '.github/workflows/scripttest.yml'
- '.github/actions/**'
- 'scripts/**'
- 'src/**'
- 'requirements*'
doc:
- '.github/workflows/documentation.yml'
- '.github/actions/**'
- 'doc/**'
- 'src/**'
- 'requirements*'
build:
- '.github/workflows/build*.yml'
- '.github/actions/**'
- 'build/**'
- 'src/**'
- 'requirements*'
```
> Run checks only if it is necessary

- .github/actions/profile/action.yml
- .github/workflows/!PR.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
- requirements-test.txt
This PR adds profiling ability for `pytests`.
As a strategy for solving #7134 we can keep `enable_profiling=true` for some time to collect information for investigating the timeout issue.
Then we can disable this feature:
```yml
enable_profiling:
default: false
type: boolean
required: false
```
Refs:
* https://github.com/man-group/pytest-plugins/tree/master/pytest-profiling
* https://github.com/man-group/pytest-plugins/issues/52
* http://www.graphviz.org/download/
* https://github.com/actions/runner/issues/1979
> Add profiling for `pytest`

- src/tribler/core/components/gigachannel/community/tests/test_gigachannel_community.py
- src/tribler/core/components/gui_process_watcher/tests/test_gui_process_watcher.py
- src/tribler/core/components/ipv8/eva/tests/test_scheduler.py
- src/tribler/core/components/ipv8/eva/transfer/tests/test_base.py
- src/tribler/core/components/ipv8/eva/transfer/tests/test_window.py
- src/tribler/core/components/knowledge/community/tests/test_knowledge_validator.py
- src/tribler/core/components/knowledge/community/tests/test_operations_requests.py
- src/tribler/core/components/knowledge/db/tests/test_knowledge_db.py
- src/tribler/core/components/libtorrent/tests/test_dht_health_manager.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
- src/tribler/core/components/libtorrent/tests/test_libtorrent_settings.py
- src/tribler/core/components/metadata_store/remote_query_community/tests/test_remote_search_by_tags.py
- src/tribler/core/components/resource_monitor/implementation/tests/test_rm_settings.py
- src/tribler/core/components/restapi/tests/test_restapi_component.py
- src/tribler/core/components/torrent_checker/torrent_checker/tests/test_torrentchecker.py
- src/tribler/core/components/tunnel/tests/test_tunnel_settings.py
- src/tribler/core/config/tests/test_tribler_config_section.py
- src/tribler/core/tests/test_check_os.py
- src/tribler/core/tests/test_start_core.py
- src/tribler/core/upgrade/tests/test_upgrader.py
- src/tribler/core/utilities/tests/test_dependencies.py
- src/tribler/core/utilities/tests/test_patch_import.py
- src/tribler/core/utilities/tests/test_path_utils.py
- src/tribler/gui/tests/test_error_handler.py
This PR removes unnecessary `async` statements from test functions.
Extracted from https://github.com/Tribler/tribler/pull/7127
> Remove unnecessary `async` statements 

- .github/workflows/guitest.yml
- src/tribler/gui/tests/conftest.py
- src/tribler/gui/tests/test_gui.py
This PR fixes https://github.com/Tribler/tribler/issues/7132 
Refs:
* https://github.com/pyvista/setup-headless-display-action
* https://github.com/jurplel/install-qt-action
> Fix Windows GUI tests

- src/tribler/core/components/tunnel/tests/test_full_session/conftest.py
- src/tribler/core/conftest.py
This PR is related to https://github.com/Tribler/tribler/issues/7126 and has a change extracted from #7127.
It reverts https://github.com/Tribler/tribler/pull/6527 which was implemented to fix https://github.com/Tribler/tribler/issues/6456. 
It seems that the fix is no longer required. My assumption is that our test suite will be more stable without this `asyncio.SelectorEventLoop()` customization.
> Revert #6527

- src/tribler/core/components/knowledge/restapi/tests/test_knowledge_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_libtorrent_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_metadata_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_remote_query_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_search_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_create_torrent_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_debug_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_settings_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_shutdown_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_statistics_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_trustview_endpoint.py
- src/tribler/core/logger/logger.py
This PR partially closes #7122 by adding `app.shutdown()` call for the `rest_api` fixture
> Call `app.shutdown()` for rest_api fixture

- src/tribler/core/components/gigachannel/community/sync_strategy.py
- src/tribler/core/components/metadata_store/db/store.py
- src/tribler/core/components/metadata_store/remote_query_community/remote_query_community.py
- src/tribler/core/components/metadata_store/remote_query_community/settings.py
- src/tribler/core/components/metadata_store/remote_query_community/tests/test_remote_query_community.py
- src/tribler/core/components/metadata_store/remote_query_community/tests/test_remote_search_by_tags.py
- src/tribler/core/components/metadata_store/restapi/search_endpoint.py
- src/tribler/core/tests/test_search_utils.py
- src/tribler/core/utilities/search_utils.py
- src/tribler/gui/qt_resources/search_results.ui
- src/tribler/gui/tests/test_gui.py
- src/tribler/gui/widgets/channelcontentswidget.py
- src/tribler/gui/widgets/channelsmenulistwidget.py
- src/tribler/gui/widgets/search_progress_bar.py
- src/tribler/gui/widgets/searchresultswidget.py
- src/tribler/gui/widgets/tablecontentdelegate.py
- src/tribler/gui/widgets/tablecontentmodel.py
This PR implements improved search with better item ranking implemented at the DB level, as described in https://github.com/Tribler/tribler/issues/2250#issuecomment-1157735819. Elements with relevant titles and many seeders are placed closer to the top of the search result list.
UI shows local search results immediately, ready without any artificial delay. Remote items show automatically with a slight delay to avoid result flickering and have highlighted background to prevent user confusion when remote results appear on the screen.
Search UI has a progress bar to show the progress for the remote searches. The tooltip of the progress bar displays the number of complete remote requests and the total number of remote requests. It is possible to click on the progress bar to stop processing …
> Improved ranking for search results and updated search UI without the artifical delay at the loading screen

- scripts/seedbox/disseminator.py
- src/tribler/core/components/gigachannel_manager/gigachannel_manager.py
- src/tribler/core/components/metadata_store/db/store.py
- src/tribler/core/components/metadata_store/db/tests/test_store.py
- src/tribler/core/components/metadata_store/remote_query_community/remote_query_community.py
- src/tribler/core/components/metadata_store/restapi/search_endpoint.py
- src/tribler/core/components/metadata_store/tests/test_channel_metadata.py
- src/tribler/core/components/popularity/community/popularity_community.py
- src/tribler/core/upgrade/db8_to_db10.py
- src/tribler/core/upgrade/tests/test_upgrader.py
- src/tribler/core/upgrade/upgrade.py
- src/tribler/core/utilities/pony_utils.py
This PR extracts the `run_threaded` function to the `pony_utils.py` and fixes the bug with the query to the Knowledge Database.
> Extract the `run_threaded` function to the `pony_utils.py`

- src/tribler/core/components/session.py
This PR fixes #7149. The core notifier should receive the `loop` argument to process notifications in asynchronous mode. The error remains unnoticed for some time because most notifications work fine in synchronous mode as well.
> Core Tribler notifier should work in async mode

- src/tribler/core/components/metadata_store/tests/test_channel_metadata.py
The test `test_default_sorting_with_fts` currently works [unstable](https://github.com/Tribler/tribler/actions/runs/3418870558/jobs/5691694862) because the `torrent_date` attribute of the `TorrentMetadata` class got unstable values that are too close to each other, and this affects the sort order of test results. In this PR, I specify "stable" torrent creation dates that are not too close to each other and the current time, so they do not randomly affect the result sort order.
> Fix unstability in test_default_sorting_with_fts

- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/tests/test_download.py
- src/tribler/core/components/reporter/exception_handler.py
- src/tribler/core/components/reporter/reported_error.py
- src/tribler/core/components/session.py
- src/tribler/gui/error_handler.py
- src/tribler/gui/tests/test_error_handler.py
This PR fixes #7136 by reraising all exceptions in the `process_alert()` function as `NoCrashException`.
It doesn't fix the root problem of #7136 but makes Tribler more stable and allows users to send the exception to us and resume the Tribler work after.
During the testing of PR extended logging was also added.
> Re-raise all exception in  the `process_alert()` function as `NoCrashException`

- doc/conf.py
- requirements-core.txt
- src/tribler/core/components/restapi/rest/debug_endpoint.py
- src/tribler/core/utilities/path_util.py
- src/tribler/core/utilities/tests/test_path_utils.py
This PR related to #7067
I haven't found any problems with the current implementation of the `tail` function. The PR contains only refactoring and tests.
I'm not sure if we need to merge it.
---
The error occurred in this line:
https://github.com/Tribler/tribler/blob/52a7f97e7f2a8ad7aebb24e87de84ddc55f897d2/src/tribler/core/components/restapi/rest/debug_endpoint.py#L311
Variables of the function:
name | value
-- | --
byte_buffer | '1024'
file_handler | "<_io.TextIOWrapper name='C:\\\\Users\\\\<user>\\\\AppData\\\\Roaming\\\\.Tribler\\\\tribler-core-info.log' mode='r' encoding='cp1251'>"
lines | '100'
lines_found | []
block_counter | '-1'
The `tail` method could be used in #7158
Refs:
* https://github.com/RobinNil/file_read_backwards
> Refactoring of the `tail` function

- .github/workflows/pytest.yml
- src/tribler/core/components/resource_monitor/implementation/core.py
- src/tribler/core/components/resource_monitor/implementation/tests/test_resource_monitor.py
- src/tribler/core/logger/logger.yaml
- src/tribler/core/upgrade/tests/test_upgrader.py
- src/tribler/core/upgrade/upgrade.py
This PR fixes #7158
1. It limits log files to 100KB each with a backup count equal to `1`. That means the overall log size will be 800KB.
$Core+GUI =(2 \cdot Error+2 \cdot Info) + (2 \cdot Error+2 \cdot Info) = 2 \cdot (2 \cdot 100KB+2 \cdot 100KB) = 800 KB  $
2. It completely removes the `resources.log` logic as it is no longer used.
3. It adds a migration for removing all old logs.
Refs:
* https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler
> Limit the log size

- src/tribler/core/components/metadata_store/db/store.py
The full-text-search query can find hundreds of thousands of matching torrents in the database. In that case, the proper ranking and ordering of all these torrents may be pretty slow. I have seen queries that required 20 seconds for execution.
In this PR, I speed up the queries by two order magnitudes (from 20 seconds to 0.2 seconds) without a noticeable loss in quality. To do this, I perform filtering of torrents in a sequence of steps:
* First, if a direct full-text query to the database finds more than 10000 torrents, only the most recent 10000 torrents are considered.
* Among these selected torrents, the ones with known seeders get priority, and 1000 torrents are selected for further consideration. When no information about seeders is available, the most recent torrents get priority. …
> 100x speedup for full-text search queries without quality loss

- .github/workflows/coverage.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
- requirements-test.txt
This PR mask flakiness of our test suite.
Related to:
* https://github.com/Tribler/tribler/issues/7167 
* https://github.com/Tribler/tribler/issues/7164
* https://github.com/Tribler/tribler/issues/7133
* https://github.com/Tribler/tribler/issues/7063
Refs:
* https://github.com/pytest-dev/pytest-rerunfailures
> Add `--reruns 1` for pytests

- src/tribler/core/components/metadata_store/remote_query_community/tests/test_remote_query_community.py
This PR fixes #7133 by changing the await logic from `await self.deliver_messages()`(with the default timeout equal to `0.1`) to the waiting for `await callback_called.wait()`.
This change removes the dependency on the real 0.1-time interval. It should stabilize the test.
> Change await event logic for the `test_remote_select_torrents` function

- requirements-test.txt
- src/tribler/core/components/knowledge/restapi/tests/test_knowledge_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_libtorrent_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_metadata_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_remote_query_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_search_endpoint.py
- src/tribler/core/components/metadata_store/tests/test_channel_download.py
- src/tribler/core/components/restapi/rest/tests/test_create_torrent_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_debug_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_events_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_settings_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_shutdown_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_statistics_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_trustview_endpoint.py
- src/tribler/core/components/socks_servers/socks5/tests/test_connection.py
- src/tribler/core/components/tests/test_base_component.py
- src/tribler/core/conftest.py
- src/tribler/core/utilities/tests/test_notifier.py
This PR fixes the "Event loop is closed" error (occurs only on Windows):
The error is a consequence of merging https://github.com/Tribler/tribler/pull/7143
The template of the `event_loop` fixture has been taken from https://github.com/pytest-dev/pytest-asyncio/releases/tag/v0.20.2.
Refs:
* https://stackoverflow.com/questions/45600579/asyncio-event-loop-is-closed-when-getting-loop
> Replace the `loop` fixture with the `event_loop` fixture.

- src/tribler/core/components/gigachannel_manager/tests/test_gigachannel_manager.py
- src/tribler/core/components/knowledge/community/tests/test_knowledge_community.py
- src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py
This PR fixes #7167 by:
1. Removing `await` statements from the `with db_session` blocks.
2. Removing `async` statements for `@db_session` annotations.
These changes were made for the whole codebase.
Currently `PonyORM` doesn't support `async` operations and it is not recommended to use any `await` statements inside `with db_session` blocks.
> Remove `await` statements from `with db_session` blocks

- src/tribler/core/start_core.py
This PR removes the `asyncio` logger level specification to make the whole Tribler logger configuration more homogenous.
> Remove `asyncio` logger level specification.

- .github/actions/save_git_info/action.yml
- .github/workflows/build_mac.yml
- .github/workflows/build_ubuntu.yml
- .github/workflows/build_windows.yml
This PR is related to #7174 and adds support for unannotated tags for our builds under GitHub Actions.
> Add support for unannotated tags

- .github/workflows/coverage.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
This PR is the continuation of #7169.
It adds `--reruns-delay 1` for pytest runs to increase the stability of the test suite.
https://github.com/Tribler/tribler/actions/runs/3479920176/jobs/5819063518#step:6:230
```python
src/tribler/core/components/popularity/community/tests/test_popularity_community.py . [ 89%]
...R.E.R.E.                                                              [ 90%]
src/tribler/core/components/libtorrent/tests/test_dht_health_manager.py .R [ 90%]
.E.R.E.R.E.R.E.R.E                                                       [ 90%]
src/tribler/core/upgrade/tests/test_upgrader.py ............             [ 91%]
src/tribler/core/utilities/tests/test_dependencies.py ....               [ 92%]
src/tribler/core/upgrade/tests/test_config_upgrade_to_76.py .            [ 92%] …
```
> Add `--reruns-delay 1`

- .github/workflows/coverage.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
- .github/workflows/pytest_custom_ipv8.yml
- .github/workflows/vars/pytest.env
During the past two months, we made a lot of small changes to pytest runs. To minimize errors related to these changes (like mistypes), we should leave only one place for defining pytest arguments.
Also this PR updates `pytest_custom_ipv8.yml` and `coverage.yml` to align them to the common style.
> Extract environment variables into `shared.env`

- src/tribler/core/components/knowledge/community/knowledge_community.py
- src/tribler/core/components/knowledge/db/knowledge_db.py
- src/tribler/core/components/knowledge/db/tests/test_knowledge_db.py
- src/tribler/core/components/knowledge/db/tests/test_knowledge_db_base.py
- src/tribler/core/components/knowledge/restapi/knowledge_endpoint.py
- src/tribler/core/components/knowledge/restapi/tests/test_knowledge_endpoint.py
- src/tribler/core/components/metadata_store/remote_query_community/remote_query_community.py
- src/tribler/core/components/metadata_store/remote_query_community/tests/test_remote_search_by_tags.py
- src/tribler/core/components/metadata_store/restapi/metadata_endpoint_base.py
- src/tribler/core/components/metadata_store/restapi/search_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_search_endpoint.py
- src/tribler/core/upgrade/tags_to_knowledge/tests/test_migration.py
@kozlovsky requested this change for `KnowledgeDatabase`.
He has noticed that methods like `get_subjects`, `get_objects`, `get_statements`, `get_suggestions` have missed the `subject_type` argument.
Therefore it was technically possible to have two subjects like `2002` both in the title and in the tag (for example). This possibility could cause confusion in the future.
The next step in this line of thought would be adding a mandatory type for all returning values.
> Add `resource_type` for subjects in queries in the `KnowledgeDatabase`

- scripts/experiments/tunnel_community/hidden_peer_discovery.py
- scripts/experiments/tunnel_community/speed_test_e2e.py
- scripts/experiments/tunnel_community/speed_test_exit.py
- scripts/seedbox/disseminator.py
- src/tribler/core/utilities/tiny_tribler_service.py
The `TinyTriblerService` was introduced in 2020 and was aimed to simplify developers' work when they have to do experiments.
2 years later, we have a history of the `TinyTriblerService` usage that makes it possible to simplify work with the `TinyTriblerService` even more. Thanks for https://github.com/Tribler/tribler/pull/7105 it could be done in a safe manner.
So the most minimalistic Tribler's run now is:
```python
from pathlib import Path
from tribler.core.components.ipv8.ipv8_component import Ipv8Component
from tribler.core.components.key.key_component import KeyComponent
from tribler.core.utilities.tiny_tribler_service import TinyTriblerService
tribler = TinyTriblerService(
working_dir=Path('.Tribler'),
components=[
Ipv8Component(),
KeyComponent()
]
)
tribler.run()
```
> Refactoring of  the `tiny_tribler_service.py`

- .github/workflows/!PR.yml
- .github/workflows/coverage.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
- requirements-test.txt
This PR helps us to collect statistics about flaky tests.
> Let's say you have a testsuite with some flaky tests that randomly break your CI build due to network issues, race conditions or other stuff that you don't want to fix immediately. The known workaround is to retry those tests automatically, for example using [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures).
One concern against plugins like this is that they just hide the bugs in your testsuite or even other code. After all your CI build is green and your code probably works most of the time.
pytest-sentry tries to make that choice a bit easier by tracking flaky test failures in a place separate from your build status. Sentry is already a good choice for keeping tabs on all kinds of errors, important or …
> Add `pytest-sentry` for pytest runs

- src/tribler/gui/tribler_window.py
Fixes https://github.com/Tribler/tribler/issues/7181
> Enable token balance refresh only if widget is available

- src/tribler/gui/core_manager.py
- src/tribler/gui/tribler_request_manager.py
Tribler can get stuck on shutdown if the request to shutdown is canceled already at the GUI level. Issue and logs are present in https://github.com/Tribler/tribler/issues/7177
This PR excludes the shutdown request from being cleared while shutting down making sure that the shutdown request is sent to the Core. 
Fixes https://github.com/Tribler/tribler/issues/7177
> Skip shutdown request clearing on Tribler shutdown

- src/tribler/core/components/restapi/rest/rest_manager.py
> Proper shutdown of aiohttp.web_runner.AppRunner by RESTManager

- src/tribler/core/components/ipv8/eva/transfer/tests/test_base.py
This PR fixes #7192 by fixing the incorrect order of the `task_group` calls.
> Fix Transfer tests

- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/tests/test_download.py
This PR fixes #7117 by skipping the information in `download.get_tracker_status()` about peers in case this information is unavailable.
> Check on an exception `handle.get_peer_info()`

- src/tribler/core/components/tunnel/community/tunnel_community.py
This PR fixes #7231 by adding the following logic. In the case of the `OrmError`, the `TunnelCommunity` ignores a payout.
> Ignore payout in the case of the `OrmError` happens

- .github/workflows/!PR.yml
> Add shared env

- .github/workflows/!PR.yml
This PR implements #7240
This PR adds the following logic. If a PR has labeled `PR: safe to check` or this PR has been pushed by a user with `write` permissions, then allow PR checks that have access to the secrets. Otherwise, only checks that do not require secrets will be executed. 
Closes #7240
> Add label check

- README.rst
This PR adds the `downloads@7.12.1 ` badge to the main readme file.
> Add the `7.12.1 downloads` badge

- .gitignore
- doc/building/building.rst
- doc/building/building_on_osx.rst
- doc/building/building_on_windows.rst
> Update the build documentation

- src/tribler/core/components/restapi/rest/rest_manager.py
- src/tribler/core/components/restapi/rest/settings.py
- src/tribler/core/utilities/process_manager/process.py
- src/tribler/core/utilities/process_manager/tests/test_process.py
- src/tribler/gui/core_manager.py
- src/tribler/gui/event_request_manager.py
- src/tribler/gui/tests/test_core_manager.py
- src/tribler/gui/tribler_window.py
This PR is based on @xoriole's PR #7162 and fixes #7137. What is different is the way how GUI determines the opened API port. In the current PR, GUI takes the `api_port` value from the processes database.
Previously, EventRequestManager initially attempted to connect to the already running independently launched Core. Then in case a new Core process is started, EventRequestManager immediately starts repeated attempts to connect to it.
Now, EventRequestManager connects to the launched Core only after the Core REST API manager is started. Before that, CoreManager periodically attempts to read the `api_port` value from the processes database.
In case of a crash, the API port values (an initial value suggested by GUI and an actual value used by Core) are available in the error report as part …
> Pass the number of the opened REST API port from Core to GUI

- .github/workflows/guitest.yml
This PR fixes Ubuntu GUI tests:
https://github.com/Tribler/tribler/actions/runs/3895935287/jobs/6651858598
The test is failing in this PR because the checks use the version of workflow from the main branch (after the merging they will be green).
```python
6s
Run sudo apt install pyqt5-dev-tools
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
libdouble-conversion3 libegl-mesa0 libegl[1](https://github.com/Tribler/tribler/actions/runs/3895935287/jobs/6651858598#step:5:1) libevdev2 libinput-bin libinput10
libmd4c0 libmtdev1 libqt5core5a libqt5dbus5 libqt5designer5 libqt5gui5
libqt5help5 libqt5network5 libqt5printsupport5 …
```
> Fix gui tests

- requirements.txt
- tribler.spec
This PR updates versions of Qt libraries.
Now they are aligned with the pyqt@5 versions from the brew which makes it easier to build Tribler on Apple Silicone.
Related to: https://github.com/Tribler/tribler/issues/7252
> Update versions of Qt libraries

- .github/actions/pyenv/action.yml
- .github/workflows/!PR.yml
- .github/workflows/build_mac.yml
- .github/workflows/build_ubuntu.yml
- .github/workflows/build_windows.yml
- .github/workflows/codacy.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/guitest.yml
- .github/workflows/pytest.yml
- .github/workflows/pytest_custom_ipv8.yml
- .github/workflows/scripttest.yml
This PR fixes the incorrect use of [context](https://docs.github.com/en/actions/learn-github-actions/contexts) that was introduced in https://github.com/Tribler/tribler/pull/7186
Now a PR workflow is the following:
1. GitHub actions checkout the code of the target branch (usually it is `main`)
2. The gatekeeper job checks that the author of the PR has a write-access to the repo or the PR has a label `PR: safe to check`
3. GitHub actions checkout the code of the source branch
4. GitHub actions execute all the checks (with read-only permissions) by using the source branch
This PR unmask the error described here https://github.com/Tribler/tribler/pull/7265
The checks in this PR are failed. It is intended, because this fix has to be in the 'main' branch to be applied.
> Fix workflows context

- requirements.txt
This PR fixes failed GUI tests in https://github.com/Tribler/tribler/pull/7257 and https://github.com/Tribler/tribler/pull/7259.
The root cause of the problem was the fact that `pyqtgraph` version `0.13.x` doesn't work properly with our GUI tests.
> Downgrade `pyqtgraph` version

- src/tribler/gui/widgets/trustgraphpage.py
> Fixes #7271: ValueError: "Unable to convert 222222 to QColor" in pyqtgraph/functions.py when starting run_tribler.py

- scripts/exit_node/run_exit_node.py
- src/run_tribler.py
- src/run_tribler_headless.py
- src/tribler/core/utilities/osutils.py
- src/tribler/core/utilities/tests/test_osutils.py
- src/tribler/core/utilities/tiny_tribler_service.py
This PR fixes #7253 by adding a possibility to specify the `create=True` option for `get_root_state_directory()`.
The `get_root_state_directory` function now raises an exception if the state directory does not exist or is not a directory.
Also, the `run_tribler_headless.py` script was updated to use `ProcessManager` instead of the removed `ProcessChecker`.
> Fix #7253: Tribler does not run if the state directory does not already exist

- src/tribler/core/utilities/utilities.py
Since we have moved away from our custom built libtorrent package with full BEP33 support to PyPi libtorrent package. The changes on this PR is required to enable the default DHT check (by joining the swarm).
> Disable BEP33 health check

- .github/workflows/!PR.yml
- .github/workflows/build_mac.yml
This PR closes #7146 by enabling mac os build as a part of PR checks.
Previously conflicting `eulagise` (perl) has been replaced by `licenseDMG.py` (python).
> Add macos build

- src/tribler/core/components/metadata_store/db/store.py
- src/tribler/core/components/metadata_store/restapi/tests/test_search_endpoint.py
- src/tribler/core/components/metadata_store/utils.py
- src/tribler/core/utilities/tests/test_utilities.py
- src/tribler/core/utilities/utilities.py
- src/tribler/gui/tests/test_gui.py
- src/tribler/gui/widgets/tablecontentmodel.py
- src/tribler/gui/widgets/triblertablecontrollers.py
This PR removes a trailing `*` symbol from the FTS queries.
The last search word is treated as a prefix with a trailing star symbol. Due to this, queries like "1" can look up all words starting with this prefix (numbers in this example). As a result, the query can attempt to fetch many millions of rows from the database, and fetching and ordering all those rows can take a very long time. The query result, in that case, can include a large number of irrelevant results.
Removing the trailing `*` symbol produces higher-quality search results and speeds up some queries up to two orders of magnitude. Without trailing `*` symbols, non-exact matches are still included in the query result, as the FTS query performs stemming.
> FTS speedup

- doc/development/development_on_osx.rst
- requirements-test.txt
This PR adds a workaround for building Tribler on Apple Silicon.
> Add a workaround for Apple Silicon

- requirements-core.txt
- requirements-test.txt
- src/tribler/core/components/tunnel/community/tunnel_community.py
- src/tribler/core/tests/test_search_utils.py
This PR updates the ipv8 version to the `2.10`
Related to #7282
> Update `ipv8` to the version `2.10`

- src/tribler/gui/network/request.py
- src/tribler/gui/network/request_manager.py
- src/tribler/gui/network/tests/test_request.py
This PR fixes #7297
The root cause of the issue is the fact that `Request.reply.readAll()` could return a value equal to `b''` which couldn't be decoded correctly by `json.loads(data)`.
> Fix empty reply decoding issue

- scripts/experiments/tunnel_community/hidden_peer_discovery.py
- scripts/experiments/tunnel_community/speed_test_exit.py
- src/tribler/core/components/metadata_store/restapi/metadata_endpoint.py
- src/tribler/core/components/restapi/rest/events_endpoint.py
- src/tribler/core/components/restapi/rest/rest_endpoint.py
- src/tribler/core/components/restapi/rest/shutdown_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_events_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_rest_endpoint.py
- src/tribler/core/components/restapi/restapi_component.py
- src/tribler/core/components/session.py
- src/tribler/core/utilities/async_group.py
- src/tribler/core/utilities/tests/test_async_group.py
- src/tribler/core/utilities/tiny_tribler_service.py
This PR fixes #7299
* `shutdown` method has been added to the `RestEndpoint` base class
* `List[Task]` has been added as a result value of the `AsyncGroup.add()` call
* Calls of `asyncio.create_task` have been fixed
> Fix `asyncio.create_task()` calls

- Dockerfile
- src/run_tribler_headless.py
- src/tribler/core/components/bandwidth_accounting/community/cache.py
- src/tribler/core/components/bandwidth_accounting/community/payload.py
- src/tribler/core/components/bandwidth_accounting/db/transaction.py
- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/tunnel/community/payload.py
- src/tribler/core/components/tunnel/community/tunnel_community.py
This PR is related to #7303 and fixes critical issues reported by Codacy
> Fix critical issues reported by Codacy

- src/tribler/gui/widgets/downloadprogressbar.py
- src/tribler/gui/widgets/downloadspage.py
This PR fixes #7316 
The actual fix is the following change (the rest is cosmetic refactoring and could be extracted to a separate PR by request):
from:
```python
qt_color.setHsl(26, 255, 128 + int(127 * (1 - piece_sum // pieces_per_pixel)))
```
to:
```python
qt_color.setHsl(26, 255, 128 + int(127 * (1 - piece_sum / pieces_per_pixel)))
```
> Fix mathematical mistake in the progress bar drawing

- src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/components/restapi/rest/events_endpoint.py
- src/tribler/core/components/restapi/rest/rest_manager.py
> Fix long shutdown

- src/tribler/core/components/libtorrent/download_manager/dht_health_manager.py
- src/tribler/core/components/metadata_store/db/orm_bindings/torrent_state.py
- src/tribler/core/components/metadata_store/db/store.py
- src/tribler/core/components/metadata_store/remote_query_community/remote_query_community.py
- src/tribler/core/components/popularity/community/tests/test_popularity_community.py
- src/tribler/core/components/socks_servers/socks5/connection.py
- src/tribler/core/components/torrent_checker/torrent_checker/dataclasses.py
- src/tribler/core/components/torrent_checker/torrent_checker/tests/test_health_info_should_update.py
- src/tribler/core/components/torrent_checker/torrent_checker/tests/test_torrentchecker.py
- src/tribler/core/components/torrent_checker/torrent_checker/tests/test_torrentchecker_session.py
- src/tribler/core/components/torrent_checker/torrent_checker/torrent_checker.py
- src/tribler/core/components/torrent_checker/torrent_checker/torrentchecker_session.py
- src/tribler/core/components/torrent_checker/torrent_checker/utils.py
- src/tribler/core/utilities/notifier.py
- src/tribler/gui/widgets/tablecontentmodel.py
This PR fixes #7287. There were several reasons for the bug:
1. When no trackers for a specific infohash were able to provide health info, the resulting health record with zero seeders and zero leechers had an incorrect `last_check` timestamp value of 0.
2. The checks in `HealthInfo.should_update()` were also incorrect, and the logic sometimes decided to keep the previous health info and not replace it with the new health info.
3. In such situations, due to the third bug, the notification was not sent to the GUI; as a result, the GUI status for the torrent was stuck in the "Checking..." state indefinitely.
Also, this PR fixes the long checking time by updating the torrent health immediately. Previously, TorrentChecker aggregated all results from all possible trackers before providing the …
> Fix and speed up health checks

- src/tribler/core/utilities/process_manager/tests/test_process.py
This PR fixes an unstable test that uses an unstable repr of a Process that does not relate to the test
> Fix unstable test_tribler_process_mark_finished

- .gitignore
This PR adds the `local/` folder to `.gitignore`. 
The developers will benefit from it by using the local folder as a place to store their "experimental/throwaway/dont-want-to-commit" code that is dependent on Tribler.
> Add `local/` to ignored folders

- src/tribler/core/tests/test_search_utils.py
- src/tribler/core/utilities/search_utils.py
As it turns out there is a minor issue in the logic of the `item_rank()`, `torrent_rank()`, and `freshness_rank()` functions.
The crux of the problem lies in how torrents with an unspecified creation date were handled. These torrents were treated as if they were created at the Unix epoch, `1970-01-01 00:00:00`. Consequently, their freshness rank was marginally above zero and gradually decreased as their assumed "creation date" grew more distant. This led to unstable results in the `test_item_rank`, as the rank values were not constant but slowly diminishing.
To resolve this issue, this PR implements a fix that ensures the freshness rank, as well as the freshness component of the composite torrent rank, is strictly zero for all torrents with unknown or invalid creation dates. This …
> Fix item_rank(), torrent_rank(), freshness_rank() functions

- src/tribler/gui/debug_window.py
- src/tribler/gui/dialogs/addtopersonalchanneldialog.py
- src/tribler/gui/dialogs/createtorrentdialog.py
- src/tribler/gui/dialogs/editmetadatadialog.py
- src/tribler/gui/dialogs/startdownloaddialog.py
- src/tribler/gui/network/request.py
- src/tribler/gui/network/request_manager.py
- src/tribler/gui/network/tests/test_request.py
- src/tribler/gui/tribler_window.py
- src/tribler/gui/widgets/channelcontentswidget.py
- src/tribler/gui/widgets/channeldescriptionwidget.py
- src/tribler/gui/widgets/downloadspage.py
- src/tribler/gui/widgets/lazytableview.py
- src/tribler/gui/widgets/triblertablecontrollers.py
This PR fixes #7333:
1. It adds the handling of `QNeworkReply` errors mentioned in #7335 by checking the QNetworkReply error code before reading the response data;
2. If there is an error or if the response data is empty, now Request does not call the `on_success` callback (renamed from `on_finish`);
3. In case of an error, it displays QNetworkReply errors in debug window as a request status code.
> On GUI side, handle Core REST API responses without data

- src/tribler/core/utilities/tiny_tribler_service.py
This PR adds an option to disable `check_already_running` as it is useful for some experiments to run multiple instances simultaneously.
> Add an option to disable `check_already_running`

- src/tribler/core/conftest.py
Currently, all failed test output look like this:
```python
============================= test session starts ==============================
collecting ... collected 1 item
test_settings.py::test_get_default_home_download_dir_exists 
-------------------------------- live log setup --------------------------------
21:29:38.116 DEBUG faker.factory(78) Looking for locale `en_US` in provider `faker.providers.address`.
21:29:38.119 DEBUG faker.factory(97) Provider `faker.providers.address` has been localized to `en_US`.
21:29:38.123 DEBUG faker.factory(78) Looking for locale `en_US` in provider `faker.providers.automotive`.
21:29:38.125 DEBUG faker.factory(97) Provider `faker.providers.automotive` has been localized to `en_US`.
21:29:38.127 DEBUG faker.factory(78) Looking for locale `en_US` in …
```
> Disable logging in the faker module for pytest.

- src/tribler/core/utilities/process_manager/process.py
- src/tribler/core/utilities/process_manager/tests/test_process.py
- src/tribler/gui/start_gui.py
- src/tribler/gui/tribler_app.py
This PR closes #7034 by fixing #7212. Namely, it fixes the following race condition:
1. Due to an unusual OS bug, two Tribler GUI processes sometimes start at the same time
2. With the help of #7212, one process determines itself as a primary process and another as a non-primary process.
3. Now, the non-primary process should check if it has some torrent URL specified as a command line argument and pass it to the primary process.
4. The non-primary process attempts to connect with the primary process through a socket.
5. **Now the bug happens**: if the non-primary process cannot connect to the primary process (for example, because the primary process just started itself and had no time to open a socket), then the non-primary process continues to work as if it was a primary process. Then …
> Properly stop non-primary process

- src/tribler/core/components/libtorrent/download_manager/download_config.py
- src/tribler/core/components/libtorrent/settings.py
- src/tribler/core/components/libtorrent/tests/test_download_config.py
- src/tribler/core/components/libtorrent/tests/test_settings.py
- src/tribler/core/config/tests/test_tribler_config.py
- src/tribler/gui/tribler_window.py
- src/tribler/gui/widgets/settingspage.py
This PR fixes #7342
The actual fix is on the core side. The fix forbids `saveas` to be `None`. Now the default value is one of the:
- `TriblerDownloads`
- `$HOME/Downloads/TriblerDownloads`
- `$HOME/TriblerDownloads`
This value comes from the function `get_default_download_dir`. 
Note that doesn't relate to the original bug. This function was not covered by tests and consisted of a bug. In this PR tests were added and the bug was fixed.
---
On the GUI side, there is a refactoring that was needed to make it possible to understand and investigate the bug.
The refactoring changes GUI startup logic.
Instead of requesting Tribler settings in parallel:
```mermaid
graph LR;
A[core connected]-->B[receive settings];
A-->C[start UI];
```
it does this sequentially now:
```mermaid
graph LR;
A[core …
```
> Fix empty `saveas` issue

- src/tribler/core/utilities/tests/test_tracker_utils.py
- src/tribler/core/utilities/tracker_utils.py
Currently, our tracker utility that parses tracker URLs does not support HTTPS. This PR adds that support. Many trackers like Ubuntu tracker have moved to use HTTPS already so it is time we support them.
> Add support for HTTPS tracker URL

- src/tribler/core/components/restapi/rest/events_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_events_endpoint.py
> Skip `on_tribler_exception` if EventsEndpoint is shutting down.

- src/tribler/core/components/restapi/rest/events_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_events_endpoint.py
This PR does the following:
1. Fixes #7353 by preventing events from being sent to the GUI when the EventsEndpoint is in the shutdown state and the event loop can already be closed. 
2. Second, it adds a queue to ensure that all events are sent to GUI in the same order as they were created:
* Previously, a separate task was created for each event, which could lead to events being sent in reverse order, causing confusion on the GUI side.
* With this update, all events are sent through the same queue, preserving the order in which they were generated. The order of messages sent is determined by the order in which they were added to the queue.
> Send events to GUI only before shutdown and in the proper order

- src/tribler/core/sentry_reporter/sentry_reporter.py
- src/tribler/core/sentry_reporter/tests/test_sentry_reporter.py
- src/tribler/gui/error_handler.py
While investigating issues from release `7.13,` I realized having a `tribler_stopped` tag in the Sentry would be nice. That helps better understand the bug itself and distinguish the severity of the bug. 
If `tribler_stopped` is set to `True`, then it is a more severe bug than a bug with `tribler_stopped` set to `False`.
As a bonus, this PR adds correct typings for the field `additional_tags`.
> Add `tribler_stopped` tag to the Sentry

- src/tribler/core/sentry_reporter/sentry_reporter.py
- src/tribler/core/sentry_reporter/tests/test_sentry_reporter.py
- src/tribler/gui/dialogs/feedbackdialog.py
This PR removes "events" and "requests" fields from a Sentry report.
See an example: https://sentry.tribler.org/organizations/tribler/issues/2065
> Remove events and requests from Sentry report

- src/tribler/gui/widgets/downloadspage.py
This PR is related to #7360 and should decrease the load by decreasing the frequency of the `downloads` request.
`Background refresh interval` has been changed from `1s` to `5s`. 
`Refresh now interval` has been changed from `0s` to `0.01s` (https://doc.qt.io/qt-5/qtimer.html#start).
This PR also offers an alternative solution for the problem addressed here: https://github.com/Tribler/tribler/pull/7372
> Decrease the frequency of the `downloads` request

- src/tribler/core/components/knowledge/knowledge_component.py
- src/tribler/core/components/knowledge/rules/knowledge_rules_processor.py
- src/tribler/core/components/knowledge/rules/tests/test_knowledge_rules_processor.py
- src/tribler/core/components/metadata_store/metadata_store_component.py
- src/tribler/core/components/metadata_store/restapi/metadata_endpoint_base.py
During the migration from the TagsDB to the KnowledgeDB all old autogenerated entries were removed (https://github.com/Tribler/tribler/pull/7070). Therefore it is necessary to restart the automatic knowledge rule extraction for the whole Metadata DB.
> Add reprocess feature for `KnowledgeRulesProcessor`

- src/tribler/core/components/gigachannel_manager/gigachannel_manager.py
In Sentry logs related to different errors [I sometimes see a log lines](https://sentry.tribler.org/organizations/tribler/issues/1949/events/0d9de1bc65ef4ab0aebb2c5788259b3f/?project=7) like "Error when tried to download a newer version of channel c3f187dbf463172a48a5c6e0cd3b513ce2bd8b0915b1ff4087055ddf6e565c1e017a2986a3d7cf142425a0d9789bd7afbfc6972dfb55792c045e0ff097575e45"
In this PR I add an error details to the log line to be able to see the reason of the error.
> Add a description to the error when tried to download a newer version of channel

- src/tribler/gui/tests/conftest.py
This PR disables logging in tests for `faker.factory` and `PyQT5.uic`. 
After the fix the output is:
```python
============================= test session starts ==============================
collecting ... collected 1 item
test_gui.py::test_feedback_dialog_report_sent 
-------------------------------- live log setup --------------------------------
14:41:15.268 INFO TriblerApplication(25) Start Tribler application. Win id: "triblerapp-guitest". Sys argv: "['/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/_jb_pytest_runner.py', '-s', '--timeout=600', '--log-cli-level=10', '--looptime', 'test_gui.py::test_feedback_dialog_report_sent']"
14:41:15.431 INFO TriblerApplication(51) No running instances (socket error: 2)
14:41:15.604 INFO NetworkUtils(46) Looking for first free …
```
> Disable logging in tests for `faker.factory` and `PyQT5.uic`

- src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py
- src/tribler/gui/error_handler.py
- src/tribler/gui/tribler_window.py
- src/tribler/gui/widgets/downloadsdetailstabwidget.py
- src/tribler/gui/widgets/downloadspage.py
- src/tribler/gui/widgets/downloadwidgetitem.py
This PR related to #7360
It optimizes the Downloads page UI logic by removing unnecessary calls and stopping sending requests while the page is inactive.
> Refactor the Downloads page

- src/tribler/core/components/restapi/rest/aiohttp_patch.py
- src/tribler/core/components/restapi/rest/rest_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_rest_manager.py
This PR fixes #7344 by money-patching of AIOHTTP iternals. The reason for the original bug is described in https://github.com/aio-libs/aiohttp/issues/7258. The fix is implemented as a `patch_make_request` function.
The essence of the bug is that the `aiohttp.web_protocol.RequestHandler.start()` coroutine erroneously continues
to run after a connection was closed from the client side, the transport was closed, and None was assigned
to `self.transport`. Then the `RequestHandler.start` coroutine calls `self._make_request(...)`, which in turn creates
an `aiohttp.web_request.Request` instance, and it has `assert transport is not None` in its constructor.
To fix the bug, the monkey-patched `_make_request` method first checks if the `self.transport is None`, and if so,
it raises the …
> Fixes #7344: AssertionError "transport is not None" in aiohttp/web_request.py

- src/tribler/core/components/gigachannel_manager/gigachannel_manager.py
- src/tribler/core/components/gigachannel_manager/tests/test_gigachannel_manager.py
Fixes the bug on checking channel updates where the existence of the channel should be checked first before trying to get the state of download.
> Fixes #7386

- src/tribler/gui/network/request.py
- src/tribler/gui/network/request_manager.py
- src/tribler/gui/network/tests/test_request.py
- src/tribler/gui/network/tests/test_request_manager.py
- src/tribler/gui/tests/test_downloadspage.py
- src/tribler/gui/widgets/downloadspage.py
This PR is related to #7360 and continues the work done in #7378.
It adds an id for each Request on the GUI side. This new functionality is utilized in the DownloadsPage to ignore outdated requests.
> Ignore old responses for the DownloadsPage

- src/tribler/core/components/component.py
- src/tribler/core/components/exceptions.py
- src/tribler/core/components/reporter/exception_handler.py
- src/tribler/core/components/reporter/reported_error.py
- src/tribler/core/components/reporter/tests/test_exception_handler.py
- src/tribler/core/components/restapi/restapi_component.py
- src/tribler/core/components/restapi/tests/test_restapi_component.py
- src/tribler/core/components/session.py
- src/tribler/core/components/tests/test_base_component.py
- src/tribler/core/sentry_reporter/sentry_reporter.py
- src/tribler/core/sentry_reporter/tests/test_sentry_reporter.py
- src/tribler/gui/error_handler.py
This PR adds a dict field to Sentry, which is accessible from any part of the Tribler code and will be included in a Sentry event.
An example of using:
```python
from tribler.core.components.reporter.exception_handler import default_core_exception_handler
reporter = default_core_exception_handler.sentry_reporter
reporter.additional_information['components'] = {
'KnowledgeComponent':
{
'db_size': 1024,
'load_time': 100
}
}
```
As a real example, the component's statuses have been added:
https://sentry.tribler.org/organizations/tribler/issues/2087/?project=3
Also, tests for SentryReporter have been refactored.
> Sentry: add the field `additional_information`

- src/tribler/gui/widgets/tablecontentmodel.py
This PR fixes #7395. As it turns out, the result of the `QAbstractTableModel.headerData` method is expected to be a pure `str` instance and not some `str` subclass (like `TranslatedString`).
It looks like in other places, Qt has no prejudice to str subclasses and renders them correctly.
But there is a slight chance we overlooked another place where the string is not rendered properly. For that reason, we can consider removing the `TranslatedString` subclass. On the other side, it looks like it is currently handled correctly in all other places, and it gives protection against incorrectly translated stings, so we can continue to use it.
> Fixes #7395 "Labels on Discovered channels are missing"

- src/tribler/gui/core_manager.py
- src/tribler/gui/dialogs/addtopersonalchanneldialog.py
- src/tribler/gui/dialogs/startdownloaddialog.py
- src/tribler/gui/network/request_manager.py
> Stop sending request after shutdown

- src/tribler/core/components/restapi/rest/events_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_events_endpoint.py
This PR fixes #7345 by suppressing `ConnectionResetError`.
`ConnectionResetError` can be raised in three cases:
1. there is no aiohttp connection
2. aiohttp transport is None
3. aiohttp transport is closing
https://github.com/aio-libs/aiohttp/blob/29b6f302ad6736f71ef3fb029d4c5bac786a2fb7/aiohttp/http_writer.py#L69-L76
```python
def _write(self, chunk: bytes) -> None:
size = len(chunk)
self.buffer_size += size
self.output_size += size
transport = self.transport
if not self._protocol.connected or transport is None or transport.is_closing():
raise ConnectionResetError("Cannot write to closing transport")
transport.write(chunk)
```
In all cases described above, we cannot do anything from the core side. All reconnect logic is on the GUI side.
The most probable root cause of the error is the …
> Suppress `ConnectionResetError`

- src/tribler/core/components/knowledge/db/knowledge_db.py
- src/tribler/core/components/knowledge/db/tests/test_knowledge_db.py
- src/tribler/core/components/knowledge/rules/knowledge_rules_processor.py
- src/tribler/core/components/knowledge/rules/tests/test_knowledge_rules_processor.py
This PR fixes deadlocks that happen with mutual updates from:
1. `KnowledgeRulesProcessor` (write attempt to `KnowledgeDB` and `MetadataDB` in the `process_batch` function)
2. `MDS` (write attempt to `KnowledgeDB` and `MetadataDB` in the constructor of `TorrentMetadata`)
```mermaid
graph TD;
P-->|write: process_batch|K(KnowledgeDB);
P[KnowledgeRulesProcessor]-->|write: process_batch|M(MetadataDB);
T[TorrentMetadata]-->|write: __init__|M;
T-->|write: __init__|K;
```
This situation arises when two factors coincide:
1. Access to DBs occur simultaneously (this is true because the `Metadata Store` uses a different thread to perform operations with the DB).
2. These accesses lock the same entity (this is true because we use SQLite and it locks the entire database, as mentioned below).
> 3.0 …
> Use separate `misc` table for the KnowledgeDB

- src/tribler/core/components/libtorrent/tests/test_download.py
- src/tribler/core/components/libtorrent/torrentdef.py
- src/tribler/core/components/libtorrent/utils/torrent_utils.py
The PR updates the `require_handle` decorator to execute the function if TorrentDef has metadata.
- Fixes https://github.com/Tribler/tribler/issues/7412
- Fixes https://github.com/Tribler/tribler/issues/6915
> Fix invalid handle when there is no torrent metadata

- src/tribler/core/components/knowledge/rules/knowledge_rules_processor.py
- src/tribler/core/components/knowledge/rules/tests/test_knowledge_rules_processor.py
- src/tribler/core/components/metadata_store/restapi/channels_endpoint.py
- src/tribler/core/components/metadata_store/restapi/metadata_endpoint_base.py
- src/tribler/core/components/metadata_store/restapi/search_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_metadata_endpoint.py
This is a continuation of the previous PR #7413 and the final fix for the deadlock problem.
It adds a thread-safe queue that is used for processing incoming MDS entities, which are created in a different thread.
Additionally, it removes unnecessary logic from Endpoints that perform writes to both databases (`KnowledgeDB` and `MetadataDB`).
As a drawback, this PR reduces the speed of tag extraction, as they are now not performed immediately upon entity addition to the `MetadataDB`. Given that tags aren't directly used in the current release and we plan to remove MDS in upcoming releases, this drawback is acceptable.
> Add queue for multithread processing

- src/run_tribler.py
- src/tribler/core/components/session.py
- src/tribler/core/start_core.py
- src/tribler/core/utilities/slow_coro_detection/__init__.py
- src/tribler/core/utilities/slow_coro_detection/main_thread_stack_tracking.py
- src/tribler/core/utilities/slow_coro_detection/patch.py
- src/tribler/core/utilities/slow_coro_detection/tests/test_main_thread_stack_tracing.py
- src/tribler/core/utilities/slow_coro_detection/tests/test_slow_coro_detection.py
- src/tribler/core/utilities/slow_coro_detection/utils.py
- src/tribler/core/utilities/slow_coro_detection/watching_thread.py
This PR adds functionality to detect slow coroutine step execution in the asyncio loop. If a coroutine step requires too much time (more than 1 second by default), the coroutine is reported to the error log.
A separate thread watches whether the main line is currently inside the coroutine for too long and reports a possible freeze.
It is possible to specify an environment variable `SLOW_CORO_STACK_TRACING=1`; in that case, the coroutine stack is also tracked and reported in case of a possible freeze. With stack tracing enabled, the Core works slower, so this option is intended to be run not on user machines (although this is possible).
> Detect slow coroutines and freezes in the asyncio loop

- src/tribler/gui/core_manager.py
I this we should increase (at least temporarily) the API_PORT_CHECK_TIMEOUT to differentiate possible reasons of #7351. It is better for a user to wait a little longer and have a chance to connect to Core than to see an error.
> Temporarily increase the core manager API port check timeout to be sure it is big enough

- src/tribler/gui/tests/test_core_manager.py
This PR fixes the `test_check_core_api_port_timeout` test that was broken by #7419
> Fix test check core api port timeout

- src/tribler/core/components/knowledge/rules/knowledge_rules_processor.py
- src/tribler/core/components/knowledge/rules/tests/test_knowledge_rules_processor.py
- src/tribler/core/components/metadata_store/restapi/channels_endpoint.py
- src/tribler/core/components/metadata_store/restapi/search_endpoint.py
- src/tribler/core/utilities/async_force_switch.py
- src/tribler/core/utilities/tests/test_async_force_switch.py
This is a continuation of the previous PR #7417 and the final PR from the `KnowledgeRulesProcessor` improvements series.
As demonstrated in #7414 by @kozlovsky, `process_batch` is one of the few "long-running" coroutines. This behavior could lead to a brief freeze of Tribler every 10 seconds. This happens on the core side and should go unnoticed by users. However, it's possible to reduce the time of synchronous `process_batch` execution by making `process_torrent_title` an async function.
I've tried to carefully isolate the use of `db_session` so it won't be affected by the switch to async. @kozlovsky, could you please confirm that I've done everything correctly?
> Make `KnowledgeRulesProcessor` less aggressive

- .github/actions/windows_dependencies/action.yml
This PR fixes #7436 by bumping libsodium version to `1.0.18`.
Version `1.0.17` is no longer available https://download.libsodium.org/libsodium/releases/libsodium-1.0.17-msvc.zip
The GUI tests will be fixed following the merger of this PR.
> Bump libsodium version to `1.0.18`

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
- src/tribler/core/components/libtorrent/tests/test_torrent_def.py
- src/tribler/core/components/libtorrent/torrentdef.py
- src/tribler/core/components/metadata_store/remote_query_community/payload_checker.py
Replaced generator expressions with similar functions, such as `map` and `filter`. In addition, replaced an indented pair of `for` loops and `if` statement with a creation of `set`. It uses a generator expression and a call to `filter` to create it in one go. This way it avoids repeatedly appending to a list. Fixes #7433 .
> Replace list comprehensions with generator expressions and similar functions

- src/tribler/core/utilities/slow_coro_detection/main_thread_stack_tracking.py
- src/tribler/core/utilities/slow_coro_detection/profiler.py
- src/tribler/core/utilities/slow_coro_detection/tests/test_main_thread_stack_tracing.py
- src/tribler/core/utilities/slow_coro_detection/tests/test_profile.py
- src/tribler/core/utilities/slow_coro_detection/tests/test_slow_coro_detection.py
- src/tribler/core/utilities/slow_coro_detection/utils.py
- src/tribler/core/utilities/slow_coro_detection/watching_thread.py
This PR does a bunch of changes to slow the coroutine detection mechanism:
1. It adds a duration for each line of the main stack trace so it becomes possible to see how long we are already into this function call, like `function started 1.268 seconds ago`.
2. It limits the number of displayed stack frames to show only the relevant function calls, so, at the last line of the traceback, you can see the actual function that causes the slowness (and not some arbitrary nested functions that happen to be executed at the moment of the periodic snapshot).
3. It adds a `@profile` decorator that logs statistics for the function and allows a developer to find the reason for its slowness and adds to the traceback a tip to use this decorator, which includes mentioning the function it should be applied …
> Profiling of slow coroutines

- src/tribler/core/components/gigachannel/community/gigachannel_community.py
- src/tribler/core/components/ipv8/discovery_booster.py
According to @qstokkink, the previously specified step interval of 0.05 seconds is too small, as the time between steps may not be enough to receive responses from other peers after the previous walk step. In this PR, I increase the time between steps and proportionally increase the timeout to be sure that the total number of steps is similar to the previous value (it was: 200 steps, now: 240 steps, a bit more)
> Fix the step interval of DiscoveryBooster

- src/tribler/core/components/gigachannel/community/gigachannel_community.py
Fixes #7427.
This PR monkey-patches the `Community.guess_address` method to add 5-second caching of its results.
It allows to speed up `EdgeWalk.take_step()` (that sometimes blocks the asyncio loop) by 100 times from 3 seconds to 0.03 seconds.
The next version of IPv8 is expected to include proper caching, so this patch can be removed after upgrading to a version of IPv8 that natively implements caching.
> 100x speedup of EdgeWalk.take_step() by caching results of GigaChannelCommunity.guess_address()

- src/tribler/core/components/restapi/rest/rest_manager.py
The  `await RESTManager.site.start()` call should be fast, but it looks like it hangs sometimes. In this PR, I added extended logging when calling `site.start()` and a timeout. It should allow understanding of what is going on in some rare cases when the site.start() appears to hang.
> Add extended logging to RESTManager.site.start() call

- src/tribler/core/logger/logger.yaml
The current size of log files is 100 kilobytes per file, with one backup file for each log file. It is too small if we are trying to find the error details in log files, as the file got deleted quickly.
In this PR, I slightly increase the size of log files: from 100 kilobytes to 1 megabyte and the number of log file backups from 1 to 2.
As a result, we should have 6 log files (`tribler-gui-info.log`, 'tribler-gui-error.log', `tribler-core-info.log`, and `tribler-core-error.log`) of 1 megabyte each and two backups for each file, 12 megabytes in total (still not too much).
> Increase the size of log files and the number of log file backups

- src/tribler/gui/dialogs/dialogcontainer.py
- src/tribler/gui/dialogs/startdownloaddialog.py
This PR fixes #7464
First, it resets the `TriblerWindow.start_download_dialog_active` flag to False when the dialog is closed.
Before this fix, Tribler assumed that the dialog was already opened and did not open it again in some situations.
Second, it fixes the Tribler crash when Tribler attempts to close and destroy the same dialog twice due to a contrived internal UI logic.
The reason for the crash: clicking on the area outside of the dialog triggers the `DialogContainer.mouseReleaseEvent` method:
```python
def mouseReleaseEvent(self, qevent):
if not self.dialog_widget.geometry().contains(qevent.localPos().toPoint()):
self.close_dialog()
```
that closes the dialog without resetting the `self.dialog` attribute of `TriblerWindow` to `None`. On the next attempt to open the dialog, …
> Fix the download torrent dialog behavior after closing it by clicking somewhere outside the dialog area

- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/tests/test_download.py
This PR fixes #7406 by moving the `self._logger.error` call into the try/except block. It also replaces `self._logger.exception` with `self._logger.warning` in case of an error, as the error's origin is known and handled adequately by the workaround.
Initially, in the discussion of #7410, I suggested adding a `safe_repr` function to wrap `alert` with it, but according to https://github.com/arvidn/libtorrent/issues/143, `on_tracker_error_alert` is the only place where the error can happen, so it is not necessary to implement a reusable function for `safe_alert`, as other `on_xyz_alert` handlers do not require a fix.
> Fixes #7406 UnicodeDecodeError in on_tracker_error_alert

- src/tribler/core/utilities/path_util.py
> Fixes #7473 FileNotFoundError when displaying the settings page

- src/tribler/gui/widgets/tablecontentmodel.py
This PR fixes #7477 by ignoring `IndexError` for the particular line. It is a reasonable fix as Channels GUI is planned to be removed in version `8.0`.
> Handle `IndexError`

- src/tribler/core/conftest.py
- src/tribler/gui/tests/conftest.py
This PR helps to reveal the root cause of #7132 by adding the execution duration of each test to the pytest output.
The modified output looks like this:
```python
src/tribler/core/utilities/async_group/tests/test_async_group.py::test_del_error PASSED [ 11%] in 0.005s
src/tribler/core/utilities/async_group/tests/test_async_group.py::test_del_no_error PASSED [ 11%] in 0.005s
src/tribler/core/utilities/async_group/tests/test_async_group.py::test_add_task_when_cancelled PASSED [ 11%] in 0.005s
src/tribler/core/components/gigachannel/community/tests/test_gigachannel_community.py::TestGigaChannelUnits::test_remote_select_channel_timeout PASSED [ 11%] in 0.259s
src/tribler/core/components/gigachannel/community/tests/test_gigachannel_community.py::TestGigaChannelUnits::test_remote_search_mapped_pe …
```
> Modify the pytest output to include the execution duration for all tests

- src/tribler/core/components/conftest.py
- src/tribler/core/components/knowledge/restapi/tests/test_knowledge_endpoint.py
- src/tribler/core/components/libtorrent/conftest.py
- src/tribler/core/components/metadata_store/conftest.py
- src/tribler/core/components/metadata_store/db/tests/test_torrent_metadata.py
- src/tribler/core/conftest.py
- src/tribler/core/utilities/tests/test_utilities.py
This PR splits big `core/conftest.py` into multiple small ones. It should slightly increase performance and simplify the maintenance of test fixtures.
Refs:
* https://docs.pytest.org/en/latest/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files
> Refactoring `conftest.py`

- src/tribler/core/conftest.py
- src/tribler/gui/tests/conftest.py
This PR adds the total runtime of the test suite to the pytest output.
Related to #7132, #7134
The modified output:
```python
src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py::test_put_channel_thumbnail PASSED      [  5%] in 0.046s (2.9s in total)
src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py::test_get_channel_contents PASSED       [  5%] in 0.082s (3.0s in total)
src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py::test_get_popular_torrents PASSED       [  5%] in 0.090s (3.1s in total)
src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py::test_get_channels_sort_by_health PASSED [  5%] in 0.087s (3.2s in total) …
```
> Add information about the total runtime of the test suite.

- .github/workflows/build_ubuntu.yml
- requirements-build.txt
- tribler.spec
Summary of the issue:
1. The binary built on Ubuntu 20.04 works on 20.04 but not Ubuntu 22.04 (and higher likely, not tested)
2. The binary built on Ubuntu 22.04 works on 22.04 but not lower.
The issue was related to `GdkPixbuf` internally required by PyQt5 File chooser on Linux. Turns out PyInstaller did not import required internal gtk libs within the build bundle. For the binaries built on the same distribution, the executable was able to find the required libs from the system but not on different distros.
A solution is presented on this PR. Here I add `PyGObject` as a build dependency for Linux which provides GTK libs for python, then add `gi` and `gi.repository` as hidden imports. These hidden imports make sure that `GdkPixbuf` is accessible and that PyQt Filechooser can work without …
> Fix crash on Ubuntu while selecting File Chooser

- src/tribler/core/conftest.py
- src/tribler/gui/tests/conftest.py
This PR makes extended logging (introduced in #7482 and #7485) dependent on `--verbose` flag.
Related to #7132, #7134
Without this PR, the output logic operates as expected when the `--verbose` flag is utilized. However, when running the test suite without this flag, we encounter an output that could be seen as inconvenient:
```
src/tribler/core/components/gigachannel/community/tests/test_gigachannel_community.py . in 1.158s (1.2s in total). in 0.230s (1.4s in total). in 0.198s (1.6s in total). in 0.131s (1.8s in total). in 0.089s (1.9s in total). in 0.084s (1.9s in total). in 0.239s (2.2s in total). in 0.584s (2.8s in total). in 0.236s (3.0s in total). in 0.433s (3.4s in total). in 0.135s (3.6s in total)^C^C in 0.009s (3.6s in total)
```
instead of 
``` …
```
> Make pytest extended logging logic dependent on `--verbose` flag

- src/tribler/core/components/popularity/community/popularity_community.py
- src/tribler/core/components/torrent_checker/torrent_checker/dataclasses.py
- src/tribler/core/components/torrent_checker/torrent_checker/tests/test_health_info_should_update.py
This PR fixes #7430 by suppressing all errors in `PopularityCommunity.gossip_random_torrents_health()`.
In #7430 the root cause of the error is a packing error in the attempt to pack the signed number -2 into an unsigned 32-bit integer.
We have several strategies for addressing this bug:
1. Inspect all instances where the leecher count is created/modified to ensure it consistently remains positive.
1. Guarantee that num_leechers is positive before invoking Community.ez_send().
1. Suppress all errors within the community.
I've opted for the third approach, in line with the existing ipv8 policy of error suppression within communities to prevent Tribler from crashing due to, for instance, a packet of death.
This bug uncovers the inconsistency in ipv8 error handling methods: some suppress …
> Consider HealthInfo with negative seeders and leechers as invalid

- src/tribler/gui/tests/test_gui.py
The reason for the non-zero exit code is the core process not being terminated correctly.
With this PR, we wait a max 10 seconds to let the core process terminate properly.
- Fixes https://github.com/Tribler/tribler/issues/7500
> Fix GUI Test non-zero exit code

- src/tribler/core/components/conftest.py
- src/tribler/core/components/knowledge/restapi/tests/test_knowledge_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_libtorrent_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_metadata_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_search_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_create_torrent_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_debug_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_settings_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_shutdown_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_statistics_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_trustview_endpoint.py
As it turns out, many REST API-related test fixtures have an `app.shutdown()` call at the end instead of `await app.shutdown()`, and it can be the reason for many problems with test stability.
In this PR, I add a `web_app` fixture that provides an instance of `aiohttp.web_app.Application` and correctly calls `await app.shutdown()` at the end.
The fixture is named `web_app` and not `app` to avoid PyCharm confusion with the `sphinx.testing.fixtures.app` fixture it tries to use when the new fixture is named `app`.
> Fix calling `await app.shutdown()` in REST API tests

- src/tribler/core/components/restapi/rest/debug_endpoint.py
The `run` method of `RESTComponent` has [the following lines](https://github.com/Tribler/tribler/blob/55d02e606d16edb1d09100a486da0deaf0385cea/src/tribler/core/components/restapi/restapi_component.py#L92):
```python
torrent_checker = None if config.gui_test_mode else torrent_checker_component.torrent_checker
tunnel_community = None if config.gui_test_mode else tunnel_component.community
gigachannel_manager = None if config.gui_test_mode else gigachannel_manager_component.gigachannel_manager
```
That is, `tunnel_community` is `None` when Tribler is started for GUI tests.
At the same time, the `DebugEndpoint` in the `RESTComponent.run` method is initialized [in the following way](https://github.com/Tribler/tribler/blob/55d02e606d16edb1d09100a486da0deaf0385cea/src/tribler/core/components/rest …
> The `get_circuit_slots` method of `DebugEndpoint` should handle the case when `tunnel_community` is `None`

- src/tribler/core/components/metadata_store/restapi/metadata_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_metadata_endpoint.py
Currently, the `RESTComponent.run` method has the following code lines:
```python
torrent_checker = None if config.gui_test_mode else torrent_checker_component.torrent_checker
tunnel_community = None if config.gui_test_mode else tunnel_component.community
gigachannel_manager = None if config.gui_test_mode else gigachannel_manager_component.gigachannel_manager
```
and
```python
self.maybe_add('/metadata', MetadataEndpoint, torrent_checker, metadata_store_component.mds,
knowledge_db=knowledge_component.knowledge_db,
tag_rules_processor=knowledge_component.rules_processor)
```
That is, under GUI tests, the `torrent_checker` argument of `MetadataEndpoint`  can be `None`. The `maybe_add` call does not handle this situation, as it can only handle `NoneComponent` arguments and not the normal …
> Fix the `get_torrent_health` endpoint in GUI tests

- src/tribler/core/conftest.py
This PR is related to #7495 and adds print information about the name of a test before it executes. It will help to investigate errors like 'Segmentation fault'  from https://github.com/Tribler/tribler/actions/runs/5378679663/jobs/9758812804?pr=7503
The output looks like:
```python
Starting "test_modify_tags"...
src/tribler/core/components/knowledge/restapi/tests/test_knowledge_endpoint.py::test_modify_tags PASSED                           [  7%] in 0.265s (5.7s in total)
Starting "test_get_suggestions_invalid_infohash"...
src/tribler/core/components/knowledge/restapi/tests/test_knowledge_endpoint.py::test_get_suggestions_invalid_infohash PASSED      [  7%] in 0.012s (5.8s in total)
Starting "test_get_suggestions"...
src/tribler/core/components/knowledge/restapi/tests/test_knowledge_endpoi …
```
> Add 'Starting <current test>...' print statement

- src/tribler/gui/tests/test_error_handler.py
Some tests (of the Core test suite) deliberately raise an AssertionError and expect it to be in `error_handler._handled_exceptions`. It is better to raise a specific `TestError` instead of a generic `AsserionError` not to be confused about whether the error was planned or unexpected. In this PR, I change `AssertionError` to `TestError` to avoid possible confusion.
The reason I want to fix it is that I had observed seen some strange cases when the string `"AssertionError"` was in `error_handler._handled_exceptions` while it was expected to be empty (unfortunately can't provide an example right now), and I want to eliminate possible cases of it.
> Use TestError instead of AssertionError in test to avoid confusion

- src/tribler/core/components/restapi/rest/tests/test_rest_manager.py
This PR fixes the flakiness of `test_aiohttp_assertion_patched` from #7495
@kozlovsky please confirm that this is a proper fix.
> Add `ClientOSError` as an expected exception

- src/tribler/core/components/restapi/rest/tests/test_events_endpoint.py
This PR fixes the flakiness of `test_write_data`. 
It's important to note that all tests that rely on `caplog` are potentially fragile.
> Fix flakiness of `test_write_data`

- src/tribler/gui/tests/test_core_manager.py
Fixes https://github.com/Tribler/tribler/issues/7510
Instead of patch decorator, context manager is used and mocked print object is used to check the call count instead of builtin print.
> Fix print issue on core manager repeated test

- requirements-test.txt
- src/tribler/core/upgrade/tests/test_version_manager.py
- src/tribler/core/upgrade/version_manager.py
- src/tribler/core/utilities/osutils.py
- src/tribler/gui/defs.py
- src/tribler/gui/tests/test_upgrade_manager.py
- src/tribler/gui/upgrade_manager.py
- Fixes: https://github.com/Tribler/tribler/issues/5907
- Fixes: https://github.com/Tribler/tribler/issues/1189
- Fixes: https://github.com/Tribler/tribler/issues/7409
Solution in the PR:
If there is no enough space to upgrade, it shows a pop up warning the user and quits Tribler on acknowledgment.
> Handle no space available situation on upgrade

- src/tribler/core/components/conftest.py
- src/tribler/core/components/knowledge/restapi/tests/test_knowledge_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_libtorrent_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_metadata_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_remote_query_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_search_endpoint.py
- src/tribler/core/components/metadata_store/tests/test_channel_download.py
- src/tribler/core/components/resource_monitor/implementation/base.py
- src/tribler/core/components/restapi/rest/debug_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_create_torrent_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_debug_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_settings_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_shutdown_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_statistics_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_trustview_endpoint.py
- src/tribler/core/conftest.py
This PR fixes `rest_api` by making it async.
Previously the common pattern was:
```python
@pytest.fixture
def rest_api(event_loop, aiohttp_client, knowledge_endpoint):
app = Application()
app.add_subapp('/knowledge', knowledge_endpoint.app)
yield event_loop.run_until_complete(aiohttp_client(app))
app.shutdown()
```
which is incorrect as `app.shutdown()` is async call.
Additionally, this PR includes some minor refactoring.
> Make `rest_api` fixture async

- src/tribler/core/components/metadata_store/tests/test_channel_download.py
This PR fixes `test_channel_update_and_download` by adding `@pytest.mark.looptime(False)` decorator as this test depends on a real `sleep`.
See:
https://github.com/Tribler/tribler/blob/9bb752c3fbfe2244724a84c89f2b26749d959c08/src/tribler/core/components/metadata_store/db/store.py#L562-L563
Refs:
* https://pypi.org/project/looptime/
> Add `@pytest.mark.looptime(False)` for `test_channel_update_and_download`

- requirements-build.txt
- tribler.spec
This PR fixes #7532 by downgrading the PyInstaller version back to 5.1
> Fix ImportError: DLL load failed while importing libtorrent: The specified module could not be found

- src/tribler/core/components/restapi/tests/test_restapi_component.py
This PR fixes "no running loop" error for the tests that use the `rest_component` fixture.
The core cause of the error is the fact that each instance of the component class should be created in the environment with the existing event loop as there is an instance of the `Event()` class created in the component's constructor.
> Make the `rest_component` fixture async

- src/tribler/core/conftest.py
- src/tribler/gui/tests/conftest.py
This PR should stabilize the test suites. It has worked for my local runs, but doesn't resolve all problems—just many of them.
My hypothesis is that, to properly release all resources used by libtorrent, object destructors must be called. This happens during garbage collection. It appears that after some tests, the garbage collector doesn't have enough time to be invoked, leading to random, inexplicable bugs. However, I'm not completely certain about this explanation.
Related to #7495 #7498
Refs:
* https://docs.pytest.org/en/stable/explanation/fixtures.html#fixture-instantiation-order
> Add `ensure_gc` for each test call

- src/tribler/core/components/libtorrent/download_manager/download.py
These `Download` fields were being set twice.
> Fixed double-setting of Download fields

- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/tests/test_download.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
- src/tribler/core/utilities/async_force_switch.py
This PR doesn't completely solve the issue causing the flakiness of the libtorrent tests. However, the changes have made the tests more responsive and should, at the very least, prevent the main thread from freezing.
Besides minor refactoring, there are two significant changes in this PR:
1. An asyncio switch was added to the `wait_for_status` function due to the potential of blocking the main thread during pytest execution. To understand the possibility, consider this example: https://github.com/Tribler/tribler/blob/018cd5fce25a0d9759d0c0d22b41b158c60428cd/src/tribler/core/utilities/tests/test_async_force_switch.py#L10-L34
2. The shutdown logic has been rewritten to be slightly more accurate. While this change may not directly influence test stability, it could contribute slightly to it. …
> Make the `libtorrent` tests more responsive

- src/tribler/core/components/bandwidth_accounting/tests/test_community.py
- src/tribler/core/components/gigachannel/community/tests/test_gigachannel_community.py
I've been told nobody uses the advanced `TestBase` functionality because there is no example code to copy-paste from in the Tribler source. So, I modernized the tests for the `BandwidthCommunity` and the `GigaChannelCommunity`.
In passing, I've also changed up some test code that has test nodes be able to observe each other's private keys (by being sent each other's `my_peer`). Secondarily, it seems to me that `test_remote_select_channel_contents_happy_eyeballs` had a 50/50 chance of succeeding when not fixing random numbers, which I also changed into a 100% success guarantee.
The `TestGigaChannelUnits` could probably be cleaned up even further by extracting string literals, etc. However, that is not the goal of this PR. The goal of this PR is only to showcase advanced `TestBase` …
> Ported Bandwidth/GigaChannel tests to modern TestBase

- src/tribler/core/components/ipv8/ipv8_component.py
- src/tribler/core/components/ipv8/tests/test_ipv8_component.py
Fixes #7552
The previous code was enabling statistics for all overlays in an empty list of overlays.
> Fixed statistics not being enabled for any overlays

- src/tribler/core/components/reporter/exception_handler.py
- src/tribler/core/components/reporter/tests/test_exception_handler.py
This PR fixes #7556. ConnectionResetError means that a client dropped a connection to the AIOHTTP server before the response was sent back. On the server side, it is not an error and should be ignored.
Before this fix, only ConnectionResetError with error code 10054 is ignored. When aiohttp raises ConnectionResetError, it does not specify any error code, so all instances of ConnectionResetError should be ignored, disregarding the error code.
Previously there were two groups of errors ignored by SentryReporter: `IGNORED_ERRORS_BY_CODE` and `IGNORED_ERRORS_BY_REGEX`. The PR adds a third group, `IGNORED_ERRORS_BY_CLASS`.
> CoreExceptionHandler should ignore all occurrences of ConnectionResetError

- doc/restapi/introduction.rst
- src/tribler/core/components/restapi/rest/rest_manager.py
- src/tribler/core/components/socks_servers/socks_servers_component.py
- src/tribler/core/start_core.py
- src/tribler/gui/core_manager.py
- src/tribler/gui/defs.py
- src/tribler/gui/event_request_manager.py
- src/tribler/gui/network/request_manager.py
- src/tribler/gui/network/tests/test_request_manager.py
- src/tribler/gui/qt_resources/mainwindow.ui
- src/tribler/gui/start_gui.py
- src/tribler/gui/tests/test_core_manager.py
- src/tribler/gui/tribler_window.py
- src/tribler/gui/widgets/settingspage.py
This PR fixes #7564. It stops using `default_network_utils.get_random_free_port()` and passes port value zero when starting a server to allow OS to choose a free port without race conditions.
The PR consists of several commits:
1. The first commit stops using `get_random_free_port()` when starting a new Socks5Server
3. The second commit renames `events_manager.connect(...)` to `events_manager.connect_to_core(...)`. The reason for this is the `connect` name is overused: the same name is used for subscribing to PyQt signals, for opening `UdpTrackerSession`, and for connecting to the sqlite3 database in ProcessManager, so it is better to have a distinct name to find all places when the specific method is used easily.
4. The third commit changes the logic of how REST API Manager gets the …
> Avoid race conditions when starting Socks5 servers and REST API by allowing OS to choose a free port

- src/tribler/gui/network/request.py
- src/tribler/gui/network/tests/test_request.py
This PR updates the HTTP response processing done on `on_finished()` call to prioritise HTTP response processing over QT QNetworkReply errors processing.
This fixes the issue where QNetworkReply error processing masks the processing of HTTP response with status codes like 413 (HTTPEntityTooLarge) as in https://github.com/Tribler/tribler/issues/7558. 
Fixes https://github.com/Tribler/tribler/issues/7558
> Prioritise HTTP status code processing over QNetworkReply errors

- src/tribler/core/__init__.py
- src/tribler/core/utilities/asyncio_fixes/tests/test_python39_and_later_wait_for.py
- src/tribler/core/utilities/asyncio_fixes/tests/test_wait_for_patch.py
- src/tribler/core/utilities/asyncio_fixes/wait_for.py
The patch fixes #7570 by monkey-patching `asyncio.tasks.wait_for` with a version that did not suppress `CancelledError`. Also, the patched version adds `base_lost_result_handler` that writes an error if a result of a completed task is lost due to a race condition. Right now, I don't think we have some lost resources due to the original `wait_for` bug, but later we can override `base_lost_result_handler` to properly close such resources if necessary.
> A patch for `asyncio.tasks.wait_for` for Python 3.8-3.11

- requirements-test.txt
- src/tribler/core/components/knowledge/restapi/tests/test_knowledge_endpoint.py
- src/tribler/core/components/metadata_store/db/orm_bindings/vsids.py
- src/tribler/core/components/metadata_store/tests/test_channel_metadata.py
- src/tribler/core/utilities/date_utils.py
In this PR, I removed pytest-freezegun plugin used for freezing the date/time on the tests. This plugin was causing performance hits as reported on sentry. This plugin is now removed and replaced with an utility providing similar functionality. The test performance has improved as a result.
> Remove dependency on pytest-freezegun plugin

- src/tribler/core/components/libtorrent/restapi/create_torrent_endpoint.py
- src/tribler/core/components/restapi/rest/rest_endpoint.py
- src/tribler/core/components/restapi/rest/rest_manager.py
- src/tribler/core/components/restapi/rest/tests/test_create_torrent_endpoint.py
- src/tribler/core/conftest.py
`test_create_torrent_endpoint.py::test_create_torrent_of_large_size` is consistently taking 20-30 seconds to finish the tests which is one of the contributor to timing out the full test suite.
This PR optimizes the test to reduce the test time to 100-200 ms (hopefully).
> Optimize the large torrent creation test

- src/tribler/core/components/metadata_store/restapi/channels_endpoint.py
- src/tribler/core/components/metadata_store/restapi/metadata_endpoint_base.py
- src/tribler/core/components/metadata_store/restapi/metadata_schema.py
- src/tribler/core/components/metadata_store/restapi/remote_query_endpoint.py
- src/tribler/core/components/metadata_store/restapi/search_endpoint.py
- src/tribler/core/utilities/tests/test_utilities.py
- src/tribler/core/utilities/utilities.py
Allows using swagger ui & enable/disable boolean flags. Fixes #7562
remote_query have been removed from openapi since it does not appear to be used.
Split definition for search and remote query as they do not take the same args.
> Support true/false for boolean url query arguments.

- .github/workflows/vars/pytest.env
Addresses https://github.com/Tribler/tribler/issues/7581
> Remove reruns and reruns-delay from pytest arguments

- src/tribler/core/components/knowledge/db/tests/test_knowledge_db.py
- src/tribler/core/components/knowledge/rules/knowledge_rules_processor.py
- src/tribler/core/components/knowledge/rules/tests/test_knowledge_rules_processor.py
This PR is related to issue #7398 and serves as the first step in the migration process.
After the implementation of this PR, all incoming titles will be stored in `knowledge.db`. Additionally, all existing titles will be moved to `knowledge.db` in the background.
In addition, this PR introduces estimated time calculation to the `KnowledgeRulesProcessor`.
> Add a title to knowledge processing

- .github/actions/windows_dependencies/action.yml
This PR fixes https://github.com/Tribler/tribler/actions/runs/6298097466/job/17096579998?pr=7604#step:4:96
Ref: https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
> Use curl for the windows_dependencies action

- requirements-core.txt
Related to #7282, #7597 and #7556
> Bump `pony` and `sentry-sdk` versions

- src/tribler/core/components/database/db/tests/test_tribler_database.py
- src/tribler/core/components/database/db/tests/test_tribler_database_base.py
- src/tribler/core/components/database/db/tribler_database.py
During the optimization of the `get_subjects_intersection` function (https://github.com/Tribler/tribler/pull/7153/commits/3619ca52e4ce09d11cf47559b02162d695bad208), the parameter `subjects_type` was overlooked. This became clear in #7606 during the Codacy check.
> Utilize the `subjects_type` parameter

- src/tribler/core/components/restapi/rest/rest_manager.py
This PR fixes the core issue of #7592. The `wait_for` wrapper actually didn't do anything useful here and provoked the `TimeoutError`. The server itself should start almost immediately, especially now, as it is directly called in the current coroutine. In case it freezes on some machine, we should be able to detect it by looking at the result of the slow coroutine detector.
> Fixes #7592: remove the `wait_for` wrapper around `await site.start()` when starting HTTP REST API server

- src/tribler/core/components/metadata_store/restapi/channels_endpoint.py
- src/tribler/core/components/metadata_store/restapi/tests/test_channels_endpoint.py
> Return `RESTResponse` error for timed out metainfo request

- src/tribler/core/components/database/database_component.py
- src/tribler/core/components/database/db/layers/tests/test_knowledge_data_access_layer.py
- src/tribler/core/components/database/db/tests/test_tribler_database.py
- src/tribler/core/components/database/db/tribler_database.py
- src/tribler/core/upgrade/tribler_db/conftest.py
- src/tribler/core/upgrade/tribler_db/decorator.py
- src/tribler/core/upgrade/tribler_db/migration_chain.py
- src/tribler/core/upgrade/tribler_db/scheme_migrations/scheme_migration_0.py
- src/tribler/core/upgrade/tribler_db/scheme_migrations/tests/test_scheme_migration_0.py
- src/tribler/core/upgrade/tribler_db/tests/test_decorator.py
- src/tribler/core/upgrade/tribler_db/tests/test_migration_chain.py
- src/tribler/core/upgrade/upgrade.py
This PR introduces a more strict and formal way of DB migrations.
The main idea behind this change is to standardize the migration procedure into a series of functions that resemble:
```python
@migration(execute_only_if_version=0)
def scheme_migration_0(db: TriblerDatabase, **kwargs):  # pylint: disable=unused-argument
db.execute('ALTER TABLE "TorrentState" ADD "has_data" BOOLEAN DEFAULT 0')
db.execute('UPDATE "TorrentState" SET "has_data" = 1 WHERE last_check > 0')
```
```python
@migration(execute_only_if_version=1)
def scheme_migration_1(db: TriblerDatabase, **kwargs):  # pylint: disable=unused-argument
db.execute('ALTER TABLE "Tracker" ADD "updated" INT DEFAULT 0')
```
This PR should fix some of the problems described in #7382
Related to #7398
> Add `TriblerDatabaseMigrationChain`

- scripts/application-tester/README.md
- scripts/application-tester/main.py
- scripts/application-tester/requirements.txt
- scripts/application-tester/tribler_apptester/executor.py
- scripts/application-tester/tribler_apptester/logger/logger.py
- scripts/application-tester/tribler_apptester/requestmgr.py
This PR encompasses two categories of modifications.
The only amendment in this section pertains to updating the `readme.md` and the code within the Application Tester to correctly set the API port for Tribler Core.
- Introducing colored logging to differentiate between Tribler logs and Application Tester logs.
- Incorporated the `--fragile` flag to make the asyncio loop fragile, mirroring the modifications applied to other tools within the `scripts` directory.
- Replaced the `configobj` dependency with the utilization of `TriblerConfig`.
> Update the Application Tester

- .readthedocs.yml
Fixes #7636
The current legacy config is no longer supported (see also https://docs.readthedocs.io/en/stable/config-file/v2.html#legacy-build-specification).
> Modernized the ReadTheDocs configuration

- doc/requirements.txt
- requirements-core.txt
- src/tribler/core/components/bandwidth_accounting/tests/test_bandwidth_endpoint.py
- src/tribler/core/components/bandwidth_accounting/tests/test_community.py
- src/tribler/core/components/database/db/tests/test_tribler_database.py
- src/tribler/core/components/gigachannel/community/tests/test_gigachannel_community.py
- src/tribler/core/components/gigachannel/community/tests/test_sync_strategy.py
- src/tribler/core/components/ipv8/adapters_tests.py
- src/tribler/core/components/ipv8/eva/tests/test_protocol.py
- src/tribler/core/components/ipv8/ipv8_component.py
- src/tribler/core/components/ipv8/tribler_community.py
- src/tribler/core/components/knowledge/community/tests/test_knowledge_community.py
- src/tribler/core/components/metadata_store/remote_query_community/tests/test_remote_query_community.py
- src/tribler/core/components/metadata_store/remote_query_community/tests/test_remote_search_by_tags.py
- src/tribler/core/components/popularity/community/tests/test_popularity_community.py
- src/tribler/core/components/popularity/community/tests/test_version_community_mixin.py
- src/tribler/core/components/restapi/rest/tests/test_statistics_endpoint.py
- src/tribler/core/components/tunnel/community/tunnel_community.py
- src/tribler/core/components/tunnel/tests/test_full_session/test_tunnel_community.py
- src/tribler/core/components/tunnel/tests/test_triblertunnel_community.py
This PR is the second attempt to update the IPv8 version to `2.12` in Tribler.
The previous PR to update the version, #7620, was rejected because communities could not `__init__` with kwargs. In this PR, I introduce adapters to allow communities to `__init__` with `args` and `kwargs`, like in the previous IPv8 version (`2.11`).
- The new class `TriblerMockIPv8` provides the old interface using the new `MockIPv8`.
- The new class `TriblerTestBase` provides the old interface using the new `TestBase`.
- An update to `TriblerCommunity` provides the old interface using the new `Community`.
_Disclaimer: I still prefer the implementation of #7620 over this._
> Updated IPv8 while keeping Community kwargs

- .github/workflows/pytest.yml
This PR increases the timeout for `pytest.yml` since it appears that 10 minutes isn't sufficient to run the Windows tests, as evidenced by: https://github.com/Tribler/tribler/actions/workflows/!main.yml
With the merge of #7582, we aim to address the "frozen tests" issue. Thus, it should be safe to extend the timeout from 10 to 15 minutes.
> Increase the timeout for `pytest.yml`

- src/tribler/core/components/libtorrent/settings.py
- src/tribler/core/components/libtorrent/tests/test_settings.py
This PR fixes #5713 by setting the limit for int fields of the libtorrent config.
Ref: https://libtorrent.org/reference-Torrent_Handle.html#max-connections-set-max-connections
> Set the limit for int values of the libtorrent config

- scripts/application_tester/tribler_apptester/data/torrent_links.txt
This PR adds [Crossref's 2023 official public data file](https://www.crossref.org/blog/2023-public-data-file-now-available-with-new-and-improved-retrieval-options/) to the list of torrent links of the app tester.
The added torrent is not small or nice to parse - like our current links - and I wholly expect it to bring down our application tester. Nevertheless, this is _not an impossible torrent for libtorrent_ to download (which you _can_ generate by going beyond the maximum recursion depth etc.) and it can be considered to be otherwise "normal": Tribler _should_ handle this.
> Added crossref public data file

- src/tribler/core/components/libtorrent/settings.py
- src/tribler/core/components/libtorrent/tests/test_settings.py
- src/tribler/core/components/torrent_checker/torrent_checker/torrentchecker_session.py
- src/tribler/core/utilities/utilities.py
This PR moves `INT32_MAX` to `utilities.py` as a recommended refactoring for #7650 and #7651.
> Extract `INT32_MAX` to utilities.py

- src/tribler/gui/network/request.py
- src/tribler/gui/network/request_manager.py
This PR introduces a `debug` parameter to `RequestManager.add()`, allowing for the caller information of a request to be printed. 
This is particularly handy when investigating the source of a request call (as I discovered during my recent attempt to remove Channel on Friday).
When the `debug` argument is set to `True`, the output will appear as follows:
```python
[tribler-gui PID:2015] 2023-10-30 12:08:08,351 - INFO - Request(108) - Finished: GET http://localhost:53611/channels?metadata_type=300&metadata_type=220&include_total=1&first=1&last=50&sort_by=votes&sort_desc=1&hide_xxx=0
Caller: <FrameSummary file /Users/<user>/Projects/github.com/Tribler/tribler/src/tribler/gui/widgets/tablecontentmodel.py, line 368 in perform_query>
[tribler-gui PID:2015] 2023-10-30 12:08:08,352 - INFO - …
```
> Add the debug parameter to the `RequestManager.add()`

- src/tribler/gui/tests/test_gui.py
- src/tribler/gui/tribler_window.py
This PR addresses issue #7641 by introducing a new flag `ui_started`, which is utilized to ascertain the appropriate time to proceed with URI handling.
> Fix TypeError: 'NoneType' object is not subscriptable in StartDownloadDialog.__init__() 

- src/tribler/core/sentry_reporter/sentry_scrubber.py
- src/tribler/gui/tribler_window.py
- src/tribler/gui/widgets/settingspage.py
This PR enhances Sentry Event reporting by including the Tribler Config data collected from the GUI side, aiding in the investigation of issues such as #7641.
See the event example here: https://sentry.tribler.org/organizations/tribler/issues/2449
> Add Tribler Config to the sentry event

- src/tribler/core/components/restapi/rest/settings_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_rest_manager.py
- src/tribler/core/config/tests/test_tribler_config.py
- src/tribler/core/config/tribler_config.py
I have some code left over from investigating #7519, which includes a refactoring of `parse_settings` and additional tests.
It is at the discretion of the reviewer to determine whether this refactoring is necessary or not.
> Extract `parse_settings` to the `TriblerConfig`

- src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler/gui/widgets/downloadprogressbar.py
- src/tribler/gui/widgets/downloadspage.py
Related to #5399 (PR 1/4)
In order to filter for the selected download in the downloads list, a new REST API parameter `"infohash"` is added to `get_downloads()` (serving `/downloads`). If the parameter is omitted, `get_downloads()` functions as before. Otherwise, the `get_peers`, `get_pieces`, and `get_files` are only applied to the download with the given infohash.
Because of the change `set_pieces()` may encounter downloads without set pieces. This is now handled.
Tangentially related to the other changes, I added a `refresh_downloads()` whenever the detail tab/window is shown.
---
Test reruns for this PR:
| **name** | **reason** |
| --- | --- |
| guitest_nix / run (macos-latest) | teardown of test_trust_page (Signal <bound PYQT_SIGNAL finished of QProcess object at 0x11fe49ee0> not …
> Only load peers, pieces, and files for the selected download

- requirements-core.txt
- src/run_tribler_headless.py
- src/tribler/core/start_core.py
- src/tribler/core/utilities/process_locking.py
- src/tribler/core/utilities/process_manager/manager.py
- src/tribler/core/utilities/process_manager/process.py
- src/tribler/core/utilities/process_manager/tests/conftest.py
- src/tribler/core/utilities/process_manager/tests/test_manager.py
- src/tribler/core/utilities/process_manager/tests/test_process.py
- src/tribler/core/utilities/tests/test_process_locking.py
- src/tribler/core/utilities/tiny_tribler_service.py
- src/tribler/gui/start_gui.py
- src/tribler/gui/tests/test_gui.py
This PR provides an alternative way (as compared to #7637) to determine the primary Tribler process. This PR uses the `filelock` library for that purpose:
* Now, when the primary Tribler GUI/Core process is running, the corresponding lock files `'tribler-gui.lock'`/`'tribler-core.lock'` are created and held until the related GUI/Core process is finished.
* ProcessManager still keeps all Tribler processes in the database but does not determine which process can be primary.
* The database of processes is still used to pass the opened REST API port from the Core process to the GUI process. The reason for this is that it is still possible that multiple processes of the same type can run in parallel (for example, one primary and several secondary processes), and it is safer to store port in a …
> Use the filelock library to determine the primary GUI/Core process

- src/tribler/core/components/knowledge/rules/knowledge_rules_processor.py
- src/tribler/core/components/knowledge/rules/tests/test_knowledge_rules_processor.py
Following the [suspension](https://github.com/Tribler/tribler/issues/7398#issuecomment-1772193981) of Knowledge Graph Migration, this PR disables two features:
1. The addition of `Title` statements to `knowledge.db`.
2. The batch processing of torrent titles.
This change aims to conserve the user's CPU resources and disk space.
> Disable background knowledge migration

- src/tribler/core/start_core.py
Fixes #5435 by removing the workaround for #5485.
Note that I will use the branch of this PR to make sure #5485 _remains resolved_. To that end, this PR _may_ be amended with fixes related to #5485. I'll keep running a custom build for this PR (https://jenkins-ci.tribler.org/job/pers/job/Build-Win64-Custom/2/) for about an hour and keep an eye on the peers. If #5485 still does not appear, I will consider it resolved.
> Use the default event loop on Windows

- src/tribler/gui/i18n/es_ES.ts
- src/tribler/gui/i18n/pt_BR.ts
- src/tribler/gui/i18n/ru_RU.ts
- src/tribler/gui/i18n/zh_CN.ts
- src/tribler/gui/qt_resources/torrents_list.ui
Fixes #6532 by adopting the default tooltip style, consistent with the rest of our tooltips.
Secondarily, this PR fixes a minor misspelling in the tooltip itself.
> Fixed non-standard tooltip stylesheet

- src/tribler/core/components/libtorrent/download_manager/download_state.py
- src/tribler/core/components/libtorrent/tests/test_download_state.py
Fixes #6454
Codacy decided that it is my responsibility to fix the fixture names. So, I added a fix for the fixtures in `test_download_state.py`.
> Handle the possible RuntimeException in handle.file_progress()

- src/tribler/core/components/libtorrent/tests/test_torrent_file_tree.py
- src/tribler/core/components/libtorrent/torrent_file_tree.py
Related to #5399 (PR 3/4)
This PR _only_ adds the data structure to power pagination of huge torrent file lists (through the `TorrentFileTree.view()` method). Because this data structure prioritizes performance, its complexity is higher than usual. Through typing, tests, and documentation I hope to have made the complexity manageable for the reader/reviewer.
As a note for future work: some of the constructions in this file are made with future versions of Python in mind. They can be shortened once we upgrade Tribler to a newer Python version.
In PR 4/4, I will hook the `TorrentFileTree` data structure into the actual downloads endpoint.
---
Test reruns for this PR:
| **name** | **reason** |
| --- | --- |
|  pytest  /  run (windows-latest)  | …
> Added a torrent file tree representation

- .github/workflows/!PR.yml
This PR introduces an option to upload binaries for a PR. This can be done if a developer adds the label `PR: upload binaries` to the PR.
Example: https://github.com/Tribler/tribler/actions/runs/6852711450
> Upload binaries by label

- pytest.ini
This PR addresses frozen test problems and enables `faulthandler` in the hope it can print the stacktrace of frozen tests.
It passes the following test:
```python
@pytest.mark.timeout(1)
def test_block():
def block_forever():
while True:
pass
blocker = threading.Thread(target=block_forever)
blocker.start()
blocker.join()  # This join will block the event loop indefinitely
```
with the following stacktrace:
```
Timeout (0:00:15)!
Thread 0x0000700007d81000 (most recent call first):
File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler/core/upgrade/tests/test_triblerversion.py", line 56 in block_forever
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910 in run
File …
```
> Enable `faulthandler`

- src/tribler/gui/dialogs/feedbackdialog.py
Fixes #7697
Basically, `reported_error.event` can be `None`.
---
🙂 Re-running Windows tests due to #7701 (fixed in #7703)
🙁 Re-running Windows tests again due to #7701 (fixed in #7703)
> Fixed reporting error without event crashing reporter

- src/tribler/core/components/bandwidth_accounting/tests/test_community.py
Fixes #7701 by patching `time.time()`.
---
Retest macos-latest due to https://github.com/Tribler/tribler/issues/6854#issuecomment-1819344565
> Fixed test_bilateral_transaction_timestamps depending on real time

- scripts/exit_node/run_exit_node.py
- src/tribler/core/components/tunnel/tests/test_full_session/test_tunnel_community.py
For PR:
* Fixes `circuit_removed`, which was failing when getting IPv8.
* Removes some unneeded components from the exit node script (like starting SOCKS5 servers).
* Refactors the exit node script to use `asyncio.run`.
> Fixed exit node script

- requirements-test.txt
This PR removes `pytest-rerunfailures` dependency as unused since #7581
> Remove `pytest-rerunfailures`

- src/tribler/core/components/bandwidth_accounting/db/database.py
- src/tribler/core/components/component.py
- src/tribler/core/components/gigachannel_manager/gigachannel_manager.py
- src/tribler/core/components/knowledge/db/knowledge_db.py
- src/tribler/core/components/metadata_store/db/store.py
- src/tribler/core/components/reporter/exception_handler.py
- src/tribler/core/components/reporter/tests/test_exception_handler.py
- src/tribler/core/components/restapi/rest/rest_manager.py
- src/tribler/core/components/tests/test_base_component.py
- src/tribler/core/upgrade/db8_to_db10.py
- src/tribler/core/upgrade/tags_to_knowledge/tags_db.py
- src/tribler/core/upgrade/tests/test_upgrader.py
- src/tribler/core/upgrade/upgrade.py
- src/tribler/core/upgrade/version_manager.py
- src/tribler/core/utilities/db_corruption_handling/base.py
- src/tribler/core/utilities/db_corruption_handling/sqlite_replacement.py
- src/tribler/core/utilities/db_corruption_handling/tests/conftest.py
- src/tribler/core/utilities/db_corruption_handling/tests/test_base.py
- src/tribler/core/utilities/db_corruption_handling/tests/test_sqlite_replacement.py
- src/tribler/core/utilities/exit_codes.py
- src/tribler/core/utilities/pony_utils.py
- src/tribler/core/utilities/tests/test_pony_utils.py
- src/tribler/gui/core_manager.py
- src/tribler/gui/defs.py
- src/tribler/gui/error_handler.py
- src/tribler/gui/event_request_manager.py
- src/tribler/gui/tribler_window.py
- src/tribler/gui/upgrade_manager.py
- src/tribler/gui/utilities.py
Fixes #7623, #7037, #5252, and #1993 (the latter is the pre-ORM version of the same problem)
This PR adds handling to the error "DatabaseError: database disk image is malformed". The error is handled in all databases that Tribler has: "metadata.db", "knowledge.db", "bandwidth.db", and "tags.db" (if it presents during the migration). The database "processes.sqlite" is already handled separately.
The main goal of the PR is to restore normal Tribler functionality by deleting the corrupted database file and allowing Tribler to create a new, fresh database file. Instead of deleting the file, we can rename it as an alternative way to handle the issue. Still, I'm not sure it is worth it, as it will take some valuable disk space, and not many users will try to restore information from the …
> Handle the "DatabaseError: database disk image is malformed" error

- src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py
Fixes https://github.com/Tribler/tribler/issues/7670.
I've removed the circuit from the peer_info, as it isn't very useful. For debugging purposes we use the debug panel.
> Removed circuit from peer_info

- src/tribler/core/components/resource_monitor/implementation/core.py
- src/tribler/core/components/resource_monitor/implementation/tests/test_resource_monitor.py
- Refactored the `get_disk_usage` method to return an optional named tuple instead of a list
- Updated the code to handle exceptions when retrieving disk usage information using `psutil.disk_usage`
- Added a new test case to verify that disk usage is None when an exception occurs in `psutil.disk_usage`
This commit improves the reliability and error handling of disk usage tracking in the resource monitor component.
Fixes #7712
> Refactor disk usage tracking and handling

- src/tribler/core/sentry_reporter/sentry_tools.py
- src/tribler/core/sentry_reporter/tests/test_sentry_tools.py
This PR adds an exclusion for the exception type found in the latest core output. Specifically, it includes the word 'warning' in the list of exclusions.
* Refactored the `parse_last_core_output` function to improve readability and maintainability.
* Added a regular expression pattern `_re_search_exception_exclusions` to exclude specific exception types from being parsed.
* Modified the `parse_last_core_output` function to skip parsing if an excluded exception type is found.
Fixes https://github.com/Tribler/tribler/issues/7713
> Add an exclusion for the exception type found in the latest core output.

- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler/core/components/libtorrent/tests/test_download.py
- src/tribler/core/components/libtorrent/tests/test_torrent_file_tree.py
- src/tribler/core/components/libtorrent/torrent_file_tree.py
- src/tribler/gui/qt_resources/mainwindow.ui
- src/tribler/gui/tests/test_gui.py
- src/tribler/gui/widgets/downloadsdetailstabwidget.py
- src/tribler/gui/widgets/downloadspage.py
- src/tribler/gui/widgets/torrentfiletreewidget.py
Fixes #5399 but not beautifully<sup>1,2,3</sup> (because this PR is becoming too big).
This PR includes the REST API integrations necessary for paginated views of files in torrents and "infinite" scrolling of the file list. Additionally, a spinner (`gui/images/spinner.gif`) is displayed while loading the file list. Screenshot:
<sup>1</sup>One of the big remaining beautification steps afterward is partial selection support for folders. Right now, the checkboxes for folders only function as "select all"/"deselect all" triggers. I'll open a separate issue for this afterward.
<sup>2</sup>Another nice feature would be to use our tree arrow icons/images instead of unicode arrows.
<sup>3</sup>Resizes of the download details widget cause all visible information in the files list to be refreshed, …
> Added torrent file trees to the download endpoint

- src/tribler/core/components/resource_monitor/implementation/core.py
- src/tribler/core/components/resource_monitor/implementation/tests/test_resource_monitor.py
- Removed `set_resource_log_enabled` and `is_resource_log_enabled` methods from `CoreResourceMonitor` class.
- Updated corresponding test case in `test_resource_monitor.py`.
- No functional changes made, only code cleanup.
This PR removes leftovers from #7160
> Refactor resource monitor code and remove unused methods

- src/tribler/core/sentry_reporter/sentry_reporter.py
- src/tribler/core/sentry_reporter/tests/test_sentry_reporter.py
This PR refactors the `SentryReporter` class to parse the "last core output" only for specific exception types. The `send_event` function now checks if the exception type is in a predefined set of types that require parsing. If it is, the last core output is split for better representation in the web view and then parsed using the `parse_last_core_output` function. The resulting core exception is added to the exceptions list, along with some additional modifications to remove unnecessary information.
Additionally, a new test case has been added to ensure that the `send_event` function correctly calls `parse_last_core_output` only for specific exception types.
It continues the work done in #7722 and makes the logic of #7066 safer.
> Refactor SentryReporter to parse last core output for specific exception types

- src/tribler/gui/widgets/settingspage.py
- src/tribler/gui/widgets/tabbuttonpanel.py
- Added a new method showEvent() in SettingsPage class in settingspage.py
- Modified on_tab_button_click() method in TabButtonPanel class in tabbuttonpanel.py to call process_button_click() method
- Created a new method process_button_click() in TabButtonPanel class to handle button click events
Fixes #7350
> Refactor `settingspage.py` and `tabbuttonpanel.py`

- src/tribler/core/exceptions.py
- src/tribler/gui/exceptions.py
This helps with testing the restart of the core on manually triggered core exceptions using Debug endpoints.
> Make TriblerCoreTestException inherit CoreError

- src/tribler/core/version.py
This PR updates Tribler version in the main branch to `7.14.0-GIT`
> Update Tribler version to 7.14

- src/run_tribler_headless.py
- src/tribler/core/start_core.py
- src/tribler/core/utilities/exit_codes.py
- src/tribler/core/utilities/tiny_tribler_service.py
- src/tribler/gui/start_gui.py
Currently, when the Tribler GUI/Core process detects that another primary process is running, it exits with the generic exit code 1.
It is better to have a separate exit code so CoreManager or ApplicationTester is able to see the reason for the sudden process termination. Introducing the specific exit codes should allow the separation of the different error reports in Sentry and the special handling of specific exit codes.
> Use dedicated exit codes when another primary GUI/Core process is running

- src/tribler/core/components/content_discovery/content_discovery_component.py
I removed the isolation of the `ContentDiscoveryCommunity` during refactoring and I forgot to add it back. This PR resolves this.
> Reisolate content discovery community

- src/tribler/core/components/libtorrent/tests/test_torrent_def.py
- src/tribler/core/components/libtorrent/torrentdef.py
Fixes #7732
We could still remove the entirety of `TorrentDefNoMetainfo` but its existence still seems convenient.
> Made `TorrentDefNoMetainfo` inherit from `TorrentDef`

- .github/CODEOWNERS
The default code owners have been updated from @Tribler/dev to @Tribler/reviewers. 
I'm going to rename the actual group after the approval/merge.
> Change default code owners to @Tribler/reviewers

- src/tribler/core/check_os.py
- src/tribler/core/tests/test_check_os.py
- src/tribler/gui/start_gui.py
This PR modifies the function `check_free_space` to ignore `OSErrors` so they cannot lead to Tribler crashing.
Additionally, in the `start_gui.py` module, the `check_free_space` function now takes a parameter specifying the root state directory to be checked for free space.
Fixes #7745
> Modify `check_free_space function` to verify available disk space

- src/tribler/core/conftest.py
- src/tribler/core/utilities/asyncio_fixes/wait_for.py
- src/tribler/core/utilities/tests/test_utilities.py
This PR contains refactoring for `test_http_get_with_redirect`, (in particular, it adds more log output) and it contains an actual fix for the #7767. This refactoring does not fix the problem, but it was a starting point for me to investigate the issue, and I decided to include this change in the PR as it improves logging for the tests and does not clutter the PR too much.
The actual fix is to call `patch_wait_for()` in `conftest.py`, as it addresses the issue 
- #7570 
which I believe we also have in our tests.
Fixes: #7767
> Fix the asyncio `wait_for` function for the core tests

- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/download_manager/download_config.py
- src/tribler/core/utilities/tests/test_path_utils.py
This PR adds tests for `Path.fix_win_long_file` and contains a small refactoring for `DownloadConfig.write` that I've done during the investigation of #5926.
> Add tests for `Path.fix_win_long_file`

- scripts/application_tester/requirements.txt
- scripts/requirements.txt
This PR removes the unnecessary `requirements.txt` from the Application Tester directory, as these requirements are superseded by Tribler's requirements.
- Removed `application_tester/requirements.txt` from the project as it was no longer needed.
- Updated `scripts/requirements.txt` to remove the reference to `application_tester/requirements.txt`.
Related #7777
> Appliction Tester: Remove unnecessary requirements

- src/tribler/core/components/libtorrent/tests/test_torrent_utils.py
- src/tribler/core/components/libtorrent/utils/torrent_utils.py
This PR fixes `RuntimeError: invalid torrent handle used` by adding try-except block:
```python
try:
result_future.set_result(func(*args, **kwargs))
except RuntimeError as e:
logger.exception(e)
```
The reasoning for eating the exception is the following:
1. Originally the `require_handle` decorator ensures that there is a handle present and the handle is valid before calling the function. If the handle is invalid, then the function will not be called.
2. The suggested change just extends this to the call itself and, in the case of a `RuntimeError`, suppresses it. 
3. For the caller, the behavior will be the same as if the check `handle.is_valid()` returns a False value.
The drawback of this change is the fact that, besides the "invalid torrent handle used," there could be another …
> Fix RuntimeError: invalid torrent handle used

- .github/workflows/stale.yml
This PR introduces a new GitHub Actions workflow for managing stale issues in our repository. Key features of this workflow include:
- Automatically marking issues as stale after 60 days of inactivity.
- Not auto-closing stale issues; instead, they will require manual review for closure.
This addition aims to improve our issue tracking and ensure that open issues remain relevant and actively discussed. It also allows for greater flexibility in managing community contributions and feedback.
Adresses: #6135
Ref: 
- https://github.com/actions/stale
> Introduce Workflow to Manage Stale Issues

- src/tribler/core/components/watch_folder/tests/test_watch_folder.py
- src/tribler/core/components/watch_folder/watch_folder.py
- src/tribler/core/config/tribler_config_section.py
- src/tribler/core/utilities/path_util.py
- src/tribler/core/utilities/rest_utils.py
- src/tribler/core/utilities/tests/test_path_utils.py
This PR fixes #7794 by adding the following block to check the validity of the path:
```python
if not directory.is_valid():
self._logger.warning(f'Cancelled. Directory is not valid: {directory}.')
return False
```
Where `is_valid` is the following:
```python
def is_valid(self):
""" Check if the path is valid.
Returns: True if the path is valid, False otherwise.
"""
try:
return self.is_file() or self.is_dir()
except OSError:
return False
```
The bulk of this PR consists of tests for previously written code, which might not be part of the fix. However, I think it's acceptable to include these to increase coverage and satisfy the coverage tool.
> Fix OSError: [WinError 123] for the `_check_watch_folder`

- src/tribler/gui/tests/test_tribler_window.py
- src/tribler/gui/tribler_window.py
This PR adds a new test case to the `test_tribler_window.py` file. The test checks that the `on_add_torrent_browse_file` method in the `TriblerWindow` class works correctly. It mocks certain methods and uses patching to simulate user interaction with a file dialog. The test verifies that the appropriate methods are called and asserts their expected behavior.
The code changes in `tribler_window.py` modify the implementation of the `on_add_torrent_browse_file` method. It now handles cases where no filenames are selected from the file dialog, preventing unnecessary processing. Additionally, it resolves each filename to its absolute URI path before appending it to the list of pending URI requests.
These changes improve the functionality and reliability of adding torrent files through browsing …
> Fix "ValueError: relative path can't be expressed as a file URI"

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
- src/tribler/core/utilities/tests/test_utilities.py
- src/tribler/core/utilities/utilities.py
This PR refactors the `parse_magnetlink` function to use `libtorrent.parse_magnet_uri` for parsing magnet links, as it seems safer and more convenient to rely on the native libtorrent parsing mechanism instead of our own.
It is includes:
- Added a new test case for parsing a magnet link with a wrong hash.
- Added a new test case for parsing a magnet link with bytes input.
- Removed two existing test cases that were testing invalid infohashes, as they are no longer needed.
This refactoring was carried out during the work on:
- #7801
> Refactor magnet link parsing logic and add new test cases

- src/tribler/core/components/libtorrent/download_manager/download.py
The code of the `Download.checkpoint()` method contains an incorrect warning. It erroneously warns "Either file does not exist or is not file" when the file exists. It should just be removed.
> Remove incorrect warning "Either file does not exist or is not file (in `Download.checkpoint()`)

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler/core/utilities/tests/test_utilities.py
- src/tribler/core/utilities/utilities.py
This PR fixes #7801 by adding the `unshorten` URI logic before querying HTTP URI.
> Fix ValueError: Can redirect only to http or https

- .github/workflows/application_tester.yml
- scripts/application_tester/README.md
- scripts/application_tester/requirements.txt
While fixing the application tester jobs on Jenkins, I found that some dependencies need to be installed to run the application tester from the Tribler repo application tester code. This is a subset of Tribler dependencies.
Several dependencies are required because of the application tester code dependence on `TriblerConfig` class.
Earlier PR https://github.com/Tribler/tribler/pull/7824 was used to test if application tester-specific dependencies are installed during tests. It was done by adding an extra dependency `requests==2.31.0` and using that dependency in the application tester code. The test is successful and the action run for that is available [here](https://github.com/Tribler/tribler/actions/runs/7555493318/job/20570601421#step:10:14).
> Add dependencies for application tester to run

- .github/workflows/second_reviewer.yml
- doc/contributing.rst
This pull request introduces a new GitHub Actions workflow titled "Second Reviewer Assignment." The primary objective of this workflow is to automate the process of assigning a second reviewer to pull requests when required, as part of our tie-breaker mechanism in code review processes.
1. **Trigger Condition**: The workflow is triggered when a label named `PR: second reviewer` is added to a pull request. It is designed to only respond to this specific label, ensuring that the action is executed intentionally and in the appropriate context.
2. **Fetching Reviewers**: The workflow fetches the list of potential reviewers from the 'reviewers' team within the 'Tribler' GitHub organization. This is done using the `actions/github-script` action with a custom script.
3. **Reviewer Assignment …
> Add `second_reviewer.yml`

- src/tribler/core/components/database/db/layers/knowledge_data_access_layer.py
While writing the follow-up for KnowledgeCommunity in [#6214](https://github.com/Tribler/tribler/issues/6214), I realized that the order of attributes in the `SimpleStatement` could be changed to appear more natural, following the (subject, predicate, object) notation.
Ref:
- https://en.wikipedia.org/wiki/Semantic_triple
> Refactor SimpleStatement class in knowledge_data_access_layer.py

- .pylintrc
- requirements-test.txt
This PR adds the `pylint-pytest` plugin to the `.pylintrc` file, enabling additional checkers for pytest. It also includes the `pylint-pytest` package in the `requirements-test.txt` file, ensuring it is installed when running tests.
The necessity of adding this plugin emerged from the notable discussion in #7764, where @drew2a proposed the use of `pylint-pytest` and @qstokkink supported the idea:
>Just to repeat - myself and the docs - adding a "name" is not the only way to resolve this. Secondarily, this has nothing to do with Pylint, other than that it will also tell you the same thing. I like the idea of adding pylint-pytest though.
Ref:
- https://github.com/Tribler/tribler/pull/7764#pullrequestreview-1774459402
- https://github.com/pylint-dev/pylint-pytest
> Add pylint-pytest plugin

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
- src/tribler/core/components/libtorrent/tests/test_torrent_def.py
- src/tribler/core/components/libtorrent/torrentdef.py
Fixes https://github.com/Tribler/tribler/issues/7836
The downloads response was not JSON serializable because the name was still being returned as bytes in case of serialization of name from torrent def of instance `TorrentDefNoMetainfo`. This PR fixes the issue.
> Fix TorrentDefNoMetainfo.get_name_utf8() to return string

- src/tribler/core/utilities/tests/test_unicode.py
While working on https://github.com/Tribler/tribler/issues/7823 I became suspicious that `recursive_unicode` was not functioning correctly. To confirm this, I wrote tests and found that the function works as expected. This PR includes these tests.
> Add tests for `recursive_unicode` function

- src/tribler/core/components/database/db/orm_bindings/torrent_metadata.py
- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
While working on #7823  I realized that there is one instance of dead code and one instance of duplicated code in get_torrent_info, both of which have been removed in this PR, along with disputing comments.
> Refactor TorrentInfoEndpoint to fix JSON encoding issue

- .github/workflows/vars/pytest.env
- src/tribler/core/conftest.py
- src/tribler/gui/tests/conftest.py
This PR fixes #7753 by disabling forced garbage collections for tunnel tests and for GUI tests.
There is a possibility that GUI tests may become less stable. If this happens, we should consider reinstating the `ensure_gc` for them. It is uncertain because `ensure_gc` was an experimental feature added when our test suite was quite unstable. Now that it is stable, we can gradually disable experimental features that were implemented to stabilize the test suite.
Ref:
- #7542
> Update pytest configuration to include the `--forced-gc` option

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/tests/conftest.py
- src/tribler/core/components/libtorrent/tests/test_download.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
With PR https://github.com/Tribler/tribler/pull/7842 merged, it raised a bug in creating TorrentDefNoMetainfo object while doing metainfo check. The metainfo check failed with the following stacktrace.
```python
[tribler-gui PID:1197156] 2024-01-24 14:13:33,359 - ERROR <error_handler:100> ErrorHandler.core_error(): 'str' object has no attribute 'decode'
File "/home/user/tribler/src/tribler/core/components/restapi/rest/rest_manager.py", line 53, in error_middleware
response = await handler(request)
File "/home/user/tribler/pyenv39/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "/home/user/tribler/src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py", line 131, in …
```
> Fix error on downloading magnetlink

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler/core/components/socks_servers/socks5/tests/test_server.py
- src/tribler/core/components/version_check/tests/test_versioncheck.py
- src/tribler/core/components/version_check/versioncheck_manager.py
- src/tribler/core/utilities/aiohttp/aiohttp_utils.py
- src/tribler/core/utilities/aiohttp/exceptions.py
- src/tribler/core/utilities/aiohttp/tests/test_aiohttp_utils.py
- src/tribler/core/utilities/tests/test_utilities.py
- src/tribler/core/utilities/utilities.py
While investigating #7671 I found all the places that use the construction `async with ClientSession(...) as session:` and consolidated them into a single place to handle `ServerConnectionError, ClientResponseError, SSLError, ClientConnectorError, asyncio.TimeoutError` with a guarantee.
Unfortunately, it turns out that the issue that led to the reopening of #7671 was caused by a completely different case.
However, I think this refactoring is worthwhile (though it is up to the reviewer to decide).
A new file named `aiohttp_utils.py` has been created. The functions `query_uri` and `unshorten` have been placed in this file.
> Refactoring `query_http_uri`

- doc/requirements.txt
This PR fixes #7814 by updating dependencies in `doc/requirements.txt`:
- Updated aiohttp to version 3.9.1
- Updated aiohttp_apispec to version 2.2.3
- Updated pydantic to version 1.10.14
- Updated pygments to version 2.17.2
- Updated sphinx to version 7.1.2
- Updated sphinx_rtd_theme to version 2.0.0
- Updated sphinxcontrib-httpdomain to version 1.8.1
- Updated sphinxcontrib-openapi to version 0.8.3
- Updated configobj to version 5.0.8
> Update dependencies in `doc/requirements.txt`

- src/tribler/gui/core_manager.py
- src/tribler/gui/tests/test_core_manager.py
This PR adds conversion to hex for the error codes.
It will help in investigating issues like #7855, as we will see the hex representation of the error code. This makes it easier to search for the error, especially in the case of Windows. For *nix systems, this change is harmless.
Related issue: #7863
> Conversion of error codes to hex for error message formatting.

- src/tribler/core/sentry_reporter/sentry_reporter.py
- src/tribler/core/sentry_reporter/sentry_tools.py
- src/tribler/core/sentry_reporter/tests/test_sentry_reporter.py
- src/tribler/core/sentry_reporter/tests/test_sentry_tools.py
This PR disables (and removes) the parse code output logic introduced in 
- #7066
The reason for this change is that we now have an error code returned along with the CoreCrashedError, making the parsing of core output unnecessary. `CoreCrashedError` can now be grouped by the error code, which was previously impossible.
While the feature for parsing code output could be improved, it requires more stringent logging rules, which were not supported by team members (see discussion in #7861).
> Sentry: Disable parse code output

- src/tribler/core/components/libtorrent/conftest.py
- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/download_manager/download_state.py
- src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/components/libtorrent/tests/test_download.py
- src/tribler/core/components/libtorrent/tests/test_download_state.py
- src/tribler/gui/debug_window.py
- src/tribler/gui/qt_resources/mainwindow.ui
- src/tribler/gui/widgets/downloadsdetailstabwidget.py
- src/tribler/gui/widgets/downloadspage.py
- src/tribler/gui/widgets/downloadwidgetitem.py
This PR fixes #7817 by changing the function to the following:
```python
def get_all_time_ratio(self) -> float:
if not self.lt_status or not self.all_time_download:
return 0
return self.all_time_upload / self.all_time_download
```
> Fix `DownloadState.get_ratio()`

- scripts/application_tester/main.py
- scripts/application_tester/tribler_apptester/executor.py
- scripts/application_tester/tribler_apptester/tests/test_executor.py
Fixes https://github.com/Tribler/tribler/issues/7847 caused by of port already in use issue.
> Fix application tester re-run failure 

- src/tribler/core/components/content_discovery/community/tests/test_content_discovery_community.py
- src/tribler/core/components/database/db/serialization.py
- src/tribler/core/components/database/db/store.py
- src/tribler/core/components/database/db/tests/test_serialization.py
- src/tribler/core/components/database/restapi/database_endpoint.py
This PR closes #7808 by removing code related to `num_entries`, which are leftovers from #7669.
The PR involves refactoring, specifically the removal of unused code.
> Remove code related to `num_entries`

- src/tribler/core/utilities/slow_coro_detection/patch.py
- src/tribler/core/utilities/slow_coro_detection/tests/test_slow_coro_detection.py
- src/tribler/core/utilities/slow_coro_detection/watching_thread.py
This PR fixes #7784 by downgrade logging of "slow coro detection"  to `warning` level.
> Downgrade "slow coro detection"  to `warning` level

- scripts/seedbox/README.md
- scripts/seedbox/requirements.txt
- scripts/seedbox/seeder.py
This PR resurrects the seedbox that was removed in 
- #7726 
Previously, it consisted of two parts:
1. A BitTorrent seedbox that seeds files using the BitTorrent protocol.
2. A channel disseminator for propagating metadata to the Tribler network.
Now, due to  #7669 the second part is no longer necessary. However, the first part could still be useful for our further work with metadata retrieval.
> Add `seeder.py`

- scripts/application_tester/tribler_apptester/actions/change_anonymity_action.py
- scripts/application_tester/tribler_apptester/actions/change_download_files_action.py
- scripts/application_tester/tribler_apptester/actions/explore_download_action.py
- scripts/application_tester/tribler_apptester/actions/remove_download_action.py
- src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler/core/components/libtorrent/tests/test_torrent_def.py
- src/tribler/core/components/libtorrent/torrentdef.py
- src/tribler/gui/tests/test_downloadspage.py
- src/tribler/gui/tests/test_gui.py
- src/tribler/gui/widgets/downloadspage.py
This PR fixes #7360
The list of optimizations includes:
1. Backend: Removal of the `get_files` parameter (as it is no longer used).
2. Backend: Optimization of querying for a specific infohash.
3. Frontend: Splitting the requests for downloads into two categories: one for selected downloads and another for non-selected downloads. Extended information like pieces and files is requested only for selected downloads.
4. Frontend: The logic for receiving data was conceptually rewritten to allow for partial updates of downloads. Now, it is possible to update just a single download, whereas previously, updating all downloads was mandatory. This opens up possibilities for further improvements.
> Optimize requests for downloads

- src/tribler/core/components/torrent_checker/torrent_checker/tests/test_torrentchecker.py
- src/tribler/core/components/torrent_checker/torrent_checker/torrent_checker.py
This PR removed the torrent checks on torrents of the user channel. Since channels are removed, it does not make sense to keep these checks anymore. Besides, for a large metadata database (~5GB), the query to select torrent from user channel is pretty slow (161.362 seconds). See log below.
```
[tribler-core PID:10196] 2024-02-02 23:21:52,505 - WARNING - tribler.core.utilities.pony_utils(268) - Long db_session detected.
Session info:
Thread: 'MainThread'
db_session duration: 161.362 seconds
db_session waited for the exclusive lock for 0.000 seconds
db_session held exclusive lock for 0.000 seconds
The db_session stack:
File "C:\Users\tribler\PycharmProjects\tribler\venv8\lib\site-packages\ipv8\taskmanager.py", line 25, in interval_runner
await task(*args)
File …
```
> Remove torrent checking for channel torrents

- src/tribler/core/components/socks_servers/socks_servers_component.py
- src/tribler/core/components/socks_servers/tests/test_socks_servers_component.py
This PR adds socks5 server ports to the reporter. Having this information will help to recognize the Network errors like [this](https://github.com/Tribler/tribler/issues/7759) by comparing the ports.
Here is how it looks on the report:
> Add SOCKS5 ports to sentry reporter

- src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/components/libtorrent/restapi/tests/test_downloads_endpoint.py
- src/tribler/core/components/restapi/restapi_component.py
- src/tribler/core/start_core.py
- src/tribler/gui/widgets/downloadsdetailstabwidget.py
- src/tribler/gui/widgets/downloadwidgetitem.py
This PR involves refactoring of the `get_downloads` function. It removes unused code, some of which is outdated (VOD), and some of which existed because `TunnelCommunity` was not created in GUI test mode. Since there seems to be no issue with creating `TunnelCommunity` in GUI test mode, this PR enables this feature and removes the obsolete code.
Previous PR:
- #7878
> Remove unused code from the `DownloadsEndpoint.get_downloads()` function

- src/tribler/core/components/socks_servers/socks5/connection.py
- src/tribler/core/components/socks_servers/socks5/tests/test_connection.py
- src/tribler/core/components/tunnel/community/dispatcher.py
- src/tribler/core/components/tunnel/tests/test_dispatcher.py
Fixes #7759 
On Windows, calling self.transport.close() can raise a CancelledError. This is because the transport is still in the event loop's transport map, and the event loop will call the transport's connection_lost method, which will call self.close() again.
This time, the transport is None, so the method will return immediately.
> Fix network name is no longer available error

- src/tribler/core/components/tunnel/tunnel_component.py
The minimum number of circuits is currently not being respected, and is always set to 1. That means if you lose that one circuit (e.g. because you only have 1 download), the download will stop completely.
> Fix for incorrect tunnel settings

- src/tribler/core/components/content_discovery/community/content_discovery_community.py
- src/tribler/core/components/content_discovery/community/tests/test_content_discovery_community.py
There are two issues addressed in this PR:
1. The request parameters included a deprecated parameter `exclude_deleted`. This parameter is popped out when doing the actual search on the metadata store now.
2. The `metadata_type` in the request parameter is received as string `'300'` which on conversion to json was turning it to list `[3, 0, 0]`. Since channels are removed, there is only one metadata type which is a single string, a simple integer conversion should be sufficient if the value is of string type.
Out of scope of this PR:
1. This PR does not address removing the deprecated parameter `exclude_deleted` from the remote search endpoint call from the GUI side.
2. Still the search query processing logic checks if the metadata_type is either an integer or list of integers. Since there …
> Fix remote search

- src/tribler.sh
Sometimes it is desirable to run multiple instances of Tribler while developing or testing community logic. Running multiple instances of Tribler with a custom community ID helps to test your community logic in isolation while still ensuring there are no runtime errors.
The PR introduces an environment variable called `DEV_MODE` which if set to `True` (case-insensitive), allows running multiple instances of Tribler on *nix environment. If the environment variable is not set, there is no change on the normal Tribler execution and prevents multiple instances of Tribler as expected.
When this feature is enabled (by setting DEV_MODE=True), the state directory for each subsequent Tribler is organized in this manner:
- First instance: `$HOME/.Tribler`  <-- default instance
- Second instance: …
> Add dev mode to enable running multiple Tribler instances

- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/socks_servers/socks5/udp_connection.py
- src/tribler/core/components/tunnel/community/tunnel_community.py
- src/tribler/core/components/tunnel/tests/test_triblertunnel_community.py
- src/tribler/gui/debug_window.py
This PR fixes various small tunnel related issues, including a couple of things related to circuit management:
* Metainfo downloads aren't being filtered out in `monitor_downloads`. This can lead to having too many circuits. Additionally, hidden services is currently joining hidden swarms for metainfo downloads, firing off a whole bunch of logic for a download that's going to disappear in a couple of minutes.
* Often (depending on the timing of `monitor_downloads`) when removing a download, it first announces itself to the DHT.
* Ensure we always have at least `min_circuits` for the default hop count. This avoids last minute circuit creation, and also makes more sense since the `TorrentChecker` will be constantly needing circuits anyway.
Other than fixing an issue with the tunnel debug …
> Improved tunnel circuit management

- Dockerfile
- README.rst
- docker-compose.yml
- src/run_tribler_headless.py
- src/tribler/core/components/restapi/rest/rest_manager.py
- src/tribler/core/components/restapi/rest/settings.py
Uses Python base image & add more input args to allow changing the mount directory.
input to the handling of input arguments is much appreciated
Fixes #7563, #7560
> Update Dockerfile to use Python base image and add input args

- src/tribler/core/components/restapi/rest/events_endpoint.py
This ValueError is raised at the shutdown stage so suppressing the error is acceptable.
Fixes #7905
> Suppress ValueError on EventsEndpoint at shutdown

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
Logging Download ATP outputs huge `resume_data` which is not much useful. This PR keeps the log line with same log level (info) but without `resume_data`.
> Do not show resume_data on logging Download ATP

- src/tribler/core/components/socks_servers/socks5/connection.py
- src/tribler/core/components/socks_servers/socks5/tests/test_connection.py
- src/tribler/core/components/tunnel/community/dispatcher.py
- src/tribler/core/components/tunnel/tests/test_dispatcher.py
Porting PR https://github.com/Tribler/tribler/pull/7889 to `release/7.13` for `7.13.2` release.
> Fix network name is no longer available error on 7.13

- doc/contributing.rst
> Update PR merging policy to use "merge –no–ff" instead of "rebase + merge –no–ff"

- requirements-core.txt
- scripts/experiments/tunnel_community/speed_test_e2e.py
- scripts/experiments/tunnel_community/speed_test_exit.py
- src/tribler/core/components/conftest.py
- src/tribler/core/components/ipv8/eva/payload.py
- src/tribler/core/components/ipv8/ipv8_component.py
- src/tribler/core/components/ipv8/settings.py
- src/tribler/core/components/knowledge/community/knowledge_payload.py
- src/tribler/core/components/socks_servers/socks5/connection.py
- src/tribler/core/components/socks_servers/socks5/server.py
- src/tribler/core/components/socks_servers/socks5/tests/test_server.py
- src/tribler/core/components/socks_servers/socks5/tests/test_udp_connection.py
- src/tribler/core/components/socks_servers/socks5/udp_connection.py
- src/tribler/core/components/socks_servers/socks_servers_component.py
- src/tribler/core/components/tunnel/community/dispatcher.py
- src/tribler/core/components/tunnel/community/payload.py
- src/tribler/core/components/tunnel/community/tunnel_community.py
- src/tribler/core/components/tunnel/tests/test_full_session/test_tunnel_community.py
- src/tribler/core/components/tunnel/tests/test_triblertunnel_community.py
This PR enables the rust endpoint for anonymous downloads.
Closes https://github.com/Tribler/tribler/issues/7684.  Closes https://github.com/Tribler/tribler/issues/4567. Closes https://github.com/Tribler/tribler/issues/4459.
Note that this PR also changes the tunnel community ID, as IPv8 breaks the tunnel protocol by adding (partial) IPv6 support.
> Enable rust endpoint for anonymous downloads

- src/tribler/core/utilities/process_manager/process.py
- src/tribler/core/utilities/process_manager/tests/test_process.py
- src/tribler/gui/event_request_manager.py
Under the current assumption that the GUI process spawns the Core process, the core process is selected from the process database with rowid higher than the rowid of the GUI process. This avoid GUI to select any previous core process (given the same PID as in the case of Flatpak) that did not finish properly (ie. exit_code or finished is None).
The CoreConnectTimeoutError was raised by GUI trying to connect to the previous instance of Core Port which is likely not available at the time of checking which esults in failure to connect to the Core within the timeout period.
Fixes https://github.com/Tribler/tribler/issues/7137
> Fix CoreConnectTimeoutError

- src/tribler/gui/core_manager.py
- src/tribler/gui/tests/test_core_manager.py
Based on the current architecture, the GUI spawns the core process and maintains its lifecycle. However, that is not always the case for some unclear reasons as reported on user sentry reports (links below). Evident from the reports is that there is still a core process running in the background which prevents any successful attempt to run Tribler again unless the core process is somehow terminated. This leads to bad user experience with repeated crash reports.
The purpose of this PR is to change how we handle the cases where there is an existing core process. Instead of crashing on user that there is an existing core process with which the GUI cannot talk to and simply crash. With the changes proposed on this PR, GUI shall try to connect to such existing core process, however, would not …
> Fix core crashed error because of existing running core

- src/tribler/core/components/reporter/exception_handler.py
- src/tribler/core/components/reporter/reported_error.py
- src/tribler/core/components/reporter/reporter_component.py
- src/tribler/core/components/reporter/tests/test_exception_handler.py
- src/tribler/core/components/reporter/tests/test_reported_error.py
- src/tribler/core/components/restapi/rest/events_endpoint.py
- src/tribler/core/components/restapi/rest/tests/test_events_endpoint.py
- src/tribler/core/components/restapi/restapi_component.py
- src/tribler/gui/core_manager.py
- src/tribler/gui/core_restart_logs.py
- src/tribler/gui/dialogs/feedbackdialog.py
- src/tribler/gui/error_handler.py
- src/tribler/gui/event_request_manager.py
- src/tribler/gui/tests/test_core_manager.py
- src/tribler/gui/tests/test_core_restart_logs.py
- src/tribler/gui/tests/test_error_handler.py
This PR addresses
- https://github.com/Tribler/tribler/issues/7647
Here is an example of Sentry report sent:
- https://sentry.tribler.org/organizations/tribler/issues/2500/?project=10&query=&referrer=issue-stream&stream_index=0
The following additional entry is added to the report:
```
core_restart_logs: [
CoreRestartLog(pid=1232211, started_at='2023-11-27 14:36:14', uptime='0:00:11',  time_to_shutdown='0:00:04',  exit_code=1, exit_status='0'), 
CoreRestartLog(pid=1232278, started_at='2023-11-27 14:36:25', uptime='still running',  time_to_shutdown='unknown',  exit_code=None, exit_status='None')
],
```
> Improve Core Process Error Handling

- requirements-core.txt
Fixes an issue when the IPv8 port is already occupied, in which case it now retries using port+1 until successful.
> Update ipv8-rust-tunnels to 0.1.17

- src/run_tribler.py
- src/tribler/core/utilities/asyncio_fixes/finish_accept_patch.py
- src/tribler/core/utilities/asyncio_fixes/tests/test_finish_accept_patch.py
This PR fixes #7759 by applying a monkey patch for the `BaseProactorEventLoop._start_serving` method on the `win32` platform, as shown in [https://github.com/python/cpython/issues/93821](https://togithub.com/python/cpython/issues/93821).
The accompanying tests cover the primary patched function that replaces `BaseProactorEventLoop._start_serving`, but the second function, `IocpProactor.accept`, is not covered as writing a full coverage test for it is a bit unpractical and unnecessary.
> A patch that fixes OSError "[WinError 64] The specified network name is no longer available"

- .github/actions/windows_dependencies/action.yml
Currently, GUI tests GitHub action refuses to work due to the following error:
```
These files don't exist: cached-bin/libsodium-1.0.18/libsodium.dll
Run C:\msys64\usr\bin\wget.exe -q https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-msvc.zip
C:\msys64\usr\bin\wget.exe -q https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-msvc.zip
7z x libsodium-1.0.18-msvc.zip
dir %RELEASE_FOLDER% /ad /b /o-n > latest_release_file
set /p latest_release= < latest_release_file
echo Latest release: %latest_release%
if not exist "cached-bin\libsodium-1.0.18" mkdir "cached-bin\libsodium-1.0.18"
copy %RELEASE_FOLDER%\%latest_release%\dynamic\libsodium.dll .\cached-bin\libsodium-1.0.18\libsodium.dll
shell: C:\Windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
env: …
```
> Fix GUI test GitHub action on Windows by replacing wget with curl

- doc/restapi/state.rst
This PR fixes #7916 by removing the `state.rst` file.
> Remove state information from REST API documentation

- src/tribler/core/components/restapi/rest/tests/test_rest_manager.py
This PR fixes #7725 by expecting ClientOSError in addition to ServerDisconnectedError when aiohttp server disconnects. It looks like there are some internal indeterminism in aiohttp regarding what error will be raised here.
> Fix flaky test by expecting both ClientOSError and ServerDisconnectedError when server disconnects

- src/tribler/core/utilities/process_manager/manager.py
- src/tribler/core/utilities/process_manager/tests/test_manager.py
This PR fixes #7931 by handling all `OperationalError` exceptions before `DatabaseError` exceptions, and by suppressing possible `PermissionError` exceptions when trying to remove the database filw after the `DatabaseError`
> Process manager should not attempt to unlink the processes database file in case of OperationalError

- MANIFEST.in
- pyproject.toml
- setup.py
- src/run_tribler.py
This PR is part of an effort to streamline binary creation for Tribler. It adds a setup.py script to build a Python wheel package. Here is how the wheel can be built and installed.
```bash
#!/bin/bash
python3 -m pip install --upgrade setuptools wheel
python3 -m pip install build
rm -rf dist  
python3 -m build
python3 -m pip uninstall -y tribler
python3 -m pip install dist/*.whl
python3 -m tribler.run
```
Note: `setup.py` has duplicated dependencies comparing with `requirements.txt`. It is left as it is. Initial thought to parse requirements.txt to retrieve the dependencies and set in setup.py but it seems it is not a recommended approach. Therefore, it is left unchanged.
> Create setup.py and fix building wheel

- README.rst
- build.py
- build/win/makedist_win.bat
- requirements-build.txt
- setup.py
This PR aims to transition from PyInstaller to Cx_Freeze for generating Windows binaries. The motivation for this change is detailed [here](https://github.com/Tribler/tribler/issues/5979).
Although Cx_Freeze supports MSI installer generation (refer to the build.py documentation in the PR), this feature is not utilized. Instead, the existing NSIS-based installation process is maintained, with the switch only affecting the executable creation, previously managed by PyInstaller.
It's important to note that this PR exclusively alters the Windows build process. For Linux and MacOS, PyInstaller remains the tool of choice for binary creation. This decision stems from the absence of malware misidentification issues and the significantly smaller binary size produced by PyInstaller compared to …
> Build windows binary using Cx_Freeze

- src/tribler/core/components/libtorrent/download_manager/download.py
This PR addresses potentially dangerous behavior where an alert object is stored in the `future`, which could exceed its time to live since it is valid only until the next `pop_alerts` call.
Refs: 
- https://libtorrent.org/reference-Session.html#pop-alerts-wait-for-alert-set-alert-notify
Related to 
- #7886
> Modify `future_setter` to not keep an alert object

- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
> Fix "ValueError: Can redirect only to http or https" in query_http_uri

- src/tribler/core/utilities/pony_utils.py
This PR fixes #7675. When the specified threshold is zero, not TriblerDbSession should issue a warning every time.
> Fix flaky test `test_patched_db_session_default_duration_threshold`

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
- src/tribler/gui/widgets/downloadspage.py
This PR fixes #7770. Now, all downloads are displayed immediately without any artificial delay.
The PR extracts the potentially blocking part of `DownloadManager.start_handle` into a separate method, `DownloadManager._async_add_torrent`, and runs the potentially blocking second method as a separate task. As a result, now all checkpoints load almost instantly and can be immediately presented to a user.
> Immediately show all downloads on Tribler start

- .github/workflows/vars/pytest.env
- src/tribler/core/components/libtorrent/conftest.py
- src/tribler/core/conftest.py
This PR fixes #7880 by disabling forced garbage collection for all core tests. Instead, forced garbage collection is applied only to the libtorrent component.
> Update pytest arguments and remove forced garbage collection

- build.py
- build/win/makedist_win.bat
- setup.py
- cx_Freeze build is missing openssl DLLs on windows. This PR adds these DLLs during the build process.
- It fixes the issue with building binaries and wheel using the setup.py script. Cx_Freeze does not support building wheels so build script is made conditional.
> Fix binary build

- src/tribler/core/components/metadata_store/db/store.py
- src/tribler/core/components/torrent_checker/torrent_checker/tests/test_torrentchecker.py
- src/tribler/core/components/torrent_checker/torrent_checker/torrent_checker.py
This PR fixes #7954 by adding the exact SQL condition `has_data = 1` to queries to the `TorrentState` table.
It allows SQLite query optimizer to use a partial index on `TorrentState` table, defined as
```sql
CREATE INDEX IF NOT EXISTS idx_torrentstate__last_check__partial
ON TorrentState (last_check, seeders, leechers, self_checked)
WHERE has_data = 1;
```
As a result, the speed of queries issued by the torrent checker icreases drastically, from 4 seconds to 0.04 seconds.
> Fix slow database queries, by using partial index `idx_torrentstate__last_check__partial`

- src/tribler/gui/tests/test_utilities.py
- src/tribler/gui/utilities.py
- src/tribler/gui/widgets/tablecontentdelegate.py
- src/tribler/gui/widgets/tablecontentmodel.py
This PR adds torrent information (such as size, health, created) to a snippet.
> Add torrent information to a snippet

- MANIFEST.in
- README.rst
- build.py
- build/win/makedist_win.bat
- pyproject.toml
- requirements-build.txt
- setup.py
- src/run_tribler.py
This PR cherry-picks the following PRs to `release/7.14` branch from main:
- https://github.com/Tribler/tribler/pull/7935
- https://github.com/Tribler/tribler/pull/7936
- https://github.com/Tribler/tribler/pull/7949
These changes are made to support building binaries using CxFreeze instead of PyInstaller on Windows. The additional details can be found on the linked PRs and their associated issues.
**Note:** The last commit is not part of the cherry-picked commits but additional pylint fixes.
> Fix Release build on 7.14 branch

- src/tribler/core/utilities/slow_coro_detection/tests/test_slow_coro_detection.py
- src/tribler/core/utilities/slow_coro_detection/utils.py
- src/tribler/core/utilities/slow_coro_detection/watching_thread.py
This PR fixes the logic of stack tracing for coroutines.
Python asyncio logic uses some optimizations when handling tasks and replaces the reference to the `Task._wakeup()` method with instances of C classes `TaskWakeupMethWrapper` or `task_wakeup`, depending on the Python version. It should be taken into account when determining whether the current handle relates to a task.
Also, the PR shows the exact duration for long coroutine steps.
> Fix coroutine stack tracking

- src/tribler/core/sentry_reporter/sentry_reporter.py
- src/tribler/core/sentry_reporter/sentry_scrubber.py
- src/tribler/core/sentry_reporter/sentry_tools.py
- src/tribler/core/sentry_reporter/tests/test_sentry_scrubber.py
- src/tribler/core/sentry_reporter/tests/test_sentry_tools.py
This PR fixes #7966.
* The first commit reconfigures Sentry logs to be consistent with Tribler logs and allows seeing Sentry errors.
* The second commit stops making substitutes to empty substrings in the middle of other strings.
> Fix sentry scrubber and logs

- src/run_tribler.py
- src/tribler/core/utilities/linecache_patch.py
- src/tribler/core/utilities/tests/test_linecache_patch.py
When Tribler binary encounters an error, it currently displays traceback with file names and line numbers only, without the actual source lines, like that:
```
File "C:\dev\tribler\src\run_tribler.py", line 124, in <module>
File "C:\dev\tribler\src\run_tribler.py", line 120, in main
File "C:\dev\tribler\src\tribler\gui\start_gui.py", line 77, in run_gui
File "C:\dev\tribler\src\tribler\gui\tribler_window.py", line 236, in __init__
The above exception was the direct cause of the following exception:
File "C:\dev\tribler\src\tribler\gui\utilities.py", line 455, in trackback_wrapper
File "C:\dev\tribler\src\tribler\gui\utilities.py", line 452, in trackback_wrapper
File "C:\dev\tribler\src\tribler\gui\tribler_window.py", line 361, in …
```
> Show Tribler source lines in traceback when running Tribler binary

- src/tribler/gui/qt_resources/mainwindow.ui
- src/tribler/gui/tribler_window.py
Fixes #7965
The bug is a combination of two facts:
1. QT dependencies upgrade made here: https://github.com/Tribler/tribler/pull/7944
2. Using the "trick" for hiding a menu arrow: https://github.com/Tribler/tribler/blob/03adf6a49744bad2a5e914324e713038d66bf10d/src/tribler/gui/qt_resources/mainwindow.ui#L340
The solution is to change `QPushButton` to `QToolButton` as it seems to work a bit more correctly in our specific case with hiding the menu indicator:
```css
QToolButton#add_torrent_button {
border-style: outset;
border-width: 1px;
border-radius: 15px;
border-color: grey;
margin-left: 15px;
padding-left: 10px;
margin-right: 10px;
}
QToolButton::menu-indicator {
image: none;
width: 0px;
}
```
Please note that the first commit is just a reformatting of the entire `mainwindow.ui` to …
> Fix corrupted "add torrent" layout

- src/run_tribler.py
- src/tribler/core/utilities/asyncio_fixes/proactor_recvfrom_patch.py
- src/tribler/core/utilities/asyncio_fixes/tests/test_proactor_recvfrom_patch.py
This PR fixes #7972. This is a backport of [https://github.com/python/cpython/pull/32011](https://togithub.com/python/cpython/pull/32011).
You can add the following two lines to the **server.py** example from #7972 and check that it works as expected with multiple clients:
```
from tribler.core.utilities.asyncio_fixes import proactor_recvfrom_patch
proactor_recvfrom_patch.apply_proactor_recvfrom_patch()
```
> Fixes #7972: UDP server stops accepting datagrams from any clients after a single client disconnects

- src/tribler/gui/widgets/search_results_model.py
- src/tribler/gui/widgets/tablecontentdelegate.py
- src/tribler/gui/widgets/tablecontentmodel.py
This PR disables the torrent grouping feature based on torrent names as was requested by @synctext.
The feature has been introduced in 
- #7025
> Remove the torrent grouping feature based on names

- src/run_tribler.py
- src/tribler/core/sentry_reporter/sentry_reporter.py
- src/tribler/core/sentry_reporter/sentry_scrubber.py
- src/tribler/core/sentry_reporter/sentry_tools.py
- src/tribler/core/sentry_reporter/tests/test_sentry_reporter.py
- src/tribler/core/sentry_reporter/tests/test_sentry_scrubber.py
- src/tribler/core/sentry_reporter/tests/test_sentry_tools.py
- src/tribler/core/utilities/asyncio_fixes/proactor_recvfrom_patch.py
- src/tribler/core/utilities/asyncio_fixes/tests/test_proactor_recvfrom_patch.py
- src/tribler/gui/dialogs/feedbackdialog.py
This PR cherry-picks important fixes from the main branch to the release branch.
* Adding Sentry tag that allows distinguishing errors of 32-bit and 64-bit Tribler versions on Windows;
* The fix for a problem when reports were undelivered to Sentry from some user machines (while declared as "reported");
* The fix for the UDP server hung.
> Cherry-pick important fixes to the release branch

- src/tribler/core/components/libtorrent/restapi/tests/test_torrentinfo_endpoint.py
- src/tribler/core/components/libtorrent/restapi/torrentinfo_endpoint.py
Updated the TorrentInfoEndpoint class to catch OSError, which includes FileNotFoundError and PermissionError, while decoding a torrent file. This ensures that the server responds with an appropriate 500 error message when such issues occur.
Fixes #7974
> Improved error handling in torrent info endpoint

- .github/workflows/!PR.yml
The workflow now includes steps to find and update comments on pull requests created by outside collaborators. If the label check fails and the user doesn't have required permissions, a comment is added or updated to instruct how to trigger full checks. This enhances communication with contributors and provides clear instructions for triggering additional checks when necessary.
Example:
Ref:
- https://github.com/marketplace/actions/create-or-update-comment
> Add comment handling for PRs from outside collaborators

- build/mac/makedist_macos.sh
This PR adds code signing for MacOS build.
The sign message which includes the Signer's Identity is to be passed via environment variable during the build process.
The final dmg created after code signing works well on earlier version of MacOS without issues. However, for the newer version of the macos, to pass through the gatekeeper, the DMG and included executables needs to be notarized using notary tool. At the moment, the notarization is not passing yet.
The fix for notarization is outside the scope of this PR. That will be addressed as part of the build script pipeline in Jenkins as notarization can take up to 30 mins to complete and requires setting up key profiles.
> Add codesign for macos build

- src/tribler/core/components/libtorrent/download_manager/download.py
- src/tribler/core/components/libtorrent/tests/test_download.py
> Handle corupted pieces in a handle status

- src/tribler/core/upgrade/tests/test_version_manager.py
- src/tribler/core/upgrade/version_manager.py
Introduced exception handling to manage potential errors during the loading of the version history file. If a VersionError is encountered, it logs a warning and attempts to remove the corrupted version file. In case of an OSError during this removal process, another warning is logged. Additionally, JSONDecodeError is now caught when attempting to load JSON from the file content, raising a VersionError if such an issue occurs. This improves robustness against corrupted or improperly formatted version history files.
Fixes #7920
> Add error handling for version history file loading

- .github/workflows/stale.yml
The stale action used in the workflow has been upgraded from version 8 to version 9. 
Fixes #7994
Ref:
- https://github.com/actions/stale/releases/tag/v9.0.0
>Version 9 of this action updated the runtime to Node.js 20. All scripts are now run with Node.js 20 instead of Node.js 16 and are affected by any breaking changes between Node.js 16 and 20.
> Upgrade stale action to v9

- src/tribler/core/components/libtorrent/download_manager/download_config.py
- src/tribler/core/components/metadata_store/category_filter/category.py
- src/tribler/core/components/metadata_store/category_filter/family_filter.py
- src/tribler/core/components/metadata_store/category_filter/l2_filter.py
- src/tribler/core/components/session.py
- src/tribler/core/logger/logger.py
- src/tribler/core/logger/tests/test_logger.py
- src/tribler/core/tests/test_configparser.py
- src/tribler/core/utilities/install_dir.py
- src/tribler/core/utilities/utilities.py
- src/tribler/gui/start_gui.py
- src/tribler/gui/utilities.py
This PR fixes #8000.
First, it fixes the logic of `is_frozen()` and several functions that return base paths for resources (such as `get_logger_config_path()`).
Second, it fixes an issue with function naming: Currently, in Tribler we have two different functions with the same name `get_base_path()` that return different results:
* One function is defined in `tribler/core/utilities/install_dir.py` and returns "some" base directory; that exact meaning of the directory is different when Tribler runs from sources and when it runs as a binary. It is only used by another function, `get_lib_path()`, which is defined in the same module.
* Another function with the same name `get_base_path()` is defined in `tribler/gui/utilities.py` and returns base directory for GUI-related resources.
To avoid …
> Fix `is_frozen`, `get_core_path()`, `get_gui_path()` when `cx_freeze` is used for building binaries

- src/tribler/core/components/content_discovery/restapi/search_endpoint.py
- src/tribler/core/components/content_discovery/restapi/tests/test_search_endpoint.py
- src/tribler/core/components/database/restapi/database_endpoint.py
- src/tribler/core/components/database/restapi/tests/test_database_endpoint.py
- src/tribler/gui/widgets/search_results_model.py
- src/tribler/gui/widgets/searchresultswidget.py
- src/tribler/gui/widgets/tablecontentmodel.py
Improvements:
- all `to_fts_query` calls have been moved from GUI to Core
Fixes
- Remote search is fixed (it was broken in #7726)
- Content filter is fixed 
Closes #7075
> Refactor search functionality

- src/tribler/gui/tests/test_utilities.py
- src/tribler/gui/utilities.py
- src/tribler/gui/widgets/downloadsdetailstabwidget.py
The function for copying the magnet link has been refactored. The code now is a bit safier.
Fixes #8016
> Refactor magnet link copy function

- src/tribler/gui/qt_resources/mainwindow.ui
- src/tribler/gui/widgets/downloadspage.py
- src/tribler/gui/widgets/settingspage.py
Are you tired of having to resize the columns in the download page all the time? me too...
This PR adds a couple of setting to set column width, for now i prefer to just have it as a "hidden" config option and in future versions we can add it in the UI, and more fancy stuff
____
This is how it looks like with my favorite options, I like the name to be the widest and the progress a bit wider than the default
____
Here is the new setting:
____
My goal is to make small changes as I get myself familiar with the code base, then I would be able to take on some more challenging issues
> Add setting to remember download columns width

- src/tribler/gui/widgets/downloadspage.py
This PR adds a simple way to hide columns in the download table
right clicking in the header `header().customContextMenuRequested,` will show a small menu 
in that menu we have options:
- allow the users to hide the clicked column `header().hideSection(index)`
- restore all hidden columns
> Add a way to hide columns in the download table

- src/tribler/core/components/knowledge/README.md
Introduced a README file for the Knowledge Component. The new documentation provides an overview of the component, including its database schema, operations available to peers, and ER diagram. It also explains the algorithm behind the community's operation and outlines changes made to the UI related to this component. This update aims to improve understanding of how the Knowledge Component functions within the larger system.
It is likely that Knowledge Community will be forgotten for some time before it is removed or modified. Therefore, I'm leaving this extracted documentation for future developers to simplify their learning journey.
Extracted from:
- #6214
- #7837
To see the rendered readme, please follow the link: https://github.com/drew2a/tribler/tree/docs/knowledge/src/tribler/core/co …
> Add README for Knowledge Component

- src/tribler/core/components/database/db/store.py
This PR fixes #8035.
The WAL mode is persistent, so it is necessary to switch it to DELETE mode at least once (see https://www.sqlite.org/wal.html).
After that, it is not strictly necessary to execute `PRAGMA journal_mode = DELETE` again, but executing it is cheap and fast, and consistently executing it every time the connection is open avoids some potential future errors.
> Change the WAL journal mode back to the default DELETE mode

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
Reworked the 'set_proxy_settings' function in the download manager to handle invalid port values more gracefully. The function now attempts to convert the port value to an integer and logs any ValueError exceptions that occur during this process. This prevents crashes when non-integer values are provided for the port. Also, reorganized import statements according to PEP8 guidelines.
Additionally, a new test case 'test_set_proxy_settings_invalid_port' has been added to verify this behavior. It checks if proxy settings are not set when an invalid port number is provided.
Fixes #8014
> Refactor proxy settings and add error handling

- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/core/components/libtorrent/tests/test_download_manager.py
This PR fixes #8040 by checking first whether do server/auth present or not
> Fixes #8040: improved error handling in set_proxy_settings

- src/tribler/core/sentry_reporter/sentry_reporter.py
- src/tribler/core/sentry_reporter/sentry_tools.py
- src/tribler/core/sentry_reporter/tests/test_sentry_reporter.py
- src/tribler/core/sentry_reporter/tests/test_sentry_tools.py
Introduced a new method `_format_breadcrumbs` to handle the formatting of breadcrumbs in `SentryReporter`. This includes removing duplicates and ordering by timestamp. The logic for this has been extracted from the `_before_send` method.
An event example: https://sentry.tribler.org/organizations/tribler/issues/2658/events/b42dc2acdc184c709ab8f9a60367c23e/
This is a post-work of 
- #8034
> Remove duplicates in breadcrumbs

- src/tribler/gui/tribler_window.py
The functionality that was triggered when the search bar was clicked has been removed. 
Fixes #6660
> Remove search bar click event

- src/tribler/gui/widgets/popular/popular_torrents_model.py
The popular torrents model now includes a 'health' column. This change enhances the information provided about each torrent, allowing users to make more informed decisions when selecting torrents.
Closes #6444
> Add health column to popular torrents display

- src/tribler/core/config/README.md
Introduced a README file to provide guidance on how to configure the Tribler instance. The document includes information about the location of the configuration files across different operating systems, structure of the configuration file, and an example on how to modify settings within it.
> Add README for Tribler config

- src/tribler/core/components/database/category_filter/family_filter.py
- src/tribler/core/components/database/database_component.py
- src/tribler/core/components/database/db/orm_bindings/torrent_metadata.py
- src/tribler/core/components/database/db/serialization.py
- src/tribler/core/components/database/restapi/database_endpoint.py
- src/tribler/core/components/libtorrent/download_manager/download_manager.py
- src/tribler/gui/utilities.py
- src/tribler/gui/widgets/settingspage.py
- src/tribler/gui/widgets/tablecontentdelegate.py
All `TODO` `FIXME` and `XXX` comments have been removed. The issue has been created:
- #8056
Fixes #1722
> Remove TODO FIXME and XXX comments

- build/mac/Readme.md
- build/mac/env.sh
- build/mac/makedist_macos.sh
- build/mac/sign_app.sh
- build/mac/sign_dmg.sh
This PR updates the MacOS (app and installer dmg) build signing.
The signing part is extracted to separate scripts from the build script. Further, app and dmg signing are separated.
The build is fully running on mac_mini on Jenkins which removes the dependency on external dependent machines previously used for signing.
Additionally, there is some refactoring done on the build script, extracting the environment variables into a separate file `env.sh`.
Here is a working build from this PR:
https://jenkins.tribler.org/job/Tribler/job/Build/job/Build-macOS/174/
> Update signing script for macos build

- .github/workflows/build.yml
This should fix the failing build of https://github.com/Tribler/tribler/actions/runs/10350852789
(I don't know how this passed on the TriblerExperimental repository, perhaps some cached dependencies?)
> Added missing Ubuntu package

- .ruff.toml
- src/run_tribler.py
- src/tribler/core/components.py
- src/tribler/core/libtorrent/download_manager/download_config.py
- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/core/session.py
- src/tribler/core/versioning/manager.py
- src/tribler/core/versioning/restapi/versioning_endpoint.py
- src/tribler/test_unit/core/versioning/restapi/test_versioning_endpoint.py
- src/tribler/test_unit/core/versioning/test_manager.py
- src/tribler/tribler_config.py
- src/tribler/ui/public/locales/en_US.json
- src/tribler/ui/public/locales/es_ES.json
- src/tribler/ui/public/locales/pt_BR.json
- src/tribler/ui/public/locales/ru_RU.json
- src/tribler/ui/public/locales/zh_CN.json
- src/tribler/ui/src/Router.tsx
- src/tribler/ui/src/config/menu.ts
- src/tribler/ui/src/pages/Settings/Versions.tsx
- src/tribler/ui/src/services/tribler.service.ts
- src/tribler/upgrade_script.py
Fixes #8079
This PR:
- Adds versions and upgrading again.
Notes:
- The `https_certfile` still exists in the main (non-versioned) `state_dir`, other files are again placed in the version's state dir.
- The latest "disk" version (`TO`) _may not be equal_ to the latest release version `version("tribler")`. For example, a version `8.1` may operate from the `8.0` state directory. This is not necessarily pretty but it avoids file copies and renaming.
> Added versioning manager

- .readthedocs.yaml
Fixes #7827
This PR:
- Adds `.readthedocs.yaml` to allow ReadTheDocs to build the docs again.
> Added ReadTheDocs configuration file

- .readthedocs.yaml
Fixes #7827 (again)
This PR:
- Updates `.readthedocs.yaml` to fetch submodules.
I also added `recursive: true`, though this is (currently) not necessary for IPv8.
> Recursively clone submodules for ReadTheDocs

- .github/workflows/build.yml
- build/win/keygen_config.txt
- build/win/makedist_win.bat
Related to #5648
This PR:
- Fixes the Windows build not being signed at all*.
- Updates the build action to strip the "v" out of the tag.
I'm not 100% sure if the paths are correct for GitHub Actions but there is only one way to find out 🙂 
*Ideally, we would have a beter solution (see #5648) but a cheap signature is still better than none at all.
> Added one-time signing keys to windows build

- src/tribler/core/restapi/rest_manager.py
Fixes #6429
This PR:
- Updates `tcp_keepalive` for ALL aiohttp protocols, allowing it to fail with OSError 22.
> Wrap tcp_keepalive to allow OSError 22

- src/tribler/core/restapi/settings_endpoint.py
- src/tribler/tribler_config.py
- src/tribler/ui/src/components/add-torrent.tsx
- src/tribler/ui/src/components/language-select.tsx
- src/tribler/ui/src/config/menu.ts
- src/tribler/ui/src/contexts/LanguageContext.tsx
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/ui/src/i18n/index.ts
- src/tribler/ui/src/lib/utils.ts
- src/tribler/ui/src/models/settings.model.tsx
- src/tribler/ui/src/pages/Settings/Anonymity.tsx
- src/tribler/ui/src/pages/Settings/Bandwidth.tsx
- src/tribler/ui/src/pages/Settings/Connection.tsx
- src/tribler/ui/src/pages/Settings/Debugging.tsx
- src/tribler/ui/src/pages/Settings/General.tsx
- src/tribler/ui/src/pages/Settings/Seeding.tsx
- src/tribler/ui/src/services/tribler.service.ts
Currently, Tribler uses the browser's `localStorage` to store the GUI settings. However, since we're using a default port of 0, the GUI settings are likely to be reset after every restart.
This PR addresses this issue by avoiding the use of `localStorage` and storing the GUI settings alongside the core settings instead.
> Store GUI settings in TriblerConfig

- README.rst
Related to #8096 (split into two PRs)
This PR:
- Updates `README.rst` to be a bit shorter, hipper, and ready for `8.0`.
See the rendered page, here: https://github.com/Tribler/tribler/blob/c17831e3df0f32e8f9afb9f82dfd392d4d6ee88e/README.rst
> Updated README for the 8.0 release

- .github/workflows/pr-npm.yml
- src/tribler/ui/src/pages/Settings/Anonymity.tsx
- src/tribler/ui/src/pages/Settings/Bandwidth.tsx
- src/tribler/ui/src/pages/Settings/Connection.tsx
- src/tribler/ui/src/pages/Settings/Debugging.tsx
- src/tribler/ui/src/pages/Settings/General.tsx
- src/tribler/ui/src/pages/Settings/Seeding.tsx
Fixes #8113
This PR:
- Adds a new PR check that builds the GUI.
- Fixes the return types of the settings pages.
> Fixed npm build

- src/tribler/test_integration/test_anon_download.py
Fixes #8109
This PR:
- Updates the file contents used in `test_anon_download` to be unique, w.r.t. `test_hidden_services`.
> Updated anon download test to have a unique file

- src/tribler/core/components.py
- src/tribler/core/session.py
- src/tribler/core/torrent_checker/torrent_checker.py
- src/tribler/core/user_activity/manager.py
Fixes #8081
This PR:
- Updates the torrent checker to only go up to ~1 metadata request per second.
- Updates the Session's types.
> Reduce torrent checking intensity

- README.rst
- doc/basics/docker.rst
- doc/basics/running.rst
- doc/building/linux.rst
- doc/building/mac.rst
- doc/building/windows.rst
- doc/index.rst
Fixes #8096
This PR:
- Updates the developer documentation for the 8.0 release.
The Docker docs still need to be properly looked at. I'll leave that for later: after the merge of #8108
> Updated development docs for 8.0

- src/tribler/core/libtorrent/download_manager/download_manager.py
Fixes #5900
This PR:
- Adds some additional DHT routers.
See the discussion in #5900: adding DHT routers probably won't increase download speed. However, this does build more resiliency - should any of the servers go offline.
> Added more default DHT routers

- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/core/libtorrent/restapi/libtorrent_endpoint.py
- src/tribler/core/session.py
- src/tribler/test_integration/test_anon_download.py
- src/tribler/test_integration/test_hidden_services.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download_manager.py
- src/tribler/test_unit/core/libtorrent/restapi/test_libtorrent_endpoint.py
Fixes #8060
This PR:
- Updates `DownloadManager.ltsessions` to store futures instead of completed sessions.
> Updated libtorrent session creation to be async

- .github/workflows/build_docker.yml
Fixes #8125 (again, oops)
This PR:
- Fixes env vars in `build_docker.yml` being specified with `=` instead of `:`.
> Fixed wrong YAML syntax in Docker build file

- build/tribler.spec
- src/run_tribler.py
- src/tribler/__init__.py
- src/tribler/core/restapi/webui_endpoint.py
Fixes #8121
This PR:
- Defines an utility function to get the webui path
- Updates pyinstaller tribler.spec to include ui files.
The pyinstaller build created with the changes is verified to work on the Mac mini (Intel) build machine.
> Fixed mac build

- build/setup.py
- build/tribler.spec
- build/win/build.py
- src/tribler/core/libtorrent/download_manager/download_manager.py
Fixes #8134
Fixes #8133
This PR:
- Fixes missing `METADATA` file generation.
- Fixes the libtorrent user agent being set to `Tribler/Experimental`.
- Removes sharing the IPv8 public key through libtorrent.
Note that PyInstaller does support metadata generation. However, I'd like the `tribler.spec` and `setup.py` to remain pretty close.
> Various version related fixes

- src/tribler/ui/src/pages/Popular/index.tsx
- src/tribler/ui/src/pages/Search/index.tsx
This PR makes torrent names on the search/popular pages clickable, whereas before you needed to double-click the table entry itself. This essentially reverts the behaviour back to that of Tribler 7.14.
> Open the download dialog when clicking on the name of a torrent

- src/tribler/core/database/layers/knowledge.py
Fixes https://github.com/Tribler/tribler/issues/8111.
> Don't crash on UnrepeatableReadErrors from knowledge db

- src/tribler/test_integration/test_anon_download.py
Fixes #8143
This PR:
- Fixes `start_anon_download` not waiting for `listen_ports` to be created.
Validated fix with:
```patch
diff --git a/src/tribler/core/libtorrent/download_manager/download_manager.py b/src/tribler/core/libtorrent/download_manager/download_manager.py
index 6346306eb..4d71bc241 100644
--- a/src/tribler/core/libtorrent/download_manager/download_manager.py
+++ b/src/tribler/core/libtorrent/download_manager/download_manager.py
@@ -475,7 +475,10 @@ class DownloadManager(TaskManager):
if alert_type == "listen_succeeded_alert":
ls_alert = cast(lt.listen_succeeded_alert, alert)
-            self.listen_ports[hops][ls_alert.address] = ls_alert.port
+            def do_later(address, port):
+                self.listen_ports[hops][address] = port
+ …
```
> Fixed anon download test not waiting for port

- src/tribler/ui/index.html
- src/tribler/ui/src/Router.tsx
- src/tribler/ui/src/components/layouts/Header.tsx
- src/tribler/ui/src/components/layouts/SideLayout.tsx
- src/tribler/ui/src/services/ipv8.service.ts
- src/tribler/ui/src/services/reporting.ts
- src/tribler/ui/src/services/tribler.service.ts
Related to #8141
This PR:
- Adds a last line of defense for uncaught TypeScript errors.
- Removes the interceptors from Axios responses.
This PR does not implement proper handling per core response yet. This is only the last resort for when "clean" error handling fails.
> Add uncaught exception handler to GUI

- src/tribler/core/database/store.py
This PR:
- Fixes no popular torrents appearing.
In the old code, the `health_list` was filled with results but the `pony_query = pony_query.where(lambda g: g.health in health_list)` refused to link the metadata with the health info.
> Fixed empty popular torrents page

- src/tribler/core/database/restapi/database_endpoint.py
- src/tribler/ui/src/pages/Popular/index.tsx
- src/tribler/ui/src/pages/Search/index.tsx
- src/tribler/ui/src/services/tribler.service.ts
Fixes #8083
This PR:
- Adds querying of peers for popular torrents.
- Removes xxx filtering from endpoints (this no longer does anything).
> Query peers for popular torrents

- src/tribler/upgrade_script.py
Fixes #8162
This PR:
- Updates the upgrader script to explicitly import old data instead of simply dumping the old data into the new database.
Notes:
- It's definitely longer but at least it works.
> Fixed upgrader script causing incorrect database relationships

- src/tribler/core/database/serialization.py
- src/tribler/core/database/store.py
Fixes #8160
This PR:
- Updates squashed blob unpacking behavior to first unpack deprecated payloads and then filter them out (instead of throwing away the whole list).
> Do not void valid metadata mixed with deprecated metadata

- src/tribler/core/torrent_checker/torrent_checker.py
Fixes #8159
This PR:
- Fixes health checks returning 0/0 even wheel seeds/leechers are found in a fresh check.
> Fixed health checks frequently being zero

- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/restapi/downloads_endpoint.py
- src/tribler/test_unit/core/libtorrent/restapi/test_downloads_endpoint.py
- src/tribler/ui/public/locales/en_US.json
- src/tribler/ui/public/locales/es_ES.json
- src/tribler/ui/public/locales/pt_BR.json
- src/tribler/ui/public/locales/ru_RU.json
- src/tribler/ui/public/locales/zh_CN.json
- src/tribler/ui/src/pages/Downloads/Trackers.tsx
- src/tribler/ui/src/services/tribler.service.ts
Fixes #2529
Fixes #1797 (implements only force-rechecking, as priorities [don't fit that well](https://github.com/Tribler/tribler/issues/2529#issuecomment-2361103711) with `libtorrent`'s tiers)
This PR:
- Adds GUI elements and REST API calls to add, remove, and force-check trackers.
> Added option to add trackers to a download

- build/debian/makedist_debian.sh
- build/setup.py
This PR:
- Fixes the GitHub tag url fed to `dch`.
- Updates `setup.py` to allow `tribler.dist-info` to exist.
> Small QOL fixes for Debian builds

- build/mac/entitlements.plist
Fixes #8175
This PR:
- Adds the unsigned library entitlement to the Mac build.
This build is tested to work on our Mac infrastructure.
> Added Mac entitlement to disable lib validation

- .gitignore
- src/run_tribler.py
Fixes #8176
This PR:
- Fixes / re-adds the ability to operate in server/headless mode
> v8 headless

- src/tribler/ui/src/services/reporting.ts
Fixes #8184
This PR:
- Fixes the GUI error reporter not checking if `handled` is `undefined`.
> Fixed error reporter not checking for undefined handled key

- src/tribler/core/libtorrent/restapi/downloads_endpoint.py
- src/tribler/ui/src/services/tribler.service.ts
Fixes #8185
This PR:
- Updates `add_download` (REST API) to accept selected files in the (bencoded) metainfo dictionary.
- Updates `startDownloadFromFile` (GUI) to mix in selected files in the metainfo dictionary.
> Fixed selected files overflowing the URL

- .github/workflows/mypy.yml
- src/tribler/core/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/restapi/file_endpoint.py
- src/tribler/core/restapi/rest_manager.py
- src/tribler/core/restapi/webui_endpoint.py
- src/tribler/core/socks5/aiohttp_connector.py
Fixes #8189
This PR:
- Updates the `mypy` workflow to install Tribler dependencies before type-checking.
> READY: Updated mypy CI check to install dependencies

- src/tribler/core/session.py
Fixes a remaining issue from #8190
This PR:
- Removes the last traces of the `UserActivityComponent`.
Somehow I missed this.
> Fixed lingering user activity code

- src/tribler/ui/package.json
- src/tribler/ui/src/components/ui/simple-table.tsx
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/ui/src/lib/utils.ts
- src/tribler/ui/src/models/file.model.tsx
- src/tribler/ui/src/pages/Downloads/Files.tsx
This PR brings back file trees, similar to the way file selection worked before introducing the web UI.
> Show file trees in SaveAs / DownloadDetails components

- build/win/build.py
Fixes #8198
This PR:
- Fixes `build.py` for `cx_Freeze` not including tribler dist info.
This fix was locally confirmed for Ubuntu, I'll test Windows later.
> Fixed Debian/Windows builds not detecting their own version

- .github/workflows/build.yml
- .github/workflows/unittests.yml
- src/tribler/core/libtorrent/torrents.py
Fixes #8200
This PR:
- Updates the unit tests to use `macos-14` instead of `macos-12`.
- Updates `create_torrent_file` to use the `v1_only` flag.
- Removes `macos-12` from the build job.
> Added workaround for deprecation of macos-12 runner

- src/tribler/core/database/store.py
- src/tribler/test_unit/core/database/test_store.py
Fixes #8201
This PR:
- Updates `get_entries_query` to ignore invalid `kwargs`, allowing responses to peers using old protocol versions.
> Updated get_entries_query to ingore deprecated kwargs

- .github/workflows/pr-comment-validate.yml
This PR:
- Updates the commit status setting to a separate GitHub secret.
> Moved commit status setting to separate secret

- .github/workflows/build.yml
Fixes #8171
This PR:
- Updates the build action to reflect the architecture of the builder machine in its output `deb`.
> Rename deb output to amd64 on amd64 builder

- doc/basics/docker.rst
Fixes #8148
This PR:
- Updates the `Docker` documentation to work with our GitHub packages release.
> Updated Docker docs

- build/debian/tribler/debian/control
Fixes #8194
This PR:
- Fixes the `.deb` build crashing early due to a missing dependency.
Now `sudo apt install ./tribler_8.0.1_all.deb` correctly pulls in the correct dependencies.
> Fixed missing dependency in deb file

- src/tribler/core/libtorrent/restapi/downloads_endpoint.py
- src/tribler/test_unit/core/libtorrent/mocks.py
- src/tribler/test_unit/core/libtorrent/restapi/test_downloads_endpoint.py
This PR fixes the video streaming endpoint.
Once merged you can stream MP4s directly from the browser by going to `/api/downloads/<infohash>/stream/<fileindex>`.
> Fix video streaming endpoint

- src/tribler/ui/src/components/ui/simple-table.tsx
No table supports sorting right now, except for the downloads table.
However, sorting isn't actually working. This PR fixes this.
> Fix download sorting

- src/tribler/ui/src/pages/Downloads/index.tsx
- src/tribler/ui/src/services/tribler.service.ts
Fixes #8216
This PR:
- Updates `getDownloads` to pass `get_availability` to the core and uses it in the download details.
> Fetch availability for download details

- src/tribler/core/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler/test_unit/core/libtorrent/restapi/test_torrentinfo_endpoint.py
- src/tribler/ui/public/locales/en_US.json
- src/tribler/ui/public/locales/es_ES.json
- src/tribler/ui/public/locales/ko_KR.json
- src/tribler/ui/public/locales/pt_BR.json
- src/tribler/ui/public/locales/ru_RU.json
- src/tribler/ui/public/locales/zh_CN.json
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/ui/src/services/tribler.service.ts
Fixes #1680
This PR:
- Adds support (and a warning) for adding torrents from an HTTPS url with an invalid certificate.
[[screenshot available here]](https://github.com/Tribler/tribler/issues/1680#issuecomment-2422225207)
> Added warning when adding torrent from invalid HTTPS

- src/tribler/core/libtorrent/download_manager/download_state.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download_state.py
- src/tribler/ui/src/pages/Downloads/Details.tsx
- src/tribler/ui/src/pages/Settings/Seeding.tsx
Fixes https://github.com/Tribler/tribler/issues/8209.
Also fixes:
* An issue with erroneously not seeding at all when `seeding_mode = 'ratio'`.
When upload was 0 and download > 0, the ratio became ∞, and the seeding ratio was immediately reached. This stopped the download before seeding could even begin.
* Seeding settings in the web UI.
> Fix empty download list when ratio is infinity

- src/tribler/ui/package-lock.json
- src/tribler/ui/package.json
- src/tribler/ui/src/lib/utils.ts
- src/tribler/ui/src/models/file.model.tsx
- src/tribler/ui/src/pages/Downloads/Actions.tsx
Fixes https://github.com/Tribler/tribler/issues/5591.
After merging, users will be able to export multiple .torrent files as a zip file. Compression is done in Javascript.
> Add ability to export multiple .torrents at once

- src/run_tribler.py
Fixes #8229
This PR:
- Fixes the tray icon not appearing on `Mac` because it was not spawned in the main thread.
Regarding the note in `mac_event_loop`: the asyncio main thread blocks while the tray icon context menu is open. I **assume** nobody will keep their menu open, but **should they do so** their Tribler core won't do anything anymore. Even so, it would be nice to fix that in the future. For now, I think this is better than nothing.
The choice for `asyncio.sleep(0.01)` instead of `asyncio.sleep(0)` was because the latter chokes up the core. With `0.01`, the core seems unaffected.
> Fixed the tray icon not appearing on Mac

- doc/.readthedocs.yaml
- doc/Makefile
- doc/basics/docker.rst
- doc/basics/running.rst
- doc/conf.py
- doc/index.rst
- doc/reference/software_architecture.dot
- doc/reference/software_architecture.rst
- src/run_tribler.py
- src/tribler/core/database/orm_bindings/torrent_metadata.py
- src/tribler/core/libtorrent/torrentdef.py
- src/tribler/core/libtorrent/uris.py
- src/tribler/core/recommender/restapi/endpoint.py
Fixes #2928
This PR:
- Adds Tribler software architecture documentation.
- Fixes some minor Sphinx errors during compilation (mostly docstring formatting).
- Fixes some minor ruff errors because I touched the files due to the previous point.
> Added software architecture documentation

- doc/.readthedocs.yaml
Fixes https://tribler.readthedocs.io/en/latest/reference/software_architecture.html showing the string `reference/software_architecture.svg` instead of the image.
This PR:
- Adds the `svg` generation step into `.readthedocs.yaml` (next to the Makefile).
I'm roughly 51% positive that this will fix the issue. However, I don't know for sure.
> Fixed ReadTheDocs image generation

- .github/workflows/build.yml
- build/win/build.py
Related to #5327, #5345
This PR:
- Adds a `deb` build for `aarch64`.
Notes:
- This builder locally tests in its own virtual environment. I'm still waiting for a phyiscal `aarch64` testing machine to arrive in the mail.
- One workaround and a version pin is needed for `cx_Freeze` (in contact with repo author to get the issue fixed).
- An Action run is available here: https://github.com/qstokkink/tribler/actions/runs/11590809339/job/32269182843
> Compile aarch64 deb

- .github/workflows/weekly_mutation_tests.yml
Fixes #8078
This PR:
- Adds a weekly mutation test workflow.
Successful run (with `workflow_dispatch`): https://github.com/qstokkink/tribler/actions/runs/11611966702
> Hook in weekly mutation test

- src/tribler/core/libtorrent/download_manager/download_config.py
- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/upgrade_script.py
Fixes #8239
This PR:
- Fixes a syntax error in the string formatting in `SaveAs.tsx`.
- Updates all `ConfigObj` instances to use `utf-8`, instead of the default `ascii`.
Notes:
- This is a confirmed fix for the setup described in https://github.com/Tribler/tribler/issues/8239#issuecomment-2451886971
- The compile step uncovered that we use the "error" key inconsistently. Sometimes it's a string and sometimes it's a mapping.
> Set UTF-8 for all ConfigObj instances

- .github/workflows/build.yml
- build/requirements.txt
Fixes #8244 
Fixes #8243
This PR:
- Adds a Tribler app test run inside of the build job.
- Fixes a regression in `cx_Freeze`. Now pinned to `7.2.3` until fixed in the upstream.
This is a confirmed fix (test run https://github.com/qstokkink/tribler/actions/runs/11661155992)
> Fixed missing lzma on 8.0.3

- build/debian/tribler/debian/control
Fixes #8242
This PR:
- Adds a fallback to `gir1.2-gtk-3.0` if `gir1.2-gtk-4.0` is missing.
Using `gir1.2-gtk-3.0` has been confirmed to work in #8242.
> Add fallback to GTK-3.0 in Debian Depends

- src/tribler/ui/src/lib/utils.ts
Fixes #8249
This PR:
- Fixes `unhexlify()` not performing variable-length decoding for UTF-8.
After fix (see #8249 for before):
> Fixed unhexlify with variable length UTF-8 decoding

- src/tribler/core/versioning/manager.py
- src/tribler/test_unit/core/versioning/test_manager.py
Fixes #8247
This PR:
- Fixes `VersioningManager.can_upgrade` comparing the release version to the database version directly.
> Fixed database version can_upgrade detection

- src/tribler/ui/public/locales/en_US.json
- src/tribler/ui/public/locales/es_ES.json
- src/tribler/ui/public/locales/ko_KR.json
- src/tribler/ui/public/locales/pt_BR.json
- src/tribler/ui/public/locales/ru_RU.json
- src/tribler/ui/public/locales/zh_CN.json
- src/tribler/ui/src/pages/Settings/Versions.tsx
This PR:
- Fixes the `Settings` / `Versions` tab not being translated.
- Fixes the warning that lists should have `key` attributes for the `Versions` page.
> Fixes for the `Versions` UI tab

- .github/workflows/build.yml
- doc/building/linux.rst
Fixes https://github.com/Tribler/tribler/issues/8242.
I removed `cpio=2.13+dfsg-7` since it isn't needed nor is version `2.13+dfsg-7` available on Ubuntu 20.04.
> Use Ubuntu 20.04 for building

- build/debian/update_metainfo.py
Fixes #8255
This PR:
- Fixes a double `<release>` tag being written (erroring out Flatpak builds).
> Fixed Debian metadata XML duplicate release tag

- src/tribler/ui/index.html
Hopefully fixes https://github.com/Tribler/tribler/issues/8251.
I've disabled translation services for the entire page. To me, this seems reasonable, since we have our own localization stuff anyway. We can always revisit this later, but I think for now stability is more important.
> Disable translation services

- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/upgrade_script.py
Fixes #8265
This PR:
- Updates `dlcheckpoints` to no longer be stored in a versioned directory.
Notes:
- The next pre-release will require a large banner that tells users to copy over their `dlcheckpoints` from a previous pre-release folder. Importing from the 7.14 release automatically creates the directory though.
> Un-version dlcheckpoints

- src/tribler/ui/src/components/ui/simple-table.tsx
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/ui/src/lib/utils.ts
- src/tribler/ui/src/pages/Debug/Asyncio/Tasks.tsx
- src/tribler/ui/src/pages/Debug/DHT/Buckets.tsx
- src/tribler/ui/src/pages/Debug/DHT/Statistics.tsx
- src/tribler/ui/src/pages/Debug/General/index.tsx
- src/tribler/ui/src/pages/Debug/IPv8/Details.tsx
- src/tribler/ui/src/pages/Debug/IPv8/Overlays.tsx
- src/tribler/ui/src/pages/Debug/Libtorrent/index.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Circuits.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Exits.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Peers.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Relays.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Swarms.tsx
- src/tribler/ui/src/pages/Downloads/Files.tsx
- src/tribler/ui/src/pages/Downloads/Peers.tsx
- src/tribler/ui/src/pages/Downloads/Trackers.tsx
- src/tribler/ui/src/pages/Downloads/index.tsx
- src/tribler/ui/src/pages/Popular/index.tsx
- src/tribler/ui/src/pages/Search/index.tsx
This PR adds sorting to all tables in the UI. I've included the tables in the debug panel, but disabled translating the header name.
Also fixes https://github.com/Tribler/tribler/issues/1261. Note that I'm only storing the sorting state for `Download` / `Popular` / `Search` tables. The sorting state is stored in local storage.
> Add sorting to all tables

- build/debian/tribler/debian/control
Fixes #8277
This PR:
- Adds a fallback to `gir1.2-ayatanaappindicator3-0.1` if `gir1.2-appindicator3-0.1` is not available.
> Added gir1.2-ayatanaappindicator3-0.1 Debian fallback

- src/tribler/core/knowledge/community.py
- src/tribler/core/versioning/manager.py
- src/tribler/ui/src/pages/Settings/Versions.tsx
- src/tribler/upgrade_script.py
Fixes #8283
Fixes #8289
This PR:
- Fixes `KnowledgeCommunity.on_message` not using `serializable=True`, causing `Database is locked` errors.
- Fixes `upgrade_script` not being guarded by `db_session` because the `Database` is outside of Pony's control, causing `Database is locked` errors.
- Fixes `dlcheckpoints` appearing as a Tribler version.
- Fixes calling `perform_upgrade()` twice causing an unhandled exception.
- Updates the versioning page to not wait several seconds before showing an update is in progress.
- Updates the version upgrade to operate in batches, not all database content at once.
> Fixed various upgrade issues

- src/tribler/core/libtorrent/restapi/downloads_endpoint.py
- src/tribler/test_unit/core/libtorrent/restapi/test_downloads_endpoint.py
Fixes #8291
This PR:
- Updates the `remove_tracker` call to also remove trackers from its (local) `metainfo`, not just the `resume_data`.
> Updated remove_tracker to also remove from metainfo

- src/tribler/core/restapi/rest_manager.py
Fixes #8293
This PR:
- Fixes `api/https_certfile` not being used.
> Fixed api/https_certfile setting being ignored

- src/tribler/core/components.py
- src/tribler/core/knowledge/community.py
Fixes #8292
This PR:
- Updates the `KnowledgeCommunity` to more aggressively ward off superfluous peers.
From my local tests, this is enough to keep the peer count under control. In the worst case, we can also blacklist/ban peers: but this does not seem necessary (yet).
> Rein in KnowledgeCommunity peer count

- src/tribler/ui/package-lock.json
- src/tribler/ui/package.json
- src/tribler/ui/src/components/layouts/Header.tsx
- src/tribler/ui/src/components/layouts/SideLayout.tsx
- src/tribler/ui/src/components/ui/autocomplete.tsx
- src/tribler/ui/src/components/ui/simple-table.tsx
- src/tribler/ui/src/config/menu.ts
- src/tribler/ui/src/pages/Downloads/index.tsx
- src/tribler/ui/src/pages/Popular/index.tsx
- src/tribler/ui/src/pages/Search/index.tsx
This PR contains the following enhancements/fixes to the web UI:
* Add a search button to the header.
* When clicking a menu, navigate directly to the last visited submenu. If no such submenu exists, use the first submenu.
* Hide search suggestions when the list is empty. This fixes a 1px line appearing when clicking on the search input.
* Show a spinner during shutdown making it easier to see when shutdown has completed.
* Allow selecting all downloads using ctrl+a (fixes https://github.com/Tribler/tribler/issues/8302).
* Use infohash as `RowId` in the downloads table. Since table selection is keyed by `RowId`, this fixes an issue with the selected download(s) magically changing after changing the hop count.
> Various UI enhancements/fixes

- src/run_tribler.py
Fixes #8290
This PR:
- Fixes the browser window not appearing on Mac M4.
This fix was confirmed in #8290.
> Fixed Mac not showing a browser window

- src/tribler/core/restapi/webui_endpoint.py
Fixes #8279
This PR:
- Fixes a blank screen appearing if the Windows registry entry for `.js`, `Content Type` is set to something other than `application/javascript`.
Notes:
- For good measure, I also added `html` explicitly to avoid similar problems
- I locally reproduced the error and confirmed this fix.
> Fixed mimetype being wrong in winreg

- src/tribler/core/database/orm_bindings/torrent_metadata.py
- src/tribler/test_unit/core/database/test_store.py
Fixes https://github.com/Tribler/tribler/issues/8324. Fixes https://github.com/Tribler/tribler/issues/8319.
> Fix for adding FFA torrents with trackers

- src/tribler/core/libtorrent/download_manager/download_manager.py
This PR:
- Fixes torrents with the name `metainfo request` being injected into the database.
> Don't notify metainfo if there is no metainfo

- src/tribler/core/torrent_checker/torrentchecker_session.py
Fixes https://github.com/Tribler/tribler/issues/8322.
> Fix infinite recursion while shutting down TrackerSession

- src/tribler/ui/src/components/ui/simple-table.tsx
Fixes https://github.com/Tribler/tribler/issues/8344.
> Fix pagination

- .github/workflows/unittests.yml
- build/docker/build.Dockerfile
- requirements.txt
- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/core/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler/test_unit/core/libtorrent/restapi/test_torrentinfo_endpoint.py
Fixes #5556
Fixes #6737
Fixes #6853
This PR:
- Updates the `libtorrent` version to `2.0.9`.
- Updates the `libtorrent` session to allow for I2P peers.
- Updates the `marshmallow` version to `3.23.3`.
The newest marshmallow version(s >= 3.24.0) [requires updates in IPv8](https://github.com/Tribler/py-ipv8/issues/1333).
> Updated libtorrent to 2.0.9

- src/tribler/ui/package-lock.json
- src/tribler/ui/package.json
- src/tribler/ui/src/components/swarm-health.tsx
- src/tribler/ui/src/components/ui/simple-table.tsx
- src/tribler/ui/src/lib/utils.ts
- src/tribler/ui/src/models/settings.model.tsx
- src/tribler/ui/src/pages/Debug/Asyncio/Tasks.tsx
- src/tribler/ui/src/pages/Debug/DHT/Buckets.tsx
- src/tribler/ui/src/pages/Debug/IPv8/index.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Circuits.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Exits.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Relays.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Swarms.tsx
- src/tribler/ui/src/pages/Downloads/index.tsx
- src/tribler/ui/src/pages/Popular/index.tsx
- src/tribler/ui/src/pages/Search/index.tsx
Fixes https://github.com/Tribler/tribler/issues/8331.
Fixes https://github.com/Tribler/tribler/issues/8348.
UI for showing/hiding columns on the downloads page:
> Allow changing column visibility

- requirements.txt
This PR:
- Removes the `marshmallow` version pinning. This is no longer necessary, since `3.25.0`.
> Removed pinned marshmallow version

- src/tribler/core/session.py
Fixes #8355
This PR:
- Updates `_except_hook` to ignore `ConnectionResetError`.
These exceptions are a result of our connections, but they escape our control and get raised internally (CPython issue 116091). So, I think this is the only way to handle the error.
> Ignore internal ConnectionResetErrors

- src/tribler/core/restapi/logging_endpoint.py
- src/tribler/core/session.py
- src/tribler/ui/src/pages/Debug/General/index.tsx
- src/tribler/ui/src/services/tribler.service.ts
Fixes #8398
This PR:
- Adds a new REST endpoint to retrieve logs.
- Updates the `General` Debug tab to also show the logs.
> Added logging output to the General Debug tab

- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/tribler_config.py
- src/tribler/ui/public/locales/en_US.json
- src/tribler/ui/public/locales/es_ES.json
- src/tribler/ui/public/locales/ko_KR.json
- src/tribler/ui/public/locales/pt_BR.json
- src/tribler/ui/public/locales/ru_RU.json
- src/tribler/ui/public/locales/zh_CN.json
- src/tribler/ui/src/models/settings.model.tsx
- src/tribler/ui/src/pages/Settings/Connection.tsx
Fixes #8287
This PR:
- Updates libtorrent session creation to inherit the config values of `announce_to_all_tiers`, `announce_to_all_trackers`, and `max_concurrent_http_announces`. The former two are lumped together in the GUI as the `announce_to_all` setting.
- Removes `set_settings` workaround for old libtorrent versions.
> Added announce to all trackers functionality

- .github/workflows/build.yml
This PR:
- Fixes the build Action trying to remove `pyipv8/create_setup_taskmanager.py`, which doesn't exist anymore.
> Fix build Action removing non-existent file

- src/tribler/core/restapi/file_endpoint.py
- src/tribler/ui/package-lock.json
- src/tribler/ui/package.json
- src/tribler/ui/public/locales/en_US.json
- src/tribler/ui/public/locales/es_ES.json
- src/tribler/ui/public/locales/ko_KR.json
- src/tribler/ui/public/locales/pt_BR.json
- src/tribler/ui/public/locales/ru_RU.json
- src/tribler/ui/public/locales/zh_CN.json
- src/tribler/ui/src/components/path-input.tsx
- src/tribler/ui/src/components/ui/context-menu.tsx
- src/tribler/ui/src/dialogs/SelectRemotePath.tsx
- src/tribler/ui/src/pages/Debug/General/index.tsx
- src/tribler/ui/src/services/tribler.service.ts
Add usability improvements to `SelectRemotePath` including:
* the ability to create a new directory (fixes https://github.com/Tribler/tribler/issues/8082)
* the ability to quickly move up the directory tree by clicking on part of the current path
* added translations
Also fixes an issue with showing the logs on the debug page.
> Usability improvements to SelectRemotePath

- src/tribler/ui/src/components/add-torrent.tsx
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/ui/src/dialogs/SelectRemotePath.tsx
Fixes https://github.com/Tribler/tribler/issues/8381.
Also fixes:
* Unique key error in `SelectRemotePath`.
* ~~An issue with the `SaveAs` dialog only being shown after the metadata has been downloaded, removing any feedback that something is happening. Only happened when coming from `AddTorrent` (introduced in https://github.com/Tribler/tribler/pull/8403).~~
* Stop requesting metainfo as soon as the user starts typing. Instead, wait until "Add" is pressed.
> Fix for using selected_files from previous downloads

- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download_manager.py
Fixes #8363
This PR:
- Adds support for parsing selected files, trackers, peers, and url seeds from magnet links.
- Adds support for adding URL seeds to a `Download`.
- Updates `Download.add_trackers()` to reannounce for immediate effect, instead of waiting for the next resume data alert ([see libtorrent docs](https://libtorrent.org/reference-Torrent_Handle.html#trackers-replace-trackers-add-tracker-post-trackers)).
> Load additional magnet URI fields

- src/tribler/core/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler/test_unit/core/libtorrent/restapi/test_torrentinfo_endpoint.py
- src/tribler/ui/src/components/add-torrent.tsx
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/ui/src/services/tribler.service.ts
Fixes #8416
This PR:
- Adds a `skipmagnet` parameter to the `torrentinfo` endpoint, allowing magnet links to resolve later in the `SaveAs` dialog (or not at all).
This should both do all the fancy HTTP forwarding and forward magnet links quickly to the SaveAs dialog. However, the price is another parameter for `getMetainfo()`.
> Allow magnet links to resolve later when adding URIs

- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/core/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler/core/libtorrent/torrents.py
- src/tribler/core/libtorrent/uris.py
- src/tribler/core/rss/rss.py
- src/tribler/test_unit/core/libtorrent/restapi/test_torrentinfo_endpoint.py
- src/tribler/test_unit/core/libtorrent/test_uris.py
Fixes #7785
This PR:
- Updates the torrent addition logic to allow for invalid SSL certificates.
> Allow downloading of torrents with invalid SSL certs

- build/docker/build.Dockerfile
- build/docker/compose.yml
Related to #6591
This PR:
- Updates `build.Dockerfile` to provide the **latest-stable full-GUI Tribler** (instead of headless) experience for X.Org-supporting platforms, including the tray icon and webbrowser opening.
Docker containers aren't really supposed to be able to manipulate the host and Python `webbrowser` doesn't normally forward to external services. So, some funky stuff is happening:
1. We fool Python into thinking the `x-www-browser` is installed. This is actually bash script that sends a `org.freedesktop.portal.OpenURI.OpenURI` event to the D-Bus with the URL it was called with.
2. We inherit the X.Org files from disk (volume), X.Org environment variables, and the user id from the host. This allows the host to interpret D-Bus events as its own.
3. _(Side note)_ We also need …
> Updated docker build script to get the latest stable release

- src/tribler/core/components.py
- src/tribler/core/rendezvous/database.py
- src/tribler/core/rendezvous/rendezvous_hook.py
- src/tribler/test_unit/core/rendezvous/test_rendezvous_hook.py
Related to #8272
This PR:
- Updates the `Rendezvous` component to only write certificates every 60 seconds and on shutdown.
> Avoid micro-writes in the Rendezvous component

- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download_manager.py
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/ui/src/lib/utils.ts
- src/tribler/ui/src/pages/Downloads/Files.tsx
Fixes #8455
This PR:
- Adds preselection from magnet links to the `SaveAs` dialog.
- Fixes the preselected files of a magnet link overwriting the (later) user configuration.
Note that I'm parsing the magnet link in the GUI. This avoids editing the existing REST endpoint and/or calling another REST route to fetch the preselected files as a result of the magnet link.
> Fixed magnet parsing overwriting user file selection

- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/core/libtorrent/download_manager/download_state.py
- src/tribler/core/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler/core/libtorrent/torrentdef.py
- src/tribler/test_unit/core/libtorrent/mocks.py
- src/tribler/test_unit/core/libtorrent/restapi/test_downloads_endpoint.py
- src/tribler/test_unit/core/libtorrent/restapi/test_torrentinfo_endpoint.py
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/ui/src/lib/utils.ts
- src/tribler/ui/src/pages/Downloads/Files.tsx
- src/tribler/ui/src/services/tribler.service.ts
Fixes #8457
Note: this is not the big refactor into `libtorrent`, just the bare minimum not to crash on v2 info dicts.
This PR:
- Adds v2 info dict support into the `TorrentDef`.
- Adds `TorrentDef.get_file_indices()` to fetch the file indices of the file list[^1].
- Updates `Files.tsx` to use `currentIndices` instead of `currentIndcices`.
- Updates various GUI files to not depend on the file list length for indices[^1].
- Updates the `TorrentInfoEndpoint` to no longer return the raw metainfo, but instead give the files and names directly (this was previously derived inside the GUI).
[^1]: The list of files is not (or, no longer) equal to the list of indices (these include padding files now).
> Added internal BitTorrent v2 support

- build/docker/build.Dockerfile
- build/docker/compose.yml
- doc/basics/docker.rst
Fixes #8458
This PR:
- Adds documentation on how to run Docker in headless mode.
- Fixes `-s` not being passed into the Docker container, effectively disabling the ability to run in headless mode.
For some reason, my tray icon is not working on the machine I tested this with. I've left that unfixed for now.
> Use ENTRYPOINT instead of CMD for Docker

- src/tribler/test_unit/test_tribler_config.py
- src/tribler/tribler_config.py
Fixes #8466
This PR:
- Fixes missing sections not regenerating from the default config when setting values.
> Fixed setting values in missing config sections

- src/tribler/core/libtorrent/torrentdef.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download_state.py
- src/tribler/test_unit/core/libtorrent/test_torrentdef.py
Fixes #8366
Fixes #8468
This PR:
- Fixes `_get_all_files_as_unicode_with_length` including padding files for v1 metainfo.
This is a tiny step toward leaning more on the `torrent_info` in the `TorrentDef`. Looking at it, we can probably replace `_get_all_files_as_unicode_with_length` with about three lines of code, if we lean on `torrent_def` fully. That's for a future PR though.
> Fixed inconsistent inclusion of padding files in tdef

- src/tribler/core/session.py
- src/tribler/test_unit/core/restapi/test_ipv8_endpoint.py
- src/tribler/ui/package-lock.json
- src/tribler/ui/package.json
- src/tribler/ui/src/components/layouts/Header.tsx
- src/tribler/ui/src/components/ui/simple-table.tsx
- src/tribler/ui/src/models/overlay.model.tsx
- src/tribler/ui/src/pages/Debug/IPv8/Details.tsx
- src/tribler/ui/src/pages/Debug/IPv8/Overlays.tsx
- src/tribler/ui/src/pages/Debug/IPv8/index.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Circuits.tsx
- src/tribler/ui/src/pages/Settings/Debugging.tsx
- src/tribler/ui/src/services/ipv8.service.ts
This PR:
* Adds message statistics in Rust and updates the statistics UI. The statistics are always enabled and can be viewed from `Debug > IPv8 > Traffic`.
* Adds the ability to test circuits in Rust. The resulting download speed can be viewed live from the tunnel debug panel.
IPv8 message stats:
Tunnel speed tests:
> Add message statistics using ipv8-rust-tunnels

- src/tribler/core/libtorrent/download_manager/download_manager.py
Fixes #8489 (experimental fix)
Fixes #8485
This PR:
- Updates `DownloadManager.remove_config()` to use `Path.unlink()` instead of `os.access()` + `os.remove()`. At best, this fixes #8489, and in the worst case this only modernizes the code.
- Updates `DownloadManager.create_session()` to use the `always_pwrite` flag.
> Various `8.1.0` fixes

- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download.py
Fixes #8485
Fixes #8503
This PR:
- Fixes Tribler considering initial loading as new completion of a torrent, forcing rechecks when using `check_after_complete`.
- Updates `mmap_file_size_cutoff` to the maximum value.
Hopefully, this is the last magic value we need to get the libtorrent 2 memory usage under control 🙏
> Various 8.1.1 fixes

- doc/basics/docker.rst
Fixes #8458
This PR:
- Fixes the Docker documentation specifying incorrect mount points.
> Fixed Docker docs to specify correct mount points

- src/tribler/ui/src/pages/Downloads/Trackers.tsx
Fixes #8494
This PR:
- Updates the GUI to show a loading spinner while the download's trackers are not available yet.
This avoids users adding a tracker while the trackers cannot be changed, leading to errors.
> Don't allow tracker changes while loading

- .github/workflows/build.yml
Fixes the v8.1.2 [build failure](https://github.com/Tribler/tribler/actions/runs/13852550070).
Confirmed fix on my fork: https://github.com/qstokkink/tribler/actions/runs/13853306201
> Incremented run-on-arc-action version

- src/tribler/ui/src/components/icons.tsx
- src/tribler/ui/src/components/swarm-health.tsx
- src/tribler/ui/src/components/ui/simple-table.tsx
- src/tribler/ui/src/components/ui/table.tsx
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/ui/src/pages/Debug/IPv8/Overlays.tsx
- src/tribler/ui/src/pages/Downloads/Trackers.tsx
- src/tribler/ui/src/pages/Downloads/index.tsx
- src/tribler/ui/src/pages/Popular/index.tsx
- src/tribler/ui/src/pages/Search/index.tsx
Fixes an issue with multiple scrollbars becoming visible next to a table after resizing (see screenshot). By adding `[&>[data-radix-scroll-area-viewport]]:max-h-[calc(100vh-57px)]` to the `ScrollArea` parent of the `Table`, we set it's height dynamically based on the viewport size minus the header size (57px).
Since these issues occur only when changing the height of the browser, I've ignored issues with tables in the debug panel.
This PR also:
* Fixes`ResizableHandle` being shown when it isn't needed.
* Removes duplicate SVG code for showing spinners.
> Fix table scrollbar issue

- src/tribler/core/restapi/logging_endpoint.py
Fixes #8485 (once and for all, for the third time 🙂)
This PR:
- Fixes a memory leak in the logging endpoint due to the `MemoryHandler` flushing mechanism.
I set the capacity to 400 records. This equates to roughly one minute of logging output before records start rotating out.
> Fixed memory leak in the logging endpoint

- src/tribler/core/libtorrent/download_manager/download_config.py
Possibly fixes https://github.com/Tribler/tribler/issues/8523.
When downloading normally, `completed_dir` is set to `""` by the UI. However, when creating a new torrent and setting it to seed automatically, `completed_dir` is set to `None` (this comes from `download_defaults`). This is then cast to str to become `"None"`. This PR fixes this issue by not setting `None` in `from_defaults`.
Note that `completed_dir = None` in the config file is interpreted as a directory called None.  The same goes for `saveas = None`.
> Fix default completed_dir

- src/tribler/ui/src/components/ui/simple-table.tsx
Second part of fixing https://github.com/Tribler/tribler/issues/8517.
Previously, we fixed shift+click, but it turns out there's a problem with shift+up/down as well. As before, this issue only occurs when sorting is set manually.
> Fix shift+up/down when sorting

- src/tribler/ui/package-lock.json
- src/tribler/ui/package.json
- src/tribler/ui/src/components/ui/scroll-area.tsx
- src/tribler/ui/src/components/ui/simple-table.tsx
- src/tribler/ui/src/components/ui/table.tsx
- src/tribler/ui/src/dialogs/CreateTorrent.tsx
- src/tribler/ui/src/dialogs/SaveAs.tsx
- src/tribler/ui/src/pages/Debug/Asyncio/SlowTasks.tsx
- src/tribler/ui/src/pages/Debug/Asyncio/Tasks.tsx
- src/tribler/ui/src/pages/Debug/DHT/Buckets.tsx
- src/tribler/ui/src/pages/Debug/DHT/Statistics.tsx
- src/tribler/ui/src/pages/Debug/IPv8/Details.tsx
- src/tribler/ui/src/pages/Debug/IPv8/Overlays.tsx
- src/tribler/ui/src/pages/Debug/Libtorrent/index.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Circuits.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Exits.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Peers.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Relays.tsx
- src/tribler/ui/src/pages/Debug/Tunnels/Swarms.tsx
- src/tribler/ui/src/pages/Downloads/Details.tsx
- src/tribler/ui/src/pages/Downloads/Files.tsx
- src/tribler/ui/src/pages/Downloads/Peers.tsx
- src/tribler/ui/src/pages/Downloads/Trackers.tsx
- src/tribler/ui/src/pages/Downloads/index.tsx
- src/tribler/ui/src/pages/Popular/index.tsx
- src/tribler/ui/src/pages/Search/index.tsx
Fixes https://github.com/Tribler/tribler/issues/8365.
Fixes https://github.com/Tribler/tribler/issues/8492 by removing the need for pagination.
This PR adds virtual scrolling to all tables, including file trees. For lists of a couple of thousand items, the difference is quite dramatic. Before you could barely scroll, now there's no slowdown at all. I've tested with up to 100k items without any issues. I think/hope it's good enough to disable pagination.
A downside is that column sizes can change as you scroll through the list. That's just because the table layout is set to auto, and only a small set of rows is being rendered at a time. I didn't want to go into calculating column sizes manually, but we can always revisit this later.
Note that there is room for additional performance …
> Add virtual scrolling

- README.rst
This PR:
- Fixes the `README`'s Python version badge not being linked properly.
> Fixed README Python 3.12 badge

- .github/workflows/build.yml
Fixes #8499
This PR:
- Updates the GitHub Actions Runner `ubuntu-20.04` to `ubuntu-22.04`.
Support is being dropped tomorrow. This covers all usages (that I could find) within Tribler and IPv8.
> Updated GA Runner Ubuntu 20.04 -> 22.04

- .github/workflows/build.yml
Fixes [the build job](https://github.com/Tribler/tribler/actions/runs/14440822939) for aarch64
This PR:
- Fixes the aarch64 build using Python 3.10. Successful build: https://github.com/qstokkink/tribler/actions/runs/14445258968
- Removes unnecessary aarch64 apt packages.
This should definitively fix the aarch64 build. The only unconfirmed 3.12 build after this is Windows x32.
> Fixed aarch64 build

- src/tribler/core/database/store.py
Fixes #8510
This PR:
- Updates the popular torrents SQL to fetch `POPULAR_TORRENTS_COUNT` results.
> Updated popular torrents SQL

- requirements.txt
- src/tribler/core/database/orm_bindings/torrent_metadata.py
- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/core/libtorrent/download_manager/download_state.py
- src/tribler/core/libtorrent/download_manager/stream.py
- src/tribler/core/libtorrent/restapi/create_torrent_endpoint.py
- src/tribler/core/libtorrent/restapi/downloads_endpoint.py
- src/tribler/core/libtorrent/restapi/torrentinfo_endpoint.py
- src/tribler/core/libtorrent/torrentdef.py
- src/tribler/core/tunnel/community.py
- src/tribler/test_integration/test_anon_download.py
- src/tribler/test_integration/test_hidden_services.py
- src/tribler/test_unit/core/database/orm_bindings/test_torrent_metadata.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download_manager.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download_state.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_stream.py
- src/tribler/test_unit/core/libtorrent/restapi/test_downloads_endpoint.py
- src/tribler/test_unit/core/libtorrent/restapi/test_torrentinfo_endpoint.py
- src/tribler/test_unit/core/libtorrent/test_torrentdef.py
- src/tribler/test_unit/core/libtorrent/test_torrents.py
- src/tribler/test_unit/core/tunnel/test_community.py
Fixes #8544
This PR:
- Updates `marshmallow` to be pinned at `3.26.1`, because `4.0.0` is incompatible with IPv8. This also requires `aiohttp==3.11.16`. I opened [an issue for this on IPv8](https://github.com/Tribler/py-ipv8/issues/1339).
- Updates the `TorrentDef` to lean more on the `atp`.
> Replace tdef innards with ATP

- requirements.txt
- src/tribler/core/content_discovery/restapi/search_endpoint.py
- src/tribler/core/database/restapi/schema.py
- src/tribler/core/restapi/events_endpoint.py
This PR:
- Updates the code base to allow the newest `aiohttp` and `marshmallow` to be used again.
> Updated IPv8 pointer + unpinned aiohttp

- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/download_manager/download_config.py
- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/core/libtorrent/torrentdef.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download.py
Fixes #8521
Fixes #8578
This PR:
- Adds a pretty print string to `TorrentDef`.
- Fixes resume data not being loaded from checkpoints.
- Fixes hashchecking on startup not properly detecting already-finished torrents.
- Fixes the printed ATP for each download always being an empty dictionary.
- Updates `DownloadConfig.get_engineresumedata()` to return `add_torrent_params` instead of a `dict`.
- Removes `Download.get_atp()` (use `.tdef.atp` instead).
> Fixed checkpoint loading and completion hash checking

- src/run_tribler.py
- src/tribler/tribler_config.py
Fixes #8520
This PR:
- Adds a `"headless"` config option, which does the same as the `--server` command line argument.
> Added headless config option

- src/tribler/core/database/restapi/database_endpoint.py
- src/tribler/core/database/restapi/schema.py
- src/tribler/core/database/store.py
- src/tribler/test_unit/core/database/restapi/test_database_endpoint.py
- src/tribler/test_unit/core/database/test_store.py
Fixes #8357
This PR:
- Adds custom tag support to the REST API.
- Fixes the `MetadataParameters` schema showing `txt_filter` instead of `fts_text`, rendering the Swagger interface inoperable.
Notes:
- The tags are stored as a comma-separated list in a string. SQL/Pony really doesn't like this in a WHERE statement: `g.tags.split(x)` will produce an `AttributeError`.
- It is possible to do a proper split in SQL. However, this is pretty heavy. Instead, as a lighter option, I opted for tag string end matching. Practically, this means that searching for the "horse" tag will return "seahorse" tags as well. If this becomes an issue, we will have to revisit this.
> Added REST API support for custom torrent tags

- .github/workflows/build.yml
Fixes [the failing build](https://github.com/Tribler/tribler/actions/runs/15069331721).
This PR:
- Updates `vcpkg install libsodium` to not use a custom triplet selector, which didn't work anymore (suddenly) but is x64 by default anyway.
I tested this on my own fork: https://github.com/qstokkink/tribler/actions/runs/15070835574
> Fixed libsodium vcpkg install

- src/tribler/core/libtorrent/restapi/downloads_endpoint.py
- src/tribler/test_unit/core/libtorrent/restapi/test_downloads_endpoint.py
Fixes #8549
This PR:
- Fixes `safe_seeding` reenabling itself if the download default of `safe_seeding: true` is used.
> Fixed safe_seeding reenabling through default

- .github/workflows/build_docker.yml
Fixes #6591
This PR:
- Adds automated Docker Hub uploads (next to our existing ghcr.io upload).
I tested this on my fork _up to_ the actual Docker Hub upload: https://github.com/qstokkink/tribler/actions/runs/15109829800/job/42466571875
**However**, there are a lot of moving parts in this chain. I fully expect a follow-up PR to be necessary. For that reason, I haven't changed the documentation to point to the Docker Hub release yet.
> Added DockerHub publish Action

- .github/workflows/build_docker.yml
- doc/basics/docker.rst
This PR:
- Adds a pointer in the docks on how to pull from `docker.io`. Tested to work.
- Fixes the `ghcr.io` Docker build:  https://github.com/Tribler/tribler/actions/runs/15167195523.
> Added docker.io doc pointer and fix ghcr build

- src/tribler/core/libtorrent/download_manager/download_manager.py
Currently, downloads aren't loading their metainfo correctly, and as a result re-download their metainfo after every restart. This PR fixes this, and also addresses the issue that stopped torrents always show "Stopped 0%" after a restart, instead showing the actual progress. For some reason, downloads that are seeding don't have this 0% issue (which is probably why we haven't seen any bug reports yet).
Also fixes an issue where a stopped download can't be moved after a restart, since moving file storage doesn't appear to be working when libtorrent's `handle.get_metainfo` returns false. Possibly also related to https://github.com/Tribler/tribler/issues/8548.
> Fix loading metainfo

- src/tribler/ui/src/components/add-torrent.tsx
- src/tribler/ui/src/pages/Settings/General.tsx
Fixes https://github.com/Tribler/tribler/issues/8356.
When "Always ask download settings" is enabled, and the user adds multiple torrents, Tribler will now show the `SaveAs` dialog for one torrent at a time.
I didn't add an additional menu option for adding torrents silently, as that defeats the purpose of having a GUI setting.
> Support for showing multiple SaveAs dialogs

- src/tribler/core/database/orm_bindings/torrent_metadata.py
- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/download_manager/download_manager.py
- src/tribler/ui/src/services/tribler.service.ts
This PR:
* Fixes an issue with `tracker_info` remaining empty while downloading from a magnet link.
* Fixes an issue with the uri not being properly encoded while getting metainfo from within the `SaveAs` dialog.
* ~Fixes an issue with not having the correct trackers after reusing the handle of a metainfo download.~
> Various metainfo fixes

- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/test_unit/core/libtorrent/download_manager/test_download.py
Fixes #8674
This PR:
- Adds unit tests for move after completion behavior.
- Fixes an empty string not being equivalent to `None`/"don't move" for move after completion.
> Fixed move after complete regression

- src/tribler/core/libtorrent/download_manager/download_manager.py
Fixes #8673
This PR:
- Fixes the segfault happening when passing libtorrent `alert` instances to Python's logging.
This was found by simply commenting out debug statements until Tribler no longer segfaulted. Then, to fix it, using the same string cast on alerts as we do for other log statements.
> Cast libtorrent alert to str before logging

- src/tribler/core/libtorrent/torrentdef.py
- src/tribler/core/watch_folder/manager.py
Fixes #8681
This PR:
- Fixes `TorrentDef._threaded_load_job` pretending that it can handle `Path` instances (it can't).
> Fixed Watch folder load exception

- src/tribler/core/libtorrent/download_manager/download_manager.py
Fixes #8686
Fixes #8688
This PR:
- Updates the IPv8 pointer.
- Updates the raw ATP logging level to `DEBUG`.
> Updated IPv8 and ATP log level

- src/tribler/core/libtorrent/download_manager/download.py
- src/tribler/core/libtorrent/restapi/downloads_endpoint.py
- src/tribler/ui/public/locales/en_US.json
- src/tribler/ui/public/locales/es_ES.json
- src/tribler/ui/public/locales/hi_IN.json
- src/tribler/ui/public/locales/ko_KR.json
- src/tribler/ui/public/locales/pt_BR.json
- src/tribler/ui/public/locales/ru_RU.json
- src/tribler/ui/public/locales/zh_CN.json
- src/tribler/ui/src/models/download.model.tsx
- src/tribler/ui/src/pages/Downloads/index.tsx
Fixes #6693
This PR:
- Adds a `Completed on` column to the GUI and downloads REST API.
Note that the ATP is persisted by Tribler, but this is not automatically updated by libtorrent.
> Added 'completed on' column
